Repository tensorflow/tensorboard, pull requests merged in 2019-11, with the labels that each got.

#2873 Fix wrong docstring: plugin tag content is bytes
  tensorboard/backend/event_processing/event_accumulator.py
  tensorboard/backend/event_processing/plugin_event_accumulator.py
Labels: cla: yes

#2876 Fix minor test failure re plugin_lib/test
  tensorboard/components/experimental/plugin_lib/BUILD
  tensorboard/components/experimental/plugin_lib/test/BUILD
Labels: cla: yes

#2877 Fix minor internal build/test failure in tf_hparams tracker
  tensorboard/plugins/hparams/tf_hparams_google_analytics_tracker/BUILD
Labels: cla: yes

#2884 docs: fix annotations related to TBLoader
  tensorboard/backend/application.py
  tensorboard/default.py
  tensorboard/plugins/base_plugin.py
  tensorboard/program.py
Labels: cla: yes

#2883 Place histogram bucketing logic on CPU explicitly when using TPUStrategy
  tensorboard/plugins/histogram/summary_v2.py
Labels: cla: yes

#2886 Make VSCode resolve imports in node_modules instead of bazel-*
  tsconfig.json
Labels: cla: yes

#2892 What-If Tool progress bar and attribution sorting updates
  tensorboard/components/vz_example_viewer/vz-example-viewer.ts
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/BUILD
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Labels: cla: yes

#2899 Defer image/audio/histogram v2 summary preprocessing using LazyTensorCreator
  tensorboard/plugins/audio/BUILD
  tensorboard/plugins/audio/summary_v2.py
  tensorboard/plugins/histogram/BUILD
  tensorboard/plugins/histogram/summary_v2.py
  tensorboard/plugins/image/BUILD
  tensorboard/plugins/image/summary_v2.py
  tensorboard/util/BUILD
  tensorboard/util/lazy_tensor_creator.py
  tensorboard/util/lazy_tensor_creator_test.py
Labels: cla: yes, core:summaries, plugin:audio, plugin:histogram, plugin:images

#2887 docs: update docs for dynamic plugin authors
  tensorboard/examples/plugins/example_basic/README.md
Labels: cla: yes

#2901 Fix JupyterHub widget display error
  tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
Labels: cla: yes, plugin:what-if-tool

#2772 Specify TensorBoard Data API for blob sequences
  tensorboard/data/provider.py
  tensorboard/data/provider_test.py
Labels: cla: yes

#2897 Update WIT regression demo with attributions
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo/tf-interactive-inference-age-demo.html
Labels: cla: yes

#2878 uploader: add `ServerInfo` protos and logic
  tensorboard/BUILD
  tensorboard/pip_package/setup.py
  tensorboard/uploader/BUILD
  tensorboard/uploader/proto/BUILD
  tensorboard/uploader/proto/server_info.proto
  tensorboard/uploader/server_info.py
  tensorboard/uploader/server_info_test.py
Labels: cla: yes, core:uploader

#2903 uploader: add simple `list` subcommand
  tensorboard/uploader/exporter.py
  tensorboard/uploader/exporter_test.py
  tensorboard/uploader/uploader_main.py
Labels: cla: yes, core:uploader

#2908 Improve usability and design of counterfactual controls (What-If Tool)
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Labels: cla: yes

#2907 ci: unpin 2019-10-23 nightlies
  .travis.yml
Labels: cla: yes, type:build/install

#2910 Remove unused deps blocking sync
  tensorboard/webapp/BUILD
  tensorboard/webapp/core/effects/BUILD
  tensorboard/webapp/header/BUILD
  tensorboard/webapp/reloader/BUILD
  tensorboard/webapp/settings/BUILD
Labels: cla: yes

#2914 Relax minimum version of requests to allow 2.21.0
  .travis.yml
  tensorboard/pip_package/setup.py
Labels: cla: yes

#2915 Post-release 2.0.1
  RELEASE.md
Labels: cla: yes

#2909 What-If Tool attribution display improvements
  tensorboard/components/vz_example_viewer/vz-example-viewer.html
  tensorboard/components/vz_example_viewer/vz-example-viewer.ts
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Labels: cla: yes

#2916 WitWidget small fixes for upcoming 1.5.0 version
  tensorboard/components/vz_example_viewer/vz-example-viewer.ts
  tensorboard/plugins/interactive_inference/What_If_Tool_Notebook_Usage.ipynb
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
  tensorboard/plugins/interactive_inference/witwidget/pip_package/setup.py
Labels: cla: yes

#2923 Fix WIT datapoint distance with attributions
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Labels: cla: yes

#2918 WitWidget 1.5.0 documentation and version number updates
  tensorboard/plugins/interactive_inference/README.md
  tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
  tensorboard/plugins/interactive_inference/witwidget/pip_package/RELEASE.md
  tensorboard/plugins/interactive_inference/witwidget/version.py
Labels: cla: yes

#2925 Make --reload_multifile default value falsy None instead of False
  tensorboard/plugins/core/core_plugin.py
Labels: cla: yes

#2922 cleanup: assert using value, not casting
  tensorboard/webapp/settings/dialog.component.test.ts
Labels: cla: yes

#2931 Remove duplicate comment
  tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-dashboard.html
Labels: cla: yes

#2930 version: add safety check for PEP 440 compliance
  tensorboard/BUILD
  tensorboard/version_test.py
Labels: cla: yes, core:backend

#2934 uploader: set user agent for frontend handshake
  tensorboard/uploader/server_info.py
  tensorboard/uploader/server_info_test.py
Labels: cla: yes

#2920 core: security validator middleware
  tensorboard/backend/BUILD
  tensorboard/backend/application.py
  tensorboard/backend/security_validator.py
  tensorboard/backend/security_validator_test.py
Labels: cla: yes

#2928 cleanup: migrate test over to karma based tooling
  tensorboard/webapp/BUILD
  tensorboard/webapp/core/effects/BUILD
  tensorboard/webapp/core/store/BUILD
  tensorboard/webapp/core/store/core.reducers.test.ts
Labels: cla: yes

#2879 uploader: request `ServerInfo` from frontend
  tensorboard/uploader/BUILD
  tensorboard/uploader/server_info.py
  tensorboard/uploader/server_info_test.py
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_main.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes, core:uploader

#2940 sync: fix Werkzeug `BaseResponse` import
  tensorboard/backend/security_validator_test.py
Labels: cla: yes, core:backend, type:bug

#2943 build: explicitly export files used by other packages
  tensorboard/defs/BUILD
Labels: cla: yes, type:build/install

#2933 build: create JavaScript file from Vulc
  tensorboard/BUILD
  tensorboard/components/BUILD
  tensorboard/defs/vulcanize.bzl
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
  tensorboard/webapp/BUILD
Labels: cla: yes

#2936 polymer: (partial) remove data binding on style
  tensorboard/components/tf_card_heading/tf-card-heading.html
  tensorboard/components/tf_paginated_view/tf-category-paginated-view.html
  tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.html
  tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-multi-line-chart-card.html
Labels: cla: yes

#2939 Remove project metadata file from docs
  docs/_project.yaml
Labels: cla: yes

#2927 docs: fix notebooks with broken imports and images
  docs/image_summaries.ipynb
  docs/scalars_and_keras.ipynb
  docs/tensorboard_in_notebooks.ipynb
Labels: cla: yes

#2947 ci: pin to non-broken nightlies
  .travis.yml
Labels: cla: yes, type:build/install

#2906 uploader: add metadata to experiment listing RPC
  tensorboard/uploader/exporter.py
  tensorboard/uploader/exporter_test.py
  tensorboard/uploader/proto/export_service.proto
Labels: cla: yes

#2954 csp: allow style to be served from 'self'
  tensorboard/backend/http_util.py
  tensorboard/backend/http_util_test.py
Labels: cla: yes

#2958 uploader: enable handshake by default
  tensorboard/uploader/uploader_main.py
Labels: cla: yes, core:uploader

#2960 diagnose: add check for `getaddrinfo`
  tensorboard/tools/diagnose_tensorboard.py
Labels: cla: yes

#2961 build: tag all web tests with "webtest"
  tensorboard/defs/defs.bzl
  tensorboard/defs/web_testing.bzl
  tensorboard/functionaltests/BUILD
Labels: cla: yes, type:build/install

#2957 vulc: simplify argument parsing
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes, type:build/install

#2959 Respect nodename in `server_info_test`
  tensorboard/uploader/server_info_test.py
Labels: cla: yes

#2944 backend: document behavior on empty experiment IDs
  tensorboard/backend/experiment_id_test.py
Labels: cla: yes, core:backend

#2950 build: deprecate shasum in Vulcanization
  tensorboard/backend/http_util.py
  tensorboard/backend/http_util_test.py
  tensorboard/defs/vulcanize.bzl
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
  tensorboard/pip_package/setup.py
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/projector/projector_plugin.py
  tensorboard/plugins/projector/tf_projector_plugin/BUILD
Labels: cla: yes

#2952 ui: add slot for injecting header items
  tensorboard/components/tf_tensorboard/test/BUILD
  tensorboard/components/tf_tensorboard/test/index.html
  tensorboard/components/tf_tensorboard/test/tensorboardTests.ts
  tensorboard/components/tf_tensorboard/test/tests.html
  tensorboard/components/tf_tensorboard/tf-tensorboard.html
Labels: cla: yes

#2946 Improve WIT parsing of model results
  tensorboard/plugins/interactive_inference/utils/inference_utils.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/colab/wit.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/wit.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/visualization.py
Labels: cla: yes

#2945 cleanup: set targeted dom-change listener
  tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-list.html
  tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-list.ts
  tensorboard/components/tf_dashboard_common/tf-multi-checkbox.html
  tensorboard/components/tf_dashboard_common/tf-multi-checkbox.ts
  tensorboard/components/tf_tensorboard/tf-tensorboard.html
  tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.html
  tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-multi-line-chart-card.html
Labels: cla: yes

#2965 Updating link to Fairness Indicators TB plugin colab
  docs/fairness-indicators.md
Labels: cla: yes

#2966 csp: allow frame-src to be configured
  tensorboard/backend/http_util.py
  tensorboard/backend/http_util_test.py
Labels: cla: yes

#2941 uploader: include metadata in `list` output
  tensorboard/uploader/BUILD
  tensorboard/uploader/exporter.py
  tensorboard/uploader/exporter_test.py
  tensorboard/uploader/uploader_main.py
  tensorboard/uploader/util.py
  tensorboard/uploader/util_test.py
Labels: cla: yes, core:uploader, type:feature

#2971 Post-release 2.0.2
  RELEASE.md
Labels: cla: yes

#2972 docs: quell fears about spurious warnings
  DEVELOPMENT.md
Labels: cla: yes, type:docs

#2975 Add empty `__init__.py`s where missing
  tensorboard/data/__init__.py
  tensorboard/defs/__init__.py
  tensorboard/examples/plugins/example_basic/__init__.py
  tensorboard/functionaltests/__init__.py
  tensorboard/plugins/interactive_inference/witwidget/pip_package/__init__.py
  tensorboard/tools/__init__.py
  tensorboard/uploader/__init__.py
Labels: cla: yes, type:cleanup

#2978 uploader: fix `util_test` internally
  tensorboard/uploader/util_test.py
Labels: cla: yes, type:bug
