Repository tensorflow/tensorboard, pull requests merged in 2019-10, with the labels that each got.

#2703 plugin: message channels for dynamic plugins
  tensorboard/components/experimental/plugin_util/BUILD
  tensorboard/components/experimental/plugin_util/message.ts
  tensorboard/components/experimental/plugin_util/plugin-guest.html
  tensorboard/components/experimental/plugin_util/plugin-guest.ts
  tensorboard/components/experimental/plugin_util/plugin-host.html
  tensorboard/components/experimental/plugin_util/plugin-host.ts
  tensorboard/components/experimental/plugin_util/test/BUILD
  tensorboard/components/experimental/plugin_util/test/iframe.html
  tensorboard/components/experimental/plugin_util/test/iframe.ts
  tensorboard/components/experimental/plugin_util/test/plugin-test.ts
  tensorboard/components/experimental/plugin_util/test/tests.html
  tensorboard/components/plugin_util/plugin-host.ts
Labels: cla: yes

#2710 Unblock the sync
  tensorboard/BUILD
  tensorboard/components/tf_ng_tensorboard/core/BUILD
  tensorboard/components/tf_ng_tensorboard/core/core.reducers.test.ts
  tensorboard/components/tf_ng_tensorboard/core/core.reducers.ts
Labels: cla: yes

#2713 sync: missing deps on sinon for core test
  tensorboard/components/tf_ng_tensorboard/core/BUILD
Labels: cla: yes

#2712 Update links for TF2
  docs/r2/get_started.ipynb
  docs/r2/migrate_tf2.ipynb
Labels: cla: yes

#2714 vulc: jscomp-ignored script in topological order
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes

#2717 mesh: remove obsolete installation instructions
  tensorboard/plugins/mesh/README.md
Labels: cla: yes

#2715 sec: enable Polymer strictTemplatePolicy
  tensorboard/components/BUILD
  tensorboard/components/ng_polymer_lib.html
  tensorboard/components/security.html
  tensorboard/components/tensorboard.html
  tensorboard/components/trace_viewer.html
  tensorboard/components/vz_chart_helpers/vz-chart-tooltip.ts
  tensorboard/plugins/graph/tf_graph_loader/tf-graph-dashboard-loader.html
  tensorboard/plugins/graph/tf_graph_loader/tf-graph-dashboard-loader.ts
  tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.html
  tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.ts
Labels: cla: yes

#2718 Doc moves for TF2
  docs/_book.yaml
  docs/_index.yaml
  docs/get_started.ipynb
  docs/graphs.ipynb
  docs/hyperparameter_tuning_with_hparams.ipynb
  docs/image_summaries.ipynb
  docs/images/graphs_autograph.png
  docs/images/graphs_computation.png
  docs/images/graphs_computation_detail.png
  docs/images/graphs_conceptual.png
  docs/images/graphs_tag_selection.png
  docs/images/hparams_parallel_coordinates.png
  docs/images/hparams_table.png
  docs/images/images_accuracy.png
  docs/images/images_arbitrary.png
  docs/images/images_cm.png
  docs/images/images_multiple.png
  docs/images/images_single.png
  docs/images/notebook_tensorboard.png
  docs/images/notebook_tensorboard_tall.png
  docs/images/notebook_tensorboard_two_runs.png
  docs/images/profiler-blocking-runtime.png
  docs/images/profiler-capture.png
  docs/images/profiler-download-logdir.png
  docs/images/profiler-idle-gpu.png
  docs/images/profiler-input-cpu.png
  docs/images/profiler-notebook-settings.png
  docs/images/profiler-prefetch-runtime.png
  docs/images/profiler-trace-viewer-select.png
  docs/images/profiler-trace-viewer.png
  docs/images/quickstart_gradient_tape.png
  docs/images/quickstart_model_fit.png
  docs/images/scalars_custom_lr.png
  docs/images/scalars_loss.png
  docs/images/what_if_tool.png
  docs/images/what_if_tool_demo_setup.png
  docs/migrate.ipynb
  docs/overview.md
  docs/scalars_and_keras.ipynb
  docs/tensorboard_in_notebooks.ipynb
  docs/tensorboard_profiling_keras.ipynb
  docs/what_if_tool.md
Labels: cla: yes

#2688 ui: add expand arrow to category paginated view
  tensorboard/components/tf_paginated_view/tf-category-paginated-view.html
Labels: cla: yes

#2721 Nav updates for TF2
  docs/_book.yaml
  docs/_index.yaml
  docs/r1/overview.md
  docs/tensorboard_profiling_keras.ipynb
Labels: cla: yes

#2722 ci: swap `tf-nightly-2.0-preview` to `tf-nightly`
  .travis.yml
  tensorboard/examples/plugins/example_basic/smoke_test.sh
  tensorboard/pip_package/test_pip_package.sh
Labels: cla: yes, type:build/install

#2723 sec: disable strictTemplatePolicy on TB and enable on projector
  tensorboard/components/BUILD
  tensorboard/components/tensorboard.html
  tensorboard/plugins/projector/tf_projector_plugin/BUILD
  tensorboard/plugins/projector/tf_projector_plugin/tf-projector-plugin.html
Labels: cla: yes

#2716 Easier WIT custom_predict_fn when using JSON inputs and other witwidget 1.4 fixes
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
  tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
Labels: cla: yes

#2730 core: add x-content-type-options: nosniff
  tensorboard/backend/http_util.py
Labels: cla: yes

#2728 WitWidget 1.4.1 patch
  tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
  tensorboard/plugins/interactive_inference/witwidget/pip_package/RELEASE.md
  tensorboard/plugins/interactive_inference/witwidget/version.py
Labels: cla: yes

#2732 application: factor out middleware installation
  tensorboard/backend/application.py
Labels: cla: yes, core:backend

#2733 application: extract path prefix logic to middleware
  tensorboard/backend/BUILD
  tensorboard/backend/application.py
  tensorboard/backend/path_prefix.py
  tensorboard/backend/path_prefix_test.py
Labels: cla: yes, core:backend

#2719 vulc: combine script in compile=True and shasum
  tensorboard/BUILD
  tensorboard/defs/vulcanize.bzl
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes

#2734 application: add redirect to ensure trailing slash
  tensorboard/backend/BUILD
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/backend/empty_path_redirect.py
  tensorboard/backend/empty_path_redirect_test.py
Labels: cla: yes, core:backend

#2731 cleanup: use http_util.Respond
  tensorboard/plugins/beholder/beholder_plugin.py
  tensorboard/plugins/debugger/debugger_plugin.py
  tensorboard/plugins/debugger/interactive_debugger_plugin.py
Labels: cla: yes

#2735 application: add middleware for experiment IDs
  tensorboard/BUILD
  tensorboard/backend/BUILD
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/backend/experiment_id.py
  tensorboard/backend/experiment_id_test.py
  tensorboard/plugin_util.py
  tensorboard/plugin_util_test.py
Labels: cla: yes, core:backend

#2742 cleanup: miscellaneous improvements to Vulcanize
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes

#2736 frontend: use experiment ID from path, not query
  tensorboard/components/tf_backend/environmentStore.ts
  tensorboard/components/tf_backend/router.ts
  tensorboard/components/tf_backend/runsStore.ts
  tensorboard/components/tf_backend/test/backendTests.ts
  tensorboard/plugins/core/BUILD
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Labels: cla: yes, core:frontend

#2737 backend: fix `--path_prefix` validation
  tensorboard/backend/application.py
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
Labels: cla: yes, core:backend

#2746 vulcanization: improvements
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes

#2749 cleanup: deprecate vulcanize-noinline
  tensorboard/components/experimental/plugin_util/test/tests.html
  tensorboard/components/vz_sorting/test/tests.html
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes

#2729 [tensor-widget] Add support for hierarchical menu and image view of tensor values
  tensorboard/components/tensor_widget/BUILD
  tensorboard/components/tensor_widget/colormap-test.ts
  tensorboard/components/tensor_widget/colormap.ts
  tensorboard/components/tensor_widget/demo/demo.html
  tensorboard/components/tensor_widget/demo/demo.ts
  tensorboard/components/tensor_widget/health-pill-types.ts
  tensorboard/components/tensor_widget/menu.ts
  tensorboard/components/tensor_widget/tensor-widget-impl.ts
  tensorboard/components/tensor_widget/tensor-widget.css
  tensorboard/components/tensor_widget/types.ts
  tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
  tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-multi-view.html
  tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-view.html
Labels: cla: yes

#2726 sec: Enable CSP and disallow random script tags
  tensorboard/backend/http_util.py
  tensorboard/defs/vulcanize.bzl
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
  tensorboard/plugins/core/core_plugin.py
Labels: cla: yes

#2747 experimental: plugin lib as ts_library
  tensorboard/components/experimental/plugin_lib/BUILD
  tensorboard/components/experimental/plugin_lib/index.ts
  tensorboard/components/experimental/plugin_lib/plugin-guest.ts
  tensorboard/components/experimental/plugin_lib/runs.ts
  tensorboard/components/experimental/plugin_lib/test/BUILD
  tensorboard/components/experimental/plugin_lib/test/test.ts
  tensorboard/components/experimental/plugin_lib/test/testable-iframe.html
  tensorboard/components/experimental/plugin_lib/test/testable-plugin-lib.ts
  tensorboard/components/experimental/plugin_util/message.ts
  tensorboard/components/experimental/plugin_util/test/BUILD
  tensorboard/components/experimental/plugin_util/test/plugin-test.ts
  tensorboard/components/experimental/plugin_util/test/tests.html
Labels: cla: yes

#2751 Expose graph plugin name
  tensorboard/plugins/graph/BUILD
  tensorboard/plugins/graph/graphs_plugin.py
  tensorboard/plugins/graph/metadata.py
Labels: cla: yes

#2757 lib: move message.ts to plugin_lib
  tensorboard/components/experimental/plugin_lib/BUILD
  tensorboard/components/experimental/plugin_lib/message.ts
  tensorboard/components/experimental/plugin_util/BUILD
  tensorboard/components/experimental/plugin_util/message.ts
Labels: cla: yes

#2755 ROC curves for multi-class (What-If Tool)
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Labels: cla: yes

#2756 csp: make it globally configurable
  tensorboard/backend/http_util.py
  tensorboard/backend/http_util_test.py
  tensorboard/plugins/core/core_plugin.py
Labels: cla: yes

#2761 sync: unblock sync by copying message.ts
  tensorboard/components/experimental/plugin_lib/BUILD
  tensorboard/components/experimental/plugin_lib/message.ts
  tensorboard/components/experimental/plugin_util/BUILD
  tensorboard/components/experimental/plugin_util/message.ts
Labels: cla: yes

#2765 CSP: allow more CSP fields to be configurable
  tensorboard/backend/http_util.py
  tensorboard/backend/http_util_test.py
Labels: cla: yes

#2766 program: add direct `absl.flags` Bazel pseudodep
  tensorboard/BUILD
Labels: cla: yes

#2769 ci: pin TF 1.x to 1.15.0rc3, not nightly
  .travis.yml
Labels: cla: yes, type:build/install

#2770 Fix link to graphs.md
  docs/r1/summaries.md
Labels: cla: yes

#2773 Consume java_import_external from bazel_tools instead of rules_closure
  third_party/workspace.bzl
Labels: cla: yes

#2763 Fix tabs left margin (What-If Tool)
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Labels: cla: yes

#2762 Fix cloud model usage with JSON input
  tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
Labels: cla: yes

#2639 Revert "build: disable mesh summary v2 test (#2625)"
  tensorboard/plugins/mesh/BUILD
Labels: cla: yes

#2778 Release WIT patch 1.4.2
  tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
  tensorboard/plugins/interactive_inference/witwidget/pip_package/RELEASE.md
  tensorboard/plugins/interactive_inference/witwidget/version.py
Labels: cla: yes

#2779 Fix typo s/sumary/summary
  docs/graphs.ipynb
Labels: cla: yes

#2700 ng: invoke dashboard reload
  tensorboard/components/tf_ng_tensorboard/header/BUILD
  tensorboard/components/tf_ng_tensorboard/header/components/header.component.css
  tensorboard/components/tf_ng_tensorboard/header/components/header.component.html
  tensorboard/components/tf_ng_tensorboard/header/components/header.component.ts
  tensorboard/components/tf_ng_tensorboard/header/containers/header.component.ts
  tensorboard/components/tf_ng_tensorboard/header/header.module.ts
  tensorboard/components/tf_ng_tensorboard/header/header.test.ts
  tensorboard/components/tf_ng_tensorboard/plugins/plugins.component.test.ts
  tensorboard/components/tf_ng_tensorboard/plugins/plugins.component.ts
Labels: cla: yes

#2780 Remove mentions of tb-nightly from README
  README.md
Labels: cla: yes

#2781 Add WIT callback creator for TFMA slicing usage
  tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
Labels: cla: yes

#2775 csp: fix bugs and properly treat projector
  tensorboard/backend/http_util.py
  tensorboard/backend/http_util_test.py
  tensorboard/pip_package/setup.py
  tensorboard/plugins/projector/projector_plugin.py
  tensorboard/plugins/projector/tf_projector_plugin/BUILD
Labels: cla: yes

#2785 Fix sliced intersection (What-If Tool)
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Labels: cla: yes

#2787 Add ml service name and version for CAIP
  tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/visualization.py
Labels: cla: yes

#2782 ng: fix the dev CSP issue
  tensorboard/BUILD
  tensorboard/components/tf_backend/tf-backend-polymer.ts
  tensorboard/components/tf_storage/tf-storage-polymer.ts
Labels: cla: yes

#2788 When turning off counterfactual, correctly update example viewer
  tensorboard/components/vz_example_viewer/vz-example-viewer.ts
Labels: cla: yes

#2795 WitWidget 1.4.3
  tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
  tensorboard/plugins/interactive_inference/witwidget/pip_package/RELEASE.md
  tensorboard/plugins/interactive_inference/witwidget/version.py
Labels: cla: yes

#2796 cleanup: application(|_test).py formatting
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
Labels: cla: yes

#2797 csp: add frame-ancestors *
  tensorboard/backend/http_util.py
  tensorboard/backend/http_util_test.py
Labels: cla: yes

#2793 program: add subcommand CLI support
  tensorboard/BUILD
  tensorboard/program.py
  tensorboard/program_test.py
  tensorboard/util/BUILD
  tensorboard/util/argparse_util.py
  tensorboard/util/argparse_util_test.py
Labels: cla: yes, core:backend

#2806 Fix typo in development instructions
  tensorboard/plugins/interactive_inference/DEVELOPMENT.md
Labels: cla: yes

#2800 proto: enable compiling gRPC services
  tensorboard/defs/protos.bzl
Labels: cla: yes, type:build/install

#2802 csp: allow blob for img
  tensorboard/backend/http_util.py
  tensorboard/backend/http_util_test.py
Labels: cla: yes

#2807 program: don’t set default flags on base parser
  tensorboard/program.py
Labels: cla: yes

#2794 ng: functional settings dialog
  package.json
  tensorboard/components/tf_ng_tensorboard/BUILD
  tensorboard/components/tf_ng_tensorboard/header/BUILD
  tensorboard/components/tf_ng_tensorboard/header/components/header.component.html
  tensorboard/components/tf_ng_tensorboard/header/header.module.ts
  tensorboard/components/tf_ng_tensorboard/header/header.test.ts
  tensorboard/components/tf_ng_tensorboard/settings/BUILD
  tensorboard/components/tf_ng_tensorboard/settings/dialog.component.css
  tensorboard/components/tf_ng_tensorboard/settings/dialog.component.test.ts
  tensorboard/components/tf_ng_tensorboard/settings/dialog.component.ts
  tensorboard/components/tf_ng_tensorboard/settings/settings.module.ts
  tensorboard/components/tf_ng_tensorboard/settings/settings_button.component.ts
  yarn.lock
Labels: cla: yes

#2809 proto: support build deps
  tensorboard/defs/BUILD
  tensorboard/defs/protos.bzl
  tensorboard/defs/tb_proto_library_test.py
  tensorboard/defs/test_base.proto
  tensorboard/defs/test_downstream.proto
Labels: cla: yes, type:build/install

#2764 [tensor-widget] Add colormap selection and Ctrl/Alt/Shift+wheel zooming
  tensorboard/components/tensor_widget/colormap-test.ts
  tensorboard/components/tensor_widget/colormap.ts
  tensorboard/components/tensor_widget/menu.ts
  tensorboard/components/tensor_widget/tensor-widget-impl.ts
  tensorboard/components/tensor_widget/tensor-widget.css
  tensorboard/components/tensor_widget/types.ts
  tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-view.html
Labels: cla: yes

#2810 util: add `grpc_util` with backoff helper
  tensorboard/BUILD
  tensorboard/util/BUILD
  tensorboard/util/grpc_util.py
  tensorboard/util/grpc_util_test.proto
  tensorboard/util/grpc_util_test.py
  tensorboard/util/test_util.py
Labels: cla: yes

#2812 core: increase frontend active request limit
  tensorboard/components/tf_backend/requestManager.ts
Labels: cla: yes

#2798 colab: use proxyPort for dynamic plugin
  tensorboard/components/tf_tensorboard/tf-tensorboard.html
  tensorboard/notebook.py
  tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
Labels: cla: yes

#2804 Fix creation of resnet110
  docs/tensorboard_profiling_keras.ipynb
Labels: cla: yes

#2811 core: fix double requests in data loader
  tensorboard/components/tf_dashboard_common/data-loader-behavior.ts
Labels: cla: yes

#2815 ng: break direct dependency on material
  tensorboard/components/tf_ng_tensorboard/angular/BUILD
  tensorboard/components/tf_ng_tensorboard/settings/BUILD
Labels: cla: yes

#2818 ng: add dependency on material icon and input
  tensorboard/components/tf_ng_tensorboard/angular/BUILD
  tensorboard/components/tf_ng_tensorboard/settings/BUILD
Labels: cla: yes

#2816 Decode the bytes
  tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
Labels: cla: yes

#2822 Add uploader gRPC client
  .travis.yml
  tensorboard/BUILD
  tensorboard/main.py
  tensorboard/pip_package/setup.py
  tensorboard/uploader/BUILD
  tensorboard/uploader/auth.py
  tensorboard/uploader/auth_test.py
  tensorboard/uploader/dev_creds.py
  tensorboard/uploader/exporter.py
  tensorboard/uploader/exporter_test.py
  tensorboard/uploader/logdir_loader.py
  tensorboard/uploader/logdir_loader_test.py
  tensorboard/uploader/peekable_iterator.py
  tensorboard/uploader/peekable_iterator_test.py
  tensorboard/uploader/proto/BUILD
  tensorboard/uploader/proto/export_service.proto
  tensorboard/uploader/proto/scalar.proto
  tensorboard/uploader/proto/write_service.proto
  tensorboard/uploader/test_util.py
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_main.py
  tensorboard/uploader/uploader_test.py
  tensorboard/uploader/util.py
  tensorboard/uploader/util_test.py
Labels: cla: yes

#2829 Bump `grpcio` version to 1.24.3
  .travis.yml
  tensorboard/pip_package/setup.py
Labels: cla: yes

#2825 scalar: fix the timing issues
  tensorboard/components/tf_dashboard_common/data-loader-behavior.ts
Labels: cla: yes

#2823 tiny typo
  tensorboard/plugins/interactive_inference/README.md
Labels: cla: yes

#2828 uploader: add license directive to build file
  tensorboard/uploader/BUILD
Labels: cla: yes

#2817 core: avoid extra network request upon run selection
  tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-dashboard.html
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Labels: cla: yes

#2834 ci: pin to non-broken nightlies
  .travis.yml
Labels: cla: yes, type:build/install

#2832 data load: prevent JSE when canceling async
  tensorboard/components/tf_dashboard_common/data-loader-behavior.ts
Labels: cla: yes

#2833 WitWidget 1.4.4
  tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
  tensorboard/plugins/interactive_inference/witwidget/pip_package/RELEASE.md
  tensorboard/plugins/interactive_inference/witwidget/version.py
Labels: cla: yes, plugin:what-if-tool

#2837 Backport `mock` assertions for Python 2 tests
  tensorboard/tools/whitespace_hygiene_test.py
  tensorboard/uploader/exporter_test.py
  tensorboard/uploader/uploader_test.py
  tensorboard/uploader/util_test.py
  third_party/mock_call_assertions.patch
  third_party/python.bzl
Labels: cla: yes, type:build/install

#2838 Set default --grpc_creds_type to ssl, not ssl_dev
  tensorboard/uploader/uploader_main.py
Labels: cla: yes

#2791 Fix GFile reading CRLF bug
  tensorboard/compat/tensorflow_stub/io/gfile.py
  tensorboard/compat/tensorflow_stub/io/gfile_test.py
Labels: cla: yes

#2841 uploader: clarify that uploads run forever
  tensorboard/uploader/uploader_main.py
Labels: cla: yes, core:uploader

#2835 ci: unpin 2019-09-17 estimator nightlies
  .travis.yml
Labels: cla: yes, type:build/install

#2845 uploader: parse JSON from Unicode for Python 3.5
  tensorboard/uploader/auth.py
  tensorboard/uploader/dev_creds.py
Labels: cla: yes, core:uploader

#2842 uploader: fix `auth revoke` help suggestion
  tensorboard/uploader/uploader_main.py
Labels: cla: yes, core:uploader

#2843 uploader: include TensorBoard version in RPCs
  tensorboard/uploader/BUILD
  tensorboard/uploader/exporter.py
  tensorboard/uploader/exporter_test.py
  tensorboard/util/BUILD
  tensorboard/util/grpc_util.py
  tensorboard/util/grpc_util_test.py
Labels: cla: yes, core:uploader

#2830 ng: load material icon sources
  tensorboard/BUILD
  tensorboard/components/BUILD
  tensorboard/components/tf_ng_tensorboard/BUILD
  tensorboard/components/tf_ng_tensorboard/app.module.ts
  tensorboard/components/tf_ng_tensorboard/settings/settings_button.component.ts
  tensorboard/defs/defs.bzl
  tensorboard/tools/BUILD
  tensorboard/tools/mat_bundle_icon_svg.sh
  third_party/js.bzl
Labels: cla: yes

#2846 Fix set examples in jupyter
  tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
Labels: cla: yes

#2847 uploader: fix export when outdir has no slash
  tensorboard/uploader/exporter.py
  tensorboard/uploader/exporter_test.py
Labels: cla: yes, core:uploader

#2848 Update witwidget to 1.4.5
  tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
  tensorboard/plugins/interactive_inference/witwidget/pip_package/RELEASE.md
  tensorboard/plugins/interactive_inference/witwidget/version.py
Labels: cla: yes

#2849 uploader: change request batch size to 128 KiB
  tensorboard/uploader/uploader.py
Labels: cla: yes, core:uploader

#2851 uploader: add TensorBoard.dev branding
  tensorboard/uploader/BUILD
  tensorboard/uploader/exporter.py
  tensorboard/uploader/proto/export_service.proto
  tensorboard/uploader/proto/write_service.proto
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_main.py
Labels: cla: yes, core:uploader

#2827 Fairness Indicators documentation
  docs/fairness-indicators.md
  docs/images/fairness-indicators.png
Labels: cla: yes

#2855 Revert "ng: load material icon sources"
  tensorboard/BUILD
  tensorboard/components/BUILD
  tensorboard/components/tf_ng_tensorboard/BUILD
  tensorboard/components/tf_ng_tensorboard/app.module.ts
  tensorboard/components/tf_ng_tensorboard/settings/settings_button.component.ts
  tensorboard/defs/defs.bzl
  tensorboard/tools/BUILD
  tensorboard/tools/mat_bundle_icon_svg.sh
  third_party/js.bzl
Labels: cla: yes

#2856 uploader: set default endpoint to production
  tensorboard/uploader/uploader_main.py
Labels: cla: yes, core:uploader

#2853 Fix comment in export.proto
  tensorboard/uploader/proto/export_service.proto
Labels: cla: yes

#2852 Improve error handling for exporting large experiments
  tensorboard/uploader/BUILD
  tensorboard/uploader/exporter.py
  tensorboard/uploader/exporter_test.py
  tensorboard/uploader/uploader_main.py
Labels: cla: yes

#2860 Update _book.yaml with Fairness Indicators
  docs/_book.yaml
Labels: cla: yes

#2864 uploader: link to `/policy/terms/`, not `terms.html`
  tensorboard/uploader/uploader_main.py
Labels: cla: yes, core:uploader

#2865 Add TensorBoard.dev getting started notebook
  docs/tbdev_getting_started.ipynb
Labels: cla: yes

#2866 Update Colab-based docs to use %tensorflow_version magic
  docs/get_started.ipynb
  docs/graphs.ipynb
  docs/hyperparameter_tuning_with_hparams.ipynb
  docs/image_summaries.ipynb
  docs/migrate.ipynb
  docs/scalars_and_keras.ipynb
  docs/tensorboard_in_notebooks.ipynb
  docs/tensorboard_profiling_keras.ipynb
Labels: cla: yes

#2861 analytics: send pathname on pageview event
  tensorboard/components/tf_tensorboard/tf-tensorboard.html
Labels: cla: yes

#2867 Wrap %tensorflow_version magic with try/except.
  docs/get_started.ipynb
  docs/graphs.ipynb
  docs/hyperparameter_tuning_with_hparams.ipynb
  docs/image_summaries.ipynb
  docs/migrate.ipynb
  docs/scalars_and_keras.ipynb
  docs/tensorboard_in_notebooks.ipynb
  docs/tensorboard_profiling_keras.ipynb
Labels: cla: yes

#2863 Updating fairness-indicators.md
  docs/fairness-indicators.md
Labels: cla: yes

#2868 Fix Colab notebooks to be valid json and to enable the docs generation workflow.
  docs/get_started.ipynb
  docs/graphs.ipynb
  docs/hyperparameter_tuning_with_hparams.ipynb
  docs/image_summaries.ipynb
  docs/migrate.ipynb
  docs/scalars_and_keras.ipynb
  docs/tbdev_getting_started.ipynb
  docs/tensorboard_profiling_keras.ipynb
Labels: cla: yes

#2871 docs: fix invalid json
  docs/tensorboard_in_notebooks.ipynb
Labels: cla: yes

#2870 Update Fairness Indicators landing page image
  docs/images/fairness-indicators.png
Labels: cla: yes
