Repository tensorflow/tensorboard, pull requests merged in 2019-08, with the labels that each got.

#2407 Allow Jupyter+TensorBoard to work w/ hostname other than localhost
  tensorboard/notebook.py
Labels: cla: yes

#2472 core: introduce rules_nodejs and angular shim
  .gitignore
  .travis.yml
  BUILD
  WORKSPACE
  angular-metadata.tsconfig.json
  package.json
  tensorboard/components/tf_ng_tensorboard/BUILD
  tensorboard/components/tf_ng_tensorboard/app-routing.module.ts
  tensorboard/components/tf_ng_tensorboard/app.component.css
  tensorboard/components/tf_ng_tensorboard/app.component.html
  tensorboard/components/tf_ng_tensorboard/app.component.ts
  tensorboard/components/tf_ng_tensorboard/app.module.ts
  tensorboard/components/tf_ng_tensorboard/main.ts
  tsconfig-test.json
  tsconfig.json
  yarn.lock
Labels: cla: yes, core:frontend

#2494 ci: use latest Pip
  .travis.yml
Labels: cla: yes, type:build/install

#2495 ci: print `pip freeze` output, for debugging
  .travis.yml
Labels: cla: yes, type:build/install

#2480 mesh: update tf-graphics dep to 2019-07-30
  third_party/js.bzl
Labels: cla: yes, plugin:mesh

#2501 docs: point to Yarn install instructions
  DEVELOPMENT.md
Labels: cla: yes, type:docs

#2498 [tensor-widget] add dtype utility and testing infrastructure
  package.json
  tensorboard/components/tensor_widget/BUILD
  tensorboard/components/tensor_widget/dtype-utils-test.ts
  tensorboard/components/tensor_widget/dtype-utils.ts
  tensorboard/components/tensor_widget/tensor-widget.html
  yarn.lock
Labels: cla: yes

#2476 Allow plugins to declare wildcard routes.
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
Labels: cla: yes

#2504 Update scalars_and_keras.ipynb
  docs/r2/scalars_and_keras.ipynb
Labels: cla: yes, type:docs

#2500 Move example plugin to plugins_examples
  tensorboard/examples/plugins/example_basic/.gitignore
  tensorboard/examples/plugins/example_basic/BUILD
  tensorboard/examples/plugins/example_basic/README.md
  tensorboard/examples/plugins/example_basic/setup.py
  tensorboard/examples/plugins/example_basic/smoke_test.sh
  tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/__init__.py
  tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/demo.py
  tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/metadata.py
  tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/plugin.py
  tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/static/index.js
  tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/summary_v2.py
Labels: cla: yes

#2506 example_basic: bump smoke test to moderate timeout
  tensorboard/examples/plugins/example_basic/BUILD
Labels: cla: yes, type:build/install

#2508 hparams: open link in new tab
  tensorboard/plugins/hparams/tf_hparams_sessions_pane/tf-hparams-sessions-pane.html
Labels: cla: yes, plugin:hparams

#2509 profile: fix trace viewer
  tensorboard/components/BUILD
  tensorboard/components/trace_viewer.html
Labels: cla: yes

#2516 Use `rel="noopener"` for `target="_blank"` links
  tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-initial-dialog.html
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
  tensorboard/plugins/projector/vz_projector/vz-projector-app.html
  tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.html
  tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.html
Labels: cla: yes, type:bug

#2517 polymer2: fixed plugin dropdown UI issue
  tensorboard/components/tf_tensorboard/tf-tensorboard.html
Labels: cla: yes

#2520 scalars: omit empty runs from `/tags` route
  tensorboard/plugins/scalar/http_api.md
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes, plugin:scalars

#2521 Wrap rollup_bundle around tf_js_binary for interop
  tensorboard/components/tensor_widget/BUILD
  tensorboard/components/tf_ng_tensorboard/BUILD
  tensorboard/defs/defs.bzl
Labels: cla: yes

#2526 Fixed Typo: 'RestNet' -> 'ResNet'
  docs/r2/tensorboard_profiling_keras.ipynb
Labels: cla: yes

#2523 ui: fixed graph causing dropdown-menu bug
  tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.html
Labels: cla: yes

#2524 ng: remove tf_web_library target
  tensorboard/components/tf_ng_tensorboard/BUILD
Labels: cla: yes

#2528 [graph plugin] Prevent health pills from showing up by default; Fix layout and default
  tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.html
  tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.html
  tensorboard/plugins/graph/tf_graph_info/tf-graph-info.html
Labels: cla: yes

#2522 Make scalars plugin tests mostly TF 2.x–compatible
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes

#2535 build: add `.bazelrc` to disable Python toolchains
  .bazelrc
Labels: cla: yes, type:build/install

#2525 Improve memory viewer and tf-op-profile tool.
  tensorboard/plugins/profile/memory_viewer/memory_usage/memory-usage.ts
  tensorboard/plugins/profile/memory_viewer/xla/logical-buffer.ts
  tensorboard/plugins/profile/tf_op_profile/tf-op-details.html
  tensorboard/plugins/profile/tf_op_profile/tf-op-profile.html
  tensorboard/plugins/profile/tf_op_profile/tf-op-table.html
  tensorboard/plugins/profile/tf_op_profile/utils.ts
Labels: cla: yes

#2539 infra: fix tomservo and nightly build
  WORKSPACE
Labels: cla: yes, type:build/install

#2540 Fix dynamic plugin bootstrap sequence in Firefox
  tensorboard/components/tf_tensorboard/tf-tensorboard.html
Labels: cla: yes, core:frontend

#2545 Fix links for example ops (tf.matmul, tf.nn.relu) in README.md
  README.md
Labels: cla: yes

#2544 graph: provide built-binary for legacy target
  tensorboard/plugins/graph/tf_graph_app/BUILD
Labels: cla: yes, plugin:graph, type:build/install

#2529 data: add partial generic data provider base class
  tensorboard/data/BUILD
  tensorboard/data/provider.py
  tensorboard/data/provider_test.py
Labels: cla: yes, core:backend

#2530 data: add multiplexer provider implementation
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/backend/event_processing/data_provider_test.py
Labels: cla: yes, core:backend

#2531 data: add `--generic_data` flag and `TBContext` field
  tensorboard/backend/BUILD
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/plugins/base_plugin.py
  tensorboard/plugins/core/core_plugin.py
Labels: cla: yes, core:backend

#2532 data: add scalars plugin integration
  tensorboard/plugins/scalar/BUILD
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes, plugin:scalars

#2546 data: add license to `BUILD` file
  tensorboard/data/BUILD
Labels: cla: yes

#2549 deps: upgrade `html5lib==1.0.1`, `bleach==2.0`, `webencodings==0.5.1`
  tensorboard/pip_package/BUILD
  tensorboard/pip_package/build_pip_package.sh
  third_party/bleach.BUILD
  third_party/html5lib.BUILD
  third_party/python.bzl
  third_party/webencodings.BUILD
  third_party/webencodings_license.patch
Labels: cla: yes, type:build/install

#2550 Add `SECURITY.md` with disclosure instructions
  SECURITY.md
Labels: cla: yes, type:docs

#2548 build: fix nondeterministic `tsc` error
  tensorboard/plugins/graph/tf_graph_common/test/hierarchy-test.ts
Labels: cla: yes, type:build/install

#2538 [tensor-widget] Implement support for (0|1|2)D numeric tensors
  tensorboard/components/tensor_widget/BUILD
  tensorboard/components/tensor_widget/demo/demo.html
  tensorboard/components/tensor_widget/demo/demo.ts
  tensorboard/components/tensor_widget/shape-utils-test.ts
  tensorboard/components/tensor_widget/shape-utils.ts
  tensorboard/components/tensor_widget/string-utils-test.ts
  tensorboard/components/tensor_widget/string-utils.ts
  tensorboard/components/tensor_widget/tensor-widget-impl.ts
  tensorboard/components/tensor_widget/tensor-widget.css
  tensorboard/components/tensor_widget/tensor-widget.ts
  tensorboard/components/tensor_widget/types.ts
Labels: cla: yes

#2552 hparams: mark public APIs as stable
  tensorboard/plugins/hparams/api.py
Labels: cla: yes

#2543 added images to nearest neighbors list
  tensorboard/plugins/projector/vz_projector/vz-projector-inspector-panel.html
  tensorboard/plugins/projector/vz_projector/vz-projector-inspector-panel.ts
Labels: cla: yes, plugin:projector, type:feature

#2551 application: fix default flag value in test stub
  tensorboard/backend/application_test.py
Labels: cla: yes

#2560 Make mesh plugin tests TF 2.x–compatible
  tensorboard/plugins/mesh/mesh_plugin_test.py
  tensorboard/plugins/mesh/metadata_test.py
  tensorboard/plugins/mesh/summary.py
  tensorboard/plugins/mesh/summary_test.py
Labels: cla: yes, type:cleanup

#2557 Make audio-related functionality and tests TF 2.x–compatible
  tensorboard/plugins/audio/BUILD
  tensorboard/plugins/audio/audio_plugin_test.py
  tensorboard/plugins/audio/summary.py
  tensorboard/plugins/audio/summary_test.py
  tensorboard/util/BUILD
  tensorboard/util/encoder.py
  tensorboard/util/encoder_test.py
Labels: cla: yes, type:cleanup

#2558 Make `plugin_event_accumulator_test` TF 2.x–compatible
  tensorboard/backend/event_processing/plugin_event_accumulator_test.py
Labels: cla: yes, type:cleanup

#2559 Make `data_compat_test` TF 2.x–compatible
  tensorboard/BUILD
  tensorboard/data_compat_test.py
Labels: cla: yes, type:cleanup

#2563 hparams: remove remaining dependency on TensorFlow
  tensorboard/BUILD
  tensorboard/default.py
  tensorboard/plugins/hparams/BUILD
  tensorboard/plugins/hparams/hparams_plugin.py
  tensorboard/plugins/hparams/hparams_plugin_loader.py
  tensorboard/plugins/hparams/metrics.py
  tensorboard/plugins/hparams/tf_hparams_dashboard/tf-hparams-dashboard.html
Labels: cla: yes

#2556 data: add `list_runs` API call and implementation
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/backend/event_processing/data_provider_test.py
  tensorboard/data/provider.py
  tensorboard/plugins/core/core_plugin.py
Labels: cla: yes

#2564 data: fix and test `__repr__` methods
  tensorboard/data/provider.py
  tensorboard/data/provider_test.py
Labels: cla: yes

#2566 build: remove `//tensorboard:tf_contrib_ffmpeg`
  tensorboard/BUILD
  tensorboard/plugins/audio/BUILD
  tensorboard/util/BUILD
Labels: cla: yes, type:cleanup

#2569 Remove --db_import_use_op flag and implementation
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/backend/event_processing/db_import_multiplexer.py
  tensorboard/backend/event_processing/db_import_multiplexer_test.py
  tensorboard/plugins/core/core_plugin.py
Labels: cla: yes, type:cleanup

#2570 ci: pin TF 1.x nightlies to 2019-08-16
  .travis.yml
Labels: cla: yes, type:build/install

#2568 graph: fixed the node inspector view
  tensorboard/plugins/graph/tf_graph_common/tf-node-icon.html
Labels: cla: yes

#2574 Remove unused TBContext.db_module field
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/plugins/base_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes, type:cleanup

#2577 Remove unused vestigial plugin EventMultiplexer APIs
  tensorboard/backend/event_processing/plugin_event_multiplexer.py
Labels: cla: yes, core:backend, type:cleanup

#2575 Refactor away TensorBoardWSGIApp in its current form
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/plugins/audio/audio_plugin_test.py
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/plugins/debugger/debugger_plugin_testlib.py
  tensorboard/plugins/debugger/interactive_debugger_plugin_test.py
  tensorboard/plugins/image/images_plugin_test.py
  tensorboard/plugins/interactive_inference/interactive_inference_plugin_test.py
  tensorboard/plugins/mesh/mesh_plugin_test.py
  tensorboard/plugins/projector/projector_plugin_test.py
Labels: cla: yes, core:backend, type:cleanup

#2565 [tensor-widget] Add slicing control to support 3D+ tensors
  tensorboard/components/tensor_widget/BUILD
  tensorboard/components/tensor_widget/demo/demo.html
  tensorboard/components/tensor_widget/demo/demo.ts
  tensorboard/components/tensor_widget/shape-utils-test.ts
  tensorboard/components/tensor_widget/shape-utils.ts
  tensorboard/components/tensor_widget/slicing-control.ts
  tensorboard/components/tensor_widget/tensor-widget-impl.ts
  tensorboard/components/tensor_widget/tensor-widget.css
Labels: cla: yes

#2576 Reincarnate TensorBoardWSGIApp as new DataProvider-friendly entry point
  tensorboard/backend/application.py
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/db_import_multiplexer.py
  tensorboard/backend/event_processing/db_import_multiplexer_test.py
Labels: cla: yes, core:backend

#2581 Update wit-widget npm package
  tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
Labels: cla: yes

#2583 [Debugger Plugin] Fix Python unit tests for TF2
  tensorboard/plugins/debugger/debug_graphs_helper_test.py
  tensorboard/plugins/debugger/interactive_debugger_plugin_test.py
  tensorboard/plugins/debugger/session_debug_test.py
Labels: cla: yes

#2582 Allow passing TBPlugin/TBLoader subclasses to TensorBoardWSGIApp
  tensorboard/BUILD
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/default.py
  tensorboard/plugins/base_plugin.py
  tensorboard/program.py
  tensorboard/program_test.py
Labels: cla: yes, type:cleanup

#2585 projector: compile the projector HTML binary
  tensorboard/plugins/projector/tf_projector_plugin/BUILD
Labels: cla: yes, plugin:projector

#2588 DOC: Fix broken summary link
  docs/r1/overview.md
Labels: cla: yes, type:docs

#2586 Create `tf-wbr-string` for safe word-breaking
  tensorboard/components/tf_runs_selector/BUILD
  tensorboard/components/tf_runs_selector/tf-runs-selector.html
  tensorboard/components/tf_runs_selector/tf-wbr-string.html
Labels: cla: yes, core:frontend

#2580 data: plumb experiment ID through runs and scalars
  tensorboard/components/tf_backend/router.ts
  tensorboard/components/tf_backend/runsStore.ts
  tensorboard/components/tf_backend/test/backendTests.ts
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Labels: cla: yes, core:frontend, type:feature

#2593 Look for `tensorflow_core._api` in summary component package
  tensorboard/summary/_tf/summary/__init__.py
Labels: cla: yes, core:summaries

#2592 scalars: appear active when data provider present
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes

#2591 tf-tensorboard: fix inactive menu hiding
  tensorboard/components/tf_tensorboard/tf-tensorboard.html
Labels: cla: yes, core:frontend, type:bug

#2600 ui: fix help animation for line chart
  tensorboard/components/vz_line_chart2/panZoomDragLayer.html
  tensorboard/components/vz_line_chart2/panZoomDragLayer.ts
  tensorboard/components/vz_line_chart2/vz-line-chart2.html
Labels: cla: yes

#2602 [tensor-widget] Further prep for sync'ing
  tensorboard/components/tensor_widget/BUILD
  tensorboard/components/tensor_widget/tensor-widget-impl.ts
  tensorboard/components/tensor_widget/tsconfig.json
  tensorboard/defs/defs.bzl
Labels: cla: yes

#2606 Promote `FrontendMetadata` from `namedtuple` to struct
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/plugin.py
  tensorboard/http_api.md
  tensorboard/plugins/BUILD
  tensorboard/plugins/audio/audio_plugin.py
  tensorboard/plugins/base_plugin.py
  tensorboard/plugins/base_plugin_test.py
  tensorboard/plugins/beholder/beholder_plugin.py
  tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
  tensorboard/plugins/debugger/debugger_plugin.py
  tensorboard/plugins/debugger/debugger_plugin_loader.py
  tensorboard/plugins/debugger/interactive_debugger_plugin.py
  tensorboard/plugins/distribution/distributions_plugin.py
  tensorboard/plugins/graph/graphs_plugin.py
  tensorboard/plugins/histogram/histograms_plugin.py
  tensorboard/plugins/hparams/hparams_plugin.py
  tensorboard/plugins/image/images_plugin.py
  tensorboard/plugins/interactive_inference/interactive_inference_plugin.py
  tensorboard/plugins/mesh/mesh_plugin.py
  tensorboard/plugins/pr_curve/pr_curves_plugin.py
  tensorboard/plugins/profile/profile_plugin.py
  tensorboard/plugins/projector/projector_plugin.py
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/text/text_plugin.py
Labels: cla: yes, core:backend

#2608 build: make use of tf_ts_library
  tensorboard/components/tf_ng_tensorboard/core/BUILD
  tensorboard/components/tf_ng_tensorboard/header/BUILD
  tensorboard/components/tf_ng_tensorboard/plugins/BUILD
  tensorboard/components/tf_ng_tensorboard/testing/BUILD
  tensorboard/components/tf_ng_tensorboard/types/BUILD
Labels: cla: yes

#2609 Upgrade protobuf to fix compilation warnings
  WORKSPACE
Labels: cla: yes, type:build/install
