Repository tensorflow/tensorboard, pull requests merged in 2019-07, with the labels that each got.

#2406 build: removed bin/genfile prefix in declare_file
  tensorboard/defs/vulcanize.bzl
  tensorboard/defs/web.bzl
  third_party/clutz.bzl
Labels: type:build/install

#2389 doc: update how to write plugin doc
  tensorboard/plugins/example/README.md
Labels: cla: yes

#2420 build: add mnemonics to actions
  tensorboard/defs/vulcanize.bzl
  tensorboard/defs/web.bzl
  tensorboard/defs/zipper.bzl
Labels: cla: yes

#2422 extract_pip_package: allow specifying output dir
  tensorboard/pip_package/extract_pip_package.sh
Labels: cla: yes, type:build/install

#2414 Add inference error messages in WIT notebook mode
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/BUILD
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
  tensorboard/plugins/interactive_inference/witwidget/notebook/colab/wit.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/lib/wit.js
  tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/wit.py
Labels: cla: yes, plugin:what-if-tool

#2426 New witwidget version
  tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
  tensorboard/plugins/interactive_inference/witwidget/version.py
Labels: cla: yes

#2373 Support undefined number of data points in the mesh.
  tensorboard/plugins/mesh/http_api.md
  tensorboard/plugins/mesh/mesh_plugin.py
  tensorboard/plugins/mesh/mesh_plugin_test.py
  tensorboard/plugins/mesh/metadata.py
  tensorboard/plugins/mesh/metadata_test.py
  tensorboard/plugins/mesh/plugin_data.proto
  tensorboard/plugins/mesh/summary.py
  tensorboard/plugins/mesh/summary_test.py
  tensorboard/plugins/mesh/tf_mesh_dashboard/mesh-loader.js
  third_party/js.bzl
Labels: cla: yes

#2419 core: update polymer2 externs
  tensorboard/components/tf_imports/BUILD
  tensorboard/components/tf_imports/polymer-externs.html
  tensorboard/components/tf_imports/polymer.html
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/BUILD
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
  third_party/js.bzl
  third_party/polymer.bzl
Labels: cla: yes

#2429 vulcanize: factor out `removeNode` helper
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes, type:cleanup

#2430 vulcanize: drop deprecated argument to `TextNode`
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes, type:cleanup

#2427 docs: update CC/Apache license name
  docs/_project.yaml
Labels: cla: yes, type:docs

#2417 text: remove legacy `PluginAsset` support
  tensorboard/plugins/text/BUILD
  tensorboard/plugins/text/text_plugin.py
  tensorboard/plugins/text/text_plugin_test.py
Labels: cla: yes, plugin:text, type:feature

#2434 Add median stats to What-If Tool regression performance stats table
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Labels: cla: yes, plugin:what-if-tool

#2436 Revert "vulcanize: drop deprecated argument to `TextNode` (#2430)"
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes

#2439 Add FAQ entry describing TB behavior without TF
  README.md
Labels: cla: yes, type:docs

#2442 hparams: allow setting trial ID
  tensorboard/plugins/hparams/keras.py
  tensorboard/plugins/hparams/keras_test.py
  tensorboard/plugins/hparams/summary_v2.py
  tensorboard/plugins/hparams/summary_v2_test.py
  tensorboard/plugins/hparams/tf_hparams_table_view/tf-hparams-table-view.html
Labels: plugin:hparams, type:feature

#2423 Fix HTML syntax and structure errors
  tensorboard/components/tf_dashboard_common/tf-dropdown-trigger.html
  tensorboard/components/tf_dashboard_common/tf-no-data-warning.html
  tensorboard/components/vz_example_viewer/vz-example-viewer.html
  tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.html
  tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-multi-line-chart-card.html
  tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-view.html
  tensorboard/plugins/graph/tf_graph_common/tf-graph-icon.html
  tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-dashboard.html
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-inference-viewer.html
  tensorboard/plugins/profile/input_pipeline_analyzer/input-pipeline-analyzer.html
  tensorboard/plugins/profile/overview_page/overview-page.html
  tensorboard/plugins/profile/tf_profile_dashboard/tf-profile-dashboard.html
  tensorboard/plugins/projector/vz_projector/vz-projector-bookmark-panel.html
Labels: type:cleanup

#2428 [debugger plugin] Initial check in of tensor-widget code
  tensorboard/components/tensor_widget/BUILD
  tensorboard/components/tensor_widget/README.md
  tensorboard/components/tensor_widget/health-pill-types.ts
  tensorboard/components/tensor_widget/tensor-widget.html
  tensorboard/components/tensor_widget/tensor-widget.ts
  tensorboard/components/tensor_widget/types.ts
  tensorboard/plugins/debugger/tf_debugger_dashboard/BUILD
Labels: plugin:debugger

#2463 build_pip_package: print build log on failure
  tensorboard/pip_package/build_pip_package.sh
Labels: type:build/install

#2460 [debugger plugin] Fix panToNode
  tensorboard/plugins/graph/tf_graph_common/scene.ts
Labels: plugin:debugger, plugin:graph, type:bug

#2468 Update get_started.ipynb
  docs/r2/get_started.ipynb
Labels: type:docs

#2470 notebook: improve cross-version compatibility
  tensorboard/manager.py
  tensorboard/manager_test.py
Labels: core:backend, type:feature

#2462 What-If Tool: Fix error message overflow issue
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Labels: plugin:what-if-tool, type:bug

#1867 Add option to read multiple active event files per directory
  README.md
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/directory_loader.py
  tensorboard/backend/event_processing/directory_loader_test.py
  tensorboard/backend/event_processing/event_file_loader.py
  tensorboard/backend/event_processing/plugin_event_accumulator.py
  tensorboard/backend/event_processing/plugin_event_accumulator_test.py
  tensorboard/backend/event_processing/plugin_event_multiplexer.py
  tensorboard/backend/event_processing/plugin_event_multiplexer_test.py
  tensorboard/plugins/core/core_plugin.py
  tensorboard/util/test_util.py
Labels: cla: yes, core:backend, core:summaries

#2475 [debugger plugin] Temporary solution to avoid double stamping
  tensorboard/plugins/debugger/BUILD
  tensorboard/plugins/debugger/debugger_plugin.py
  tensorboard/plugins/debugger/debugger_plugin_loader.py
  tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
Labels: cla: yes, plugin:debugger

#2478 backend: eliminate unnecessary metaprogramming
  tensorboard/backend/event_processing/plugin_event_accumulator.py
Labels: cla: yes, core:backend, type:cleanup

#2482 Fix warning with numpy 17.x+
  tensorboard/compat/tensorflow_stub/dtypes.py
Labels: cla: yes
