Repository tensorflow/tensorboard, pull requests merged in 2019-12, with the labels that each got.

#2988 Temporarily disable dynamic plugin smoke test to unbreak build
  tensorboard/examples/plugins/example_basic/BUILD
Labels: cla: yes, type:build/install

#2986 Use `tensorboard.errors` in histograms and distributions
  tensorboard/plugins/distribution/BUILD
  tensorboard/plugins/distribution/distributions_plugin.py
  tensorboard/plugins/distribution/distributions_plugin_test.py
  tensorboard/plugins/histogram/BUILD
  tensorboard/plugins/histogram/histograms_plugin.py
  tensorboard/plugins/histogram/histograms_plugin_test.py
Labels: cla: yes, plugin:distributions, plugin:histogram

#2979 data: add tensor support to data provider interface
  tensorboard/data/BUILD
  tensorboard/data/provider.py
  tensorboard/data/provider_test.py
Labels: cla: yes, core:backend, type:feature

#2980 data: add tensor support to multiplexer provider
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/backend/event_processing/data_provider_test.py
Labels: cla: yes, core:backend, type:feature

#2989 histograms: omit empty runs from `/tags` route
  tensorboard/plugins/distribution/distributions_plugin_test.py
  tensorboard/plugins/distribution/http_api.md
  tensorboard/plugins/histogram/histograms_plugin.py
  tensorboard/plugins/histogram/histograms_plugin_test.py
  tensorboard/plugins/histogram/http_api.md
Labels: cla: yes, plugin:histogram

#2981 data: add histograms plugin integration
  tensorboard/plugins/distribution/BUILD
  tensorboard/plugins/distribution/distributions_plugin.py
  tensorboard/plugins/distribution/distributions_plugin_test.py
  tensorboard/plugins/histogram/BUILD
  tensorboard/plugins/histogram/histograms_plugin.py
  tensorboard/plugins/histogram/histograms_plugin_test.py
Labels: cla: yes, plugin:histogram, type:feature

#2955 documentaion: Update tensorflow tutorial links. Add a link to hosted TensorBoard
  README.md
Labels: cla: yes

#2992 (colab) Add 'list' and 'delete' to tbdev
  docs/tbdev_getting_started.ipynb
Labels: cla: yes

#2898 updating umap version
  tensorboard/plugins/projector/vz_projector/umap.d.ts
  third_party/js.bzl
Labels: cla: yes

#2994 data: define `convert_*_event` at module level
  tensorboard/backend/event_processing/data_provider.py
Labels: cla: yes, core:backend

#2840 Align stub GFile with current TF FileIO API
  tensorboard/compat/tensorflow_stub/BUILD
  tensorboard/compat/tensorflow_stub/io/gfile.py
  tensorboard/compat/tensorflow_stub/io/gfile_tf_test.py
Labels: cla: yes

#2991 Graph plugin: Read from Data Provider
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/backend/event_processing/event_multiplexer.py
  tensorboard/backend/event_processing/plugin_event_accumulator.py
  tensorboard/backend/event_processing/plugin_event_accumulator_test.py
  tensorboard/backend/event_processing/plugin_event_multiplexer.py
  tensorboard/data/provider.py
  tensorboard/plugins/graph/BUILD
  tensorboard/plugins/graph/graphs_plugin.py
  tensorboard/plugins/graph/graphs_plugin_test.py
  tensorboard/plugins/graph/graphs_plugin_v2_test.py
  third_party/python.bzl
Labels: cla: yes

#2996 Expose visibility for build rules needed for WIT dynamic plugin
  tensorboard/components/BUILD
  tensorboard/components/vz_line_chart2/BUILD
Labels: cla: yes

#2993 web.bzl: avoid depset union operators
  tensorboard/defs/web.bzl
Labels: cla: yes, type:build/install

#2973 docs: remove outdated `bazel-bin` instructions
  DEVELOPMENT.md
Labels: cla: yes, type:docs

#3000 data: require experiment ID in multiplexer provider
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/plugins/graph/graphs_plugin_test.py
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes, core:backend

#3001 Fix graph plugin with data provider, and its test
  tensorboard/plugins/graph/graphs_plugin.py
  tensorboard/plugins/graph/graphs_plugin_test.py
Labels: cla: yes

#3010 readme: update Travis badge to travis-ci.org
  README.md
Labels: cla: yes, type:docs

#3011 ng-tensorboard: Fix iframe based plugin rendering
  tensorboard/webapp/plugins/BUILD
  tensorboard/webapp/plugins/plugins.component.css
  tensorboard/webapp/plugins/plugins.component.html
  tensorboard/webapp/plugins/plugins.component.ts
  tensorboard/webapp/plugins/plugins.container.test.ts
  tensorboard/webapp/plugins/plugins.container.ts
  tensorboard/webapp/plugins/plugins.module.ts
Labels: cla: yes

#2999 Add link to TensorBoard.dev from tensorboard base page.
  docs/_index.yaml
Labels: cla: yes

#3016 notebook: fix `cgi.escape` for Python 3.8
  tensorboard/notebook.py
Labels: cla: yes, core:backend, type:bug

#3019 Fixed the typing on ts 3.7+
  tensorboard/webapp/plugins/plugins.component.ts
Labels: cla: yes

#3020 ng: fixed the TS conformance issue
  tensorboard/webapp/plugins/plugins.component.ts
Labels: cla: yes

#3021 pylint: remove long-line suppressions on imports
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/backend/event_processing/plugin_event_multiplexer.py
  tensorboard/backend/event_processing/plugin_event_multiplexer_test.py
  tensorboard/plugins/audio/audio_plugin_test.py
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
  tensorboard/plugins/custom_scalar/summary_test.py
  tensorboard/plugins/debugger/debugger_plugin_test.py
  tensorboard/plugins/debugger/debugger_plugin_testlib.py
  tensorboard/plugins/debugger/events_writer_manager_test.py
  tensorboard/plugins/debugger/interactive_debugger_plugin_test.py
  tensorboard/plugins/distribution/distributions_plugin_test.py
  tensorboard/plugins/graph/graphs_plugin.py
  tensorboard/plugins/graph/graphs_plugin_test.py
  tensorboard/plugins/histogram/histograms_plugin_test.py
  tensorboard/plugins/image/images_plugin_test.py
  tensorboard/plugins/interactive_inference/interactive_inference_plugin_test.py
  tensorboard/plugins/pr_curve/pr_curves_plugin_test.py
  tensorboard/plugins/profile/profile_plugin.py
  tensorboard/plugins/profile/profile_plugin_test.py
  tensorboard/plugins/projector/projector_plugin_test.py
  tensorboard/plugins/scalar/scalars_plugin_test.py
  tensorboard/plugins/text/text_plugin_test.py
Labels: cla: yes, type:cleanup

#3022 pylint: remove `g-import-not-at-top` suppressions
  tensorboard/__init__.py
  tensorboard/backend/application_test.py
  tensorboard/backend/event_processing/directory_loader_test.py
  tensorboard/backend/http_util_test.py
  tensorboard/backend/security_validator_test.py
  tensorboard/compat/__init__.py
  tensorboard/default_test.py
  tensorboard/lazy_test.py
  tensorboard/main.py
  tensorboard/manager_e2e_test.py
  tensorboard/manager_test.py
  tensorboard/plugins/beholder/__init__.py
  tensorboard/plugins/beholder/beholder_plugin_loader.py
  tensorboard/plugins/debugger/debugger_plugin_loader.py
  tensorboard/plugins/debugger/debugger_plugin_testlib.py
  tensorboard/plugins/hparams/backend_context_test.py
  tensorboard/plugins/hparams/keras_test.py
  tensorboard/plugins/hparams/list_metric_evals_test.py
  tensorboard/plugins/hparams/list_session_groups_test.py
  tensorboard/plugins/hparams/summary_v2_test.py
  tensorboard/plugins/interactive_inference/interactive_inference_plugin_loader.py
  tensorboard/plugins/interactive_inference/interactive_inference_plugin_test.py
  tensorboard/plugins/interactive_inference/utils/inference_utils_test.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/visualization.py
  tensorboard/plugins/mesh/mesh_plugin_test.py
  tensorboard/plugins/profile/profile_plugin_loader.py
  tensorboard/program_test.py
  tensorboard/summary/_tf/summary/__init__.py
  tensorboard/uploader/exporter_test.py
  tensorboard/uploader/uploader_test.py
  tensorboard/uploader/util_test.py
Labels: cla: yes, type:cleanup

#3023 black: manually format CRC table
  tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py
Labels: cla: yes, type:cleanup

#3024 python: fix invalid escape sequences
  tensorboard/backend/application_test.py
  tensorboard/manager_test.py
Labels: cla: yes, type:cleanup

#3025 pylint: remove unnecessary long-line suppressions
  tensorboard/compat/tensorflow_stub/errors.py
  tensorboard/plugins/debugger/debugger_plugin_loader.py
  tensorboard/plugins/debugger/debugger_server_lib.py
  tensorboard/plugins/interactive_inference/interactive_inference_plugin_loader.py
Labels: cla: yes, type:cleanup

#3013 plugins: add raw scalars example plugin
  tensorboard/examples/plugins/example_raw_scalars/.gitignore
  tensorboard/examples/plugins/example_raw_scalars/BUILD
  tensorboard/examples/plugins/example_raw_scalars/README.md
  tensorboard/examples/plugins/example_raw_scalars/setup.py
  tensorboard/examples/plugins/example_raw_scalars/smoke_test.sh
  tensorboard/examples/plugins/example_raw_scalars/tensorboard_plugin_example_raw_scalars/__init__.py
  tensorboard/examples/plugins/example_raw_scalars/tensorboard_plugin_example_raw_scalars/demo.py
  tensorboard/examples/plugins/example_raw_scalars/tensorboard_plugin_example_raw_scalars/plugin.py
  tensorboard/examples/plugins/example_raw_scalars/tensorboard_plugin_example_raw_scalars/static/index.js
  tensorboard/examples/plugins/example_raw_scalars/tensorboard_plugin_example_raw_scalars/static/model.js
  tensorboard/examples/plugins/example_raw_scalars/tensorboard_plugin_example_raw_scalars/static/style.css
  tensorboard/examples/plugins/example_raw_scalars/tensorboard_plugin_example_raw_scalars/static/views.js
Labels: cla: yes

#3039 pip_package: strip file timestamps from wheel
  tensorboard/pip_package/build_pip_package.sh
Labels: cla: yes, type:build/install

#3045 deps: factor out `requirements.txt` files
  tensorboard/pip_package/BUILD
  tensorboard/pip_package/build_pip_package.sh
  tensorboard/pip_package/requirements.txt
  tensorboard/pip_package/requirements_dev.txt
  tensorboard/pip_package/setup.py
Labels: cla: yes, type:build/install

#3047 test: fix concurrent web test execution
  tensorboard/defs/web.bzl
  tensorboard/defs/web_testing.bzl
Labels: cla: yes, type:build/install

#3037 Rename Angular files to match internal style guide
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_module.ts
  tensorboard/webapp/BUILD
  tensorboard/webapp/app_container.css
  tensorboard/webapp/app_container.ng.html
  tensorboard/webapp/app_container.ts
  tensorboard/webapp/app_module.ts
  tensorboard/webapp/bootstrap.ts
  tensorboard/webapp/config_dev.ts
  tensorboard/webapp/config_prod.ts
  tensorboard/webapp/core/BUILD
  tensorboard/webapp/core/actions/BUILD
  tensorboard/webapp/core/actions/core_actions.ts
  tensorboard/webapp/core/actions/index.ts
  tensorboard/webapp/core/core_module.ts
  tensorboard/webapp/core/effects/BUILD
  tensorboard/webapp/core/effects/core_effects.ts
  tensorboard/webapp/core/effects/core_effects_test.ts
  tensorboard/webapp/core/effects/index.ts
  tensorboard/webapp/core/store/BUILD
  tensorboard/webapp/core/store/core_reducers.ts
  tensorboard/webapp/core/store/core_reducers_test.ts
  tensorboard/webapp/core/store/core_selectors.ts
  tensorboard/webapp/core/store/core_types.ts
  tensorboard/webapp/core/store/index.ts
  tensorboard/webapp/core/testing/index.ts
  tensorboard/webapp/header/BUILD
  tensorboard/webapp/header/header_component.css
  tensorboard/webapp/header/header_component.ng.html
  tensorboard/webapp/header/header_component.ts
  tensorboard/webapp/header/header_container.ts
  tensorboard/webapp/header/header_module.ts
  tensorboard/webapp/header/header_test.ts
  tensorboard/webapp/main.ts
  tensorboard/webapp/main_prod.ts
  tensorboard/webapp/plugins/BUILD
  tensorboard/webapp/plugins/plugins_component.ng.html
  tensorboard/webapp/plugins/plugins_component.ts
  tensorboard/webapp/plugins/plugins_container.ts
  tensorboard/webapp/plugins/plugins_container_test.ts
  tensorboard/webapp/plugins/plugins_module.ts
  tensorboard/webapp/reloader/BUILD
  tensorboard/webapp/reloader/reloader_component.ts
  tensorboard/webapp/reloader/reloader_component_test.ts
  tensorboard/webapp/reloader/reloader_module.ts
  tensorboard/webapp/settings/BUILD
  tensorboard/webapp/settings/dialog_component.css
  tensorboard/webapp/settings/dialog_component.ts
  tensorboard/webapp/settings/dialog_component_test.ts
  tensorboard/webapp/settings/settings_button_component.ts
  tensorboard/webapp/settings/settings_module.ts
  tensorboard/webapp/webapp_data_source/BUILD
  tensorboard/webapp/webapp_data_source/tb_server_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_server_data_source_module.ts
Labels: cla: yes

#3033 docs: add instructions for linting Python code
  DEVELOPMENT.md
Labels: cla: yes, type:docs

#3048 graph: getGradient should always return a string
  tensorboard/plugins/graph/tf_graph_common/node.ts
Labels: cla: yes

#3046 ci: use `requirements.txt` sources of truth
  .travis.yml
Labels: cla: yes, type:build/install

#3044 as_numpy_dtype is a property, not a method
  tensorboard/compat/tensorflow_stub/dtypes.py
Labels: cla: yes

#3049 cleanup: fix badly dedented strings
  tensorboard/backend/application.py
  tensorboard/backend/event_processing/db_import_multiplexer_test.py
  tensorboard/backend/event_processing/reservoir.py
  tensorboard/backend/event_processing/sqlite_writer.py
  tensorboard/examples/plugins/example_raw_scalars/tensorboard_plugin_example_raw_scalars/plugin.py
  tensorboard/manager_e2e_test.py
  tensorboard/notebook.py
  tensorboard/plugin_util_test.py
  tensorboard/plugins/beholder/im_util.py
  tensorboard/plugins/beholder/visualizer.py
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
  tensorboard/plugins/graph/graph_util_test.py
  tensorboard/plugins/graph/keras_util.py
  tensorboard/plugins/graph/keras_util_test.py
  tensorboard/plugins/histogram/histograms_plugin.py
  tensorboard/plugins/hparams/backend_context_test.py
  tensorboard/plugins/hparams/keras_test.py
  tensorboard/plugins/hparams/list_metric_evals_test.py
  tensorboard/plugins/hparams/list_session_groups_test.py
  tensorboard/plugins/hparams/summary_v2.py
  tensorboard/plugins/hparams/summary_v2_test.py
  tensorboard/plugins/image/images_plugin.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/colab/wit.py
  tensorboard/plugins/pr_curve/pr_curves_plugin.py
  tensorboard/plugins/profile/trace_events_json_test.py
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/text/text_plugin_test.py
  tensorboard/scripts/generate_testdata.py
  tensorboard/tools/diagnose_tensorboard.py
  tensorboard/uploader/uploader_main.py
Labels: cla: yes, type:cleanup

#3059 hparams: accept Numpy scalars as hyperparameter values
  tensorboard/plugins/hparams/BUILD
  tensorboard/plugins/hparams/summary_v2.py
  tensorboard/plugins/hparams/summary_v2_test.py
Labels: cla: yes, plugin:hparams, type:feature

#3064 [DebuggerV2] Move constituent views of the debugger-v2 plugin to views/
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_module.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/inactive/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/inactive/inactive_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/inactive/inactive_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/inactive/inactive_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/inactive/inactive_container.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/inactive/inactive_module.ts
Labels: cla: yes

#3052 mesh: encapsulate access to caches
  tensorboard/plugins/mesh/mesh_plugin.py
Labels: cla: yes, plugin:mesh

#3071 Remove empty `secure_download.sh`
  ci/secure_download.sh
Labels: cla: yes

#3070 Upgrade Travis to Xenial and floating tf-nightly
  .travis.yml
Labels: cla: yes

#3053 mesh: replace broken caches with direct lookups
  tensorboard/plugins/mesh/mesh_plugin.py
  tensorboard/plugins/mesh/mesh_plugin_test.py
Labels: cla: yes, plugin:mesh, type:bug

#3080 Fix broken What-If Tool path string
  tensorboard/plugins/interactive_inference/witwidget/notebook/colab/wit.py
Labels: cla: yes

#3083 [cleanup] add dependency on material icon
  tensorboard/webapp/BUILD
Labels: cla: yes

#3079 Add list of cleanup commits for `blame.ignoreRevsFile`
  .git-blame-ignore-revs
  DEVELOPMENT.md
Labels: cla: yes, type:cleanup

#3084 [ng] strict dep on settings test
  tensorboard/webapp/settings/BUILD
Labels: cla: yes

#3082 [JS] upgrade dependencies
  angular-metadata.tsconfig.json
  package.json
  tensorboard/webapp/core/effects/core_effects.ts
  yarn.lock
Labels: cla: yes

#3087 Revert zone.js upgrade and pin to 0.9
  package.json
  yarn.lock
Labels: cla: yes
