Repository tensorflow/tensorboard, pull requests merged in 2019-09, with the labels that each got.

#2611 Properly handle bad requests to plugin data endpoints
  tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/plugin.py
  tensorboard/plugins/audio/audio_plugin.py
  tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
  tensorboard/plugins/image/images_plugin.py
  tensorboard/plugins/mesh/mesh_plugin.py
  tensorboard/plugins/scalar/scalars_plugin.py
Labels: cla: yes, type:bug

#2605 scalar: fix tiny chart
  tensorboard/components/tf_paginated_view/test/categoryPaginatedViewTests.ts
  tensorboard/components/tf_paginated_view/test/tests.html
  tensorboard/components/tf_paginated_view/tf-category-paginated-view.html
  tensorboard/components/tf_paginated_view/tf-dom-repeat.html
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Labels: cla: yes

#2610 build: make ng source sync-able
  tensorboard/components/tf_ng_tensorboard/BUILD
  tensorboard/components/tf_ng_tensorboard/angular/BUILD
  tensorboard/components/tf_ng_tensorboard/app.component.ts
  tensorboard/components/tf_ng_tensorboard/app.module.ts
  tensorboard/components/tf_ng_tensorboard/core/BUILD
  tensorboard/components/tf_ng_tensorboard/core/core.actions.ts
  tensorboard/components/tf_ng_tensorboard/core/core.effects.test.ts
  tensorboard/components/tf_ng_tensorboard/core/core.effects.ts
  tensorboard/components/tf_ng_tensorboard/core/core.reducers.test.ts
  tensorboard/components/tf_ng_tensorboard/core/core.reducers.ts
  tensorboard/components/tf_ng_tensorboard/core/core.service.ts
  tensorboard/components/tf_ng_tensorboard/header/BUILD
  tensorboard/components/tf_ng_tensorboard/header/containers/header.component.test.ts
  tensorboard/components/tf_ng_tensorboard/header/containers/header.component.ts
  tensorboard/components/tf_ng_tensorboard/plugins/BUILD
  tensorboard/components/tf_ng_tensorboard/plugins/plugins.component.test.ts
  tensorboard/components/tf_ng_tensorboard/plugins/plugins.component.ts
  tensorboard/components/tf_ng_tensorboard/testing/BUILD
  tensorboard/components/tf_ng_tensorboard/types/api.ts
  tensorboard/defs/defs.bzl
  tsconfig.json
Labels: cla: yes

#2613 scalars: include experiment ID in download links
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
Labels: cla: yes

#2594 [tensor-widget] Add detailed-value tooltip and single-element selection
  tensorboard/components/tensor_widget/BUILD
  tensorboard/components/tensor_widget/selection-test.ts
  tensorboard/components/tensor_widget/selection.ts
  tensorboard/components/tensor_widget/shape-utils-test.ts
  tensorboard/components/tensor_widget/shape-utils.ts
  tensorboard/components/tensor_widget/slicing-control.ts
  tensorboard/components/tensor_widget/tensor-widget-impl.ts
  tensorboard/components/tensor_widget/tensor-widget.css
  tensorboard/components/tensor_widget/types.ts
Labels: cla: yes

#2618 data: make `ScalarTimeSeries` and `ScalarDatum` value types
  tensorboard/data/provider.py
  tensorboard/data/provider_test.py
Labels: cla: yes

#2625 build: disable mesh summary v2 test
  tensorboard/plugins/mesh/BUILD
Labels: cla: yes

#2626 core: remove unused `mode` on `/data/environment`
  tensorboard/components/tf_backend/environmentStore.ts
  tensorboard/http_api.md
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
Labels: cla: yes, core:frontend

#2623 [debugger] Add bool & string support; Utilize TensorWidget for visualization of 3D+ tensors
  tensorboard/components/tensor_widget/BUILD
  tensorboard/components/tensor_widget/demo/demo.html
  tensorboard/components/tensor_widget/demo/demo.ts
  tensorboard/components/tensor_widget/dtype-utils-test.ts
  tensorboard/components/tensor_widget/dtype-utils.ts
  tensorboard/components/tensor_widget/slicing-control.ts
  tensorboard/components/tensor_widget/string-utils-test.ts
  tensorboard/components/tensor_widget/string-utils.ts
  tensorboard/components/tensor_widget/tensor-widget-impl.ts
  tensorboard/components/tensor_widget/tensor-widget.html
  tensorboard/plugins/debugger/tf_debugger_dashboard/tensor-shape-helper.ts
  tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
  tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-multi-view.html
  tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-view.html
Labels: cla: yes

#2629 Update protobuf and protobuf_js workspace deps to 3.8.0
  WORKSPACE
  third_party/workspace.bzl
Labels: cla: yes

#2633 ui: fix run selector toggle all with many items
  tensorboard/components/tf_dashboard_common/tf-multi-checkbox.ts
Labels: cla: yes

#2630 Add What-If Tool developers guide doc
  tensorboard/plugins/interactive_inference/DEVELOPMENT.md
  tensorboard/plugins/interactive_inference/README.md
Labels: cla: yes

#2640 proto: sync to TensorFlow v1.15.0-rc0
  tensorboard/compat/proto/config.proto
  tensorboard/compat/proto/debug.proto
  tensorboard/compat/proto/meta_graph.proto
  tensorboard/compat/proto/node_def.proto
  tensorboard/compat/proto/op_def.proto
  tensorboard/compat/proto/resource_handle.proto
  tensorboard/compat/proto/rewriter_config.proto
  tensorboard/compat/proto/saved_object_graph.proto
  tensorboard/compat/proto/struct.proto
  tensorboard/compat/proto/types.proto
  tensorboard/compat/proto/variable.proto
  tensorboard/compat/proto/verifier_config.proto
Labels: cla: yes

#2657 build: make tensor_widget build with JSComp
  tensorboard/components/tensor_widget/BUILD
  tensorboard/components/tensor_widget/externs.js
  tensorboard/components/tensor_widget/tensor-widget-interop.ts
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/externs.js
  tensorboard/plugins/debugger/tf_debugger_dashboard/tf-tensor-value-view.html
Labels: cla: yes

#2616 ng: render inactive plugins
  tensorboard/components/tf_ng_tensorboard/header/containers/header.component.css
  tensorboard/components/tf_ng_tensorboard/header/containers/header.component.html
  tensorboard/components/tf_ng_tensorboard/header/containers/header.component.test.ts
  tensorboard/components/tf_ng_tensorboard/header/containers/header.component.ts
  tensorboard/components/tf_ng_tensorboard/header/header.module.ts
Labels: cla: yes

#2627 data: expose `data_location` integration point
  tensorboard/backend/application.py
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/backend/event_processing/data_provider_test.py
  tensorboard/components/tf_backend/environmentStore.ts
  tensorboard/components/tf_backend/router.ts
  tensorboard/components/tf_backend/test/backendTests.ts
  tensorboard/data/provider.py
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes, core:backend

#2617 ng, cleanup: stricter lint
  tensorboard/components/tf_ng_tensorboard/app.component.ts
  tensorboard/components/tf_ng_tensorboard/core/core.effects.ts
  tensorboard/components/tf_ng_tensorboard/core/core.service.ts
  tensorboard/components/tf_ng_tensorboard/plugins/plugins.component.ts
Labels: cla: yes

#2653 build: add sourceURL to map scripts in devtools
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes

#2659 sync: fix the ng_tensorboard deps definition
  tensorboard/components/tf_ng_tensorboard/angular/BUILD
  tensorboard/components/tf_ng_tensorboard/header/BUILD
Labels: cla: yes, type:build/install

#2631 errors: add unified error types
  tensorboard/BUILD
  tensorboard/__init__.py
  tensorboard/backend/BUILD
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/errors.py
  tensorboard/errors_test.py
  tensorboard/pip_package/test_pip_package.sh
  tensorboard/plugins/scalar/BUILD
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes, core:backend

#2632 data: specify error semantics
  tensorboard/data/provider.py
Labels: cla: yes, core:backend

#2655 ci: upgrade flake8 and yamllint
  .travis.yml
  tensorboard/compat/tensorflow_stub/io/gfile_s3_test.py
  tensorboard/plugins/interactive_inference/interactive_inference_plugin.py
Labels: cla: yes, type:build/install

#2656 hparams: remove `Experiment` from public API docs
  tensorboard/plugins/hparams/api.py
Labels: cla: yes, plugin:hparams, type:docs

#2461 What-If Tool: Add ability to sort PD plots by interestingness
  tensorboard/plugins/interactive_inference/interactive_inference_plugin.py
  tensorboard/plugins/interactive_inference/interactive_inference_plugin_test.py
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo/tf-interactive-inference-age-demo.html
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo/tf-interactive-inference-demo.html
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo/tf-interactive-inference-iris-demo.html
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo/tf-interactive-inference-multi-demo.html
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
  tensorboard/plugins/interactive_inference/utils/inference_utils.py
  tensorboard/plugins/interactive_inference/utils/inference_utils_test.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/colab/wit.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/lib/wit.js
  tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/wit.py
Labels: cla: yes

#2664 core: split magic `--logdir_spec` out from verbatim `--logdir`
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/program.py
Labels: cla: yes, core:backend

#2665 projector: visualize_embeddings API change
  tensorboard/plugins/projector/BUILD
  tensorboard/plugins/projector/__init__.py
  tensorboard/plugins/projector/projector_api_test.py
Labels: cla: yes

#2666 cleanup: set style using CSS
  tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
Labels: cla: yes

#2668 ci: pin to non-broken estimator nightlies
  .travis.yml
Labels: cla: yes, type:build/install

#2667 infra: upgrade threejs to r108
  third_party/js.bzl
Labels: cla: yes

#2670 summary: export v2 symbols as defaults
  tensorboard/pip_package/test_pip_package.sh
  tensorboard/summary/__init__.py
  tensorboard/summary/summary_test.py
Labels: cla: yes, core:summaries, tf-2.0

#2589 core: bind to localhost rather than all interfaces
  README.md
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/program.py
  tensorboard/program_test.py
Labels: cla: yes, core:backend

#2672 Release 2.0.0
  .travis.yml
  RELEASE.md
  tensorboard/compat/proto/config.proto
  tensorboard/compat/proto/meta_graph.proto
  tensorboard/compat/proto/rewriter_config.proto
  tensorboard/compat/proto/variable.proto
  tensorboard/compat/proto/verifier_config.proto
  tensorboard/version.py
Labels: cla: yes

#2662 Make example_basic smoke test work on MacOS
  tensorboard/examples/plugins/example_basic/smoke_test.sh
Labels: cla: yes

#2679 Fix StopIteration issue in Python 3.7 (PEP 479)
  tensorboard/backend/event_processing/directory_watcher.py
Labels: cla: yes

#2683 Use _pywrap_events_writer
  tensorboard/plugins/debugger/debugger_plugin_testlib.py
  tensorboard/plugins/debugger/events_writer_manager.py
Labels: cla: yes

#2647 Add counterfactual analysis for regression models (What-If Tool)
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Labels: cla: yes

#2682 Fix threshold optimizations in WIT
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Labels: cla: yes

#2660 Add WIT ability to consume arbitrary prediction-time information
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
  tensorboard/plugins/interactive_inference/utils/inference_utils.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/colab/wit.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/lib/wit.js
  tensorboard/plugins/interactive_inference/witwidget/notebook/visualization.py
Labels: cla: yes

#2669 Fix PD plots in py3
  tensorboard/plugins/interactive_inference/utils/BUILD
  tensorboard/plugins/interactive_inference/utils/inference_utils.py
  tensorboard/plugins/interactive_inference/utils/inference_utils_test.py
  tensorboard/plugins/interactive_inference/witwidget/pip_package/setup.py
Labels: cla: yes

#2686 program_test: bind to all interfaces
  tensorboard/program_test.py
Labels: cla: yes

#2514 Add TF2.0 migration guide
  docs/_book.yaml
  docs/r2/migrate_tf2.ipynb
Labels: cla: yes, type:docs

#2694 Fix Fairness optimization dialogs (What-If Tool)
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Labels: cla: yes

#2309 lib: add a library for cross-frame communication
  tensorboard/components/plugin_util/BUILD
  tensorboard/components/plugin_util/message.ts
  tensorboard/components/plugin_util/plugin-guest.html
  tensorboard/components/plugin_util/plugin-guest.ts
  tensorboard/components/plugin_util/plugin-host.html
  tensorboard/components/plugin_util/plugin-host.ts
  tensorboard/components/plugin_util/test/BUILD
  tensorboard/components/plugin_util/test/iframe.html
  tensorboard/components/plugin_util/test/iframe.ts
  tensorboard/components/plugin_util/test/plugin-test.ts
  tensorboard/components/plugin_util/test/tests.html
Labels: cla: yes

#2663 What-If Tool Attribution display redesign
  tensorboard/components/vz_example_viewer/vz-example-viewer.html
  tensorboard/components/vz_example_viewer/vz-example-viewer.ts
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Labels: cla: yes

#2697 diagnose: use non-deprecated `logging.warning`
  tensorboard/tools/diagnose_tensorboard.py
Labels: cla: yes

#2695 build: update closure-related deps
  WORKSPACE
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
  third_party/js.bzl
Labels: cla: yes

#2696 Various fixes from latest changes
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
  tensorboard/plugins/interactive_inference/utils/inference_utils.py
  tensorboard/plugins/interactive_inference/utils/inference_utils_test.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/colab/wit.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/lib/wit.js
Labels: cla: yes

#2701 Update WIT attribution colors
  tensorboard/components/vz_example_viewer/vz-example-viewer.ts
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Labels: cla: yes

#2698 Add ability to adjust attributions.
  tensorboard/plugins/interactive_inference/witwidget/notebook/base.py
  tensorboard/plugins/interactive_inference/witwidget/notebook/visualization.py
Labels: cla: yes

#2671 ui: fix downloader links before run selection
  tensorboard/components/tf_dashboard_common/tf-downloader.html
Labels: cla: yes

#2704 Fix slicing buckets in WIT
  tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html
Labels: cla: yes

#2702 Update witwidget to version 1.4
  tensorboard/plugins/interactive_inference/witwidget/notebook/jupyter/js/package.json
  tensorboard/plugins/interactive_inference/witwidget/pip_package/RELEASE.md
  tensorboard/plugins/interactive_inference/witwidget/version.py
Labels: cla: yes

#2706 diagnose: warn about `tensorflow-tensorboard`
  tensorboard/tools/diagnose_tensorboard.py
Labels: cla: yes
