Repository tensorflow/tensorboard, pull requests merged in 2020-11, with the labels that each got.

#4262 Uploader messaging oneshot
  tensorboard/uploader/upload_tracker.py
  tensorboard/uploader/upload_tracker_test.py
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_subcommand.py
  tensorboard/uploader/uploader_subcommand_test.py
Labels: cla: yes

#4266 Show alert on fetch run failures
  tensorboard/webapp/alert/views/alert_snackbar_module.ts
  tensorboard/webapp/runs/BUILD
  tensorboard/webapp/runs/runs_module.ts
Labels: cla: yes

#4270 ui: add 'regex' to the run and tag filter
  tensorboard/webapp/metrics/views/main_view/filter_input_component.ng.html
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
Labels: cla: yes

#4269 bug: prevent double data fetch on stamp
  tensorboard/webapp/plugins/plugins_component.ts
  tensorboard/webapp/plugins/plugins_container_test.ts
Labels: cla: yes

#4263 Now Correctly filters out Null Values
  tensorboard/webapp/plugins/npmi/util/filter_annotations.ts
  tensorboard/webapp/plugins/npmi/util/filter_annotations_test.ts
Labels: cla: yes

#4271 [time series] render images as pixelated
  tensorboard/webapp/metrics/views/card_renderer/image_card_component.scss
Labels: cla: yes

#4253 Re-enable scalars multirun endpoint
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.ts
Labels: cla: yes

#4272 cleanup: remove dangling type import on d3
  .github/workflows/ci.yml
  tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/BUILD
Labels: cla: yes

#4275 Corrected the link for summary_iterator in README.md
  README.md
Labels: cla: yes

#4278 license_test: use `git-grep` to respect gitignore
  tensorboard/tools/license_test.sh
Labels: cla: yes, type:build/install

#4280 rust: remove placeholder code
  tensorboard/data/server/BUILD
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  tensorboard/data/server/lib.rs
  tensorboard/data/server/main.rs
  third_party/rust/BUILD.bazel
  third_party/rust/crates.bzl
  third_party/rust/remote/byteorder-1.3.4.BUILD.bazel
Labels: cla: yes, core:rustboard

#4281 rust: add `crc` dependency
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  third_party/rust/BUILD.bazel
  third_party/rust/crates.bzl
  third_party/rust/remote/build_const-0.2.1.BUILD.bazel
  third_party/rust/remote/crc-1.8.1.BUILD.bazel
Labels: cla: yes, core:rustboard

#4282 rust: implement TFRecord CRC masking operation
  tensorboard/data/server/BUILD
  tensorboard/data/server/lib.rs
  tensorboard/data/server/masked_crc.rs
Labels: cla: yes, core:rustboard

#4293 ci: lint Rust code
  .github/workflows/ci.yml
Labels: cla: yes, core:rustboard, type:build/install

#4292 rust: regenerate build with cargo-raze 0.7.0
  .github/workflows/ci.yml
  tensorboard/data/server/Cargo.toml
  third_party/rust/BUILD.bazel
  third_party/rust/crates.bzl
  third_party/rust/remote/BUILD.build_const-0.2.1.bazel
  third_party/rust/remote/BUILD.crc-1.8.1.bazel
Labels: cla: yes, core:rustboard

#4295 rust: add `ScriptedReader` test helper
  tensorboard/data/server/BUILD
  tensorboard/data/server/lib.rs
  tensorboard/data/server/scripted_reader.rs
Labels: cla: yes, core:rustboard

#4297 rust: add `rand` and `rand_chacha` dependencies
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  third_party/rust/BUILD.bazel
  third_party/rust/crates.bzl
  third_party/rust/remote/BUILD.cfg-if-0.1.10.bazel
  third_party/rust/remote/BUILD.getrandom-0.1.15.bazel
  third_party/rust/remote/BUILD.libc-0.2.80.bazel
  third_party/rust/remote/BUILD.ppv-lite86-0.2.10.bazel
  third_party/rust/remote/BUILD.rand-0.7.3.bazel
  third_party/rust/remote/BUILD.rand_chacha-0.2.2.bazel
  third_party/rust/remote/BUILD.rand_core-0.5.1.bazel
  third_party/rust/remote/BUILD.rand_hc-0.2.0.bazel
  third_party/rust/remote/BUILD.wasi-0.9.0+wasi-snapshot-preview1.bazel
Labels: cla: yes, core:rustboard, dependencies

#4304 Update protos for TF v2.4.0-rc1
  tensorboard/compat/proto/config.proto
  tensorboard/compat/proto/cpp_shape_inference.proto
  tensorboard/compat/proto/saved_object_graph.proto
  tensorboard/compat/proto/types.proto
Labels: cla: yes

#4305 rust: add `byteorder` dependency
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  third_party/rust/BUILD.bazel
  third_party/rust/crates.bzl
  third_party/rust/remote/BUILD.byteorder-1.3.4.bazel
Labels: cla: yes, core:rustboard, dependencies

#4307 workspace: upgrade to newer `rules_rust`
  WORKSPACE
Labels: cla: yes, core:rustboard, dependencies, type:build/install

#4308 Fix mouse interaction in hparam parallel coords, scatter plot
  tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/tf-hparams-parallel-coords-plot.ts
  tensorboard/plugins/hparams/tf_hparams_scatter_plot_matrix_plot/tf-hparams-scatter-plot-matrix-plot.ts
Labels: cla: yes

#4283 line chart: data drawable, a class that renders
  tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/drawable.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/drawable_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/paint_brush.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/series_line_view.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/types.ts
Labels: cla: yes

#4284 line chart: refactor to separate internal types
  tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/coordinator.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/coordinator_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/drawable.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/drawable_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/internal_types.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/public_types.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_types.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/svg_renderer.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/threejs_coordinator.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/utils.ts
Labels: cla: yes

#4302 rust: add documentation server
  tensorboard/data/server/BUILD
  tensorboard/data/server/rustboard_core_doc_server.py
Labels: cla: yes, core:rustboard, type:docs

#4285 line chart: Chart, the library entry point
  tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/chart.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/chart_types.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/integration_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/public_types.ts
Labels: cla: yes

#4306 rust: add TFRecord reading module
  tensorboard/data/server/BUILD
  tensorboard/data/server/lib.rs
  tensorboard/data/server/tf_record.rs
Labels: cla: yes, core:rustboard

#4286 refactor: runs-table from mat-table to ngFor
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
  tensorboard/webapp/runs/views/runs_table/runs_table_component.scss
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_module.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Labels: cla: yes

#4298 rust: implement bipartite reservoir sampling
  tensorboard/data/server/BUILD
  tensorboard/data/server/lib.rs
  tensorboard/data/server/reservoir.rs
Labels: cla: yes, core:rustboard

#4317 rust: compile gRPC bindings with Tonic
  tensorboard/data/server/BUILD
  tensorboard/data/server/gen_protos_tool.rs
Labels: cla: yes, core:rustboard, type:build/install

#4318 rust: add demo Tonic server
  tensorboard/data/server/BUILD
  tensorboard/data/server/demo.pb.rs
  tensorboard/data/server/demo.proto
  tensorboard/data/server/gen_protos_tool.rs
  tensorboard/data/server/lib.rs
  tensorboard/data/server/main.rs
Labels: cla: yes, core:rustboard

#4322 rust: add `thiserror` dependency
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  third_party/rust/BUILD.bazel
  third_party/rust/crates.bzl
  third_party/rust/remote/BUILD.thiserror-1.0.22.bazel
  third_party/rust/remote/BUILD.thiserror-impl-1.0.22.bazel
Labels: cla: yes, core:rustboard, dependencies

#4324 ci: don’t update Cargo lockfile
  .github/workflows/ci.yml
  tensorboard/data/server/DEVELOPMENT.md
Labels: cla: yes, core:rustboard, type:build/install

#4323 cleanup: add readonly to not changing prop
  tensorboard/webapp/widgets/line_chart_v2/lib/drawable.ts
Labels: cla: yes

#4315 rust: add event file reading module
  tensorboard/data/server/BUILD
  tensorboard/data/server/event_file.rs
  tensorboard/data/server/lib.rs
  tensorboard/data/server/scripted_reader.rs
  tensorboard/data/server/tf_record.rs
Labels: cla: yes, core:rustboard

#4288 bug: widen click target for hparam/metric filter checkboxes
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
  tensorboard/webapp/runs/views/runs_table/runs_table_component.scss
Labels: cla: yes

#4327 sync: fix build
  tensorboard/webapp/feature_flag/actions/BUILD
Labels: cla: yes

#4314 data: add `DataProvider` gRPC service spec
  tensorboard/data/proto/BUILD
  tensorboard/data/proto/data_provider.proto
Labels: cla: yes, core:rustboard

#4326 feat: add an ability to enable gpu line chart
  tensorboard/webapp/feature_flag/effects/BUILD
  tensorboard/webapp/feature_flag/effects/feature_flag_effects_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts
  tensorboard/webapp/feature_flag/testing.ts
  tensorboard/webapp/feature_flag/types.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
Labels: cla: yes

#4329 sync: add data-id to runs-table for testability
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
Labels: cla: yes

#4330 sync: fix strict_deps on feature_flag_testing
  tensorboard/webapp/feature_flag/effects/BUILD
  tensorboard/webapp/webapp_data_source/BUILD
Labels: cla: yes

#4331 rust: build `tensorboard.data` protos
  tensorboard/data/server/BUILD
  tensorboard/data/server/gen_protos_tool.rs
  tensorboard/data/server/lib.rs
  tensorboard/data/server/tensorboard.data.pb.rs
Labels: cla: yes, core:rustboard

#4287 line chart: OffscreenCanvas support for Chart
  tensorboard/webapp/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/compact_data_series.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/compact_data_series_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/message_types.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart_bridge.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_pool.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_pool_test.ts
Labels: cla: yes

#4332 Remove `frame-ancestors *` CSP directive
  tensorboard/backend/http_util.py
  tensorboard/backend/http_util_test.py
  tensorboard/backend/security_validator.py
Labels: cla: yes

#4333 data: make `downsample` required, but permit zero
  tensorboard/data/proto/data_provider.proto
  tensorboard/data/server/tensorboard.data.pb.rs
Labels: cla: yes, core:rustboard

#4289 line chart: refactor to move interface for Scale to types file
  tensorboard/webapp/widgets/line_chart_v2/lib/coordinator.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/scale.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/scale_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/scale_types.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/BUILD
Labels: cla: yes

#4335 rust: add `tempfile` dependency
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  third_party/rust/BUILD.bazel
Labels: cla: yes, core:rustboard, dependencies

#4299 rust: support reservoir preemption
  tensorboard/data/server/reservoir.rs
Labels: cla: yes, core:rustboard

#4336 rust: run `libc` build script
  tensorboard/data/server/Cargo.toml
  third_party/rust/remote/BUILD.libc-0.2.80.bazel
Labels: cla: yes, core:rustboard, dependencies

#4338 rust: add `clap` dependency
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  third_party/rust/BUILD.bazel
  third_party/rust/crates.bzl
  third_party/rust/remote/BUILD.atty-0.2.14.bazel
  third_party/rust/remote/BUILD.clap-3.0.0-beta.2.bazel
  third_party/rust/remote/BUILD.clap_derive-3.0.0-beta.2.bazel
  third_party/rust/remote/BUILD.hermit-abi-0.1.17.bazel
  third_party/rust/remote/BUILD.os_str_bytes-2.4.0.bazel
  third_party/rust/remote/BUILD.proc-macro-error-1.0.4.bazel
  third_party/rust/remote/BUILD.proc-macro-error-attr-1.0.4.bazel
  third_party/rust/remote/BUILD.strsim-0.10.0.bazel
  third_party/rust/remote/BUILD.termcolor-1.1.0.bazel
  third_party/rust/remote/BUILD.textwrap-0.12.1.bazel
  third_party/rust/remote/BUILD.unicode-width-0.1.8.bazel
  third_party/rust/remote/BUILD.vec_map-0.8.2.bazel
  third_party/rust/remote/BUILD.version_check-0.9.2.bazel
  third_party/rust/remote/BUILD.winapi-0.3.9.bazel
  third_party/rust/remote/BUILD.winapi-util-0.1.5.bazel
Labels: cla: yes, core:rustboard, dependencies

#4342 rust: create `types` module with primitives like `Step`
  tensorboard/data/server/BUILD
  tensorboard/data/server/lib.rs
  tensorboard/data/server/reservoir.rs
  tensorboard/data/server/types.rs
Labels: cla: yes, core:rustboard

#4347 feat: selector to read fastChart feature flag
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
Labels: cla: yes

#4341 rust: use `thiserror` for error types
  tensorboard/data/server/BUILD
  tensorboard/data/server/event_file.rs
  tensorboard/data/server/masked_crc.rs
  tensorboard/data/server/tf_record.rs
Labels: cla: yes, core:rustboard

#4348 feat: persist fastChart feature flag to url
  tensorboard/webapp/routes/core_deeplink_provider.ts
  tensorboard/webapp/routes/core_deeplink_provider_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
Labels: cla: yes

#4340 rust: add `data_compat` module
  tensorboard/data/server/BUILD
  tensorboard/data/server/data_compat.rs
  tensorboard/data/server/lib.rs
Labels: cla: yes, core:rustboard

#4350 docs: publish “RustBoard technical design” doc
  docs/design/images/.gitattributes
  docs/design/images/rustboard_data_flow.svg
  docs/design/rustboard.md
Labels: cla: yes, core:rustboard, type:docs

#4343 rust: create multi-file run loader
  tensorboard/data/server/BUILD
  tensorboard/data/server/data_compat.rs
  tensorboard/data/server/lib.rs
  tensorboard/data/server/run.rs
Labels: cla: yes, core:rustboard

#4357 rust: upgrade to Rust 1.48.0
  .github/workflows/ci.yml
  third_party/rust.bzl
Labels: cla: yes, core:rustboard, type:build/install

#4358 rust: add `walkdir` dependency
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  third_party/rust/BUILD.bazel
  third_party/rust/crates.bzl
  third_party/rust/remote/BUILD.same-file-1.0.6.bazel
  third_party/rust/remote/BUILD.walkdir-2.3.1.bazel
Labels: cla: yes, core:rustboard, dependencies

#4334 feat: combine graph by prefixing with unique name
  tensorboard/plugins/graph/BUILD
  tensorboard/plugins/graph/graph_util.py
  tensorboard/plugins/graph/graph_util_test.py
  tensorboard/plugins/graph/graphs_plugin.py
Labels: cla: yes

#4349 rust: promote event values to `data_compat`
  tensorboard/data/server/data_compat.rs
  tensorboard/data/server/run.rs
Labels: cla: yes, core:rustboard

#4353 data: add `ListPlugins` RPC
  tensorboard/data/proto/data_provider.proto
  tensorboard/data/server/tensorboard.data.pb.rs
Labels: cla: yes, core:rustboard

#4339 line chart: Angular entry point to line chart
  tensorboard/webapp/BUILD
  tensorboard/webapp/widgets/line_chart_v2/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/testing.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/utils.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_internal_utils.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_internal_utils_test.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_module.ts
Labels: cla: yes

#4366 infra: error on dep on ng_module
  .github/workflows/ci.yml
  tensorboard/webapp/widgets/line_chart_v2/sub_view/BUILD
Labels: cla: yes

#4360 cleanup: use Parse instead of Merge
  tensorboard/plugins/graph/graph_util_test.py
Labels: cla: yes

#4351 rust: define shared `Commit` type
  tensorboard/data/server/BUILD
  tensorboard/data/server/commit.rs
  tensorboard/data/server/lib.rs
  tensorboard/data/server/types.rs
Labels: cla: yes, core:rustboard

#4344 line chart: temporarily add demo component
  tensorboard/webapp/widgets/line_chart_v2/BUILD
  tensorboard/webapp/widgets/line_chart_v2/demo.html
  tensorboard/webapp/widgets/line_chart_v2/demo_main.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/BUILD
  tensorboard/webapp/widgets/line_chart_v2/line_chart_demo_component.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_demo_module.ts
Labels: cla: yes

#4367 infra: upgrade Bazel to 3.7.0 (1 of 4)
  .travis.yml
  WORKSPACE
  ci/bazelrc
Labels: cla: yes

#4368 infra: upgrade Bazel to 3.7.0 (2 of 4)
  .travis.yml
Labels: cla: yes

#4369 infra: upgrade Bazel to 3.7.0 (3 of 4)
  .travis.yml
Labels: cla: yes

#4370 infra: upgrade Bazel to 3.7.0 (4 of 4)
  .travis.yml
Labels: cla: yes

#4345 line chart: fix issues with line chart
  tensorboard/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/chart.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/integration_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart_bridge.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
Labels: cla: yes

#4379 sync: unbreak the sync, removing line chart demo
  tensorboard/webapp/widgets/line_chart_v2/BUILD
  tensorboard/webapp/widgets/line_chart_v2/demo.html
  tensorboard/webapp/widgets/line_chart_v2/demo_main.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_demo_component.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_demo_module.ts
Labels: cla: yes

#4361 build: set `srcs_version = "PY3"` everywhere
  tensorboard/BUILD
  tensorboard/backend/BUILD
  tensorboard/backend/event_processing/BUILD
  tensorboard/compat/BUILD
  tensorboard/compat/proto/BUILD
  tensorboard/compat/tensorflow_stub/BUILD
  tensorboard/data/BUILD
  tensorboard/defs/protos.bzl
  tensorboard/defs/web_testing.bzl
  tensorboard/examples/plugins/example_raw_scalars/BUILD
  tensorboard/functionaltests/BUILD
  tensorboard/pip_package/BUILD
  tensorboard/plugins/BUILD
  tensorboard/plugins/audio/BUILD
  tensorboard/plugins/core/BUILD
  tensorboard/plugins/custom_scalar/BUILD
  tensorboard/plugins/debugger_v2/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/inactive/BUILD
  tensorboard/plugins/distribution/BUILD
  tensorboard/plugins/graph/BUILD
  tensorboard/plugins/histogram/BUILD
  tensorboard/plugins/hparams/BUILD
  tensorboard/plugins/image/BUILD
  tensorboard/plugins/mesh/BUILD
  tensorboard/plugins/npmi/BUILD
  tensorboard/plugins/pr_curve/BUILD
  tensorboard/plugins/profile_redirect/BUILD
  tensorboard/plugins/projector/BUILD
  tensorboard/plugins/scalar/BUILD
  tensorboard/plugins/text/BUILD
  tensorboard/plugins/text_v2/BUILD
  tensorboard/scripts/BUILD
  tensorboard/summary/BUILD
  tensorboard/summary/writer/BUILD
  tensorboard/uploader/BUILD
  tensorboard/util/BUILD
  third_party/bleach.BUILD
  third_party/html5lib.BUILD
  third_party/markdown.BUILD
  third_party/mock.BUILD
  third_party/portpicker.BUILD
  third_party/six.BUILD
  third_party/urllib3.BUILD
  third_party/webencodings.BUILD
  third_party/werkzeug.BUILD
Labels: cla: yes, type:build/install

#4374 feat: reverse fill color for histograms
  tensorboard/plugins/histogram/vz_histogram_timeseries/vz-histogram-timeseries.ts
Labels: cla: yes

#4346 line chart: add utility for smoothing line chart
  tensorboard/webapp/widgets/line_chart_v2/BUILD
  tensorboard/webapp/widgets/line_chart_v2/data_transformer.ts
  tensorboard/webapp/widgets/line_chart_v2/data_transformer_test.ts
Labels: cla: yes

#4375 cleanup: debugger to use tf_ng_module
  .github/workflows/ci.yml
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/BUILD
Labels: cla: yes

#4364 rust: extract test utils for writing event files
  tensorboard/data/server/BUILD
  tensorboard/data/server/lib.rs
  tensorboard/data/server/run.rs
  tensorboard/data/server/writer.rs
Labels: cla: yes, core:rustboard

#4377 line chart: export types for consumer of line chart
  tensorboard/webapp/widgets/line_chart_v2/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
  tensorboard/webapp/widgets/line_chart_v2/types.ts
Labels: cla: yes

#4355 rust: implement data provider server with fake data
  tensorboard/data/server/BUILD
  tensorboard/data/server/lib.rs
  tensorboard/data/server/main.rs
  tensorboard/data/server/server.rs
Labels: cla: yes, core:rustboard

#4352 rust: commit changes after loading runs
  tensorboard/data/server/commit.rs
  tensorboard/data/server/data_compat.rs
  tensorboard/data/server/run.rs
Labels: cla: yes, core:rustboard

#4384 rust: rename `run::TimeSeries` to `StageTimeSeries`
  tensorboard/data/server/run.rs
Labels: cla: yes, core:rustboard

#4387 rust: add `grpc_cli` tips to DEVELOPMENT.md
  tensorboard/data/server/DEVELOPMENT.md
Labels: cla: yes, core:rustboard, type:docs

#4380 rust: discover event files in log directories
  tensorboard/data/server/BUILD
  tensorboard/data/server/lib.rs
  tensorboard/data/server/logdir.rs
Labels: cla: yes, core:rustboard

#4381 rust: reload data in log directories
  tensorboard/data/server/logdir.rs
Labels: cla: yes, core:rustboard

#4383 rust: add `log` and `env_logger` dependencies
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  third_party/rust/BUILD.bazel
  third_party/rust/crates.bzl
  third_party/rust/remote/BUILD.aho-corasick-0.7.15.bazel
  third_party/rust/remote/BUILD.env_logger-0.8.2.bazel
  third_party/rust/remote/BUILD.humantime-2.0.1.bazel
  third_party/rust/remote/BUILD.log-0.4.11.bazel
  third_party/rust/remote/BUILD.memchr-2.3.4.bazel
  third_party/rust/remote/BUILD.regex-1.4.2.bazel
  third_party/rust/remote/BUILD.regex-syntax-0.6.21.bazel
  third_party/rust/remote/BUILD.thread_local-1.0.1.bazel
Labels: cla: yes, core:rustboard, dependencies

#4393 Update tbdev_getting_started.ipynb
  docs/tbdev_getting_started.ipynb
Labels: cla: yes

#4389 cleanup: remove TypeScript build from tf_web_library
  tensorboard/defs/web.bzl
Labels: cla: yes

#4391 cleanup: refactor chai/mocha test to jasmine
  tensorboard/components/tensor_widget/BUILD
  tensorboard/components/tensor_widget/colormap-test.ts
  tensorboard/components/tensor_widget/dtype-utils-test.ts
  tensorboard/components/tensor_widget/selection-test.ts
  tensorboard/components/tensor_widget/shape-utils-test.ts
  tensorboard/components/tensor_widget/string-utils-test.ts
Labels: cla: yes

#4385 rust: implement `ListRuns` RPC
  tensorboard/data/server/main.rs
  tensorboard/data/server/run.rs
  tensorboard/data/server/server.rs
Labels: cla: yes, core:rustboard

#4359 line chart: integrate to time series
  tensorboard/webapp/metrics/views/card_renderer/BUILD
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_module.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
  tensorboard/webapp/widgets/line_chart_v2/types.ts
Labels: cla: yes

#4388 rust: install logging framework
  tensorboard/data/server/BUILD
  tensorboard/data/server/logdir.rs
  tensorboard/data/server/main.rs
  tensorboard/data/server/run.rs
Labels: cla: yes, core:rustboard

#4386 rust: implement `ListScalars` and `ReadScalars`
  tensorboard/data/server/server.rs
  tensorboard/data/server/types.rs
Labels: cla: yes, core:rustboard

#4394 cleanup: remove duplicate requirejs dep
  package.json
Labels: cla: yes

#4404 webapp: add noscript message
  tensorboard/webapp/index_polymer3.uninlined.html
Labels: cla: yes, core:frontend, type:feature

#4356 data: implement gRPC data provider for scalars
  tensorboard/BUILD
  tensorboard/data/BUILD
  tensorboard/data/grpc_provider.py
  tensorboard/data/grpc_provider_test.py
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/program.py
Labels: cla: yes, core:rustboard

#4397 rust: add nice command-line argument parsing
  tensorboard/data/server/BUILD
  tensorboard/data/server/main.rs
Labels: cla: yes, core:rustboard

#4396 cleanup: move source code component from debugger-v2 to widgets
  tensorboard/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_module.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_module.ts
  tensorboard/webapp/BUILD
  tensorboard/webapp/widgets/source_code/BUILD
  tensorboard/webapp/widgets/source_code/load_monaco_shim.ts
  tensorboard/webapp/widgets/source_code/load_monaco_shim_test.ts
  tensorboard/webapp/widgets/source_code/monaco/BUILD
  tensorboard/webapp/widgets/source_code/source_code_component.css
  tensorboard/webapp/widgets/source_code/source_code_component.ng.html
  tensorboard/webapp/widgets/source_code/source_code_component.ts
  tensorboard/webapp/widgets/source_code/source_code_container.ts
  tensorboard/webapp/widgets/source_code/source_code_container_test.ts
  tensorboard/webapp/widgets/source_code/source_code_module.ts
  tensorboard/webapp/widgets/source_code/testing.ts
Labels: cla: yes

#4398 rust: add `--verbose` to control log level
  tensorboard/data/server/main.rs
Labels: cla: yes, core:rustboard

#4395 data: represent scalars as `f32`
  tensorboard/data/grpc_provider_test.py
  tensorboard/data/proto/data_provider.proto
  tensorboard/data/server/commit.rs
  tensorboard/data/server/data_compat.rs
  tensorboard/data/server/logdir.rs
  tensorboard/data/server/run.rs
  tensorboard/data/server/server.rs
  tensorboard/data/server/tensorboard.data.pb.rs
Labels: cla: yes, core:rustboard
