Repository tensorflow/tensorboard, pull requests merged in 2020-10, with the labels that each got.

#4204 remove LICENSE exports files where no LICENSE exists (pt 2)
  tensorboard/backend/BUILD
  tensorboard/backend/event_processing/BUILD
  tensorboard/compat/BUILD
  tensorboard/compat/proto/BUILD
  tensorboard/data/BUILD
  tensorboard/logo/BUILD
  tensorboard/plugins/BUILD
  tensorboard/plugins/audio/BUILD
  tensorboard/plugins/core/BUILD
  tensorboard/plugins/custom_scalar/BUILD
  tensorboard/plugins/distribution/BUILD
  tensorboard/plugins/graph/BUILD
  tensorboard/plugins/histogram/BUILD
  tensorboard/plugins/hparams/BUILD
  tensorboard/plugins/image/BUILD
  tensorboard/plugins/mesh/BUILD
  tensorboard/plugins/metrics/BUILD
  tensorboard/plugins/profile_redirect/BUILD
  tensorboard/plugins/projector/BUILD
  tensorboard/plugins/scalar/BUILD
  tensorboard/plugins/text/BUILD
  tensorboard/scripts/BUILD
  tensorboard/summary/writer/BUILD
Labels: cla: yes

#4205 Refactor import of components necessary for Polymer <-> Angular interop.
  tensorboard/components/BUILD
  tensorboard/components/polymer3_interop_helper.ts
  tensorboard/components/polymer3_lib.ts
Labels: cla: yes

#4211 Defining a new build target for tensor.proto and its deps.
  tensorboard/compat/proto/BUILD
Labels: cla: yes

#4215 Revert "Defining a new build target for tensor.proto and its deps. (#…
  tensorboard/compat/proto/BUILD
Labels: cla: yes

#4213 bug: fix AppRouting interference with URL queryParam-reading components
  tensorboard/components/tf_backend/router.ts
  tensorboard/plugins/projector/vz_projector/vz-projector.ts
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
Labels: cla: yes

#4212 program: note Google-internal signal handling patch
  tensorboard/program.py
Labels: cla: yes, core:backend

#4218 Use GET instead of POST requests for hparams in colab environment.
  tensorboard/plugins/hparams/tf_hparams_dashboard/tf-hparams-dashboard.ts
Labels: cla: yes

#4206 Get label colour from raw confusion matrix
  docs/image_summaries.ipynb
Labels: cla: yes

#4210 Add a newline to improve output readability
  tensorboard/uploader/uploader_subcommand.py
Labels: cla: yes

#4222 Create dedicated build rule for mat_icon_module.ts
  tensorboard/webapp/BUILD
Labels: cla: yes

#4226 histogram: update symbol name for TPU summary special-case
  tensorboard/plugins/histogram/summary_v2.py
Labels: cla: yes, core:summaries, plugin:histogram

#4227 fix timeseries color picker positioning
  tensorboard/webapp/app_container.ts
Labels: cla: yes

#4228 bazelrc: use fast Python protos
  .bazelrc
  tensorboard/uploader/server_info_test.py
Labels: cla: yes, theme:performance, type:build/install

#4223 Add feature flag ngrx selector for Colab environment
  tensorboard/webapp/app_module.ts
  tensorboard/webapp/feature_flag/actions/BUILD
  tensorboard/webapp/feature_flag/actions/feature_flag_actions.ts
  tensorboard/webapp/feature_flag/store/BUILD
  tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts
  tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_types.ts
  tensorboard/webapp/feature_flag/store/testing.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
Labels: cla: yes

#4229 Add overridable sanitize() step to tf-markdown-view.
  tensorboard/components/tf_markdown_view/BUILD
  tensorboard/components/tf_markdown_view/sanitize.ts
  tensorboard/components/tf_markdown_view/tf-markdown-view.ts
Labels: cla: yes

#4219 AppRouting should preserve hash on same-RouteId navigations
  tensorboard/webapp/app_routing/effects/app_routing_effects.ts
  tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
Labels: cla: yes

#4220 Update ngrx store for pinned cards from storage
  tensorboard/webapp/metrics/data_source/types.ts
  tensorboard/webapp/metrics/store/BUILD
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts
  tensorboard/webapp/metrics/store/metrics_store_internal_utils_test.ts
  tensorboard/webapp/metrics/store/metrics_types.ts
  tensorboard/webapp/metrics/testing.ts
  tensorboard/webapp/metrics/types.ts
Labels: cla: yes

#4233 Temporarily disable usage of scalars_multirun endpoint
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.ts
Labels: cla: yes, plugin:scalars

#4160 Projector Plugin: Fix bookmark loading (issue #4159)
  tensorboard/plugins/projector/vz_projector/vz-projector-bookmark-panel.ts
Labels: cla: yes

#4236 cleanup: remove extraneous console.log in test
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
Labels: cla: yes, type:cleanup

#4231 line-chart: create reusable worker
  tensorboard/webapp/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/worker.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker_pool.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker_pool_test.ts
Labels: cla: yes

#4237 Revert "line-chart: create reusable worker"
  tensorboard/webapp/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/worker.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker_pool.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker_pool_test.ts
Labels: cla: yes

#4235 cleanup: NO_ERRORS_SCHEMA to avoid noise in test
  tensorboard/webapp/plugins/npmi/npmi_container_test.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_test.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_test.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_toolbar/annotations_list_toolbar_test.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_toolbar/annotations_search/annotations_search_test.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_test.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/legend/legend_test.ts
  tensorboard/webapp/plugins/npmi/views/data_selection/data_selection_test.ts
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/metric_arithmetic_element_test.ts
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_operator/metric_arithmetic_operator_test.ts
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_test.ts
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_search/metric_search_test.ts
  tensorboard/webapp/plugins/npmi/views/data_selection/results_download/results_download_test.ts
  tensorboard/webapp/plugins/npmi/views/main/main_container_test.ts
  tensorboard/webapp/plugins/npmi/views/selected_annotations/selected_annotations_test.ts
  tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/violin_filter_test.ts
  tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filters_test.ts
Labels: cla: yes, type:cleanup

#4239 line-chart: create reusable worker
  tensorboard/webapp/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/worker.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker_pool.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker_pool_test.ts
Labels: cla: yes

#4221 feat: persist pinned cards in URL with DeepLinkProvider
  tensorboard/webapp/BUILD
  tensorboard/webapp/metrics/store/metrics_selectors.ts
  tensorboard/webapp/metrics/store/metrics_selectors_test.ts
  tensorboard/webapp/routes/BUILD
  tensorboard/webapp/routes/core_deeplink_provider.ts
  tensorboard/webapp/routes/core_deeplink_provider_test.ts
  tensorboard/webapp/routes/index.ts
Labels: cla: yes

#4245 [time series] prevent pinning cards from exceeding limit
  tensorboard/webapp/metrics/BUILD
  tensorboard/webapp/metrics/actions/index.ts
  tensorboard/webapp/metrics/metrics_module.ts
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/store/metrics_selectors.ts
  tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts
  tensorboard/webapp/metrics/store/metrics_store_internal_utils_test.ts
  tensorboard/webapp/metrics/views/card_renderer/card_view_container.ts
  tensorboard/webapp/metrics/views/card_renderer/card_view_test.ts
Labels: cla: yes

#4251 infra: remove sourcemap for sass
  tensorboard/defs/defs.bzl
Labels: cla: yes

#4252 Remove pickling of text arrays on export
  tensorboard/uploader/exporter.py
  tensorboard/uploader/exporter_test.py
Labels: cla: yes

#4241 line chart: added scale libraries
  tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/scale.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/scale_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/scale_types.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/types.ts
Labels: cla: yes

#4258 sync: depend on third_party d3 indirection
  tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/scale.ts
Labels: cla: yes

#4254 Improve messaging when uploading empty experiments
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_subcommand.py
  tensorboard/uploader/uploader_subcommand_test.py
Labels: cla: yes

#4259 CI to detect the direct dependency to "@npm//d3"
  .github/workflows/ci.yml
Labels: cla: yes

#4024 Updates list of TPU-compatible ops for the TB graph viewer.
  tensorboard/plugins/graph/tf_graph_common/op.ts
Labels: cla: yes

#4238 Added Embedding Handling
  tensorboard/plugins/npmi/BUILD
  tensorboard/plugins/npmi/README.md
  tensorboard/plugins/npmi/http_api.md
  tensorboard/plugins/npmi/metadata.py
  tensorboard/plugins/npmi/npmi_plugin.py
  tensorboard/plugins/npmi/npmi_plugin_test.py
  tensorboard/plugins/npmi/npy_to_embedding_data_demo.py
  tensorboard/plugins/npmi/summary.py
  tensorboard/webapp/plugins/npmi/actions/npmi_actions.ts
  tensorboard/webapp/plugins/npmi/data_source/npmi_data_source.ts
  tensorboard/webapp/plugins/npmi/data_source/npmi_data_source_test.ts
  tensorboard/webapp/plugins/npmi/effects/npmi_effects_test.ts
  tensorboard/webapp/plugins/npmi/store/npmi_reducers.ts
  tensorboard/webapp/plugins/npmi/store/npmi_reducers_test.ts
  tensorboard/webapp/plugins/npmi/store/npmi_types.ts
  tensorboard/webapp/plugins/npmi/testing/index.ts
Labels: cla: yes

#4260 Linkify text in alert message UI
  tensorboard/webapp/alert/views/BUILD
  tensorboard/webapp/alert/views/alert_display_snackbar_container.ng.html
  tensorboard/webapp/alert/views/alert_display_snackbar_container.scss
  tensorboard/webapp/alert/views/alert_display_snackbar_container.ts
  tensorboard/webapp/util/string.ts
  tensorboard/webapp/util/string_test.ts
Labels: cla: yes

#4265 experiments: add `related_links` field
  tensorboard/webapp/experiments/types.ts
Labels: cla: yes, core:frontend
