Repository tensorflow/tensorboard, pull requests merged in 2020-05, with the labels that each got.

#3574 [DebuggerV2] Remove a problematic assertion in debugger_v2_plugin_test
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes

#3560 DataFrame API: Initial implementation of ExperimentFromDev
  tensorboard/BUILD
  tensorboard/data/experimental/BUILD
  tensorboard/data/experimental/base_experiment.py
  tensorboard/data/experimental/experiment_from_dev.py
  tensorboard/data/experimental/experiment_from_dev_test.py
  tensorboard/data/experimental/test_binary.py
  tensorboard/pip_package/BUILD
  tensorboard/pip_package/requirements_dev.txt
Labels: cla: yes

#3578 Factor tag type constants out of event accumulator
  tensorboard/backend/BUILD
  tensorboard/backend/application.py
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/event_accumulator.py
  tensorboard/backend/event_processing/plugin_event_accumulator.py
  tensorboard/backend/event_processing/tag_types.py
  tensorboard/plugins/distribution/BUILD
  tensorboard/plugins/distribution/distributions_plugin_test.py
  tensorboard/plugins/graph/BUILD
  tensorboard/plugins/graph/graphs_plugin.py
  tensorboard/plugins/histogram/BUILD
  tensorboard/plugins/histogram/histograms_plugin_test.py
  tensorboard/plugins/scalar/BUILD
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes, type:build/install, type:cleanup

#3576 Remove some non-critical uses of TensorFlow
  tensorboard/BUILD
  tensorboard/backend/BUILD
  tensorboard/backend/http_util.py
  tensorboard/backend/json_util.py
  tensorboard/backend/process_graph.py
  tensorboard/data_compat.py
  tensorboard/plugins/audio/BUILD
  tensorboard/plugins/audio/audio_plugin.py
  tensorboard/plugins/graph/BUILD
  tensorboard/plugins/histogram/histograms_plugin.py
  tensorboard/plugins/hparams/backend_context.py
  tensorboard/plugins/image/BUILD
  tensorboard/plugins/image/images_plugin.py
  tensorboard/plugins/pr_curve/BUILD
  tensorboard/plugins/pr_curve/pr_curves_plugin.py
  tensorboard/plugins/scalar/BUILD
  tensorboard/plugins/scalar/scalars_plugin.py
Labels: cla: yes, type:build/install, type:cleanup

#3575 Allow server to specify maximum tensor upload size
  tensorboard/uploader/proto/server_info.proto
  tensorboard/uploader/server_info.py
  tensorboard/uploader/server_info_test.py
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_subcommand.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes

#3581 Don't require max_tensor_point_size to be set
  tensorboard/uploader/uploader.py
Labels: cla: yes

#3572 Remove unused vz_line_chart
  tensorboard/components/vz_line_chart/BUILD
  tensorboard/components/vz_line_chart/index.html
  tensorboard/components/vz_line_chart/vz-line-chart.html
  tensorboard/components/vz_line_chart/vz-line-chart.ts
  tensorboard/components/vz_line_chart2/BUILD
  tensorboard/components/vz_line_chart2/dragZoomInteraction.html
  tensorboard/components/vz_line_chart2/dragZoomInteraction.ts
Labels: cla: yes, type:cleanup

#3577 uploader: implement tensor exporting
  tensorboard/uploader/BUILD
  tensorboard/uploader/exporter.py
  tensorboard/uploader/exporter_test.py
Labels: cla: yes

#3564 [DebuggerV2] Implement HTTP route /graphs/op_info
  tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
  tensorboard/plugins/debugger_v2/debug_data_provider.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes

#3580 [DebuggerV2] Clicking on Inf/NaN alerts scrolls to the 1st graph execution with Inf/NaN
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container_test.ts
Labels: cla: yes

#3584 ng: set active plugin to first enabled plugin
  tensorboard/webapp/core/store/core_reducers.ts
  tensorboard/webapp/core/store/core_reducers_test.ts
Labels: cla: yes

#3588 uploader: display per-experiment tensor bytes in `dev list` output
  tensorboard/uploader/formatters.py
  tensorboard/uploader/formatters_test.py
  tensorboard/uploader/uploader_subcommand.py
Labels: cla: yes

#3587 ng: no active plugin warning page
  tensorboard/webapp/plugins/plugins_component.ng.html
  tensorboard/webapp/plugins/plugins_component.ts
  tensorboard/webapp/plugins/plugins_container.ts
  tensorboard/webapp/plugins/plugins_container_test.ts
Labels: cla: yes

#3591 ng: add plugin-id on tab for testability
  tensorboard/webapp/header/plugin_selector_component.ng.html
Labels: cla: yes

#3593 diagnose: warn on broken What-If Tool version
  tensorboard/tools/diagnose_tensorboard.py
Labels: cla: yes

#3595 [DebuggerV2] Stub out GraphComponent in the frontend
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_module.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_container.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_module.ts
Labels: cla: yes

#3582 vulc: fix mangled DOM due to a bug in the printer
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes, plugin:graph, type:build/install

#3571 Implement commitChanges on vz-line-chart2
  tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
  tensorboard/components/vz_line_chart2/line-chart.ts
  tensorboard/components/vz_line_chart2/microbenchmark/renders_spec.ts
  tensorboard/components/vz_line_chart2/vz-line-chart2.ts
  tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.html
  tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-multi-line-chart-card.html
  tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-line-chart.html
  tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-card.html
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
Labels: cla: yes

#3599 Cache bleach.Cleaner for faster conversion of markdown to safe html
  tensorboard/plugin_util.py
Labels: cla: yes

#3598 [DebuggerV2] Cleanup: properly implement angular OnChanges interface
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/source_code_component.ts
Labels: cla: yes

#3603 ng: remove deprecated `get` and use `inject`
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_container_test.ts
  tensorboard/webapp/core/effects/core_effects_test.ts
  tensorboard/webapp/core/views/hash_storage_test.ts
  tensorboard/webapp/deeplink/deeplink_test.ts
  tensorboard/webapp/deeplink/hash_test.ts
  tensorboard/webapp/feature_flag/effects/feature_flag_effects_test.ts
  tensorboard/webapp/header/header_test.ts
  tensorboard/webapp/plugins/plugins_container_test.ts
  tensorboard/webapp/reloader/reloader_component_test.ts
  tensorboard/webapp/settings/dialog_component_test.ts
  tensorboard/webapp/settings/polymer_interop_test.ts
  tensorboard/webapp/settings/settings_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
  tensorboard/webapp/webapp_data_source/tb_server_data_source_test.ts
Labels: cla: yes

#3602 Specify injectable as injectable.
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
Labels: cla: yes

#3604 vulc: fix pretty print messing up whitespace
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes, type:build/install

#3606 [Debugger] Replace some usage of innerHTML with innerText
  tensorboard/plugins/graph/tf_graph_debugger_data_card/tf-graph-debugger-data-card.html
Labels: cla: yes

#3601 cleanup: add @Override on interface impl
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes

#3600 [DebuggerV2] Add backend route /graphs/graph_info
  tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
  tensorboard/plugins/debugger_v2/debug_data_provider.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes

#3594 [DebuggerV2] A few improvements to the /graphs/op_info route
  tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
  tensorboard/plugins/debugger_v2/debug_data_multiplexer_test.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes

#3617 profile: suggest canonical Pip package name
  tensorboard/plugins/profile_redirect/tf_profile_redirect_dashboard/tf-profile-redirect-dashboard.html
Labels: cla: yes, plugin:profile

#3618 Updating documentation
  docs/fairness-indicators.md
Labels: cla: yes

#3561 Fix projector plugin links in docs
  docs/tensorboard_projector_plugin.ipynb
Labels: cla: yes

#3620 Update keras_util_test with explicit model name
  tensorboard/plugins/graph/keras_util_test.py
Labels: cla: yes

#3624 uploader: validate tensors before uploading them
  tensorboard/uploader/BUILD
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes

#3609 Tolerate boto3 1.13.1 range error code
  tensorboard/compat/tensorflow_stub/io/gfile.py
Labels: cla: yes

#3625 Expand UploadLimits proto and use it in TensorBoardUploader.
  tensorboard/uploader/proto/server_info.proto
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes

#3611 [DebuggerV2] Add ngrx states, data source and selectors for graph ops
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/data_source/tfdbg2_data_source.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
Labels: cla: yes

#3619 [DebuggerV2] Refactor selectors to use intermediate selectors
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
Labels: cla: yes

#3631 Uploader uses entire UploadLimits from handshake
  tensorboard/uploader/proto/server_info.proto
  tensorboard/uploader/server_info.py
  tensorboard/uploader/server_info_test.py
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_subcommand.py
Labels: cla: yes

#3630 [DebuggerV2] Add basic reducers for graph ops
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_graphs_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
Labels: cla: yes

#3638 Update broken link to r1 estimators tutorial in graph.md
  docs/r1/graphs.md
Labels: cla: yes

#3641 cleanup: fix undeclared and incorrect BUILD deps
  tensorboard/plugins/audio/BUILD
  tensorboard/plugins/core/BUILD
  tensorboard/plugins/custom_scalar/BUILD
  tensorboard/plugins/distribution/BUILD
  tensorboard/plugins/graph/BUILD
  tensorboard/plugins/histogram/BUILD
  tensorboard/plugins/pr_curve/BUILD
  tensorboard/plugins/projector/BUILD
  tensorboard/plugins/scalar/BUILD
  tensorboard/plugins/text/BUILD
Labels: cla: yes

#3637 Migrate _parse_samples_per_plugin() into flag definition itself
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/plugins/core/core_plugin.py
Labels: cla: yes, core:backend

#3642 perf: apply layout/layer bound where possible
  tensorboard/components/tf_dashboard_common/tf-dashboard-layout.html
  tensorboard/components/tf_dashboard_common/tf-multi-checkbox.html
  tensorboard/components/tf_paginated_view/tf-category-paginated-view.html
  tensorboard/components/vz_chart_helpers/vz-chart-tooltip.ts
  tensorboard/components/vz_line_chart2/vz-line-chart2.html
Labels: cla: yes

#3614 uploader: add rpc method GetExperiment to ExporterService
  tensorboard/uploader/proto/export_service.proto
Labels: cla: yes

#3605 DataFrame: Flatten MultiIndex; Set include_wall_time=False
  tensorboard/data/experimental/base_experiment.py
  tensorboard/data/experimental/experiment_from_dev.py
  tensorboard/data/experimental/experiment_from_dev_test.py
  tensorboard/data/experimental/test_binary.py
Labels: cla: yes

#3649 ng: allow i18n in Angular
  package.json
  tensorboard/defs/defs.bzl
  yarn.lock
Labels: cla: yes

#3654 cleanup: add more missing event_processing:data_provider deps
  tensorboard/plugins/histogram/BUILD
  tensorboard/plugins/image/BUILD
Labels: cla: yes, type:cleanup

#3636 [DebuggerV2] Basic implementation of ngrx container for graph
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_container.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_module.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_op_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_op_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_op_component.ts
Labels: cla: yes

#3651 DataFrame API: Let get_scalars() fail faster if pandas is not installed
  tensorboard/data/experimental/BUILD
  tensorboard/data/experimental/experiment_from_dev.py
Labels: cla: yes

#3646 DataFrame API: Let pivot default to False
  tensorboard/data/experimental/base_experiment.py
  tensorboard/data/experimental/experiment_from_dev.py
  tensorboard/data/experimental/experiment_from_dev_test.py
  tensorboard/data/experimental/test_binary.py
Labels: cla: yes

#3659 Revert "uploader: add rpc method GetExperiment to ExporterService"
  tensorboard/uploader/proto/export_service.proto
Labels: cla: yes

#3658 CI: Apply new Jupyter Notebook formatting checks (and fix the resulting failure)
  .github/workflows/ci.yml
  tensorboard/plugins/mesh/Mesh_Plugin_Tensorboard.ipynb
Labels: cla: yes

#3655 core: make TensorBoardWSGIApp args a bit easier to use
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
Labels: cla: yes, core:backend, type:cleanup

#3645 [DebuggerV2] Add effects to load graph ops & associated stack frames
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
Labels: cla: yes

#3640 Give min-height to run selectors
  tensorboard/components/tf_dashboard_common/dashboard-style.html
  tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-dashboard.html
  tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-dashboard.html
  tensorboard/plugins/distribution/tf_distribution_dashboard/tf-distribution-dashboard.html
  tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-dashboard.html
  tensorboard/plugins/image/tf_image_dashboard/tf-image-dashboard.html
  tensorboard/plugins/mesh/tf_mesh_dashboard/tf-mesh-dashboard.html
  tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-dashboard.html
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
  tensorboard/plugins/text/tf_text_dashboard/tf-text-dashboard.html
Labels: cla: yes

#3662 [DebuggerV2] Clicking tensor in graph execution component brings up graph view
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_op_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container_test.ts
Labels: cla: yes

#3663 Reverts Vulcanization printer changes
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes

#3673 build: fix Pip package creation to use Python 3
  tensorboard/pip_package/build_pip_package.sh
Labels: cla: yes, type:build/install

#3676 Add TensorBoard.dev's histograms support to README
  README.md
Labels: cla: yes

#3670 [DebuggerV2] Generalize StackTrace component to accommodate graph ops
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_graphs_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_container.ts
Labels: cla: yes

#3681 docs: clarify that `matmul`, etc. are not summary ops
  README.md
Labels: cla: yes

#3677 2.2.2 Post-release: Add 2.2.2 relnotes to RELEASE.md
  RELEASE.md
Labels: cla: yes

#3684 [DebuggerV2] Refactor container tests for clearer directory organization
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/execution_data_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_test.ts
Labels: cla: yes
