Repository tensorflow/tensorboard, pull requests merged in 2020-06, with the labels that each got.

#3653 Projector config at root becomes default config for any present runs
  tensorboard/plugins/projector/projector_plugin.py
Labels: cla: yes, plugin:projector

#3679 do not misconstrue Optimizer slot values as embeddings
  tensorboard/plugins/projector/projector_plugin.py
Labels: cla: yes, plugin:projector

#3692 debugger: add missing `:expect_ngrx_store_testing` deps
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/BUILD
Labels: cla: yes, plugin:debugger, type:build/install

#3689 ci: update `buildifier` to 3.0.0
  .github/workflows/ci.yml
Labels: cla: yes, type:build/install

#3685 [projector] support tensor stored in binary format
  tensorboard/plugins/projector/projector_plugin.py
Labels: cla: yes, plugin:projector

#3691 ci: enforce `load-on-top` lint warning
  .github/workflows/ci.yml
Labels: cla: yes, type:build/install

#3687 [DebuggerV2] Improve the scrolling experience of the eager timeline
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_store_utils.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/execution_data_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_container_test.ts
Labels: cla: yes

#3639 Introduce reload-on-ready prop to dashboard
  tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-dashboard.html
  tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-dashboard.html
  tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-dashboard.html
  tensorboard/plugins/debugger/tf_debugger_dashboard/tf-debugger-dashboard.html
  tensorboard/plugins/distribution/tf_distribution_dashboard/tf-distribution-dashboard.html
  tensorboard/plugins/histogram/tf_histogram_dashboard/tf-histogram-dashboard.html
  tensorboard/plugins/image/tf_image_dashboard/tf-image-dashboard.html
  tensorboard/plugins/mesh/tf_mesh_dashboard/tf-mesh-dashboard.html
  tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-dashboard.html
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
  tensorboard/plugins/text/tf_text_dashboard/tf-text-dashboard.html
Labels: cla: yes

#3633 Use tf-wbr-string in tf-node-info
  tensorboard/components/tf_runs_selector/BUILD
  tensorboard/components/tf_runs_selector/tf-runs-selector.html
  tensorboard/components/tf_wbr_string/BUILD
  tensorboard/components/tf_wbr_string/test/BUILD
  tensorboard/components/tf_wbr_string/test/tests.html
  tensorboard/components/tf_wbr_string/test/tfWbrStringTests.ts
  tensorboard/components/tf_wbr_string/tf-wbr-string.html
  tensorboard/plugins/graph/tf_graph_info/BUILD
  tensorboard/plugins/graph/tf_graph_info/tf-node-info.html
  tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.html
Labels: cla: yes

#3699 Revert "Use tf-wbr-string in tf-node-info (#3633)"
  tensorboard/components/tf_runs_selector/BUILD
  tensorboard/components/tf_runs_selector/tf-runs-selector.html
  tensorboard/components/tf_runs_selector/tf-wbr-string.html
  tensorboard/components/tf_wbr_string/BUILD
  tensorboard/components/tf_wbr_string/test/BUILD
  tensorboard/components/tf_wbr_string/test/tests.html
  tensorboard/components/tf_wbr_string/test/tfWbrStringTests.ts
  tensorboard/plugins/graph/tf_graph_info/BUILD
  tensorboard/plugins/graph/tf_graph_info/tf-node-info.html
  tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.html
Labels: cla: yes

#3698 Refactor distributions plugin name into metadata file
  tensorboard/plugins/distribution/BUILD
  tensorboard/plugins/distribution/distributions_plugin.py
  tensorboard/plugins/distribution/metadata.py
Labels: cla: yes

#3589 ng: prevent double dashboard reload on mount
  tensorboard/webapp/plugins/plugins_component.ts
  tensorboard/webapp/plugins/plugins_container.ts
  tensorboard/webapp/plugins/plugins_container_test.ts
Labels: cla: yes

#3695 program: include dynamic plugins by default
  tensorboard/default.py
  tensorboard/main.py
Labels: cla: yes, core:backend, type:bug

#3674 Support jupyter-server-proxy (and other proxies)
  tensorboard/notebook.py
Labels: cla: yes

#3700 Rollforward "Use tf-wbr-string in tf-node-info"
  tensorboard/components/tf_runs_selector/BUILD
  tensorboard/components/tf_runs_selector/tf-runs-selector.html
  tensorboard/components/tf_wbr_string/BUILD
  tensorboard/components/tf_wbr_string/test/BUILD
  tensorboard/components/tf_wbr_string/test/tests.html
  tensorboard/components/tf_wbr_string/test/tfWbrStringTests.ts
  tensorboard/components/tf_wbr_string/tf-wbr-string.html
  tensorboard/plugins/graph/tf_graph_info/BUILD
  tensorboard/plugins/graph/tf_graph_info/tf-node-info.html
  tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.html
Labels: cla: yes

#3697 [DebuggerV2] Use Map for graph ops
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_graphs_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
Labels: cla: yes

#3696 data: specify more precise downsampling semantics
  tensorboard/backend/event_processing/data_provider_test.py
  tensorboard/data/provider.py
Labels: cla: yes, core:backend, type:docs

#3705 Revert "ng: prevent double dashboard reload on mount "
  tensorboard/webapp/plugins/plugins_component.ts
  tensorboard/webapp/plugins/plugins_container.ts
  tensorboard/webapp/plugins/plugins_container_test.ts
Labels: cla: yes, core:frontend

#3678 uploader: display upload statistics while uploading data
  tensorboard/uploader/BUILD
  tensorboard/uploader/flags_parser.py
  tensorboard/uploader/upload_tracker.py
  tensorboard/uploader/upload_tracker_test.py
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_subcommand.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes

#3706 ng: make error page last reload time hideable
  tensorboard/webapp/plugins/plugins_component.ng.html
  tensorboard/webapp/plugins/plugins_component.ts
Labels: cla: yes, core:frontend

#3708 Unify instances of logger warn() to warning()
  tensorboard/backend/application.py
  tensorboard/backend/event_processing/event_accumulator.py
  tensorboard/backend/event_processing/event_accumulator_test.py
  tensorboard/backend/event_processing/event_multiplexer.py
  tensorboard/backend/event_processing/plugin_event_accumulator.py
  tensorboard/backend/event_processing/plugin_event_accumulator_test.py
  tensorboard/backend/event_processing/plugin_event_multiplexer.py
  tensorboard/backend/security_validator.py
  tensorboard/backend/security_validator_test.py
  tensorboard/encode_png_benchmark.py
  tensorboard/plugins/audio/metadata.py
  tensorboard/plugins/beholder/beholder_plugin.py
  tensorboard/plugins/beholder/video_writing.py
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/debugger/debugger_plugin.py
  tensorboard/plugins/debugger/debugger_server_lib.py
  tensorboard/plugins/debugger/tensor_store.py
  tensorboard/plugins/graph/graphs_plugin.py
  tensorboard/plugins/histogram/metadata.py
  tensorboard/plugins/image/metadata.py
  tensorboard/plugins/pr_curve/metadata.py
  tensorboard/plugins/projector/projector_plugin.py
  tensorboard/plugins/scalar/metadata.py
  tensorboard/plugins/text/metadata.py
  tensorboard/program.py
  tensorboard/uploader/exporter.py
Labels: cla: yes

#3707 uploader: add options --dry_run and --one_shot
  tensorboard/uploader/BUILD
  tensorboard/uploader/dry_run_stubs.py
  tensorboard/uploader/dry_run_stubs_test.py
  tensorboard/uploader/flags_parser.py
  tensorboard/uploader/upload_tracker.py
  tensorboard/uploader/upload_tracker_test.py
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_subcommand.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes

#3682 [DebuggerV2] Highlight same-file frames and stick to bottommost frame
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_graphs_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_store_utils.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_store_utils_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_container.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_container_test.ts
Labels: cla: yes

#3713 [DebuggerV2] Remove flakiness in a Python unit test
  tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
  tensorboard/plugins/debugger_v2/debug_data_multiplexer_test.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes

#3716 [DebuggerV2] Remove transitive dependency on store-internal helper
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_store_helpers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_store_utils.ts
Labels: cla: yes

#3721 [DebuggerV2] Fix a few CSS issues in overall layout
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.css
Labels: cla: yes

#3723 Roll forward vulcanization printer change with check for outside-head link importing
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes

#3694 projector: always check root logdir for embeddings
  tensorboard/plugins/projector/projector_plugin.py
Labels: cla: yes, plugin:projector, type:bug

#3726 uploader: refactor nested context managers
  tensorboard/uploader/uploader.py
Labels: cla: yes

#3719 Fix custom scalars full width mode
  tensorboard/components/tf_paginated_view/tf-dom-repeat.html
  tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-dashboard.html
Labels: cla: yes

#3729 ng: change default page size
  tensorboard/webapp/core/store/core_types.ts
Labels: cla: yes

#3730 tf-runs-selector: fix data location clipping behavior
  tensorboard/components/tf_runs_selector/tf-runs-selector.html
Labels: cla: yes, core:frontend

#3725 ng: use replaceState for null pluginId to non-null
  tensorboard/webapp/core/views/hash_storage_component.ts
  tensorboard/webapp/core/views/hash_storage_test.ts
Labels: cla: yes

#3733 ng: removed unwanted console statement
  tensorboard/webapp/core/views/hash_storage_component.ts
Labels: cla: yes

#3734 (cleanup) Code clarity fixes
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes

#3727 Updating fairness-indicators.md
  docs/fairness-indicators.md
Labels: cla: yes

#3731 ng: remove paper-styles global style rules
  tensorboard/components/tf_tensorboard/style.html
  third_party/polymer.bzl
Labels: cla: yes, core:frontend, type:cleanup

#3739 ng: fix iframe plugin rendering
  tensorboard/webapp/plugins/plugins_component.ts
Labels: cla: yes

#3737 [DebuggerV2] Introduce data reloading
  tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/execution_data_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_container_test.ts
Labels: cla: yes

#3742 cleanup: fix branding TensorBoard in docs
  tensorboard/http_api.md
  tensorboard/plugins/hparams/http_api.md
Labels: cla: yes

#3741 Expose line chart "scaled to fit" state
  tensorboard/components/vz_line_chart2/vz-line-chart2.ts
Labels: cla: yes

#3743 [DebuggerV2] Improve CSS layout of rightmost sections
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.ng.html
Labels: cla: yes

#3749 Documentation for Text Plugin's HTTP API
  tensorboard/plugins/text/http_api.md
Labels: cla: yes

#3746 Support transformation extent method for log scale charts
  tensorboard/components/vz_line_chart2/log-scale.ts
Labels: cla: yes

#3744 [DataFrame API] Add tutorial notebook
  docs/_book.yaml
  docs/dataframe_api.ipynb
Labels: cla: yes

#3754 ng: integrate the experimental api
  tensorboard/components/experimental/plugin_util/BUILD
  tensorboard/components/experimental/plugin_util/plugin-host.html
  tensorboard/webapp/plugins/plugins_component.ts
  tensorboard/webapp/plugins/plugins_container_test.ts
Labels: cla: yes

#3756 Make HParams Analytics conform to strictTemplatePolicy via `_template: null`
  tensorboard/plugins/hparams/tf_hparams_google_analytics_tracker/tf-hparams-google-analytics-tracker.html
Labels: cla: yes

#3757 cleanup: remove unused :application deps
  tensorboard/BUILD
  tensorboard/plugins/custom_scalar/BUILD
  tensorboard/plugins/debugger/BUILD
  tensorboard/plugins/distribution/BUILD
  tensorboard/plugins/graph/BUILD
  tensorboard/plugins/histogram/BUILD
  tensorboard/plugins/mesh/BUILD
  tensorboard/plugins/pr_curve/BUILD
  tensorboard/plugins/text/BUILD
Labels: cla: yes, type:cleanup

#3759 Create "Upload" button to provide instructions for uploading to TensorBoard.dev
  tensorboard/webapp/BUILD
  tensorboard/webapp/tbdev_upload/BUILD
  tensorboard/webapp/tbdev_upload/tbdev_upload_button_component.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ng.html
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.scss
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_module.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_test.ts
  tensorboard/webapp/testing/mat_icon.module.ts
  third_party/js.bzl
Labels: cla: yes

#3763 HParams: remove internal-only Google Analytics tracker
  tensorboard/plugins/hparams/tf_hparams_google_analytics_tracker/BUILD
  tensorboard/plugins/hparams/tf_hparams_google_analytics_tracker/test/tf-hparams-google-analytics-tracker-test.html
  tensorboard/plugins/hparams/tf_hparams_google_analytics_tracker/tf-hparams-google-analytics-tracker.html
  tensorboard/plugins/hparams/tf_hparams_main/BUILD
  tensorboard/plugins/hparams/tf_hparams_main/tf-hparams-main.html
Labels: cla: yes

#3766 DataFrame: Fix NOTE section and error in an output cell
  docs/dataframe_api.ipynb
Labels: cla: yes

#3762 Add distributions to list of launched dashboards for TensorBoard.dev
  README.md
Labels: cla: yes

#3764 Add ability to copy sample command in TensorBoard.dev upload dialog
  tensorboard/webapp/BUILD
  tensorboard/webapp/angular/BUILD
  tensorboard/webapp/tbdev_upload/BUILD
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ng.html
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.scss
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_module.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_test.ts
  tensorboard/webapp/testing/mat_icon.module.ts
  third_party/js.bzl
Labels: cla: yes

#3745 Angular-based Text Plugin v2 backend (experimental)
  tensorboard/BUILD
  tensorboard/default.py
  tensorboard/plugins/text_v2/BUILD
  tensorboard/plugins/text_v2/http_api.md
  tensorboard/plugins/text_v2/text_v2_plugin.py
  tensorboard/plugins/text_v2/text_v2_plugin_test.py
Labels: cla: yes, plugin:text

#3776 [Debugger] Fix a failing test due to usage of deprecated numpy API
  tensorboard/plugins/debugger/health_pill_calc.py
Labels: cla: yes

#3768 Fix numpy deprecation warnings
  tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/plugin.py
  tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
  tensorboard/plugins/custom_scalar/summary_test.py
  tensorboard/plugins/text/text_plugin.py
  tensorboard/util/tensor_util.py
Labels: cla: yes, type:cleanup
