Repository tensorflow/tensorboard, pull requests merged in 2020-03, with the labels that each got.

#3310 uploader: require experiment metadata from server
  tensorboard/uploader/BUILD
  tensorboard/uploader/exporter.py
  tensorboard/uploader/exporter_test.py
  tensorboard/uploader/uploader_main.py
Labels: cla: yes, core:uploader

#3308 uploader: export experiment metadata
  tensorboard/uploader/BUILD
  tensorboard/uploader/exporter.py
  tensorboard/uploader/exporter_test.py
  tensorboard/uploader/util.py
  tensorboard/uploader/util_test.py
Labels: cla: yes, core:uploader

#3319 Silence deprecation warning spam about tf_record_iterator
  tensorboard/backend/event_processing/event_file_loader.py
Labels: cla: yes

#3320 Use cPython 3.5–compatible function definitions
  .github/workflows/ci.yml
  pyproject.toml
  tensorboard/data/provider.py
Labels: cla: yes, type:build/install

#3325 uploader: fix invalid argument error handling
  tensorboard/uploader/uploader_main.py
Labels: cla: yes, core:uploader, type:bug

#3324 Add 2.1.1 relnotes to RELEASE.md
  RELEASE.md
Labels: cla: yes

#3313 [DebuggerV2] Add mat-slider to TimelineComponent
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_container.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_module.ts
  tensorboard/webapp/angular/BUILD
Labels: cla: yes

#3327 style: fix settings panel
  tensorboard/webapp/settings/dialog_component.css
  tensorboard/webapp/settings/dialog_component.ts
Labels: cla: yes

#3329 ng: theme using material theme
  WORKSPACE
  tensorboard/defs/defs.bzl
  tensorboard/webapp/BUILD
  tensorboard/webapp/_angular_material_theming.scss
  tensorboard/webapp/_palette.scss
  tensorboard/webapp/_theme.scss
  tensorboard/webapp/header/BUILD
  tensorboard/webapp/header/header_component.ts
  tensorboard/webapp/header/plugin_selector_component.css
  tensorboard/webapp/header/plugin_selector_component.scss
  tensorboard/webapp/index.html
  tensorboard/webapp/styles.scss
Labels: cla: yes

#3334 [DebuggerV2] Remove unneeded dependecy from the timeline BUILD target
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/BUILD
Labels: cla: yes

#3337 Size of text in heading changed to default style in Image plugin dashboard
  tensorboard/plugins/image/tf_image_dashboard/tf-image-dashboard.html
Labels: cla: yes, plugin:images

#3333 cleanup: mirror bazel_{nodejs,sass} rules
  WORKSPACE
Labels: cla: yes

#3338 Rename TensorPointMetadata to TensorTag
  tensorboard/uploader/proto/tensor.proto
Labels: cla: yes

#3312 base_plugin: enforce kwarg-only initializers
  tensorboard/plugins/BUILD
  tensorboard/plugins/base_plugin.py
Labels: cla: yes

#3332 Buildifier format js.bzl for future edits
  .github/workflows/ci.yml
  third_party/js.bzl
Labels: cla: yes

#3339 ci: tighten Pip installs for linting
  .github/workflows/ci.yml
Labels: cla: yes, type:build/install

#3346 Fix links to summaries page
  docs/r1/graphs.md
  docs/r1/histograms.md
Labels: cla: yes

#3328 ng: reconfigure MetaReducer to use Injectable
  tensorboard/webapp/app_module.ts
  tensorboard/webapp/reducer_config.ts
Labels: cla: yes

#3340 cleanup: add third_party/js.bzl format to ignore
  .git-blame-ignore-revs
Labels: cla: yes

#3344 Experimental plugins specified using ExperimentalPluginLoader
  tensorboard/backend/BUILD
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/backend/experimental_plugin.py
  tensorboard/components/tf_backend/router.ts
  tensorboard/components/tf_backend/test/backendTests.ts
Labels: cla: yes

#3330 [DebuggerV2] Add types, selectors, reducers & effects for source code
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/data_source/tfdbg2_data_source.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
Labels: cla: yes

#3347 bug: fix the tooltip not disappearing issue
  tensorboard/components/vz_chart_helpers/plottable-interactions.js
Labels: cla: yes

#3343 [DebuggerV2] Support FULL_HEALTH debug mode; Display readable dtype string
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/extract_dtypes_from_python.py
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/execution_data_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/execution_data_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/execution_data_container.ts
Labels: cla: yes

#3352 Update the TensorBoard profiling doc to use the new profiler.
  docs/images/profiler-blocking-runtime.png
  docs/images/profiler-capture.png
  docs/images/profiler-download-logdir.png
  docs/images/profiler-idle-gpu.png
  docs/images/profiler-input-cpu.png
  docs/images/profiler-notebook-settings.png
  docs/images/profiler-prefetch-runtime.png
  docs/images/profiler-trace-viewer-select.png
  docs/images/profiler-trace-viewer.png
  docs/images/profiler_trace_viewer_bad_ip.png
  docs/images/profiler_trace_viewer_good_ip.png
  docs/tensorboard_profiling_keras.ipynb
Labels: cla: yes

#3349 ng: refactor theming for reusability
  tensorboard/defs/defs.bzl
  tensorboard/webapp/BUILD
  tensorboard/webapp/styles.scss
  tensorboard/webapp/theme/BUILD
  tensorboard/webapp/theme/_tb_palette.scss
  tensorboard/webapp/theme/_tb_theme.scss
Labels: cla: yes

#3336 ng: implement reload button and info icon
  tensorboard/webapp/BUILD
  tensorboard/webapp/core/actions/core_actions.ts
  tensorboard/webapp/core/effects/core_effects.ts
  tensorboard/webapp/core/effects/core_effects_test.ts
  tensorboard/webapp/header/BUILD
  tensorboard/webapp/header/header_component.ts
  tensorboard/webapp/header/header_module.ts
  tensorboard/webapp/header/header_test.ts
  tensorboard/webapp/header/reload_container.ts
  tensorboard/webapp/testing/mat_icon.module.ts
  third_party/js.bzl
Labels: cla: yes

#3348 plugin_util: cache Markdown converter for speed
  tensorboard/plugin_util.py
Labels: cla: yes, core:backend, theme:performance, type:bug

#3350 cleanup: lint scss formats using prettier
  package.json
Labels: cla: yes

#3355 Rename BlobState enum values
  tensorboard/uploader/proto/blob.proto
Labels: cla: yes

#3356 lint: add --diff flag to show black diff
  .github/workflows/ci.yml
Labels: cla: yes

#3357 debugger: fix genrule for sync
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/extract_dtypes_from_python.py
Labels: cla: yes

#3363 Revert "Rename BlobState enum values (#3355)"
  tensorboard/uploader/proto/blob.proto
Labels: cla: yes

#3365 cleanup: unused dependencies from js.bzl
  third_party/js.bzl
Labels: cla: yes, type:cleanup

#3370 Rename BlobState enum values (#3355)
  tensorboard/uploader/proto/blob.proto
Labels: cla: yes

#2371 Confirm that the connection to tensorboard works or change to localhost
  tensorboard/program.py
Labels: cla: yes

#3268 Refactor Uploader to use Generic Data, and upload blobs.
  tensorboard/uploader/BUILD
  tensorboard/uploader/test_util.py
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes

#3366 ng: allow reload button to be reused
  tensorboard/webapp/header/header_module.ts
Labels: cla: yes

#3359 [DebuggerV2] Create ngrx state and effects for fetching individual source-file contents
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/data_source/tfdbg2_data_source.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_store_utils.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
Labels: cla: yes

#3368 Added S3_ENDPOINT variable
  tensorboard/compat/tensorflow_stub/io/gfile.py
Labels: cla: yes

#3380 Reverts a small inadvertent change to a license file.
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
Labels: cla: yes

#3373 Add message types and rpc method to support exporting BLOBs
  tensorboard/uploader/proto/blob.proto
  tensorboard/uploader/proto/export_service.proto
Labels: cla: yes

#3379 sec: update transitive dependencies
  yarn.lock
Labels: cla: yes

#3377 Add --plugins option to uploader
  tensorboard/uploader/proto/server_info.proto
  tensorboard/uploader/server_info.py
  tensorboard/uploader/server_info_test.py
  tensorboard/uploader/uploader_main.py
Labels: cla: yes

#3382 hparams: add missing build dep to `:metadata`
  tensorboard/plugins/hparams/BUILD
Labels: cla: yes, plugin:hparams, type:build/install

#3372 Update the main images to overview page in profiling tutorial.
  docs/images/profiler_overview_page_bad_ip.png
  docs/images/profiler_overview_page_good_ip.png
  docs/images/tb_call_1.png
  docs/images/tb_call_2.png
  docs/tensorboard_profiling_keras.ipynb
Labels: cla: yes

#3384 Revert "Add message types and rpc method to support exporting BLOBs (#3373)
  tensorboard/uploader/proto/blob.proto
  tensorboard/uploader/proto/export_service.proto
Labels: cla: yes

#3387 chore: update yarn.lock
  yarn.lock
Labels: cla: yes

#3386 hparams: write valid tensor summaries
  tensorboard/BUILD
  tensorboard/dataclass_compat.py
  tensorboard/dataclass_compat_test.py
  tensorboard/plugins/hparams/BUILD
  tensorboard/plugins/hparams/metadata.py
  tensorboard/plugins/hparams/summary.py
  tensorboard/plugins/hparams/summary_test.py
  tensorboard/plugins/hparams/summary_v2.py
  tensorboard/plugins/hparams/summary_v2_test.py
Labels: cla: yes, plugin:hparams

#3390 Roll forward "Add message types and rpc method to support exporting BLOBs"
  tensorboard/uploader/proto/blob.proto
  tensorboard/uploader/proto/export_service.proto
Labels: cla: yes

#3374 [DebuggerV2] Add shim for loadMonaco() method and supporting external libraries
  package.json
  tensorboard/BUILD
  tensorboard/components/tf_imports/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/load_monaco_shim.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/load_monaco_shim_test.ts
  yarn.lock
Labels: cla: yes

#3392 proto: sync to TensorFlow v2.2.0-rc0
  tensorboard/compat/proto/allocation_description.proto
  tensorboard/compat/proto/api_def.proto
  tensorboard/compat/proto/attr_value.proto
  tensorboard/compat/proto/cluster.proto
  tensorboard/compat/proto/config.proto
  tensorboard/compat/proto/cost_graph.proto
  tensorboard/compat/proto/debug.proto
  tensorboard/compat/proto/function.proto
  tensorboard/compat/proto/graph.proto
  tensorboard/compat/proto/meta_graph.proto
  tensorboard/compat/proto/node_def.proto
  tensorboard/compat/proto/op_def.proto
  tensorboard/compat/proto/resource_handle.proto
  tensorboard/compat/proto/rewriter_config.proto
  tensorboard/compat/proto/saved_object_graph.proto
  tensorboard/compat/proto/saver.proto
  tensorboard/compat/proto/step_stats.proto
  tensorboard/compat/proto/struct.proto
  tensorboard/compat/proto/summary.proto
  tensorboard/compat/proto/tensor.proto
  tensorboard/compat/proto/tensor_description.proto
  tensorboard/compat/proto/tensor_shape.proto
  tensorboard/compat/proto/trackable_object_graph.proto
  tensorboard/compat/proto/types.proto
  tensorboard/compat/proto/variable.proto
  tensorboard/compat/proto/verifier_config.proto
  tensorboard/compat/proto/versions.proto
Labels: cla: yes

#3396 Revert "[DebuggerV2] Add shim for loadMonaco() method and supporting …
  package.json
  tensorboard/BUILD
  tensorboard/components/tf_imports/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/load_monaco_shim.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/load_monaco_shim_test.ts
  yarn.lock
Labels: cla: yes

#3375 Add link to TensorBoard.dev in the TensorBoard docs home page
  docs/_index.yaml
Labels: cla: yes

#3378 Add name and description to Colab example
  docs/tbdev_getting_started.ipynb
Labels: cla: yes

#3400 Revert "Add --plugins option to uploader (#3377)"
  tensorboard/uploader/proto/server_info.proto
  tensorboard/uploader/server_info.py
  tensorboard/uploader/server_info_test.py
  tensorboard/uploader/uploader_main.py
Labels: cla: yes, core:uploader

#3393 EngProd: Improve error message for fixing mismatched tf protos.
  tensorboard/compat/proto/proto_test.py
Labels: cla: yes

#3405 favicon: check in source image and inline at build time
  tensorboard/components/BUILD
  tensorboard/components/tensorboard.html
  tensorboard/components/tensorboard.uninlined.html
  tensorboard/logo/BUILD
  tensorboard/logo/favicon.png
  tensorboard/logo/inline_favicon.sh
  tensorboard/webapp/BUILD
  tensorboard/webapp/index.html
  tensorboard/webapp/index.uninlined.html
Labels: cla: yes

#3406 favicon: update to new branding
  tensorboard/logo/favicon.png
  tensorboard/logo/logo.svg
  tensorboard/logo/logo_circled.svg
  tensorboard/logo/sublogo.svg
  tensorboard/tools/license_test.sh
Labels: cla: yes, core:frontend, theme:ui-polish, type:feature

#3402 Add --plugins option to uploader
  tensorboard/uploader/proto/server_info.proto
  tensorboard/uploader/server_info.py
  tensorboard/uploader/server_info_test.py
  tensorboard/uploader/uploader_main.py
Labels: cla: yes

#3411 [DebuggerV2] Add shim for loadMonaco() method & supporting 3rd-party libraries
  package.json
  tensorboard/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/load_monaco_shim.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/load_monaco_shim_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_code/monaco/BUILD
  yarn.lock
Labels: cla: yes

#3424 Post release 2.2.0
  RELEASE.md
  tensorboard/version.py
Labels: cla: yes

#3422 Update golden values and disabled corresponding tests in keras_util_test
  tensorboard/plugins/graph/keras_util_test.py
Labels: cla: yes

#3426 ng: reload now only reloads current dashboard
  tensorboard/webapp/plugins/plugins_component.ts
  tensorboard/webapp/plugins/plugins_container_test.ts
Labels: cla: yes

#3420 ng: create feature_flag store for enabling exp features
  tensorboard/webapp/BUILD
  tensorboard/webapp/app_module.ts
  tensorboard/webapp/feature_flag/BUILD
  tensorboard/webapp/feature_flag/actions/BUILD
  tensorboard/webapp/feature_flag/actions/feature_flag_actions.ts
  tensorboard/webapp/feature_flag/effects/BUILD
  tensorboard/webapp/feature_flag/effects/feature_flag_effects.ts
  tensorboard/webapp/feature_flag/effects/feature_flag_effects_test.ts
  tensorboard/webapp/feature_flag/feature_flag_module.ts
  tensorboard/webapp/feature_flag/store/BUILD
  tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts
  tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_types.ts
  tensorboard/webapp/feature_flag/store/testing.ts
  tensorboard/webapp/feature_flag/types.ts
  tensorboard/webapp/webapp_data_source/BUILD
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_module.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_testing.ts
Labels: cla: yes

#3430 [DebuggerV2] Avoid loading source files that are loaded or loading
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
Labels: cla: yes

#3415 backend: always provide data provider on context
  tensorboard/backend/application.py
  tensorboard/plugins/core/core_plugin.py
Labels: cla: yes, core:backend

#3416 hparams: follow standard `is_active` pattern
  tensorboard/plugins/hparams/hparams_plugin.py
Labels: cla: yes, plugin:hparams

#3427 Add suppression to externs that conflict with Closure Compiler builtins.
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/externs.js
Labels: cla: yes

#3417 hparams: encapsulate direct multiplexer access
  tensorboard/plugins/hparams/backend_context.py
  tensorboard/plugins/hparams/list_session_groups.py
  tensorboard/plugins/hparams/metrics.py
Labels: cla: yes, plugin:hparams

#3418 hparams: thread experiment ID through data access
  tensorboard/plugins/hparams/backend_context.py
  tensorboard/plugins/hparams/backend_context_test.py
  tensorboard/plugins/hparams/get_experiment.py
  tensorboard/plugins/hparams/hparams_plugin.py
  tensorboard/plugins/hparams/list_session_groups.py
  tensorboard/plugins/hparams/list_session_groups_test.py
  tensorboard/plugins/hparams/metrics.py
Labels: cla: yes, plugin:hparams

#3431 ng: conditionally enable debugger_v2
  tensorboard/BUILD
  tensorboard/default.py
  tensorboard/webapp/BUILD
  tensorboard/webapp/app_state.ts
  tensorboard/webapp/core/effects/BUILD
  tensorboard/webapp/core/effects/core_effects.ts
  tensorboard/webapp/core/effects/core_effects_test.ts
  tensorboard/webapp/feature_flag/store/BUILD
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/webapp_data_source/BUILD
  tensorboard/webapp/webapp_data_source/tb_server_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_server_data_source_test.ts
Labels: cla: yes

#3435 data: add tests for blob sequence handling
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/data_provider_test.py
Labels: cla: yes, core:backend

#3433 data: optimize `read_scalars` by skipping scans
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/backend/event_processing/plugin_event_accumulator.py
  tensorboard/backend/event_processing/plugin_event_multiplexer.py
Labels: cla: yes, core:backend, theme:performance

#3419 hparams: read from generic data APIs
  tensorboard/plugins/hparams/BUILD
  tensorboard/plugins/hparams/backend_context.py
  tensorboard/plugins/hparams/backend_context_test.py
  tensorboard/plugins/hparams/list_session_groups_test.py
Labels: cla: yes, plugin:hparams

#3438 hparams: reduce scalar reads while building sessions
  tensorboard/plugins/hparams/backend_context.py
  tensorboard/plugins/hparams/list_session_groups.py
  tensorboard/plugins/hparams/metrics.py
Labels: cla: yes, plugin:hparams, theme:performance

#3410 uploader: add blob exporting
  tensorboard/uploader/BUILD
  tensorboard/uploader/exporter.py
  tensorboard/uploader/exporter_test.py
Labels: cla: yes

#3442 ng: fix tiny charts
  tensorboard/webapp/plugins/plugins_component.ts
  tensorboard/webapp/plugins/plugins_container_test.ts
Labels: cla: yes

#3446 demos: use Windows-compatible path names
  tensorboard/plugins/audio/audio_demo.py
  tensorboard/plugins/scalar/scalars_demo.py
Labels: cla: yes, os:windows

#3447 Disable autoreload by default in Angular frontend
  tensorboard/webapp/core/store/core_reducers.ts
Labels: cla: yes, core:frontend

#3428 ng: disable reload button for disable_reload=True
  tensorboard/webapp/core/testing/index.ts
  tensorboard/webapp/header/header_test.ts
  tensorboard/webapp/header/reload_container.ts
  tensorboard/webapp/plugins/plugins_component.ts
  tensorboard/webapp/plugins/plugins_container_test.ts
Labels: cla: yes

#3449 hparams: minimize calls to context.hparams_metadata()
  tensorboard/plugins/hparams/backend_context.py
  tensorboard/plugins/hparams/list_session_groups.py
Labels: cla: yes, plugin:hparams

#3448 Uploader: Add `total_blob_bytes` field to `Experiment` proto
  tensorboard/uploader/proto/experiment.proto
Labels: cla: yes

#3454 README.md: add GitHub Actions CI badge
  README.md
Labels: cla: yes, type:docs

#3455 docs: adopt `nbfmt.py` formatting, enforced in CI
  .github/workflows/ci.yml
  docs/get_started.ipynb
  docs/graphs.ipynb
  docs/hyperparameter_tuning_with_hparams.ipynb
  docs/image_summaries.ipynb
  docs/migrate.ipynb
  docs/scalars_and_keras.ipynb
  docs/tbdev_getting_started.ipynb
  docs/tensorboard_in_notebooks.ipynb
  docs/tensorboard_profiling_keras.ipynb
  tensorboard/plugins/mesh/Mesh_Plugin_Tensorboard.ipynb
  tensorboard/tools/docs_list_format_test.sh
Labels: cla: yes, type:build/install, type:docs

#3440 docs: fix broken links in `overview.md`
  docs/r1/overview.md
Labels: cla: yes, type:docs
