Repository tensorflow/tensorboard, pull requests merged in 2020-04, with the labels that each got.

#3457 Include the size of the blob in the WriteBlobRequest
  tensorboard/uploader/proto/write_service.proto
  tensorboard/uploader/uploader.py
Labels: cla: yes

#3461 Uploader: remove py2-compatible versions of file-system functions
  tensorboard/uploader/exporter.py
  tensorboard/uploader/exporter_test.py
Labels: cla: yes

#3462 docs: import TensorFlow in `migrate.ipynb`
  docs/migrate.ipynb
Labels: cla: yes, type:docs

#3458 cleanup: lint and protect against skipped tests
  .github/workflows/ci.yml
Labels: cla: yes

#3463 ci: update `nbfmt.py` to enforce exact output
  .github/workflows/ci.yml
Labels: cla: yes, type:build/install, type:docs

#3453 Provide upload limits in ServerInfo, and skip uploading blobs that are too large
  tensorboard/uploader/proto/server_info.proto
  tensorboard/uploader/server_info.py
  tensorboard/uploader/server_info_test.py
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_main.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes

#3467 uploader: Add field mask for total_blob_bytes
  tensorboard/uploader/proto/experiment.proto
Labels: cla: yes

#3459 docs: remove `%tensorflow_version 2.x` directives
  docs/get_started.ipynb
  docs/graphs.ipynb
  docs/hyperparameter_tuning_with_hparams.ipynb
  docs/scalars_and_keras.ipynb
  docs/tbdev_getting_started.ipynb
  docs/tensorboard_in_notebooks.ipynb
Labels: cla: yes, type:docs

#3471 Move uploader flag parsing to its own file and add basic tests
  tensorboard/uploader/BUILD
  tensorboard/uploader/flags_parser.py
  tensorboard/uploader/flags_parser_test.py
  tensorboard/uploader/uploader_main.py
Labels: cla: yes

#3472 [DebuggerV2] Add HTTP route /graph_execution/digests
  tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
  tensorboard/plugins/debugger_v2/debug_data_provider.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes

#3476 build: refactor ng_polymer_lib to be reused.
  tensorboard/components/BUILD
  tensorboard/components/polymer_lib.html
  tensorboard/components/tensorboard.uninlined.html
  tensorboard/webapp/BUILD
  tensorboard/webapp/index.uninlined.html
Labels: cla: yes

#3477 ng: remove config and use enableProdMode
  tensorboard/webapp/BUILD
  tensorboard/webapp/bootstrap.ts
  tensorboard/webapp/config_dev.ts
  tensorboard/webapp/config_prod.ts
  tensorboard/webapp/main.ts
  tensorboard/webapp/main_prod.ts
  tensorboard/webapp/reducer_config.ts
Labels: cla: yes

#3485 build: include `__init__.py` in `//tensorboard`
  tensorboard/BUILD
Labels: cla: yes, type:bug

#3486 application: on plugin load failure, log and continue
  tensorboard/backend/BUILD
  tensorboard/backend/application.py
Labels: cla: yes, core:backend

#3488 ci: retry mirror URLs test
  tensorboard/tools/mirror_urls_test.sh
Labels: cla: yes, type:build/install

#3489 build: update `yarn.lock`
  yarn.lock
Labels: cla: yes, core:frontend, type:build/install

#3487 docs: specify Python 3 for virtualenv creation
  DEVELOPMENT.md
Labels: cla: yes, type:docs

#3478 hparams: inline `Context.experiment`
  tensorboard/plugins/hparams/backend_context.py
  tensorboard/plugins/hparams/backend_context_test.py
  tensorboard/plugins/hparams/get_experiment.py
Labels: cla: yes, plugin:hparams

#3479 hparams: recognize empty plugin content
  tensorboard/plugins/hparams/backend_context.py
Labels: cla: yes, plugin:hparams

#3473 docs: remove `pip install` from TensorBoard.dev guide
  docs/tbdev_getting_started.ipynb
Labels: cla: yes, type:docs

#3483 Disable auto reload if page is not visible
  tensorboard/components/tf_tensorboard/autoReloadBehavior.ts
  tensorboard/components/tf_tensorboard/test/autoReloadTests.ts
Labels: cla: yes

#3482 [DebuggerV2] Add HTTP route /graph_execution/data
  tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
  tensorboard/plugins/debugger_v2/debug_data_provider.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes

#3480 uploader: add `--json` flag to the `list` command
  tensorboard/uploader/BUILD
  tensorboard/uploader/flags_parser.py
  tensorboard/uploader/formatters.py
  tensorboard/uploader/formatters_test.py
  tensorboard/uploader/uploader_main.py
Labels: cla: yes

#3491 plugin_util: use thread-local Markdown converter
  tensorboard/plugin_util.py
Labels: cla: yes, core:backend

#3464 uploader: display binary object bytes in `tensorboard dev list` output
  tensorboard/uploader/formatters.py
  tensorboard/uploader/formatters_test.py
  tensorboard/uploader/uploader_main.py
Labels: cla: yes

#3494 ng: make sure we do not push 'null' onto hash
  tensorboard/webapp/core/views/hash_storage_component.ts
  tensorboard/webapp/core/views/hash_storage_test.ts
Labels: cla: yes

#3492 Support comma-separated --plugins lists for "dev" subcommand
  tensorboard/uploader/flags_parser.py
  tensorboard/uploader/flags_parser_test.py
Labels: cla: yes

#3495 uploader: use fixed (UTC) timezone in formatter unit tests
  tensorboard/uploader/formatters_test.py
Labels: cla: yes

#3466 uploader: remove dev_creds.py
  tensorboard/uploader/BUILD
  tensorboard/uploader/dev_creds.py
  tensorboard/uploader/uploader_main.py
Labels: cla: yes, core:uploader

#3499 Fix 'visibilitychange' event handling in auto reload logic
  tensorboard/components/tf_tensorboard/autoReloadBehavior.ts
  tensorboard/components/tf_tensorboard/test/autoReloadTests.ts
Labels: cla: yes

#3497 Prefilter graphs in the uploader
  tensorboard/BUILD
  tensorboard/backend/process_graph.py
  tensorboard/dataclass_compat.py
  tensorboard/dataclass_compat_test.py
  tensorboard/uploader/uploader.py
Labels: cla: yes

#3401 Add microbenchmark for vz_line_chart
  tensorboard/components/vz_line_chart2/microbenchmark/BUILD
  tensorboard/components/vz_line_chart2/microbenchmark/README.md
  tensorboard/components/vz_line_chart2/microbenchmark/async.ts
  tensorboard/components/vz_line_chart2/microbenchmark/main.html
  tensorboard/components/vz_line_chart2/microbenchmark/main.ts
  tensorboard/components/vz_line_chart2/microbenchmark/polymer_util.ts
  tensorboard/components/vz_line_chart2/microbenchmark/renders_spec.ts
  tensorboard/components/vz_line_chart2/microbenchmark/reporter.ts
  tensorboard/components/vz_line_chart2/microbenchmark/runner.ts
  tensorboard/components/vz_line_chart2/microbenchmark/spec.ts
  tensorboard/components/vz_line_chart2/microbenchmark/types.ts
Labels: cla: yes

#3502 [DebuggerV2] Temporarily disable debugger_v2_plugin_test
  tensorboard/plugins/debugger_v2/BUILD
Labels: cla: yes

#3504 build: lock down `data_compat` and `dataclass_compat`
  tensorboard/BUILD
Labels: cla: yes, type:build/install

#3503 Detect and skip corrupt GraphDefs
  tensorboard/BUILD
  tensorboard/dataclass_compat.py
  tensorboard/dataclass_compat_test.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes

#3505 benchmark: remove unused deps
  tensorboard/components/vz_line_chart2/microbenchmark/BUILD
Labels: cla: yes

#3507 uploader: fix graph RPC test
  tensorboard/uploader/uploader_test.py
Labels: cla: yes, core:uploader

#3508 Catch RuntimeWarning when parsing GraphDef protos.
  tensorboard/dataclass_compat.py
  tensorboard/dataclass_compat_test.py
Labels: cla: yes

#3515 summary: avoid using 'tensorflow' package in import logic
  tensorboard/summary/_tf/summary/__init__.py
Labels: cla: yes, core:summaries

#3519 uploader_test: check logical equality of protos
  tensorboard/uploader/uploader_test.py
Labels: cla: yes, type:build/install

#3510 uploader: inline graph filtering from `dataclass_compat`
  tensorboard/BUILD
  tensorboard/dataclass_compat.py
  tensorboard/dataclass_compat_test.py
  tensorboard/uploader/BUILD
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes, core:uploader

#3517 Upgrade handlebars 4.7.3 -> 4.7.6 to avoid optimist dep
  yarn.lock
Labels: cla: yes

#3521 Update description and landing page video
  docs/_index.yaml
Labels: cla: yes, type:docs

#3498 Disable auto reload if page is not visible in ng_tensorboard
  tensorboard/webapp/reloader/reloader_component.ts
  tensorboard/webapp/reloader/reloader_component_test.ts
Labels: cla: yes

#3523 Update README with TensorBoard.dev graph info
  README.md
Labels: cla: yes

#3511 backend: move compat transforms to event file loading
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/event_accumulator.py
  tensorboard/backend/event_processing/event_file_inspector.py
  tensorboard/backend/event_processing/event_file_loader.py
  tensorboard/backend/event_processing/plugin_event_accumulator.py
  tensorboard/backend/event_processing/plugin_event_accumulator_test.py
  tensorboard/dataclass_compat_test.py
  tensorboard/uploader/BUILD
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes, core:backend

#3525 compat: avoid tf.__version__ in tf2 API lazy loader
  tensorboard/compat/__init__.py
Labels: cla: yes, core:summaries

#3512 dataclass_compat: track initial tag metadata
  tensorboard/backend/event_processing/event_file_loader.py
  tensorboard/backend/event_processing/plugin_event_accumulator_test.py
  tensorboard/dataclass_compat.py
  tensorboard/dataclass_compat_test.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes, core:backend

#3500 audio: deprecate labels and stop reading them
  tensorboard/BUILD
  tensorboard/dataclass_compat.py
  tensorboard/dataclass_compat_test.py
  tensorboard/plugins/audio/audio_plugin.py
  tensorboard/plugins/audio/audio_plugin_test.py
  tensorboard/plugins/audio/plugin_data.proto
  tensorboard/plugins/audio/summary.py
  tensorboard/plugins/audio/summary_test.py
Labels: cla: yes, core:backend, core:summaries, plugin:audio

#3514 audio: add generic data support
  tensorboard/plugins/audio/BUILD
  tensorboard/plugins/audio/audio_plugin.py
  tensorboard/plugins/audio/audio_plugin_test.py
Labels: cla: yes, plugin:audio

#3490 util: add `timing.log_latency`
  tensorboard/BUILD
  tensorboard/util/BUILD
  tensorboard/util/timing.py
  tensorboard/util/timing_test.py
Labels: cla: yes, theme:performance

#3529 text: batch HTML sanitization
  tensorboard/plugin_util.py
  tensorboard/plugin_util_test.py
  tensorboard/plugins/text/text_plugin.py
Labels: cla: yes, plugin:text, theme:performance

#3531 Add the missing `route-prefix` property to `<vz-projector-app>`
  tensorboard/plugins/projector/vz_projector/vz-projector-app.html
Labels: cla: yes

#3423 Add projector plugin colab
  docs/_book.yaml
  docs/images/embedding_projector.png
  docs/images/embedding_projector_anderson.png
  docs/images/embedding_projector_hitchcock.png
  docs/tensorboard_projector_plugin.ipynb
Labels: cla: yes, plugin:projector, type:docs

#3239 Upgrade min Bazel required and upgrade CI to use 2.1
  .travis.yml
  WORKSPACE
Labels: cla: yes

#3528 [DebuggerV2] Flesh out graph execution data display
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_module.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.ng.html
  tensorboard/webapp/angular/BUILD
Labels: cla: yes

#3533 ng: expose core initialState as public
  tensorboard/webapp/core/store/BUILD
  tensorboard/webapp/core/store/core_initial_state_provider.ts
  tensorboard/webapp/core/store/core_initial_state_provider_test.ts
  tensorboard/webapp/core/store/core_reducers.ts
  tensorboard/webapp/core/store/core_types.ts
Labels: cla: yes

#3535 Bump Bazel minimum version to 2.1.0 to match CI
  .bazelrc
  WORKSPACE
Labels: cla: yes, type:build/install

#3532 Refactor tests for _ScalarBatchedRequestSender
  tensorboard/uploader/uploader_test.py
Labels: cla: yes

#3524 improve rerender of vz_line_chart
  tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
  tensorboard/components/vz_line_chart2/line-chart.ts
  tensorboard/components/vz_line_chart2/vz-line-chart2.ts
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
Labels: cla: yes, theme:performance

#3538 Remove standalone uploader binary target
  tensorboard/BUILD
  tensorboard/main.py
  tensorboard/uploader/BUILD
  tensorboard/uploader/flags_parser.py
  tensorboard/uploader/flags_parser_test.py
  tensorboard/uploader/uploader_subcommand.py
Labels: cla: yes

#3539 Remove functionality of legacy DB mode
  tensorboard/BUILD
  tensorboard/backend/BUILD
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/db_import_multiplexer.py
  tensorboard/backend/event_processing/db_import_multiplexer_test.py
  tensorboard/backend/event_processing/sqlite_writer.py
  tensorboard/http_api.md
  tensorboard/plugins/base_plugin.py
  tensorboard/plugins/core/BUILD
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/plugins/histogram/histograms_plugin.py
  tensorboard/plugins/image/images_plugin.py
  tensorboard/plugins/pr_curve/pr_curves_plugin.py
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/scalar/scalars_plugin_test.py
  tensorboard/util/BUILD
Labels: cla: yes, core:backend, type:feature

#3537 Refactor logic common to send Tensors and Scalars
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes

#3546 scalars: remove unused tooltip column DOM
  tensorboard/components/vz_line_chart2/line-chart.ts
Labels: cla: yes

#3544 [DebuggerV2] Revise and re-enable debugger_v2_plugin_test for Const ops
  tensorboard/plugins/debugger_v2/BUILD
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes

#3526 [DebuggerV2] Use more efficient read in /execution/data and /graph_execution/data routes
  tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
Labels: cla: yes

#3550 [DebuggerV2] Highlight stack frame being shown in SourceCodeComponent
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_container.ts
Labels: cla: yes

#3552 Partially revert "improve rerender of vz_line_chart (#3524)"
  tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
  tensorboard/components/vz_line_chart2/line-chart.ts
  tensorboard/components/vz_line_chart2/vz-line-chart2.ts
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.html
Labels: cla: yes, plugin:pr-curves, type:bug

#3553 pr_curves: compute available time entries on client
  tensorboard/plugins/pr_curve/http_api.md
  tensorboard/plugins/pr_curve/pr_curves_plugin.py
  tensorboard/plugins/pr_curve/pr_curves_plugin_test.py
  tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-card.html
  tensorboard/plugins/pr_curve/tf_pr_curve_dashboard/tf-pr-curve-dashboard.html
Labels: cla: yes, plugin:pr-curves

#3530 [DebuggerV2] Start DebugDataMultiplexer reading at plugin creation
  tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
  tensorboard/plugins/debugger_v2/debug_data_multiplexer_test.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes

#3555 pr_curves: remove dead `_create_time_entry` helper
  tensorboard/plugins/pr_curve/pr_curves_plugin.py
Labels: cla: yes, plugin:pr-curves, type:cleanup

#3556 pr_curves: add generic data support
  tensorboard/BUILD
  tensorboard/dataclass_compat.py
  tensorboard/dataclass_compat_test.py
  tensorboard/plugins/pr_curve/BUILD
  tensorboard/plugins/pr_curve/pr_curves_plugin.py
  tensorboard/plugins/pr_curve/pr_curves_plugin_test.py
Labels: cla: yes, plugin:pr-curves

#3545 Support writing tensors in uploader
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes

#3558 pr_curves: compute `num_thresholds` from data size
  tensorboard/plugins/pr_curve/pr_curves_plugin.py
Labels: cla: yes, plugin:pr-curves, theme:performance

#3559 Stabilize generic data for plugins at parity
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/plugins/histogram/histograms_plugin.py
  tensorboard/plugins/histogram/histograms_plugin_test.py
  tensorboard/plugins/image/images_plugin.py
  tensorboard/plugins/image/images_plugin_test.py
  tensorboard/plugins/text/text_plugin.py
  tensorboard/plugins/text/text_plugin_test.py
Labels: cla: yes, core:backend, plugin:histogram, plugin:images, plugin:text

#3569 Use bare raise for reraising _OutOfSpaceError
  tensorboard/uploader/uploader.py
Labels: cla: yes

#3566 build: lock down default visibilities
  tensorboard/backend/event_processing/BUILD
  tensorboard/components/vz_bar_chart/BUILD
  tensorboard/components/vz_chart_helpers/BUILD
  tensorboard/components/vz_example_viewer/BUILD
  tensorboard/plugins/hparams/external_users/BUILD
  tensorboard/plugins/hparams/tf_hparams_backend/BUILD
  tensorboard/plugins/hparams/tf_hparams_dashboard/BUILD
  tensorboard/plugins/hparams/tf_hparams_google_analytics_tracker/BUILD
  tensorboard/plugins/hparams/tf_hparams_main/BUILD
  tensorboard/tools/BUILD
  third_party/BUILD
  third_party/chromium/BUILD
  third_party/protobuf/BUILD
Labels: cla: yes, type:build/install, type:cleanup

#3567 build: use `//tensorboard:internal` for debugger
  tensorboard/plugins/debugger/BUILD
Labels: cla: yes, type:build/install, type:cleanup

#3565 lib: clarify extents of public API
  tensorboard/__init__.py
Labels: cla: yes, type:cleanup

#3563 ng: fix infinite loop when on plugin selector
  tensorboard/webapp/header/header_test.ts
  tensorboard/webapp/header/plugin_selector_component.ng.html
  tensorboard/webapp/header/plugin_selector_component.scss
  tensorboard/webapp/header/plugin_selector_component.ts
Labels: cla: yes
