Repository tensorflow/tensorboard, pull requests merged in 2020-09, with the labels that each got.

#4103 refactor: remove analytics.html dependency
  tensorboard/plugins/projector/polymer3/vz_projector/BUILD
  tensorboard/plugins/projector/polymer3/vz_projector/bundle.ts
  tensorboard/plugins/projector/polymer3/vz_projector/standalone_lib.html
Labels: cla: yes

#4114 Remove vestigial files
  tensorboard/components/analytics.html
  tensorboard/components/polymer_lib.html
  tensorboard/components/security.html
  tensorboard/components/tensorboard.uninlined.html
  tensorboard/components_polymer3/BUILD
  tensorboard/components_polymer3/experimental/plugin_lib/BUILD
Labels: cla: yes

#4117 chore: misc sync fixes (unused in workspace.bzl, license comments)
  .github/workflows/ci.yml
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/BUILD
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/BUILD
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_operator/BUILD
  third_party/workspace.bzl
Labels: cla: yes

#4032 Add TB.dev instructions to TB getting started notebook.
  docs/get_started.ipynb
Labels: cla: yes

#4119 Optional feature keyed types and mat_icon_module naming
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
  tensorboard/webapp/BUILD
  tensorboard/webapp/feature_flag/store/feature_flag_types.ts
  tensorboard/webapp/header/header_test.ts
  tensorboard/webapp/plugins/npmi/store/npmi_types.ts
  tensorboard/webapp/plugins/text_v2/store/text_types.ts
  tensorboard/webapp/settings/dialog_component_test.ts
  tensorboard/webapp/settings/settings_test.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_test.ts
  tensorboard/webapp/testing/BUILD
  tensorboard/webapp/testing/mat_icon_module.ts
Labels: cla: yes

#4123 blame: ignore Prettier 2.1.1 reformatting
  .git-blame-ignore-revs
Labels: cla: yes, type:cleanup

#4120 infra: upgrade FE deps
  package.json
  tensorboard/webapp/testing/BUILD
  tsconfig-lax.json
  tsconfig.json
  yarn.lock
Labels: cla: yes

#4125 docstring: Argument here is `path_prefix`, not `flags`
  tensorboard/backend/application.py
Labels: cla: yes

#4135 [nPMI] Tooltips removed for Titles
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_toolbar/BUILD
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_toolbar/annotations_list_toolbar_component.ng.html
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_toolbar/annotations_list_toolbar_module.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/header/BUILD
  tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_component.ng.html
  tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_module.ts
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/metric_arithmetic_element_module.ts
  tensorboard/webapp/plugins/npmi/views/selected_annotations/BUILD
  tensorboard/webapp/plugins/npmi/views/selected_annotations/selected_annotations_component.ng.html
  tensorboard/webapp/plugins/npmi/views/selected_annotations/selected_annotations_module.ts
  tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/BUILD
  tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/violin_filter_component.ng.html
  tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/violin_filter_module.ts
Labels: cla: yes, plugin:npmi

#4132 [nPMI] Showing Hidden Annotations on Toggle
  tensorboard/webapp/plugins/npmi/util/filter_annotations.ts
Labels: cla: yes, plugin:npmi

#4136 [nPMI] Change "Sorting" to "Sort" throughout the Plugin
  tensorboard/webapp/plugins/npmi/actions/npmi_actions.ts
  tensorboard/webapp/plugins/npmi/store/npmi_reducers.ts
  tensorboard/webapp/plugins/npmi/store/npmi_reducers_test.ts
  tensorboard/webapp/plugins/npmi/store/npmi_selectors.ts
  tensorboard/webapp/plugins/npmi/store/npmi_selectors_test.ts
  tensorboard/webapp/plugins/npmi/store/npmi_types.ts
  tensorboard/webapp/plugins/npmi/testing/index.ts
  tensorboard/webapp/plugins/npmi/util/metric_type.ts
  tensorboard/webapp/plugins/npmi/util/sort_annotations.ts
  tensorboard/webapp/plugins/npmi/util/sort_annotations_test.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_component.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_container.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_component.ng.html
  tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_component.scss
  tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_component.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_container.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_test.ts
Labels: cla: yes, plugin:npmi

#4134 [nPMI] React to both Sidebar Width and Window Width Changes
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_component.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_container.ts
  tensorboard/webapp/plugins/npmi/views/selected_annotations/parallel_coordinates/parallel_coordinates_component.ts
  tensorboard/webapp/plugins/npmi/views/selected_annotations/parallel_coordinates/parallel_coordinates_container.ts
Labels: cla: yes, plugin:npmi

#4133 [nPMI] Automatically Change sorting when Metric Filter Added
  tensorboard/webapp/plugins/npmi/store/npmi_reducers.ts
  tensorboard/webapp/plugins/npmi/store/npmi_reducers_test.ts
Labels: cla: yes, plugin:npmi

#4130 [nPMI] Fixed Run Sorting for Annotation and Height of Rows
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_component.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_container.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_test.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_component.ng.html
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_component.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_container.ts
Labels: cla: yes, plugin:npmi

#4140 Revert "Automatically Change sorting when Metric Filter Added (#4133)"
  tensorboard/webapp/plugins/npmi/store/npmi_reducers.ts
  tensorboard/webapp/plugins/npmi/store/npmi_reducers_test.ts
Labels: cla: yes

#4141 Roll forward "Automatically Change sorting when Metric Filter Added (#4133)"
  tensorboard/webapp/plugins/npmi/store/npmi_reducers.ts
  tensorboard/webapp/plugins/npmi/store/npmi_reducers_test.ts
Labels: cla: yes

#4142 csp: make connect-src configurable
  tensorboard/backend/http_util.py
  tensorboard/backend/http_util_test.py
Labels: cla: yes

#4143 cleanup: remove unused html file in Polymer 3 land
  tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.html
  tensorboard/components/vz_line_chart2/dragZoomInteraction.html
Labels: cla: yes, type:cleanup

#4129 [nPMI] Fixed Filter Chips
  tensorboard/webapp/plugins/npmi/util/filter_annotations.ts
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/metric_arithmetic_element_component.ts
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/metric_arithmetic_element_test.ts
Labels: cla: yes, plugin:npmi

#4146 [nPMI] Changed to Use Template Colors throughout CSS
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_component.scss
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/metric_arithmetic_element_component.scss
  tensorboard/webapp/plugins/npmi/views/main/main_component.scss
  tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/violin_filter_component.scss
  tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/violin_filter_component.ts
  tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filters_component.scss
Labels: cla: yes, plugin:npmi

#4145 [nPMI] Fixed MinBuffer for Scrolling when PC gets minimized.
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_component.ng.html
Labels: cla: yes, plugin:npmi

#4131 [nPMI] Util Tests and Annotations Row Filtered by Regex
  tensorboard/webapp/BUILD
  tensorboard/webapp/plugins/npmi/testing/index.ts
  tensorboard/webapp/plugins/npmi/util/BUILD
  tensorboard/webapp/plugins/npmi/util/coordinate_data_test.ts
  tensorboard/webapp/plugins/npmi/util/filter_annotations.ts
  tensorboard/webapp/plugins/npmi/util/filter_annotations_test.ts
  tensorboard/webapp/plugins/npmi/util/metric_type.ts
  tensorboard/webapp/plugins/npmi/util/metric_type_test.ts
  tensorboard/webapp/plugins/npmi/util/sort_annotations_test.ts
  tensorboard/webapp/plugins/npmi/util/violin_data_test.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_container.ts
  tensorboard/webapp/plugins/npmi/views/data_selection/results_download/BUILD
  tensorboard/webapp/plugins/npmi/views/data_selection/results_download/results_download_container.ts
  tensorboard/webapp/plugins/npmi/views/data_selection/results_download/results_download_module.ts
Labels: cla: yes, plugin:npmi

#4144 Remove legacy multiplexer codepaths for plugins at parity
  tensorboard/plugins/core/BUILD
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/plugins/distribution/BUILD
  tensorboard/plugins/distribution/distributions_plugin_test.py
  tensorboard/plugins/histogram/BUILD
  tensorboard/plugins/histogram/histograms_plugin.py
  tensorboard/plugins/histogram/histograms_plugin_test.py
  tensorboard/plugins/image/images_plugin.py
  tensorboard/plugins/image/images_plugin_test.py
  tensorboard/plugins/text/BUILD
  tensorboard/plugins/text/text_plugin.py
  tensorboard/plugins/text/text_plugin_test.py
Labels: cla: yes

#4147 [nPMI] Updated Plugin README
  tensorboard/plugins/npmi/README.md
Labels: cla: yes, plugin:npmi

#4148 [nPMI] Run Color Selection
  tensorboard/components/BUILD
  tensorboard/components/polymer3_lib.ts
  tensorboard/components/tf_color_scale/BUILD
  tensorboard/components/tf_color_scale/tf-color-scale-polymer.ts
  tensorboard/webapp/plugins/npmi/store/npmi_types.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_component.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_component.ng.html
  tensorboard/webapp/plugins/npmi/views/selected_annotations/parallel_coordinates/parallel_coordinates_component.ts
  tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/violin_filter_component.ts
Labels: cla: yes, plugin:npmi

#4149 cleanup: break projector dependency on weblas with tf
  package.json
  tensorboard/plugins/projector/vz_projector/BUILD
  tensorboard/plugins/projector/vz_projector/data.ts
  tensorboard/plugins/projector/vz_projector/knn.ts
  tensorboard/plugins/projector/vz_projector/util.ts
  tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts
  tensorboard/plugins/projector/vz_projector/vz-projector.ts
  tensorboard/webapp/third_party/BUILD
  tensorboard/webapp/third_party/tfjs.ts
  yarn.lock
Labels: cla: yes

#4155 Plugin/Projector: Document renaming of standalone build target
  tensorboard/plugins/projector/README.md
Labels: cla: yes

#4157 projector: fix UMAP dependency issue
  tensorboard/defs/rollup_config.js
  tensorboard/plugins/projector/vz_projector/BUILD
  tensorboard/plugins/projector/vz_projector/data.ts
  tensorboard/plugins/projector/vz_projector/umap.d.ts
Labels: cla: yes

#4163 proto: sync to TensorFlow e1a7896aaf93 (2020-09-14)
  tensorboard/compat/proto/cluster.proto
  tensorboard/compat/proto/config.proto
  tensorboard/compat/proto/cpp_shape_inference.proto
  tensorboard/compat/proto/debug.proto
  tensorboard/compat/proto/event.proto
  tensorboard/compat/proto/meta_graph.proto
  tensorboard/compat/proto/rewriter_config.proto
  tensorboard/compat/proto/saved_object_graph.proto
  tensorboard/compat/proto/saver.proto
  tensorboard/compat/proto/struct.proto
  tensorboard/compat/proto/tfprof_log.proto
  tensorboard/compat/proto/trackable_object_graph.proto
  tensorboard/compat/proto/verifier_config.proto
Labels: cla: yes

#4167 [oss-timeseries] migrate internal design doc on routing
  docs/design/route_namespaced_state.md
Labels: cla: yes

#4165 [oss-timeseries] add deps for typing, color picker, platform-browser
  package.json
  tensorboard/webapp/angular/BUILD
  yarn.lock
Labels: cla: yes

#4156 cleanup: remove weblas
  package.json
  tensorboard/components/tf_imports/BUILD
  tensorboard/components/tf_imports/weblas.html
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/externs.js
  tensorboard/pip_package/BUILD
  third_party/js.bzl
  yarn.lock
Labels: cla: yes

#3238 Fix scalar demo
  tensorboard/plugins/scalar/scalars_demo.py
Labels: cla: yes

#4162 proto_test: on failure, show all non-empty diffs
  tensorboard/compat/proto/proto_test.py
Labels: cla: yes

#4152 [nPMI] csv to plugin data
  tensorboard/plugins/npmi/BUILD
  tensorboard/plugins/npmi/README.md
  tensorboard/plugins/npmi/csv_to_plugin_data_demo.py
Labels: cla: yes, plugin:npmi

#4171 [oss-timeseries] add angular material build targets.
  tensorboard/webapp/angular/BUILD
Labels: cla: yes

#4168 [oss-timeseries] migrate metrics backend
  tensorboard/plugins/metrics/BUILD
  tensorboard/plugins/metrics/http_api.md
  tensorboard/plugins/metrics/metadata.py
  tensorboard/plugins/metrics/metrics_loader.py
  tensorboard/plugins/metrics/metrics_plugin.py
  tensorboard/plugins/metrics/metrics_plugin_test.py
Labels: cla: yes

#4172 [oss-timeseries] add testing/, types/, util/
  tensorboard/webapp/BUILD
  tensorboard/webapp/testing/BUILD
  tensorboard/webapp/testing/dom.ts
  tensorboard/webapp/testing/lang.ts
  tensorboard/webapp/testing/mat_icon_module.ts
  tensorboard/webapp/testing/material.ts
  tensorboard/webapp/types/BUILD
  tensorboard/webapp/types/ui.ts
  tensorboard/webapp/util/BUILD
  tensorboard/webapp/util/colors.ts
  tensorboard/webapp/util/colors_test.ts
  tensorboard/webapp/util/lang.ts
  tensorboard/webapp/util/lang_test.ts
  tensorboard/webapp/util/ngrx.ts
  tensorboard/webapp/util/ngrx_test.ts
  tensorboard/webapp/util/string.ts
  tensorboard/webapp/util/string_test.ts
  tensorboard/webapp/util/types.ts
  tensorboard/webapp/util/value_formatter.ts
  tensorboard/webapp/util/value_formatter_test.ts
Labels: cla: yes

#4179 [oss-timeseries] fix missed app_routing/ dep needed for sync
  tensorboard/webapp/app_routing/BUILD
Labels: cla: yes

#4177 Update scalars demo for TF2
  tensorboard/plugins/scalar/BUILD
  tensorboard/plugins/scalar/scalars_demo_eager.py
Labels: cla: yes

#4185 chore: bump Chromium version used in functional tests
  third_party/workspace.bzl
Labels: cla: yes

#4186 Turn TBServerDataSource errors into application state
  tensorboard/webapp/core/actions/core_actions.ts
  tensorboard/webapp/core/effects/BUILD
  tensorboard/webapp/core/effects/core_effects.ts
  tensorboard/webapp/core/effects/core_effects_test.ts
  tensorboard/webapp/core/store/BUILD
  tensorboard/webapp/core/store/core_reducers.ts
  tensorboard/webapp/core/store/core_reducers_test.ts
  tensorboard/webapp/core/store/core_selectors.ts
  tensorboard/webapp/core/store/core_types.ts
  tensorboard/webapp/core/testing/index.ts
  tensorboard/webapp/core/types.ts
  tensorboard/webapp/header/header_test.ts
  tensorboard/webapp/plugins/BUILD
  tensorboard/webapp/plugins/plugins_container_test.ts
  tensorboard/webapp/types/data.ts
  tensorboard/webapp/webapp_data_source/BUILD
  tensorboard/webapp/webapp_data_source/tb_server_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_server_data_source_test.ts
Labels: cla: yes

#4192 Render PluginLoadState errors in the UI and allow parent components to override error UI
  tensorboard/webapp/plugins/BUILD
  tensorboard/webapp/plugins/plugins_component.ng.html
  tensorboard/webapp/plugins/plugins_component.ts
  tensorboard/webapp/plugins/plugins_container.ts
  tensorboard/webapp/plugins/plugins_container_test.ts
Labels: cla: yes

#4193 uploader: accept internal alternate experiment name flag
  tensorboard/uploader/flags_parser.py
Labels: cla: yes

#4194 uploader: allow reporting the TB.dev URL via callback
  tensorboard/uploader/uploader_subcommand.py
Labels: cla: yes

#4196 remove LICENSE from exports_files where there is no LICENSE file to be exported
  tensorboard/uploader/BUILD
  tensorboard/uploader/proto/BUILD
  tensorboard/util/BUILD
Labels: cla: yes

#4195 docs: add bind_all to allow docker access
  docs/tensorboard_in_notebooks.ipynb
Labels: cla: yes

#4199 uploader: move UploadIntent tests to uploader_subcommand_test.py
  tensorboard/uploader/BUILD
  tensorboard/uploader/uploader_subcommand_test.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes

#4200 uploader: add test for experiment_url_callback
  tensorboard/uploader/uploader_subcommand_test.py
Labels: cla: yes

#4201 Copy experiment_url_callback docstring to one more place
  tensorboard/uploader/uploader_subcommand.py
Labels: cla: yes

#4202 Load polymer3 portions of app JavaScript before Angular portions.
  tensorboard/webapp/index_polymer3.uninlined.html
Labels: cla: yes

#4203 Expect grpc_testing to be included in internal BUILD files.
  tensorboard/uploader/BUILD
Labels: cla: yes

#4197 Fix URL hash loss upon initial navigation
  tensorboard/webapp/app_routing/effects/app_routing_effects.ts
  tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
  tensorboard/webapp/app_routing/location.ts
Labels: cla: yes
