Repository tensorflow/tensorboard, pull requests merged in 2020-07, with the labels that each got.

#3765 [DebuggerV2] Highlight inputs of graph-execution event
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_graphs_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container_test.ts
Labels: cla: yes

#3780 program: increase port scan limit from 10 to 100
  tensorboard/program.py
Labels: cla: yes

#3772 Add "Close" and "Learn More" buttons to TensorBoard.dev Upload dialog
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ng.html
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.scss
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_test.ts
Labels: cla: yes

#3773 Add "Upload" button to header for local users
  tensorboard/webapp/header/BUILD
  tensorboard/webapp/header/header_component.ts
  tensorboard/webapp/header/header_module.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_button_component.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ng.html
  tensorboard/webapp/tbdev_upload/tbdev_upload_module.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_test.ts
Labels: cla: yes

#3786 Revert "Add "Upload" button to header for local users"
  tensorboard/webapp/header/BUILD
  tensorboard/webapp/header/header_component.ts
  tensorboard/webapp/header/header_module.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_button_component.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ng.html
  tensorboard/webapp/tbdev_upload/tbdev_upload_module.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_test.ts
Labels: cla: yes

#3787 Add "Upload" button to header for local users
  tensorboard/webapp/header/BUILD
  tensorboard/webapp/header/header_component.ts
  tensorboard/webapp/header/header_module.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_button_component.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ng.html
  tensorboard/webapp/tbdev_upload/tbdev_upload_module.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_test.ts
Labels: cla: yes

#3788 Mark new tbdev_upload class members as readonly
  tensorboard/webapp/tbdev_upload/tbdev_upload_button_component.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ts
Labels: cla: yes

#3781 scalars: return not found for existent but non-scalar tags
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes, plugin:scalars

#3789 ng: make brand styling consistent
  tensorboard/webapp/header/header_component.ts
Labels: cla: yes

#3795 Fix “data provider on by default” logic
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/histogram/histograms_plugin.py
  tensorboard/plugins/image/images_plugin.py
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/text/text_plugin.py
Labels: cla: yes

#3793 scalars: add HTTP-level tests of download behavior
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes, plugin:scalars, type:cleanup

#3779 Change default FE to Angular TB
  tensorboard/BUILD
  tensorboard/components/BUILD
  tensorboard/pip_package/test_pip_package.sh
  tensorboard/webapp/BUILD
Labels: cla: yes

#3791 Update dots when changing histogram color scale
  tensorboard/plugins/histogram/vz_histogram_timeseries/vz-histogram-timeseries.html
Labels: cla: yes

#3797 ci: enforce `constant-glob` lint warning
  .github/workflows/ci.yml
  tensorboard/compat/tensorflow_stub/BUILD
Labels: cla: yes, type:build/install

#3796 data: make `DataProvider` method args keyword-only
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/backend/event_processing/data_provider_test.py
  tensorboard/data/provider.py
  tensorboard/plugins/audio/audio_plugin.py
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/plugins/debugger_v2/debug_data_provider.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
  tensorboard/plugins/graph/graphs_plugin.py
  tensorboard/plugins/hparams/backend_context.py
  tensorboard/plugins/image/images_plugin.py
  tensorboard/plugins/pr_curve/pr_curves_plugin.py
Labels: cla: yes, core:backend

#3783 Populate ${logdir} in "Upload to TensorBoard.dev" dialog
  tensorboard/webapp/core/actions/core_actions.ts
  tensorboard/webapp/core/effects/core_effects.ts
  tensorboard/webapp/core/effects/core_effects_test.ts
  tensorboard/webapp/core/store/core_reducers.ts
  tensorboard/webapp/core/store/core_reducers_test.ts
  tensorboard/webapp/core/store/core_selectors.ts
  tensorboard/webapp/core/store/core_types.ts
  tensorboard/webapp/core/testing/index.ts
  tensorboard/webapp/tbdev_upload/BUILD
  tensorboard/webapp/tbdev_upload/tbdev_upload_button_component.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ng.html
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.scss
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_container.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_module.ts
  tensorboard/webapp/tbdev_upload/tbdev_upload_test.ts
  tensorboard/webapp/types/api.ts
  tensorboard/webapp/webapp_data_source/tb_server_data_source.ts
Labels: cla: yes

#3794 custom-scalars: fix bug in data download logic and add tests
  tensorboard/plugins/custom_scalar/BUILD
  tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
  tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
Labels: cla: yes, plugin:custom-scalars

#3802 custom-scalars: activate iff custom layout exists
  tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
  tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
Labels: cla: yes, plugin:custom-scalars

#3803 custom-scalars: add data provider to test context
  tensorboard/plugins/custom_scalar/BUILD
  tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
Labels: cla: yes, plugin:custom-scalars

#3804 scalars: remove vestigial dual-test infrastructure
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes, plugin:scalars

#3808 cleanup: added missing ngrx/store/testing deps
  tensorboard/webapp/tbdev_upload/BUILD
Labels: cla: yes

#3811 Fix getURLPluginData in Angular entry point
  tensorboard/components/tf_storage/storage.ts
  tensorboard/components/tf_tensorboard/tf-tensorboard.html
  tensorboard/webapp/deeplink/hash.ts
Labels: cla: yes

#3814 Fix broken deeplink test
  tensorboard/webapp/deeplink/deeplink_test.ts
Labels: cla: yes

#3790 Add the run state in the core state
  tensorboard/webapp/core/BUILD
  tensorboard/webapp/core/actions/BUILD
  tensorboard/webapp/core/actions/core_actions.ts
  tensorboard/webapp/core/store/BUILD
  tensorboard/webapp/core/store/core_reducers.ts
  tensorboard/webapp/core/store/core_reducers_test.ts
  tensorboard/webapp/core/store/core_selectors.ts
  tensorboard/webapp/core/store/core_selectors_test.ts
  tensorboard/webapp/core/store/core_types.ts
  tensorboard/webapp/core/testing/index.ts
  tensorboard/webapp/core/types.ts
Labels: cla: yes

#3792 Depend on d3 via npm
  package.json
  tensorboard/components/tf_imports/BUILD
  tensorboard/pip_package/BUILD
  tensorboard/webapp/third_party/BUILD
  tensorboard/webapp/third_party/d3.ts
  third_party/js.bzl
  yarn.lock
Labels: cla: yes

#3813 Preserve domains in line chart when changing settings
  tensorboard/components/vz_line_chart2/line-chart.ts
  tensorboard/components/vz_line_chart2/log-scale.ts
  tensorboard/components/vz_line_chart2/vz-line-chart2.ts
Labels: cla: yes

#3818 ng: turn off state serialiability check
  tensorboard/webapp/app_module.ts
Labels: cla: yes

#3807 Linkify first mention of "TensorBoard.dev" in Upload dialog
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ng.html
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.scss
Labels: cla: yes

#3785 [DebuggerV2] Add screenshots to inactive page
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/inactive/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/inactive/images/cutout-1-alerts.png
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/inactive/images/cutout-2-tracing.png
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/inactive/images/cutout-3-code.png
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/inactive/inactive_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/inactive/inactive_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/inactive/inactive_component.uninlined.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/inactive/inline_images.py
Labels: cla: yes

#3815 data: add `AuthProvider` and `AuthContext`
  tensorboard/data/BUILD
  tensorboard/data/auth.py
  tensorboard/data/auth_test.py
Labels: cla: yes, core:backend

#3827 application: simplify `_handling_errors` plumbing
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
Labels: cla: yes, core:backend

#3823 ng: fetch and populate the runs in the store
  tensorboard/webapp/core/effects/BUILD
  tensorboard/webapp/core/effects/core_effects.ts
  tensorboard/webapp/core/effects/core_effects_test.ts
  tensorboard/webapp/types/api.ts
  tensorboard/webapp/webapp_data_source/BUILD
  tensorboard/webapp/webapp_data_source/tb_server_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_server_data_source_test.ts
Labels: cla: yes

#3826 auth: move out of `data` package to root
  tensorboard/BUILD
  tensorboard/auth.py
  tensorboard/auth_test.py
  tensorboard/data/BUILD
Labels: cla: yes, core:backend

#3816 backend: add `RequestContext`
  tensorboard/BUILD
  tensorboard/context.py
  tensorboard/context_test.py
  tensorboard/plugin_util.py
  tensorboard/plugin_util_test.py
Labels: cla: yes, core:backend

#3828 Revert logic that preserves axis domains
  tensorboard/components/vz_line_chart2/line-chart.ts
  tensorboard/components/vz_line_chart2/vz-line-chart2.ts
Labels: cla: yes

#3817 data: add `ctx` parameter to `DataProvider` methods
  tensorboard/backend/application_test.py
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/data/provider.py
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/plugins/debugger_v2/debug_data_provider.py
Labels: cla: yes, core:backend

#3819 data: require `ctx` and fix all call sites
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/backend/event_processing/data_provider_test.py
  tensorboard/plugins/audio/audio_plugin.py
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/plugins/custom_scalar/BUILD
  tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
  tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
  tensorboard/plugins/distribution/BUILD
  tensorboard/plugins/distribution/distributions_plugin.py
  tensorboard/plugins/distribution/distributions_plugin_test.py
  tensorboard/plugins/graph/BUILD
  tensorboard/plugins/graph/graphs_plugin.py
  tensorboard/plugins/graph/graphs_plugin_test.py
  tensorboard/plugins/histogram/BUILD
  tensorboard/plugins/histogram/histograms_plugin.py
  tensorboard/plugins/histogram/histograms_plugin_test.py
  tensorboard/plugins/hparams/BUILD
  tensorboard/plugins/hparams/backend_context.py
  tensorboard/plugins/hparams/backend_context_test.py
  tensorboard/plugins/hparams/get_experiment.py
  tensorboard/plugins/hparams/hparams_plugin.py
  tensorboard/plugins/hparams/list_metric_evals.py
  tensorboard/plugins/hparams/list_metric_evals_test.py
  tensorboard/plugins/hparams/list_session_groups.py
  tensorboard/plugins/hparams/list_session_groups_test.py
  tensorboard/plugins/image/images_plugin.py
  tensorboard/plugins/pr_curve/BUILD
  tensorboard/plugins/pr_curve/pr_curves_plugin.py
  tensorboard/plugins/pr_curve/pr_curves_plugin_test.py
  tensorboard/plugins/scalar/BUILD
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/scalar/scalars_plugin_test.py
  tensorboard/plugins/text/BUILD
  tensorboard/plugins/text/text_plugin.py
  tensorboard/plugins/text/text_plugin_test.py
  tensorboard/plugins/text_v2/BUILD
  tensorboard/plugins/text_v2/text_v2_plugin.py
  tensorboard/plugins/text_v2/text_v2_plugin_test.py
Labels: cla: yes, core:backend

#3824 application: integrate auth providers and context
  tensorboard/backend/BUILD
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
Labels: cla: yes, core:backend

#3830 Make `auth` and `context` py2-compatible
  tensorboard/BUILD
  tensorboard/auth.py
  tensorboard/context.py
Labels: cla: yes, core:backend, type:build/install

#3758 [DebuggerV2] Add tutorial doc
  docs/_book.yaml
  docs/debugger_v2.md
  docs/images/debugger_v2_1_full_view.png
  docs/images/debugger_v2_2_nan_inf_alerts.png
  docs/images/debugger_v2_3_graph_input.png
  docs/images/debugger_v2_4_source_code.png
Labels: cla: yes

#3832 [DebuggerV2] Add title to tensor names in GraphExecutionComponent
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_container_test.ts
Labels: cla: yes

#3821 [DebuggerV2] Remove experimental status of plugin
  tensorboard/default.py
Labels: cla: yes

#3836 resin: use CSS variable instead of prop->style binding
  tensorboard/plugins/text/tf_text_dashboard/tf-text-loader.html
Labels: cla: yes

#3839 ci: pin to non-broken nightlies
  .travis.yml
Labels: cla: yes, type:build/install

#3838 scalars: refactor tests to use public interfaces
  tensorboard/plugins/scalar/BUILD
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes, plugin:scalars

#3833 [DebuggerV2] Refactor and clean up stack-frame-related types
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/data_source/tfdbg2_data_source.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_graphs_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_store_utils.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_store_utils_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_container.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_container_test.ts
Labels: cla: yes

#3831 reland: preserve domains in line chart when changing settings
  tensorboard/components/vz_line_chart2/line-chart.ts
  tensorboard/components/vz_line_chart2/vz-line-chart2.ts
Labels: cla: yes

#3846 beholder: add deprecation warning and UI banner
  tensorboard/plugins/beholder/README.md
  tensorboard/plugins/beholder/beholder.py
  tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-dashboard.html
Labels: cla: yes, plugin:beholder

#3834 HParams: display "no data" message, like other plugins
  tensorboard/plugins/hparams/tf_hparams_main/tf-hparams-main.html
  tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/tf-hparams-parallel-coords-plot.html
  tensorboard/plugins/hparams/tf_hparams_query_pane/tf-hparams-query-pane.html
Labels: cla: yes, plugin:hparams

#3850 Revert "[Projector] make root directory config default for available runs"
  tensorboard/plugins/projector/projector_plugin.py
Labels: cla: yes

#3848 cleanup: remove unused iron_ajax
  tensorboard/components/tf_dashboard_common/BUILD
  third_party/polymer.bzl
Labels: cla: yes

#3851 lib: make `errors` submodule lazy
  tensorboard/BUILD
  tensorboard/__init__.py
Labels: cla: yes, core:backend

#3852 errors: add `UnauthenticatedError`
  tensorboard/BUILD
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/backend/http_util.py
  tensorboard/backend/http_util_test.py
  tensorboard/errors.py
  tensorboard/errors_test.py
Labels: cla: yes, core:backend

#3849 ci: unpin 2020-07-12 nightlies
  .travis.yml
Labels: cla: yes, type:build/install

#3825 Added the Angular wrapper for tf-runs-selector
  tensorboard/webapp/BUILD
  tensorboard/webapp/core/store/core_reducers.ts
  tensorboard/webapp/core/store/core_reducers_test.ts
  tensorboard/webapp/core/store/core_selectors.ts
  tensorboard/webapp/core/store/core_selectors_test.ts
  tensorboard/webapp/core/store/core_types.ts
  tensorboard/webapp/core/testing/index.ts
  tensorboard/webapp/runs/BUILD
  tensorboard/webapp/runs/runs_module.ts
  tensorboard/webapp/runs/views/legacy_runs_selector/BUILD
  tensorboard/webapp/runs/views/legacy_runs_selector/legacy_runs_selector_component.ts
  tensorboard/webapp/runs/views/legacy_runs_selector/legacy_runs_selector_container.ts
  tensorboard/webapp/runs/views/legacy_runs_selector/legacy_runs_selector_module.ts
  tensorboard/webapp/runs/views/legacy_runs_selector/legacy_runs_selector_test.ts
Labels: cla: yes

#3853 [DebugerV2] Fix unintended markdown section header caused by hash
  docs/debugger_v2.md
Labels: cla: yes

#3799 nPMI Plugin Backend (experimental)
  tensorboard/BUILD
  tensorboard/default.py
  tensorboard/plugins/npmi/BUILD
  tensorboard/plugins/npmi/README.md
  tensorboard/plugins/npmi/http_api.md
  tensorboard/plugins/npmi/metadata.py
  tensorboard/plugins/npmi/npmi_plugin.py
  tensorboard/plugins/npmi/npmi_plugin_test.py
  tensorboard/plugins/npmi/plugin_data.proto
  tensorboard/plugins/npmi/summary.py
  tensorboard/plugins/npmi/summary_test.py
Labels: cla: yes

#3855 application: add injection point for middleware
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
Labels: cla: yes, core:backend

#3822 Add utm_source to outbound TensorBoard.dev links
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ng.html
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.ts
Labels: cla: yes

#3847 data: add dispatching data provider
  tensorboard/data/BUILD
  tensorboard/data/dispatching_provider.py
  tensorboard/data/dispatching_provider_test.py
Labels: cla: yes, core:backend

#3858 data: simplify dispatching provider tests
  tensorboard/data/dispatching_provider_test.py
Labels: cla: yes, core:backend

#3861 fix data_ingester_test on Python 3.8
  tensorboard/backend/event_processing/data_ingester_test.py
Labels: cla: yes, os:windows

#3862 Update protos for TF v2.3.0-rc2
  tensorboard/compat/proto/config.proto
  tensorboard/compat/proto/cost_graph.proto
  tensorboard/compat/proto/resource_handle.proto
  tensorboard/compat/proto/rewriter_config.proto
  tensorboard/compat/proto/saved_object_graph.proto
  tensorboard/compat/proto/struct.proto
  tensorboard/compat/proto/update.sh
Labels: cla: yes

#3863 run selector interop: populate initial state
  tensorboard/webapp/runs/views/legacy_runs_selector/legacy_runs_selector_component.ts
  tensorboard/webapp/runs/views/legacy_runs_selector/legacy_runs_selector_test.ts
Labels: cla: yes

#3874 Scalars plugin: Return 400 if run or tag is not specified
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes

#3875 Scalars plugin: Clean up unused Python imports
  tensorboard/plugins/scalar/BUILD
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes

#3876 Change our Plottable monkey patch to TypeScript
  tensorboard/components/vz_chart_helpers/BUILD
  tensorboard/components/vz_chart_helpers/plottable-interactions.d.ts
  tensorboard/components/vz_chart_helpers/plottable-interactions.ts
Labels: cla: yes

#3844 migration prep: introduce relaxed tsconfig
  BUILD
  tensorboard/defs/defs.bzl
  tsconfig-lax.json
Labels: cla: yes

#3879 cleanup: remove extraneous license header
  tensorboard/components/vz_chart_helpers/plottable-interactions.ts
Labels: cla: yes

#3881 chore: remove beholder
  tensorboard/BUILD
  tensorboard/components/tf_tensorboard/BUILD
  tensorboard/components/tf_tensorboard/default-plugins.html
  tensorboard/default.py
  tensorboard/pip_package/BUILD
  tensorboard/pip_package/setup.py
  tensorboard/pip_package/test_pip_package.sh
  tensorboard/plugins/beholder/BUILD
  tensorboard/plugins/beholder/README.md
  tensorboard/plugins/beholder/__init__.py
  tensorboard/plugins/beholder/beholder.py
  tensorboard/plugins/beholder/beholder_demo.py
  tensorboard/plugins/beholder/beholder_plugin.py
  tensorboard/plugins/beholder/beholder_plugin_loader.py
  tensorboard/plugins/beholder/beholder_test.py
  tensorboard/plugins/beholder/colormaps.py
  tensorboard/plugins/beholder/docs/array_1d.png
  tensorboard/plugins/beholder/docs/array_2d.png
  tensorboard/plugins/beholder/docs/array_4d.png
  tensorboard/plugins/beholder/docs/array_4d_activations.png
  tensorboard/plugins/beholder/docs/beholder.png
  tensorboard/plugins/beholder/docs/controls.png
  tensorboard/plugins/beholder/file_system_tools.py
  tensorboard/plugins/beholder/im_util.py
  tensorboard/plugins/beholder/resources/arrays-missing.png
  tensorboard/plugins/beholder/resources/frame-missing.png
  tensorboard/plugins/beholder/resources/no-data.png
  tensorboard/plugins/beholder/tf_beholder_dashboard/BUILD
  tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-dashboard.html
  tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-info.html
  tensorboard/plugins/beholder/tf_beholder_dashboard/tf-beholder-video.html
  tensorboard/plugins/beholder/video_writing.py
  tensorboard/plugins/beholder/visualizer.py
  tensorboard/plugins/debugger/BUILD
  tensorboard/plugins/debugger/im_util.py
  tensorboard/plugins/debugger/tensor_helper_test.py
  tensorboard/plugins/debugger/tensor_store_test.py
  tensorboard/tools/license_test.sh
Labels: cla: yes, plugin:beholder

#3883 Remove spurious startup warnings about "missing TensorBoard installation"
  DEVELOPMENT.md
  tensorboard/BUILD
Labels: cla: yes

#3845 migration prep: add library dependency
  package.json
  yarn.lock
Labels: cla: yes

#3886 chore: use real version of rollup plugins
  package.json
  tensorboard/defs/defs.bzl
  tensorboard/defs/rollup_config.js
  yarn.lock
Labels: cla: yes

#3888 cleanup: removed unused example viewer
  tensorboard/components/vz_example_viewer/BUILD
  tensorboard/components/vz_example_viewer/index.html
  tensorboard/components/vz_example_viewer/vz-example-viewer.html
  tensorboard/components/vz_example_viewer/vz-example-viewer.ts
Labels: cla: yes

#3890 migrate: tf_utils
  tensorboard/components_polymer3/tf_utils/BUILD
  tensorboard/components_polymer3/tf_utils/tf-utils.html
  tensorboard/components_polymer3/tf_utils/utils.ts
Labels: cla: yes

#3892 migrate: vz_chart_helper
  package.json
  tensorboard/components_polymer3/vz_chart_helpers/BUILD
  tensorboard/components_polymer3/vz_chart_helpers/plottable-interactions.ts
  tensorboard/components_polymer3/vz_chart_helpers/vz-chart-helpers.html
  tensorboard/components_polymer3/vz_chart_helpers/vz-chart-helpers.ts
  tensorboard/components_polymer3/vz_chart_helpers/vz-chart-tooltip.html
  tensorboard/components_polymer3/vz_chart_helpers/vz-chart-tooltip.ts
  yarn.lock
Labels: cla: yes

#3893 migrate: components_polymer3/vz_sorting
  tensorboard/components_polymer3/vz_sorting/BUILD
  tensorboard/components_polymer3/vz_sorting/sorting.ts
  tensorboard/components_polymer3/vz_sorting/test/BUILD
  tensorboard/components_polymer3/vz_sorting/vz-sorting.html
Labels: cla: yes

#3885 npmi: demo Data Generator
  tensorboard/plugins/npmi/BUILD
  tensorboard/plugins/npmi/README.md
  tensorboard/plugins/npmi/npmi_demo.py
  tensorboard/plugins/npmi/npmi_demo_data.py
  tensorboard/plugins/npmi/npmi_plugin.py
Labels: cla: yes, plugin:npmi

#3896 migrate: tf_globals
  tensorboard/components_polymer3/tf_globals/BUILD
  tensorboard/components_polymer3/tf_globals/globals-polymer.ts
  tensorboard/components_polymer3/tf_globals/globals.ts
  tensorboard/components_polymer3/tf_globals/tf-globals.html
Labels: cla: yes

#3891 migrate tf_markdown_view
  tensorboard/components_polymer3/tf_markdown_view/BUILD
  tensorboard/components_polymer3/tf_markdown_view/tf-markdown-view.ts
Labels: cla: yes

#3899 migrate: tf_color_scale
  tensorboard/components_polymer3/tf_color_scale/BUILD
  tensorboard/components_polymer3/tf_color_scale/colorScale.ts
  tensorboard/components_polymer3/tf_color_scale/palettes.ts
  tensorboard/components_polymer3/tf_color_scale/test/BUILD
  tensorboard/components_polymer3/tf_color_scale/tf-color-scale.html
Labels: cla: yes, polymer3

#3897 migrate: components_polymer3/tf_storage
  tensorboard/components_polymer3/tf_storage/BUILD
  tensorboard/components_polymer3/tf_storage/index.ts
  tensorboard/components_polymer3/tf_storage/listeners.ts
  tensorboard/components_polymer3/tf_storage/storage.ts
  tensorboard/components_polymer3/tf_storage/test/BUILD
  tensorboard/components_polymer3/tf_storage/tf-storage-polymer.ts
Labels: cla: yes, polymer3

#3889 migrate: tf-wbr-string
  tensorboard/components_polymer3/tf_wbr_string/BUILD
  tensorboard/components_polymer3/tf_wbr_string/test/BUILD
  tensorboard/components_polymer3/tf_wbr_string/tf-wbr-string.html
  tensorboard/components_polymer3/tf_wbr_string/tf-wbr-string.ts
Labels: cla: yes, polymer3

#3894 migrate: vz_line_chart2
  tensorboard/components_polymer3/vz_chart_helpers/vz-chart-helpers.ts
  tensorboard/components_polymer3/vz_line_chart2/BUILD
  tensorboard/components_polymer3/vz_line_chart2/dragZoomInteraction.ts
  tensorboard/components_polymer3/vz_line_chart2/line-chart-exporter.ts
  tensorboard/components_polymer3/vz_line_chart2/line-chart.ts
  tensorboard/components_polymer3/vz_line_chart2/linear-scale.ts
  tensorboard/components_polymer3/vz_line_chart2/log-scale.ts
  tensorboard/components_polymer3/vz_line_chart2/panZoomDragLayer.html.ts
  tensorboard/components_polymer3/vz_line_chart2/panZoomDragLayer.ts
  tensorboard/components_polymer3/vz_line_chart2/test/BUILD
  tensorboard/components_polymer3/vz_line_chart2/tf-scale.ts
  tensorboard/components_polymer3/vz_line_chart2/vz-line-chart2.html
  tensorboard/components_polymer3/vz_line_chart2/vz-line-chart2.ts
Labels: cla: yes, polymer3

#3901 migrate: plugins/profile_redirect/polymer3
  tensorboard/plugins/profile_redirect/polymer3/tf_profile_redirect_dashboard/BUILD
  tensorboard/plugins/profile_redirect/polymer3/tf_profile_redirect_dashboard/tf-profile-redirect-dashboard.html
  tensorboard/plugins/profile_redirect/polymer3/tf_profile_redirect_dashboard/tf-profile-redirect-dashboard.ts
Labels: cla: yes, polymer3

#3904 audio: delete unused `tf-audio-grid`
  tensorboard/plugins/audio/polymer3/tf_audio_dashboard/tf-audio-grid.html
  tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-grid.html
Labels: cla: yes, plugin:audio, type:cleanup

#3905 migrate: components_polymer3/tf_card_heading
  tensorboard/components_polymer3/tf_card_heading/BUILD
  tensorboard/components_polymer3/tf_card_heading/tf-card-heading-style.ts
  tensorboard/components_polymer3/tf_card_heading/tf-card-heading.html
  tensorboard/components_polymer3/tf_card_heading/tf-card-heading.ts
  tensorboard/components_polymer3/tf_card_heading/util.html
  tensorboard/components_polymer3/tf_card_heading/util.ts
Labels: cla: yes, polymer3

#3900 migrate: components_polymer3/analytics
  tensorboard/components_polymer3/BUILD
  tensorboard/components_polymer3/analytics.ts
Labels: cla: yes, polymer3

#3907 Remove setRemoveUnusedPrototypePropertiesInExterns
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes

#3908 migrate: tf_dashboard_common
  tensorboard/components_polymer3/tf_dashboard_common/BUILD
  tensorboard/components_polymer3/tf_dashboard_common/array-update-helper.html
  tensorboard/components_polymer3/tf_dashboard_common/array-update-helper.ts
  tensorboard/components_polymer3/tf_dashboard_common/dashboard-style.ts
  tensorboard/components_polymer3/tf_dashboard_common/data-loader-behavior.html
  tensorboard/components_polymer3/tf_dashboard_common/data-loader-behavior.ts
  tensorboard/components_polymer3/tf_dashboard_common/registerDomModule.ts
  tensorboard/components_polymer3/tf_dashboard_common/run-color-style.ts
  tensorboard/components_polymer3/tf_dashboard_common/scrollbar-style.ts
  tensorboard/components_polymer3/tf_dashboard_common/tensorboard-color.ts
  tensorboard/components_polymer3/tf_dashboard_common/tf-dashboard-layout.ts
  tensorboard/components_polymer3/tf_dashboard_common/tf-downloader.ts
  tensorboard/components_polymer3/tf_dashboard_common/tf-dropdown-trigger.ts
  tensorboard/components_polymer3/tf_dashboard_common/tf-filterable-checkbox-dropdown.html
  tensorboard/components_polymer3/tf_dashboard_common/tf-filterable-checkbox-dropdown.ts
  tensorboard/components_polymer3/tf_dashboard_common/tf-filterable-checkbox-list.html
  tensorboard/components_polymer3/tf_dashboard_common/tf-filterable-checkbox-list.ts
  tensorboard/components_polymer3/tf_dashboard_common/tf-multi-checkbox-demo.html
  tensorboard/components_polymer3/tf_dashboard_common/tf-multi-checkbox.html
  tensorboard/components_polymer3/tf_dashboard_common/tf-multi-checkbox.ts
  tensorboard/components_polymer3/tf_dashboard_common/tf-no-data-warning.ts
  tensorboard/components_polymer3/tf_dashboard_common/tf-option-selector.html
  tensorboard/components_polymer3/tf_dashboard_common/tf-option-selector.ts
Labels: cla: yes, polymer3

#3909 migrate: components_polymer3/tf_paginated_view
  tensorboard/components_polymer3/tf_paginated_view/BUILD
  tensorboard/components_polymer3/tf_paginated_view/index.ts
  tensorboard/components_polymer3/tf_paginated_view/paginatedViewStore.ts
  tensorboard/components_polymer3/tf_paginated_view/test/BUILD
  tensorboard/components_polymer3/tf_paginated_view/tf-category-paginated-view.html
  tensorboard/components_polymer3/tf_paginated_view/tf-category-paginated-view.ts
  tensorboard/components_polymer3/tf_paginated_view/tf-dom-repeat.html
  tensorboard/components_polymer3/tf_paginated_view/tf-dom-repeat.ts
  tensorboard/components_polymer3/tf_paginated_view/tf-paginated-view-store.ts
Labels: cla: yes, polymer3

#3912 migrate: components_polymer2/tf_runs_selector
  tensorboard/components_polymer3/tf_runs_selector/BUILD
  tensorboard/components_polymer3/tf_runs_selector/tf-runs-selector.html
  tensorboard/components_polymer3/tf_runs_selector/tf-runs-selector.ts
Labels: cla: yes, polymer3

#3913 sync: remove explicit dependency on py_library
  tensorboard/plugins/npmi/BUILD
Labels: cla: yes

#3911 hparams: remove tf_hparams_main:legacy and visibility group
  tensorboard/plugins/hparams/polymer3/external_users/BUILD
  tensorboard/plugins/hparams/polymer3/tf_hparams_main/BUILD
  tensorboard/plugins/hparams/tf_hparams_main/BUILD
Labels: cla: yes, plugin:hparams

#3915 Allow existing tf_web_library to provide Polymer css without TypeScript
  tensorboard/components/tensor_widget/BUILD
  tensorboard/components/tensor_widget/tensor-widget.html
Labels: cla: yes

#3919 sync: allow InkyBehavior to be imported internally
  tensorboard/components_polymer3/polymer/BUILD
  tensorboard/components_polymer3/polymer/paper_inky_focus_behavior.ts
  tensorboard/components_polymer3/tf_dashboard_common/BUILD
  tensorboard/components_polymer3/tf_dashboard_common/tf-dropdown-trigger.ts
Labels: cla: yes, polymer3

#3923 migrate: use registerStyleDomModule for style declaration
  tensorboard/components/tensor_widget/BUILD
  tensorboard/components/tensor_widget/tensor-widget-style.uninlined.ts
  tensorboard/components_polymer3/polymer/BUILD
  tensorboard/components_polymer3/polymer/register_style_dom_module.ts
  tensorboard/components_polymer3/tf_card_heading/BUILD
  tensorboard/components_polymer3/tf_card_heading/tf-card-heading-style.ts
  tensorboard/components_polymer3/tf_dashboard_common/BUILD
  tensorboard/components_polymer3/tf_dashboard_common/dashboard-style.ts
  tensorboard/components_polymer3/tf_dashboard_common/registerDomModule.ts
  tensorboard/components_polymer3/tf_dashboard_common/run-color-style.ts
  tensorboard/components_polymer3/tf_dashboard_common/scrollbar-style.ts
  tensorboard/components_polymer3/tf_paginated_view/BUILD
  tensorboard/components_polymer3/vz_line_chart2/BUILD
  tensorboard/components_polymer3/vz_line_chart2/panZoomDragLayer.html.ts
Labels: cla: yes, polymer3

#3922 sync: unblock sync by not using location API
  tensorboard/components_polymer3/tf_storage/storage.ts
Labels: cla: yes, polymer3

#3926 migrate: text plugin
  package.json
  tensorboard/plugins/text/polymer3/tf_text_dashboard/BUILD
  tensorboard/plugins/text/polymer3/tf_text_dashboard/tf-text-dashboard.html
  tensorboard/plugins/text/polymer3/tf_text_dashboard/tf-text-dashboard.ts
  tensorboard/plugins/text/polymer3/tf_text_dashboard/tf-text-loader.html
  tensorboard/plugins/text/polymer3/tf_text_dashboard/tf-text-loader.ts
  yarn.lock
Labels: cla: yes, plugin:text, polymer3

#3924 sync: breakout polymer mixin lib out
  tensorboard/components_polymer3/polymer/BUILD
  tensorboard/components_polymer3/polymer/utils_mixin.ts
  tensorboard/components_polymer3/tf_dashboard_common/BUILD
  tensorboard/components_polymer3/tf_dashboard_common/data-loader-behavior.ts
Labels: cla: yes, polymer3

#3925 sync: remove export on class that extends LegacyElementMixin
  tensorboard/components_polymer3/tf_dashboard_common/data-loader-behavior.ts
  tensorboard/components_polymer3/tf_paginated_view/tf-category-paginated-view.ts
  tensorboard/components_polymer3/tf_paginated_view/tf-dom-repeat.ts
  tensorboard/components_polymer3/vz_chart_helpers/vz-chart-tooltip.ts
  tensorboard/components_polymer3/vz_line_chart2/line-chart.ts
Labels: cla: yes, polymer3

#3910 migrate: components_polymer3/tf_line_chart_data_loader
  tensorboard/components_polymer3/tf_line_chart_data_loader/BUILD
  tensorboard/components_polymer3/tf_line_chart_data_loader/tf-line-chart-data-loader.html
  tensorboard/components_polymer3/tf_line_chart_data_loader/tf-line-chart-data-loader.ts
  tensorboard/components_polymer3/vz_line_chart2/vz-line-chart2.ts
Labels: cla: yes, polymer3

#3927 Revert " migrate: components_polymer3/tf_line_chart_data_loader"
  tensorboard/components_polymer3/tf_line_chart_data_loader/BUILD
  tensorboard/components_polymer3/tf_line_chart_data_loader/tf-line-chart-data-loader.html
  tensorboard/components_polymer3/tf_line_chart_data_loader/tf-line-chart-data-loader.ts
  tensorboard/components_polymer3/vz_line_chart2/vz-line-chart2.ts
Labels: cla: yes

#3928 polymer3: fixed broken/faulty register_style
  tensorboard/components_polymer3/polymer/register_style_dom_module.ts
Labels: cla: yes, polymer3

#3929 migrate: tf-line-chart-data-loader
  tensorboard/components_polymer3/tf_dashboard_common/data-loader-behavior.ts
  tensorboard/components_polymer3/tf_line_chart_data_loader/BUILD
  tensorboard/components_polymer3/tf_line_chart_data_loader/tf-line-chart-data-loader.ts
  tensorboard/components_polymer3/vz_line_chart2/vz-line-chart2.ts
Labels: cla: yes

#3935 sync: work around type error
  tensorboard/components_polymer3/vz_line_chart2/line-chart.ts
Labels: cla: yes
