Repository tensorflow/tensorboard, pull requests merged in 2020-02, with the labels that each got.

#3205 pagination: fix pagination input interaction
  tensorboard/components/tf_paginated_view/tf-category-paginated-view.html
Labels: cla: yes

#3211 Keep legacy scheme URL params for WIT
  tensorboard/components/tf_storage/storage.ts
Labels: cla: yes

#3182 Dynamically created plugins from a component registry for extensibility
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_module.ts
  tensorboard/webapp/plugins/BUILD
  tensorboard/webapp/plugins/plugin_registry_module.ts
  tensorboard/webapp/plugins/plugin_registry_types.ts
  tensorboard/webapp/plugins/plugins_component.ng.html
  tensorboard/webapp/plugins/plugins_component.ts
  tensorboard/webapp/plugins/plugins_container_test.ts
  tensorboard/webapp/plugins/plugins_module.ts
  tensorboard/webapp/plugins/testing/BUILD
  tensorboard/webapp/plugins/testing/index.ts
Labels: cla: yes

#3200 ci: run TF 1.x builds against 1.15.0, not its RC
  .travis.yml
Labels: cla: yes, type:build/install

#3217 scalars: remove unused global constants
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.html
Labels: cla: yes

#3216 Add plugin to redirect users to new profile plugin
  tensorboard/BUILD
  tensorboard/components/tf_tensorboard/BUILD
  tensorboard/components/tf_tensorboard/default-plugins.html
  tensorboard/default.py
  tensorboard/plugins/profile_redirect/BUILD
  tensorboard/plugins/profile_redirect/__init__.py
  tensorboard/plugins/profile_redirect/profile_redirect_plugin.py
  tensorboard/plugins/profile_redirect/profile_redirect_plugin_test.py
  tensorboard/plugins/profile_redirect/tf_profile_redirect_dashboard/BUILD
  tensorboard/plugins/profile_redirect/tf_profile_redirect_dashboard/tf-profile-redirect-dashboard.html
Labels: cla: yes, plugin:profile

#3218 profile: defer to dynamic plugin when available
  tensorboard/plugins/profile/profile_plugin_loader.py
Labels: cla: yes, plugin:profile

#3214 docs: publish “Generic data APIs and implementations” design doc
  docs/design/generic_data_apis.md
Labels: cla: yes, type:docs

#3220 add lint check against PY2 BUILD targets
  .github/workflows/ci.yml
  tensorboard/uploader/BUILD
Labels: cla: yes, type:cleanup

#3221 docs: publish “Generic data ingestion” design doc
  docs/design/generic_data_ingestion.md
Labels: cla: yes, type:docs

#3224 doc: a tip about debugging UI tests
  DEVELOPMENT.md
Labels: cla: yes

#3228 ci: add proto lint test with `clang-format`
  .clang-format
  .github/workflows/ci.yml
  tensorboard/plugins/custom_scalar/layout.proto
Labels: cla: yes, type:build/install

#3225 cleanup: fix import statement
  tensorboard/webapp/webapp_data_source/BUILD
  tensorboard/webapp/webapp_data_source/tb_server_data_source_module.ts
Labels: cla: yes

#3230 Convert BaseResponse to wrappers.BaseResponse
  tensorboard/backend/empty_path_redirect_test.py
  tensorboard/backend/experiment_id_test.py
  tensorboard/backend/path_prefix_test.py
Labels: cla: yes

#3231 Remove unused import in fonts.bzl
  third_party/fonts.bzl
Labels: cla: yes

#3234 Proto changes to support experiment name & description.
  tensorboard/uploader/proto/export_service.proto
  tensorboard/uploader/proto/write_service.proto
Labels: cla: yes

#3235 [DebuggerV2] Start fleshing out alerts component
  tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/data_source/tfdbg2_data_source.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_container.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_module.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_container.ts
Labels: cla: yes

#3236 Update export/write services for eventual tensor storage
  tensorboard/uploader/proto/BUILD
  tensorboard/uploader/proto/export_service.proto
  tensorboard/uploader/proto/tensor.proto
  tensorboard/uploader/proto/write_service.proto
Labels: cla: yes

#3243 Update --reload_multifile_inactive_secs default to 24 hours
  tensorboard/plugins/core/core_plugin.py
Labels: cla: yes, core:backend

#3226 Add the WriteBlob bidirectional streaming RPC to the write service.
  tensorboard/uploader/proto/BUILD
  tensorboard/uploader/proto/blob.proto
  tensorboard/uploader/proto/write_service.proto
Labels: cla: yes

#3248 Show warning if trace viewer is used with WebComponents v0
  tensorboard/components/tf_trace_viewer/tf-trace-viewer.html
Labels: cla: yes

#3245 Add experient_metadata to DataProvider
  tensorboard/data/provider.py
  tensorboard/data/provider_test.py
Labels: cla: yes

#3253 Add wall_time field to GetOrCreateBlobSequenceRequest
  tensorboard/uploader/proto/write_service.proto
Labels: cla: yes

#3254 [CorePlugin] Add experiment metadata to /data/environment route response
  tensorboard/components/tf_backend/environmentStore.ts
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
Labels: cla: yes

#3251 Fix typo in "Getting Started with TensorBoard.dev".
  docs/tbdev_getting_started.ipynb
Labels: cla: yes

#3257 Remove now-unused @org_tensorflow_serving_api repo
  third_party/python.bzl
  third_party/tf_serving.BUILD
Labels: cla: yes

#3255 Extract Experiment/ExperimentMask messages into experiment.proto
  tensorboard/uploader/exporter.py
  tensorboard/uploader/exporter_test.py
  tensorboard/uploader/proto/BUILD
  tensorboard/uploader/proto/experiment.proto
  tensorboard/uploader/proto/export_service.proto
  tensorboard/uploader/proto/write_service.proto
  tensorboard/uploader/uploader_main.py
Labels: cla: yes, core:uploader

#3215 Refactor uploader to ease adding new data types
  tensorboard/uploader/BUILD
  tensorboard/uploader/peekable_iterator.py
  tensorboard/uploader/peekable_iterator_test.py
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes

#3252 Upgrade npm bazel dependency for ibazel
  DEVELOPMENT.md
  package.json
  yarn.lock
Labels: cla: yes

#3265 scalars: promote generic data to stable
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes, plugin:scalars, type:feature

#3267 Add trailing newline
  tensorboard/uploader/proto/blob.proto
Labels: cla: yes

#3266 text: add data provider support
  tensorboard/BUILD
  tensorboard/dataclass_compat.py
  tensorboard/plugins/text/BUILD
  tensorboard/plugins/text/text_plugin.py
  tensorboard/plugins/text/text_plugin_test.py
Labels: cla: yes, plugin:text, type:feature

#3270 Disable io_wrapper glob test
  tensorboard/backend/event_processing/io_wrapper_test.py
Labels: cla: yes

#3275 profile: remove Test PyPI index specification
  tensorboard/plugins/profile_redirect/tf_profile_redirect_dashboard/tf-profile-redirect-dashboard.html
Labels: cla: yes, plugin:profile, type:feature

#3271 data: expose downsampling preferences to plugins
  tensorboard/backend/application.py
  tensorboard/plugins/base_plugin.py
  tensorboard/plugins/histogram/histograms_plugin.py
  tensorboard/plugins/image/images_plugin.py
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/text/text_plugin.py
Labels: cla: yes

#3272 data: perform downsampling in multiplexer provider
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/backend/event_processing/data_provider_test.py
  tensorboard/plugins/graph/graphs_plugin.py
Labels: cla: yes

#3274 Add experiment name, description and time getters to environmentStore
  tensorboard/components/tf_backend/environmentStore.ts
Labels: cla: yes

#3262 support meta labels shorter than the embedding (ie unlabelled embeddi…
  tensorboard/plugins/projector/vz_projector/data.ts
  tensorboard/plugins/projector/vz_projector/projectorScatterPlotAdapter.ts
  tensorboard/plugins/projector/vz_projector/vz-projector-inspector-panel.ts
Labels: cla: yes

#3249 Allow tensorboard title in header to be click target with configurable url
  tensorboard/components/tf_tensorboard/test/tensorboardTests.ts
  tensorboard/components/tf_tensorboard/test/tests.html
  tensorboard/components/tf_tensorboard/tf-tensorboard.html
Labels: cla: yes

#3276 build: add an `__init__`-only `tensorboard` library
  tensorboard/BUILD
Labels: cla: yes, type:build/install

#3278 ci: skip `yarn install` on Travis
  .travis.yml
Labels: cla: yes, type:build/install

#3280 Always pass experiment IDs to scalars_impl
  tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
  tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
  tensorboard/plugins/hparams/hparams_plugin.py
  tensorboard/plugins/hparams/list_metric_evals.py
  tensorboard/plugins/hparams/list_metric_evals_test.py
Labels: cla: yes

#3286 build: clamp down `//tensorboard:lib` visibility
  tensorboard/BUILD
Labels: cla: yes

#3287 docs: drop profile plugin offline policy exemption
  ADDING_A_PLUGIN.md
  README.md
Labels: cla: yes, type:docs

#3284 data: require kwargs for time series initializers
  tensorboard/data/BUILD
  tensorboard/data/provider.py
  tensorboard/data/provider_test.py
Labels: cla: yes

#3261 ng: make Polymer pagination configurable from Ng
  tensorboard/components/tf_paginated_view/tf-paginated-view-store.html
  tensorboard/webapp/BUILD
  tensorboard/webapp/app_container.ng.html
  tensorboard/webapp/app_module.ts
  tensorboard/webapp/core/actions/core_actions.ts
  tensorboard/webapp/core/store/core_reducers.ts
  tensorboard/webapp/core/store/core_selectors.ts
  tensorboard/webapp/core/store/core_types.ts
  tensorboard/webapp/core/testing/index.ts
  tensorboard/webapp/settings/BUILD
  tensorboard/webapp/settings/dialog_component.ts
  tensorboard/webapp/settings/dialog_component_test.ts
  tensorboard/webapp/settings/polymer_interop_container.ts
  tensorboard/webapp/settings/polymer_interop_test.ts
  tensorboard/webapp/settings/settings_module.ts
Labels: cla: yes

#3290 data: document that `TensorTimeSeries` extends `_TimeSeries`
  tensorboard/data/provider.py
Labels: cla: yes

#3281 Turn off JSCompiler for ng_tensorboard
  tensorboard/components/BUILD
Labels: cla: yes

#3277 Support experiment name and description in uploader
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_main.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes

#3291 Fix vz_projector tests
  tensorboard/plugins/projector/vz_projector/test/BUILD
  tensorboard/plugins/projector/vz_projector/test/tests.html
Labels: cla: yes

#3285 [DebuggerV2] Add support for alert-type filtering to /alerts route
  tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
  tensorboard/plugins/debugger_v2/debug_data_provider.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes

#3269 [DebuggerV2] Add click callback to alert type; highlight alerts in timeline
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/actions/debugger_actions.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/data_source/tfdbg2_data_source.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/testing/index.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_container.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/alerts_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.css
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/timeline_container.ts
Labels: cla: yes

#3292 graph: fix no data UI
  tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.html
Labels: cla: yes

#3283 Let ExperimentIdMiddleware to be nested
  tensorboard/backend/experiment_id.py
  tensorboard/backend/experiment_id_test.py
Labels: cla: yes

#3293 [DebuggerV2] Remove extraneous import line
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
Labels: cla: yes

#3263 Add demo for projector plugin
  tensorboard/BUILD
  tensorboard/plugins/projector/BUILD
  tensorboard/plugins/projector/projector_demo.py
Labels: cla: yes, plugin:projector

#3289 projector: factor metadata out from frontend plugin
  tensorboard/plugins/projector/BUILD
  tensorboard/plugins/projector/__init__.py
  tensorboard/plugins/projector/metadata.py
  tensorboard/plugins/projector/projector_plugin.py
Labels: cla: yes, plugin:projector, type:build/install, type:cleanup

#3299 uploader: add `PluginControl` handshake protos
  tensorboard/uploader/proto/server_info.proto
Labels: cla: yes

#3302 [Core Plugin] Remove redundant call in _serve_environment()
  tensorboard/plugins/core/core_plugin.py
Labels: cla: yes

#3296 Updated misspelling
  docs/get_started.ipynb
Labels: cla: yes

#3303 Docs - Get Started - PEP8 Code Style Fix
  docs/get_started.ipynb
Labels: cla: yes

#3304 uploader: factor test defaults into helpers
  tensorboard/uploader/uploader_test.py
Labels: cla: yes, core:uploader

#3300 uploader: only send data for allowed plugins
  tensorboard/uploader/BUILD
  tensorboard/uploader/server_info.py
  tensorboard/uploader/server_info_test.py
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_main.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes, core:uploader

#3305 uploader: fix rate limiting for logdir polling
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes, core:uploader, type:bug

#3298 Fixed broken Embedding Projector link
  README.md
Labels: cla: yes, plugin:projector, type:docs

#3307 uploader: export experiments to subdirectories
  tensorboard/uploader/exporter.py
  tensorboard/uploader/exporter_test.py
Labels: cla: yes, core:uploader

#3311 uploader: remove inoperative `f`-string
  tensorboard/uploader/uploader_main.py
Labels: cla: yes, core:uploader, type:bug
