Repository tensorflow/tensorboard, pull requests merged in 2020-12, with the labels that each got.

#4402 line chart: adjust opacity in webgl using HSL
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
Labels: cla: yes

#4407 notebook: don’t filter polled instances by PID
  tensorboard/manager.py
Labels: cla: yes, core:backend, os:windows, type:bug

#4410 blame: ignore Black v20.8b1 and py27/py35 reformattings
  .git-blame-ignore-revs
Labels: cla: yes, type:cleanup

#4408 rust: add option to kill server at stdin EOF
  tensorboard/data/server/main.rs
Labels: cla: yes, core:rustboard

#4403 rust: implement RPC-time downsampling
  tensorboard/data/server/BUILD
  tensorboard/data/server/downsample.rs
  tensorboard/data/server/lib.rs
  tensorboard/data/server/server.rs
Labels: cla: yes, core:rustboard

#4414 black: reformat `tensorboard/manager.py`
  tensorboard/manager.py
Labels: cla: yes, type:build/install

#4399 rust: add short style guide
  tensorboard/data/server/DEVELOPMENT.md
Labels: cla: yes, core:rustboard, type:docs

#4390 cleanup: remove unused tf_import and workspace dep
  tensorboard/BUILD
  tensorboard/components/tf_imports/BUILD
  tensorboard/components/tf_imports/README.md
  tensorboard/components/tf_imports/d3.html
  tensorboard/components/tf_imports/dagre.html
  tensorboard/components/tf_imports/graphlib.html
  tensorboard/components/tf_imports/lodash.html
  tensorboard/components/tf_imports/numericjs.html
  tensorboard/components/tf_imports/plottable.html
  tensorboard/components/tf_imports/polymer-externs.html
  tensorboard/components/tf_imports/polymer.html
  tensorboard/components/tf_imports/tf_graphics_lib.html
  tensorboard/components/tf_imports/threejs.html
  tensorboard/components/tf_imports/umap-js.html
  tensorboard/components/tf_imports/vaadin-grid.html
  tensorboard/components/tf_imports/vaadin-split-layout.html
  tensorboard/components/tf_imports/web-component-tester.d.ts
  tensorboard/defs/BUILD
  tensorboard/defs/clutz.d.ts
  tensorboard/pip_package/BUILD
  third_party/clutz.BUILD
  third_party/clutz.bzl
  third_party/js.bzl
  third_party/polymer.bzl
  third_party/typings.bzl
  third_party/workspace.bzl
Labels: cla: yes

#4371 line chart: fix the nice domain for small constant
  tensorboard/webapp/widgets/line_chart_v2/lib/scale.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/scale_test.ts
Labels: cla: yes

#4415 cleanup: remove unused viewRef in app
  tensorboard/webapp/app_container.ng.html
Labels: cla: yes

#4417 refactor: extract store provider to a separate module
  tensorboard/webapp/BUILD
  tensorboard/webapp/app_module.ts
  tensorboard/webapp/store_module.ts
Labels: cla: yes

#4372 Limit max scalar smoothing to 0.99 / 0.999
  tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
Labels: cla: yes

#4418 ui: allow disabled dropdown options
  tensorboard/webapp/widgets/dropdown/dropdown_component.ts
Labels: cla: yes

#4419 ui: fix styles in dropdowns, smoothing input
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss
  tensorboard/webapp/widgets/dropdown/dropdown_component.scss
Labels: cla: yes

#4416 line chart: improve worker doc and check for assumption
  tensorboard/webapp/widgets/line_chart_v2/lib/worker.ts
Labels: cla: yes

#4405 line chart: implement ignoreOutlier
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/widgets/line_chart_v2/BUILD
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_internal_utils.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_internal_utils_test.ts
Labels: cla: yes

#4411 program: add gRPC data ingester
  tensorboard/BUILD
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/data_ingester.py
  tensorboard/data/BUILD
  tensorboard/data/ingester.py
  tensorboard/data/ingester_test.py
  tensorboard/data/server/DEVELOPMENT.md
  tensorboard/data/server/main.rs
  tensorboard/data/server_ingester.py
  tensorboard/data/server_ingester_test.py
  tensorboard/plugins/core/core_plugin.py
  tensorboard/program.py
Labels: cla: yes, core:backend, core:rustboard

#4426 mesh: fix `is_active` without multiplexer
  tensorboard/plugins/mesh/mesh_plugin.py
  tensorboard/plugins/mesh/mesh_plugin_test.py
Labels: cla: yes, core:rustboard, plugin:mesh, type:bug

#4424 rust: remove some `..Default::default()`s
  tensorboard/data/server/server.rs
Labels: cla: yes, core:rustboard, type:cleanup

#4428 sync: add @ngrx/store dep on app since app_container uses it
  tensorboard/webapp/BUILD
Labels: cla: yes

#4432 ci: add nightly scheduled GitHub Actions job
  .github/workflows/ci.yml
Labels: cla: yes, type:build/install

#4435 ci: remove Travis configs
  .travis.yml
  README.md
  WORKSPACE
  ci/bazelrc_travis
  tensorboard/tools/mirror_urls_test.sh
Labels: cla: yes, type:build/install

#4425 metrics: gracefully degrade without tensors/blobs
  tensorboard/data/provider.py
  tensorboard/plugins/metrics/metrics_plugin.py
Labels: cla: yes, core:rustboard, plugin:time-series

#4427 line chart: calc extent without illegal values
  tensorboard/webapp/widgets/line_chart_v2/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/scale.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/scale_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/scale_types.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_internal_utils.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_internal_utils_test.ts
Labels: cla: yes

#4429 rust: support loading data server from Pip package
  tensorboard/data/server/DEVELOPMENT.md
  tensorboard/data/server/pip_package/BUILD
  tensorboard/data/server/pip_package/build.py
  tensorboard/data/server/pip_package/build_test.py
  tensorboard/data/server/pip_package/install.py
  tensorboard/data/server/pip_package/setup.py
  tensorboard/data/server/pip_package/tensorboard_data_server/__init__.py
  tensorboard/data/server_ingester.py
Labels: cla: yes, core:rustboard, type:build/install

#4434 ci: build and store data server Pip package
  .github/workflows/ci.yml
Labels: cla: yes, core:rustboard, type:build/install

#4436 rust: add macOS Pip package builds
  .github/workflows/ci.yml
  tensorboard/data/server/logdir.rs
  tensorboard/data/server/pip_package/build.py
Labels: cla: yes, core:rustboard, type:build/install

#4437 rust: rename `main.rs` to `cli.rs`
  tensorboard/data/server/BUILD
  tensorboard/data/server/Cargo.toml
  tensorboard/data/server/cli.rs
Labels: cla: yes, core:rustboard

#4438 rust: add `main.rs` wrapper around core `mod cli`
  tensorboard/data/server/BUILD
  tensorboard/data/server/Cargo.toml
  tensorboard/data/server/cli.rs
  tensorboard/data/server/lib.rs
  tensorboard/data/server/main.rs
Labels: cla: yes, core:rustboard

#4376 infra: upgrade frontend dependencies
  BUILD
  WORKSPACE
  package.json
  tensorboard/defs/BUILD
  tensorboard/defs/defs.bzl
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_selectors.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/alerts/BUILD
  tensorboard/webapp/alert/effects/index.ts
  tensorboard/webapp/alert/store/alert_reducers.ts
  tensorboard/webapp/alert/store/alert_selectors.ts
  tensorboard/webapp/angular/BUILD
  tensorboard/webapp/app_container.ts
  tensorboard/webapp/app_routing/BUILD
  tensorboard/webapp/app_routing/effects/app_routing_effects.ts
  tensorboard/webapp/core/effects/core_effects.ts
  tensorboard/webapp/core/store/core_reducers.ts
  tensorboard/webapp/core/store/core_selectors.ts
  tensorboard/webapp/core/views/BUILD
  tensorboard/webapp/core/views/hash_storage_test.ts
  tensorboard/webapp/deeplink/hash_test.ts
  tensorboard/webapp/feature_flag/actions/feature_flag_actions.ts
  tensorboard/webapp/feature_flag/effects/feature_flag_effects.ts
  tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts
  tensorboard/webapp/metrics/effects/index.ts
  tensorboard/webapp/metrics/views/BUILD
  tensorboard/webapp/metrics/views/card_renderer/BUILD
  tensorboard/webapp/metrics/views/main_view/BUILD
  tensorboard/webapp/metrics/views/right_pane/BUILD
  tensorboard/webapp/plugins/npmi/effects/npmi_effects.ts
  tensorboard/webapp/plugins/npmi/store/npmi_reducers.ts
  tensorboard/webapp/plugins/npmi/store/npmi_selectors.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/BUILD
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/BUILD
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_toolbar/BUILD
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_toolbar/annotations_search/BUILD
  tensorboard/webapp/plugins/npmi/views/annotations_list/header/BUILD
  tensorboard/webapp/plugins/npmi/views/annotations_list/legend/legend_element/BUILD
  tensorboard/webapp/plugins/npmi/views/data_selection/BUILD
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/BUILD
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/BUILD
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_operator/BUILD
  tensorboard/webapp/plugins/npmi/views/data_selection/results_download/BUILD
  tensorboard/webapp/plugins/npmi/views/main/BUILD
  tensorboard/webapp/plugins/npmi/views/selected_annotations/BUILD
  tensorboard/webapp/plugins/npmi/views/selected_annotations/parallel_coordinates/BUILD
  tensorboard/webapp/plugins/npmi/views/violin_filters/BUILD
  tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/BUILD
  tensorboard/webapp/plugins/text_v2/effects/text_effects.ts
  tensorboard/webapp/plugins/text_v2/store/text_v2_reducers.ts
  tensorboard/webapp/plugins/text_v2/store/text_v2_selectors.ts
  tensorboard/webapp/reloader/BUILD
  tensorboard/webapp/runs/effects/runs_effects.ts
  tensorboard/webapp/runs/runs_module.ts
  tensorboard/webapp/widgets/dropdown/BUILD
  tensorboard/webapp/widgets/source_code/source_code_container.ts
  third_party/workspace.bzl
  yarn.lock
Labels: cla: yes

#4433 rust: replace static fixture with test helpers
  tensorboard/data/server/commit.rs
  tensorboard/data/server/server.rs
Labels: cla: yes, type:cleanup

#4440 rust: bind server to `::1` by default
  tensorboard/data/server/cli.rs
Labels: cla: yes, core:rustboard

#4441 rust: fix panic when reading explicit tensors/blobs
  tensorboard/data/server/run.rs
Labels: cla: yes, core:rustboard

#4444 line chart: omit nan from interactive view
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ng.html
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts
Labels: cla: yes

#4445 Rename FEAUTURE_FLAG_FEATURE_KEY to FEATURE_FLAG_FEATURE_KEY.
  tensorboard/webapp/feature_flag/feature_flag_module.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_types.ts
  tensorboard/webapp/feature_flag/store/testing.ts
Labels: cla: yes

#4448 ci: collapse some build jobs
  .github/workflows/ci.yml
Labels: cla: yes, theme:performance, type:build/install

#4453 make TF deps include //tensorboard/summary:tf_summary
  tensorboard/BUILD
  tensorboard/plugins/metrics/BUILD
  tensorboard/plugins/scalar/BUILD
  tensorboard/summary/BUILD
Labels: cla: yes, core:summaries, type:cleanup

#4454 graph: use data provider if no multiplexer available
  tensorboard/plugins/graph/graphs_plugin.py
Labels: cla: yes, core:rustboard, plugin:graph

#4449 Remove unnecessary type cast to CoreState.
  tensorboard/webapp/core/store/core_initial_state_provider.ts
Labels: cla: yes

#4456 Do not specify default values in QueryParamsFeatureFlagDataSource. Rely on initialState defaults instead.
  tensorboard/webapp/feature_flag/actions/feature_flag_actions.ts
  tensorboard/webapp/feature_flag/effects/feature_flag_effects.ts
  tensorboard/webapp/feature_flag/effects/feature_flag_effects_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts
  tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts
  tensorboard/webapp/webapp_data_source/BUILD
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
Labels: cla: yes

#4442 line chart: add circle and triangle drawer
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_types.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/svg_renderer.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
Labels: cla: yes

#4457 line chart: fix layout in Safari
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_grid_view.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.scss
Labels: cla: yes

#4459 chore: typecheck 'monaco' types in source code component
  tensorboard/webapp/widgets/source_code/BUILD
  tensorboard/webapp/widgets/source_code/source_code_component.ts
  tensorboard/webapp/widgets/source_code/source_code_container.ts
Labels: cla: yes

#4447 rust: add logdir loading benchmark
  tensorboard/data/server/BUILD
  tensorboard/data/server/Cargo.toml
  tensorboard/data/server/bench.rs
Labels: cla: yes, core:rustboard, theme:performance

#4460 line chart: add paint brush methods for circle/triangle
  tensorboard/webapp/widgets/line_chart_v2/lib/paint_brush.ts
Labels: cla: yes

#4373 bug: apply new scale niceDomain to vz-line-chart
  tensorboard/components/vz_line_chart2/BUILD
  tensorboard/components/vz_line_chart2/linear-scale.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/scale.ts
Labels: cla: yes

#4443 line chart: make threejs coordinator match DOM size
  tensorboard/webapp/widgets/line_chart_v2/lib/coordinator.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/coordinator_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/threejs_coordinator.ts
Labels: cla: yes

#4463 line chart: make sure tooltip repositions when scrolled
  tensorboard/webapp/metrics/views/main_view/BUILD
  tensorboard/webapp/metrics/views/main_view/main_view_component.ng.html
  tensorboard/webapp/metrics/views/main_view/main_view_module.ts
Labels: cla: yes

#4464 misc: fix lint and test output in Source Diff component
  tensorboard/webapp/widgets/source_code/source_code_diff_component.ts
  tensorboard/webapp/widgets/source_code/source_code_diff_container.ts
  tensorboard/webapp/widgets/source_code/source_code_diff_container_test.ts
Labels: cla: yes

#4458 Provide and consume FeatureFlagState StoreConfig, allowing other Tensorboards to override default feature flag values.
  tensorboard/webapp/feature_flag/feature_flag_module.ts
  tensorboard/webapp/feature_flag/store/BUILD
  tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
Labels: cla: yes

#4469 graph: add demo for exotic graph types
  tensorboard/plugins/graph/BUILD
  tensorboard/plugins/graph/graphs_demo.py
Labels: cla: yes, plugin:graph

#4461 line chart: draw NaN with triangle
  tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/drawable.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/integration_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/svg_renderer.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/series_line_view.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/testing.ts
Labels: cla: yes

#4474 line chart: introduce formatter
  tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/formatter.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/formatter_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/public_types.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/BUILD
  tensorboard/webapp/widgets/line_chart_v2/sub_view/axis_formatter.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/axis_formatter_test.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts
Labels: cla: yes

#4470 graph: use DataProvider-compatible APIs
  tensorboard/backend/event_processing/plugin_event_accumulator_test.py
  tensorboard/dataclass_compat.py
  tensorboard/dataclass_compat_test.py
  tensorboard/plugins/graph/BUILD
  tensorboard/plugins/graph/graphs_plugin.py
  tensorboard/plugins/graph/graphs_plugin_test.py
  tensorboard/plugins/graph/metadata.py
Labels: cla: yes, core:rustboard, plugin:graph

#4473 graph: use data provider API exclusively
  tensorboard/dataclass_compat.py
  tensorboard/dataclass_compat_test.py
  tensorboard/plugins/graph/BUILD
  tensorboard/plugins/graph/graphs_plugin.py
  tensorboard/plugins/graph/graphs_plugin_test.py
Labels: cla: yes, core:rustboard, plugin:graph, plugin:graph:profile

#4466 Pass FeatureFlags to CUSTOM_ELEMENT dashboards; use in Scalars dashboard for inColab and scalarsBatchSize.
  tensorboard/plugins/scalar/tf_scalar_dashboard/BUILD
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.ts
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-dashboard.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
  tensorboard/webapp/feature_flag/testing.ts
  tensorboard/webapp/feature_flag/types.ts
  tensorboard/webapp/plugins/BUILD
  tensorboard/webapp/plugins/plugins_component.ts
  tensorboard/webapp/plugins/plugins_container.ts
  tensorboard/webapp/plugins/plugins_container_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
Labels: cla: yes

#4264 [nPMI] Embeddings Similar
  tensorboard/webapp/plugins/npmi/actions/npmi_actions.ts
  tensorboard/webapp/plugins/npmi/data_source/npmi_data_source.ts
  tensorboard/webapp/plugins/npmi/data_source/npmi_data_source_test.ts
  tensorboard/webapp/plugins/npmi/effects/BUILD
  tensorboard/webapp/plugins/npmi/effects/npmi_effects.ts
  tensorboard/webapp/plugins/npmi/effects/npmi_effects_test.ts
  tensorboard/webapp/plugins/npmi/store/npmi_reducers.ts
  tensorboard/webapp/plugins/npmi/store/npmi_reducers_test.ts
  tensorboard/webapp/plugins/npmi/store/npmi_selectors.ts
  tensorboard/webapp/plugins/npmi/store/npmi_selectors_test.ts
  tensorboard/webapp/plugins/npmi/store/npmi_types.ts
  tensorboard/webapp/plugins/npmi/testing/index.ts
  tensorboard/webapp/plugins/npmi/util/sort_annotations.ts
  tensorboard/webapp/plugins/npmi/util/sort_annotations_test.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/BUILD
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_component.ng.html
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_component.scss
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_component.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_container.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_module.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_test.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_component.ng.html
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_component.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_container.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_toolbar/annotations_list_toolbar_container.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_toolbar/annotations_list_toolbar_test.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_component.ng.html
  tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_container.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/header/header_test.ts
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/metric_arithmetic_element_container.ts
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/metric_arithmetic_element_test.ts
  tensorboard/webapp/plugins/npmi/views/main/BUILD
  tensorboard/webapp/plugins/npmi/views/main/main_component.ng.html
  tensorboard/webapp/plugins/npmi/views/main/main_component.scss
  tensorboard/webapp/plugins/npmi/views/main/main_container.ts
  tensorboard/webapp/plugins/npmi/views/main/main_container_test.ts
  tensorboard/webapp/plugins/npmi/views/main/main_module.ts
  tensorboard/webapp/plugins/npmi/views/selected_annotations/parallel_coordinates/BUILD
  tensorboard/webapp/plugins/npmi/views/selected_annotations/parallel_coordinates/parallel_coordinates_component.ts
  tensorboard/webapp/plugins/npmi/views/selected_annotations/parallel_coordinates/parallel_coordinates_container.ts
  tensorboard/webapp/plugins/npmi/views/selected_annotations/parallel_coordinates/parallel_coordinates_test.ts
  tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/BUILD
  tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/violin_filter_component.ts
  tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/violin_filter_container.ts
  tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/violin_filter_test.ts
Labels: cla: yes

#4475 line chart: transfer data with 64 bit precision
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/compact_data_series.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/compact_data_series_test.ts
Labels: cla: yes

#4478 graph: simplify tests
  tensorboard/plugins/graph/graphs_plugin_test.py
  tensorboard/plugins/graph/graphs_plugin_v2_test.py
Labels: cla: yes, core:rustboard, plugin:graph, type:cleanup

#4467 cleanup: depend on d3 redirection module
  tensorboard/plugins/projector/vz_projector/BUILD
  tensorboard/plugins/projector/vz_projector/projectorScatterPlotAdapter.ts
  tensorboard/plugins/projector/vz_projector/scatterPlotVisualizerCanvasLabels.ts
  tensorboard/plugins/projector/vz_projector/vector.ts
  tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts
Labels: cla: yes

#4480 ci: persist Rust caches for Pip package build
  .github/workflows/ci.yml
Labels: cla: yes, core:rustboard, dependencies, theme:performance

#4477 line chart: add temporal scale
  tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/scale.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/scale_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/scale_types.ts
Labels: cla: yes

#4462 scalar card: implement full tooltip
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ng.html
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.scss
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts
  tensorboard/webapp/widgets/line_chart_v2/types.ts
Labels: cla: yes

#4484 Identify which tensor is too large, when dropping from upload
  tensorboard/uploader/uploader.py
Labels: cla: yes

#4485 sync: fix missing material dependency
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/BUILD
Labels: cla: yes

#4471 Allow SourceDiff clients to update 'renderSideBySide'
  tensorboard/webapp/widgets/source_code/source_code_diff_component.ts
  tensorboard/webapp/widgets/source_code/source_code_diff_container.ts
  tensorboard/webapp/widgets/source_code/source_code_diff_container_test.ts
  tensorboard/webapp/widgets/source_code/testing.ts
Labels: cla: yes

#4482 Use `nonlocal` rather than `box[0]` in tests
  tensorboard/auth_test.py
  tensorboard/data/server_ingester_test.py
  tensorboard/lazy_test.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes, type:cleanup

#4490 line chart: tooltip UX improvements
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts
Labels: cla: yes

#4493 py3: remove `argparse_util` helper
  tensorboard/BUILD
  tensorboard/program.py
  tensorboard/util/BUILD
  tensorboard/util/argparse_util.py
  tensorboard/util/argparse_util_test.py
Labels: cla: yes, type:cleanup

#4479 projector: fix `RunPaths` result aliasing
  tensorboard/plugins/projector/projector_plugin.py
Labels: cla: yes, core:rustboard, plugin:projector

#4506 Revert "projector: fix `RunPaths` result aliasing (#4479)"
  tensorboard/plugins/projector/projector_plugin.py
Labels: cla: yes, plugin:projector

#4509 ts: pass explicit args to promise resolvers
  tensorboard/components/tf_backend/requestManager.ts
  tensorboard/components/vz_line_chart2/microbenchmark/async.ts
  tensorboard/components/vz_line_chart2/microbenchmark/polymer_util.ts
  tensorboard/plugins/projector/vz_projector/data.ts
Labels: cla: yes, core:frontend, type:cleanup
