Repository tensorflow/tensorboard, pull requests merged in 2020-01, with the labels that each got.

#3051 [DebuggerV2] Implement /runs route
  tensorboard/plugins/debugger_v2/BUILD
  tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
  tensorboard/plugins/debugger_v2/debug_data_provider.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes

#3094 ci: remove Python 2.7 from `.travis.yml`
  .travis.yml
Labels: cla: yes, type:build/install

#3072 [Migration] image plugin
  tensorboard/components/tf_categorization_utils/BUILD
  tensorboard/components/tf_categorization_utils/categorizationUtils.ts
  tensorboard/plugins/image/tf_image_dashboard/BUILD
  tensorboard/plugins/image/tf_image_dashboard/tf-image-dashboard.ts
  tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.ts
Labels: cla: yes

#3009 images: remove unused width and height on frontend
  tensorboard/plugins/image/http_api.md
  tensorboard/plugins/image/images_plugin.py
  tensorboard/plugins/image/images_plugin_test.py
  tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
Labels: cla: yes, plugin:images

#3096 [migrate] delete unused image plugin files
  tensorboard/plugins/image/tf_image_dashboard/tf-image-dashboard.html
  tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html
Labels: cla: yes

#3095 [migration] computed decorator should not be used on complex properties
  tensorboard/tools/migration/src/helper.ts
  tensorboard/tools/migration/src/polymerelementify.ts
Labels: cla: yes

#3097 [migration] migrate components/experimental
  tensorboard/components/experimental/plugin_lib/BUILD
  tensorboard/components/experimental/plugin_lib/message.ts
  tensorboard/components/experimental/plugin_lib/plugin-guest.ts
  tensorboard/components/experimental/plugin_util/BUILD
  tensorboard/components/experimental/plugin_util/index.ts
  tensorboard/components/experimental/plugin_util/message.html
  tensorboard/components/experimental/plugin_util/message.ts
  tensorboard/components/experimental/plugin_util/plugin-host-ipc.ts
  tensorboard/components/experimental/plugin_util/plugin-host.html
  tensorboard/components/experimental/plugin_util/runs-host-impl.ts
Labels: cla: yes

#3099 [docs] fix link to image in plugin docs
  ADDING_A_PLUGIN.md
Labels: cla: yes

#3100 Fix TensorFlow `Event` proto pollution in test
  tensorboard/backend/event_processing/plugin_event_accumulator_test.py
Labels: cla: yes, type:bug

#3098 [migrate] preserve preamble in all transforms
  tensorboard/tools/migration/src/helper.ts
  tensorboard/tools/migration/src/polymer-html.ts
  tensorboard/tools/migration/src/polymerelementify.ts
  tensorboard/tools/migration/src/script-extract.ts
  tensorboard/tools/migration/src/transfer-import.ts
Labels: cla: yes

#3093 Updates images_demo for TF v2 compatiblity.
  tensorboard/plugins/image/images_demo.py
Labels: cla: yes

#3102 ci: move linting to GitHub actions
  .github/workflows/ci.yml
  .travis.yml
  package.json
Labels: cla: yes, type:build/install

#3110 [DebuggerV2] Add missing BUILD dependency for "data_source"
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/data_source/BUILD
Labels: cla: yes

#3111 [DebuggerV2] Fix a missing build dep
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/BUILD
Labels: cla: yes

#3108 [backend] Split IsTensorFlowEventsFile into two separate functions
  tensorboard/backend/event_processing/event_accumulator.py
  tensorboard/backend/event_processing/io_wrapper.py
  tensorboard/backend/event_processing/io_wrapper_test.py
  tensorboard/backend/event_processing/plugin_event_accumulator.py
Labels: cla: yes

#3105 [migration] migrate plugins/audio
  tensorboard/plugins/audio/tf_audio_dashboard/BUILD
  tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-dashboard.html
  tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-dashboard.ts
  tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-loader.html
  tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-loader.ts
  tensorboard/plugins/audio/tf_audio_dashboard/types.ts
Labels: cla: yes

#3112 [DebuggerV2] Add more missing BUILD deps
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/BUILD
Labels: cla: yes

#3103 [DebuggerV2] Implement the backend execution/digests route
  tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
  tensorboard/plugins/debugger_v2/debug_data_provider.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_types.ts
Labels: cla: yes

#3116 When available, use inspect.getfullargspec instead of inspect.getargspec.
  tensorboard/backend/event_processing/event_file_loader.py
Labels: cla: yes

#3060 Add download links to HParams plugin
  tensorboard/plugins/hparams/BUILD
  tensorboard/plugins/hparams/download_data.py
  tensorboard/plugins/hparams/download_data_test.py
  tensorboard/plugins/hparams/hparams_plugin.py
  tensorboard/plugins/hparams/tf_hparams_backend/tf-hparams-backend.html
  tensorboard/plugins/hparams/tf_hparams_query_pane/tf-hparams-query-pane.html
Labels: cla: yes, plugin:hparams, type:feature

#3088 graphs: use non-null tag name for run graphs
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/plugins/graph/graphs_plugin.py
  tensorboard/plugins/graph/metadata.py
Labels: cla: yes, plugin:graph

#3089 data: enforce `RunTagFilter` typing
  tensorboard/data/provider.py
  tensorboard/data/provider_test.py
Labels: cla: yes, core:backend

#3126 data: use `six.string_types` for `RunTagFilter` type checking
  tensorboard/data/provider.py
Labels: cla: yes, core:backend

#2711 Fix retracing warnings in the range loop.
  docs/migrate.ipynb
Labels: cla: yes

#3113 Document offline policy and privacy guarantees
  ADDING_A_PLUGIN.md
  README.md
Labels: cla: yes, type:docs

#3122 backend: fix locking for `_plugin_to_tag_to_content`
  tensorboard/backend/event_processing/plugin_event_accumulator.py
Labels: cla: yes, core:backend, type:bug

#3128 windows: explicitly register correct MIME types
  tensorboard/program.py
Labels: cla: yes, os:windows

#3129 plugins_listing: handle failures in plugin `is_active`
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
Labels: cla: yes, core:backend

#3124 data: add `list_plugins` for `is_active` support
  tensorboard/backend/BUILD
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/backend/event_processing/data_provider_test.py
  tensorboard/backend/event_processing/plugin_event_accumulator.py
  tensorboard/backend/event_processing/plugin_event_accumulator_test.py
  tensorboard/backend/event_processing/plugin_event_multiplexer.py
  tensorboard/backend/event_processing/plugin_event_multiplexer_test.py
  tensorboard/data/provider.py
  tensorboard/plugins/base_plugin.py
  tensorboard/plugins/distribution/distributions_plugin.py
Labels: cla: yes, core:backend, type:feature

#3123 [DebuggerV2] Implement backend routes: source_files
  tensorboard/plugins/debugger_v2/BUILD
  tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
  tensorboard/plugins/debugger_v2/debug_data_multiplexer_test.py
  tensorboard/plugins/debugger_v2/debug_data_provider.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes

#3127 TB versions after 2.1 should work with TF 2.1
  tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
Labels: cla: yes

#3130 data: fix `is_active`s in generic data mode
  tensorboard/plugins/graph/graphs_plugin.py
  tensorboard/plugins/graph/graphs_plugin_test.py
  tensorboard/plugins/histogram/histograms_plugin.py
  tensorboard/plugins/histogram/histograms_plugin_test.py
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes

#2997 data: add docs about data classes
  tensorboard/data/provider.py
Labels: cla: yes, core:backend, type:docs

#3143 Disable tests based on tf.contrib if tf.contrib is not available
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/plugins/scalar/scalars_plugin_test.py
Labels: cla: yes

#3144 infra: require Python3.6 to install Black
  tensorboard/pip_package/requirements_dev.txt
Labels: cla: yes

#3138 [DebuggerV2] Implement routes /execution/data and /stack_frames/stack_frames
  tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
  tensorboard/plugins/debugger_v2/debug_data_provider.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes

#3131 data: use histograms in multiplexer provider test
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/data_provider_test.py
Labels: cla: yes

#3146 Rewrite core_plugin_test.py to use DB import mode instead of tf.contrib DB writer
  tensorboard/plugins/core/BUILD
  tensorboard/plugins/core/core_plugin_test.py
Labels: cla: yes, core:backend, type:cleanup

#3155 [DebuggerV2] Remove extraneous Jasmine dep
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/timeline/BUILD
Labels: cla: yes

#3156 Fix dependencies
  WORKSPACE
  third_party/js.bzl
Labels: cla: yes

#3158 [DebuggerV2] Minor test fixes for Py2/3 compatibility
  tensorboard/plugins/debugger_v2/BUILD
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes

#3159 Enable strict Typescript option
  tensorboard/components/experimental/plugin_lib/message.ts
  tensorboard/components/experimental/plugin_util/message.ts
  tsconfig.json
Labels: cla: yes

#3150 [DebuggerV2] Some minor refactoring and cleanup in backend
  tensorboard/plugins/debugger_v2/BUILD
  tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes

#3132 data: add data class protos and compat layer
  tensorboard/BUILD
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/backend/event_processing/data_provider_test.py
  tensorboard/backend/event_processing/plugin_event_accumulator.py
  tensorboard/backend/event_processing/plugin_event_accumulator_test.py
  tensorboard/compat/proto/summary.proto
  tensorboard/data_compat.py
  tensorboard/dataclass_compat.py
  tensorboard/dataclass_compat_test.py
Labels: cla: yes

#3167 ci: don’t store Pip HTTP cache
  .travis.yml
Labels: cla: yes, type:build/install

#3161 data: rename `latest_max_index` to `max_length`
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/data/provider.py
  tensorboard/data/provider_test.py
Labels: cla: yes

#3160 Disallow period from plugin names
  ADDING_A_PLUGIN.md
  tensorboard/backend/application.py
  tensorboard/backend/application_test.py
Labels: cla: yes

#3085 [ng] Hash storage component to make changes to the hash
  tensorboard/webapp/BUILD
  tensorboard/webapp/app_container.ng.html
  tensorboard/webapp/app_module.ts
  tensorboard/webapp/core/actions/core_actions.ts
  tensorboard/webapp/core/store/core_reducers.ts
  tensorboard/webapp/core/store/core_reducers_test.ts
  tensorboard/webapp/core/views/BUILD
  tensorboard/webapp/core/views/hash_storage_component.ts
  tensorboard/webapp/core/views/hash_storage_container.ts
  tensorboard/webapp/core/views/hash_storage_module.ts
  tensorboard/webapp/core/views/hash_storage_test.ts
  tensorboard/webapp/webapp_data_source/tb_server_data_source.ts
Labels: cla: yes

#3165 Break plugin controls away from header
  tensorboard/webapp/header/BUILD
  tensorboard/webapp/header/header_component.ng.html
  tensorboard/webapp/header/header_component.ts
  tensorboard/webapp/header/header_module.ts
  tensorboard/webapp/header/header_test.ts
  tensorboard/webapp/header/plugin_selector_component.css
  tensorboard/webapp/header/plugin_selector_component.ng.html
  tensorboard/webapp/header/plugin_selector_component.ts
  tensorboard/webapp/header/plugin_selector_container.ts
Labels: cla: yes

#3169 [sync] add dummy ngrx/store/testing dep
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/BUILD
  tensorboard/webapp/angular/BUILD
  tensorboard/webapp/core/effects/BUILD
  tensorboard/webapp/core/views/BUILD
  tensorboard/webapp/header/BUILD
  tensorboard/webapp/plugins/BUILD
  tensorboard/webapp/reloader/BUILD
  tensorboard/webapp/settings/BUILD
Labels: cla: yes

#3172 Fix buildifier lint errors and improve linting on CI:
  .github/workflows/ci.yml
  tensorboard/components/tf_categorization_utils/BUILD
  tensorboard/components/tf_tensorboard/BUILD
  tensorboard/functionaltests/browsers/BUILD
  tensorboard/plugins/core/BUILD
  tensorboard/plugins/hparams/tf_hparams_scatter_plot_matrix_view/BUILD
Labels: cla: yes

#3162 data: remove `latest_max_index`
  tensorboard/data/provider.py
  tensorboard/data/provider_test.py
Labels: cla: yes

#3137 Update example plugin to check static asset paths
  tensorboard/examples/plugins/example_raw_scalars/BUILD
  tensorboard/examples/plugins/example_raw_scalars/tensorboard_plugin_example_raw_scalars/plugin.py
  tensorboard/examples/plugins/example_raw_scalars/test.py
Labels: cla: yes

#3179 uploader: make `util_test` py3-compatible internally
  tensorboard/uploader/util_test.py
Labels: cla: yes, type:bug

#3180 custom_scalars: use `tensorboard.compat` protos in test
  tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
Labels: cla: yes, type:cleanup

#3185 Change EventFileLoader to use tf_record_iterator when possible
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/event_file_loader.py
  tensorboard/backend/event_processing/event_file_loader_test.py
Labels: cla: yes

#3181 test_util: don’t warn when raw byte strings passed
  tensorboard/util/test_util.py
Labels: cla: yes, type:cleanup

#3164 Update README with legacy logdir_spec
  README.md
Labels: cla: yes

#3183 images: add data provider support
  tensorboard/BUILD
  tensorboard/dataclass_compat.py
  tensorboard/plugins/image/images_plugin.py
  tensorboard/plugins/image/images_plugin_test.py
Labels: cla: yes, plugin:images

#3192 main: add `<html lang="en">` tag
  tensorboard/components/tensorboard.html
Labels: cla: yes

#3193 base_plugin: make `is_ng_component` default idiomatic
  tensorboard/plugins/base_plugin.py
Labels: cla: yes

#3197 Update main.py comment on setting GCS_READ_CACHE_DISABLED
  tensorboard/main.py
Labels: cla: yes, type:cleanup

#3194 Ensure EventFileLoader only uses no-TF stub when required
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/event_file_loader.py
  tensorboard/compat/__init__.py
  tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py
  tensorboard/plugins/projector/projector_plugin.py
Labels: cla: yes, core:backend, type:cleanup

#3198 notf: make `struct.unpack`s portable
  tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py
Labels: cla: yes, core:notf, type:bug

#3195 [DebuggerV2] Backend: Implement basic features of /alerts route
  tensorboard/plugins/debugger_v2/debug_data_multiplexer.py
  tensorboard/plugins/debugger_v2/debug_data_provider.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes

#3201 pip_package: only build Python 3 wheel
  .travis.yml
  tensorboard/pip_package/build_pip_package.sh
  tensorboard/pip_package/test_pip_package.sh
Labels: cla: yes, type:build/install

#3204 Import `Callable` from `collections.abc`
  tensorboard/plugins/audio/audio_plugin_test.py
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/plugins/debugger/debugger_plugin_test.py
  tensorboard/plugins/debugger/events_writer_manager_test.py
  tensorboard/plugins/distribution/distributions_plugin_test.py
  tensorboard/plugins/graph/graphs_plugin_test.py
  tensorboard/plugins/histogram/histograms_plugin_test.py
  tensorboard/plugins/image/images_plugin_test.py
  tensorboard/plugins/mesh/mesh_plugin_test.py
  tensorboard/plugins/pr_curve/pr_curves_plugin_test.py
  tensorboard/plugins/scalar/scalars_plugin_test.py
  tensorboard/plugins/text/text_plugin_test.py
  tensorboard/summary/summary_test.py
Labels: cla: yes

#3203 docs: publish “TensorBoard in Colab” design doc
  docs/design/colab_integration.md
  docs/design/images/colab_screenshot.png
Labels: cla: yes, type:docs
