Repository tensorflow/tensorboard, pull requests merged in 2021-10, with the labels that each got.

#5352 histogram: apply lazy tensor and set up _buckets_v3 skeleton
  tensorboard/plugins/histogram/summary_v2.py
Labels: plugin:histogram, core:summaries, cla: yes

#5354 histogram: add demo examples for edge cases
  tensorboard/plugins/histogram/histograms_demo.py
Labels: plugin:histogram, cla: yes

#5357 hparams: treat no data as an empty experiment rather than an error
  tensorboard/plugins/hparams/BUILD
  tensorboard/plugins/hparams/backend_context.py
  tensorboard/plugins/hparams/backend_context_test.py
  tensorboard/plugins/hparams/get_experiment.py
  tensorboard/plugins/hparams/hparams_plugin.py
Labels: plugin:hparams, cla: yes

#5351 runs-table: do not match against exp name
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
  tensorboard/webapp/util/matcher.ts
  tensorboard/webapp/util/matcher_test.ts
Labels: cla: yes

#5349 runs table: fix color-picker position
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
  tensorboard/webapp/theme/_tb_theme.template.scss
Labels: cla: yes

#5360 refactor: move settings template in to html
  tensorboard/webapp/settings/_views/BUILD
  tensorboard/webapp/settings/_views/settings_dialog_component.ng.html
  tensorboard/webapp/settings/_views/settings_dialog_component.ts
Labels: cla: yes

#5358 time series: move settings pane opened state to store
  tensorboard/webapp/metrics/actions/index.ts
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/store/metrics_selectors.ts
  tensorboard/webapp/metrics/store/metrics_types.ts
  tensorboard/webapp/metrics/testing.ts
  tensorboard/webapp/metrics/views/main_view/main_view_container.ts
  tensorboard/webapp/metrics/views/main_view/main_view_test.ts
Labels: cla: yes

#5362 time series: remember settings pane open state
  tensorboard/webapp/metrics/metrics_module.ts
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/store/metrics_selectors_test.ts
  tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts
  tensorboard/webapp/persistent_settings/_data_source/types.ts
Labels: cla: yes

#5374 chore: Update protos to tensorflow/tensorflow@cfe7e5cfd41"
  tensorboard/compat/proto/BUILD
  tensorboard/compat/proto/config.proto
  tensorboard/compat/proto/coordination_service.proto
Labels: cla: yes

#5376 Add Alias selector which includes numbers
  tensorboard/webapp/app_routing/BUILD
  tensorboard/webapp/app_routing/store/BUILD
  tensorboard/webapp/app_routing/store/app_routing_selectors.ts
  tensorboard/webapp/app_routing/store_only_utils.ts
  tensorboard/webapp/experiments/types.ts
Labels: cla: yes

#5363 Update scalars_and_keras.ipynb
  docs/scalars_and_keras.ipynb
Labels: cla: yes
