Repository tensorflow/tensorboard, pull requests merged in 2021-02, with the labels that each got.

#4631 infra: use terser on tf_js_binary
  tensorboard/defs/BUILD
  tensorboard/defs/defs.bzl
  tensorboard/defs/terser_config.json
Labels: cla: yes

#4592 [npmi] Run ID to RunName
  tensorboard/webapp/plugins/npmi/data_source/npmi_data_source.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/BUILD
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_component.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_container.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/annotation_test.ts
  tensorboard/webapp/plugins/npmi/views/main/main_component.scss
Labels: cla: yes

#4635 Revert "introduce py_repl() rule for a convenient Bazel-aware python shell"
  tensorboard/BUILD
  tensorboard/defs/py_repl.bzl
Labels: cla: yes

#4626 line chart: adjust tooltip positions
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts
Labels: cla: yes

#4633 rust: add `rayon` dependency
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  third_party/rust/BUILD.bazel
  third_party/rust/crates.bzl
  third_party/rust/remote/BUILD.crossbeam-channel-0.5.0.bazel
  third_party/rust/remote/BUILD.crossbeam-deque-0.8.0.bazel
  third_party/rust/remote/BUILD.crossbeam-utils-0.8.1.bazel
  third_party/rust/remote/BUILD.rayon-1.5.0.bazel
  third_party/rust/remote/BUILD.rayon-core-1.9.0.bazel
Labels: cla: yes, core:rustboard, dependencies

#4634 rust: load runs in parallel
  tensorboard/data/server/BUILD
  tensorboard/data/server/bench.rs
  tensorboard/data/server/cli.rs
  tensorboard/data/server/logdir.rs
Labels: cla: yes, core:rustboard, theme:performance, type:feature

#4638 change RequestContext WSGI environ key to comply with spec
  tensorboard/context.py
Labels: cla: yes, core:backend, type:cleanup

#4632 line chart: fix line chart not updating bug
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
Labels: cla: yes

#4639 introduce py_repl() rule for a convenient Bazel-aware python shell
  tensorboard/BUILD
  tensorboard/defs/py_repl.bzl
Labels: cla: yes

#4641 types: set `defaultFlags` as required property
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_types.ts
  tensorboard/webapp/feature_flag/store/testing.ts
Labels: cla: yes

#4643 rust: add `reqwest` dependency
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  third_party/rust/BUILD.bazel
  third_party/rust/crates.bzl
  third_party/rust/remote/BUILD.bumpalo-3.6.0.bazel
  third_party/rust/remote/BUILD.cc-1.0.66.bazel
  third_party/rust/remote/BUILD.core-foundation-0.9.1.bazel
  third_party/rust/remote/BUILD.core-foundation-sys-0.8.2.bazel
  third_party/rust/remote/BUILD.encoding_rs-0.8.26.bazel
  third_party/rust/remote/BUILD.foreign-types-0.3.2.bazel
  third_party/rust/remote/BUILD.foreign-types-shared-0.1.1.bazel
  third_party/rust/remote/BUILD.form_urlencoded-1.0.0.bazel
  third_party/rust/remote/BUILD.futures-io-0.3.12.bazel
  third_party/rust/remote/BUILD.futures-task-0.3.8.bazel
  third_party/rust/remote/BUILD.futures-util-0.3.8.bazel
  third_party/rust/remote/BUILD.hyper-tls-0.5.0.bazel
  third_party/rust/remote/BUILD.idna-0.2.0.bazel
  third_party/rust/remote/BUILD.ipnet-2.3.0.bazel
  third_party/rust/remote/BUILD.js-sys-0.3.47.bazel
  third_party/rust/remote/BUILD.matches-0.1.8.bazel
  third_party/rust/remote/BUILD.mime-0.3.16.bazel
  third_party/rust/remote/BUILD.native-tls-0.2.7.bazel
  third_party/rust/remote/BUILD.once_cell-1.5.2.bazel
  third_party/rust/remote/BUILD.openssl-0.10.32.bazel
  third_party/rust/remote/BUILD.openssl-probe-0.1.2.bazel
  third_party/rust/remote/BUILD.openssl-sys-0.9.60.bazel
  third_party/rust/remote/BUILD.pkg-config-0.3.19.bazel
  third_party/rust/remote/BUILD.reqwest-0.11.0.bazel
  third_party/rust/remote/BUILD.schannel-0.1.19.bazel
  third_party/rust/remote/BUILD.security-framework-2.0.0.bazel
  third_party/rust/remote/BUILD.security-framework-sys-2.0.0.bazel
  third_party/rust/remote/BUILD.serde_urlencoded-0.7.0.bazel
  third_party/rust/remote/BUILD.tinyvec-1.1.1.bazel
  third_party/rust/remote/BUILD.tinyvec_macros-0.1.0.bazel
  third_party/rust/remote/BUILD.tokio-native-tls-0.3.0.bazel
  third_party/rust/remote/BUILD.unicode-bidi-0.3.4.bazel
  third_party/rust/remote/BUILD.unicode-normalization-0.1.16.bazel
  third_party/rust/remote/BUILD.url-2.2.0.bazel
  third_party/rust/remote/BUILD.vcpkg-0.2.11.bazel
  third_party/rust/remote/BUILD.wasm-bindgen-0.2.70.bazel
  third_party/rust/remote/BUILD.wasm-bindgen-backend-0.2.70.bazel
  third_party/rust/remote/BUILD.wasm-bindgen-futures-0.4.20.bazel
  third_party/rust/remote/BUILD.wasm-bindgen-macro-0.2.70.bazel
  third_party/rust/remote/BUILD.wasm-bindgen-macro-support-0.2.70.bazel
  third_party/rust/remote/BUILD.wasm-bindgen-shared-0.2.70.bazel
  third_party/rust/remote/BUILD.web-sys-0.3.47.bazel
  third_party/rust/remote/BUILD.winapi-0.3.9.bazel
  third_party/rust/remote/BUILD.winreg-0.7.0.bazel
Labels: cla: yes, core:rustboard, dependencies

#4636 rust: extract `Logdir` trait for other filesystems
  tensorboard/data/server/BUILD
  tensorboard/data/server/bench.rs
  tensorboard/data/server/cli.rs
  tensorboard/data/server/disk_logdir.rs
  tensorboard/data/server/lib.rs
  tensorboard/data/server/logdir.rs
  tensorboard/data/server/run.rs
Labels: cla: yes, core:rustboard

#4645 rust: add GCS listing and reading
  tensorboard/data/server/BUILD
  tensorboard/data/server/Cargo.toml
  tensorboard/data/server/cli.rs
  tensorboard/data/server/gcs.rs
  tensorboard/data/server/gcs/client.rs
  tensorboard/data/server/gcs/gsutil.rs
  tensorboard/data/server/lib.rs
Labels: cla: yes, core:rustboard, type:feature

#4648 types: make `features` omittable by typing
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_types.ts
  tensorboard/webapp/feature_flag/store/testing.ts
Labels: cla: yes

#4650 Revert "types: make `features` omittable by typing"
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_types.ts
  tensorboard/webapp/feature_flag/store/testing.ts
Labels: cla: yes

#4637 Instrument graph code with debug events
  tensorboard/components/tb_debug/BUILD
  tensorboard/components/tb_debug/index.ts
  tensorboard/components/tb_debug/types.ts
  tensorboard/defs/defs.bzl
  tensorboard/plugins/graph/BUILD
  tensorboard/plugins/graph/tf_graph/BUILD
  tensorboard/plugins/graph/tf_graph/tf-graph-scene.ts
  tensorboard/plugins/graph/tf_graph/tf-graph.ts
  tensorboard/plugins/graph/tf_graph_common/BUILD
  tensorboard/plugins/graph/tf_graph_common/common_test.ts
  tensorboard/plugins/graph/tf_graph_common/graph.ts
  tensorboard/plugins/graph/tf_graph_common/hierarchy.ts
  tensorboard/plugins/graph/tf_graph_common/loader.ts
  tensorboard/plugins/graph/tf_graph_common/parser.ts
  tensorboard/plugins/graph/tf_graph_common/util.ts
  tensorboard/webapp/testing/require_js_karma_config.js
Labels: cla: yes

#4651 Disable terser on polymer bundle in dev assets mode
  tensorboard/components/BUILD
  tensorboard/defs/defs.bzl
  tensorboard/webapp/dev_assets/BUILD
Labels: cla: yes

#4655 Revert "Disable terser on polymer bundle in dev assets mode (#4651)"
  tensorboard/components/BUILD
  tensorboard/defs/defs.bzl
  tensorboard/webapp/dev_assets/BUILD
Labels: cla: yes

#4652 cleanup: remove unused imports in graph code
  tensorboard/plugins/graph/tf_graph/tf-graph-scene.ts
  tensorboard/plugins/graph/tf_graph_common/render.ts
  tensorboard/plugins/graph/tf_graph_common/scene.ts
  tensorboard/plugins/graph/tf_graph_loader/tf-graph-dashboard-loader.ts
  tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.ts
Labels: cla: yes

#4653 chore: stricter types for JSON.parse
  tensorboard/components/tensor_widget/slicing-control.ts
  tensorboard/components/tensor_widget/tensor-widget-impl.ts
  tensorboard/defs/strict_type_check.d.ts
  tensorboard/plugins/projector/vz_projector/data-provider-server.ts
  tensorboard/plugins/projector/vz_projector/vz-projector-bookmark-panel.ts
  tensorboard/plugins/projector/vz_projector/vz-projector-dashboard.ts
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-card.ts
Labels: cla: yes

#4654 Reland "Disable terser on polymer bundle in dev assets mode (#4651)"
  tensorboard/components/BUILD
  tensorboard/defs/defs.bzl
  tensorboard/webapp/dev_assets/BUILD
  tensorboard/webapp/index_polymer3.uninlined.html
Labels: cla: yes

#4616 Support http server port reuse
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/program.py
  tensorboard/program_test.py
Labels: cla: yes

#4658 line chart: add trapezoid renderer
  tensorboard/webapp/widgets/line_chart_v2/lib/paint_brush.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_types.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/svg_renderer.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
Labels: cla: yes

#4657 graph: instrument debug events for user actions
  tensorboard/components/tb_debug/types.ts
  tensorboard/plugins/graph/tf_graph/tf-graph.ts
  tensorboard/plugins/graph/tf_graph_common/loader.ts
  tensorboard/plugins/graph/tf_graph_common/util.ts
  tensorboard/plugins/graph/tf_graph_controls/BUILD
  tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts
  tensorboard/plugins/graph/tf_graph_node_search/BUILD
  tensorboard/plugins/graph/tf_graph_node_search/tf-graph-node-search.ts
Labels: cla: yes

#4663 line chart: scale aware scroll to zoom
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_utils.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_utils_test.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts
Labels: cla: yes

#4664 type: allow complete omission of `features`
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_types.ts
  tensorboard/webapp/feature_flag/store/testing.ts
Labels: cla: yes

#4668 Expand palette definitions to include all weights.
  tensorboard/webapp/theme/_tb_palette.scss
Labels: cla: yes

#4669 docs: require scheme for TBdev gRPC API endpoint
  tensorboard/uploader/proto/server_info.proto
Labels: cla: yes, core:uploader, tbdev, type:docs

#4659 debugger_v2: start multiplexer lazily
  docs/debugger_v2.md
  tensorboard/plugins/debugger_v2/debugger_v2_plugin.py
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes, plugin:debugger, theme:performance, type:bug

#4646 rust: add GCS logdir support
  tensorboard/data/server/BUILD
  tensorboard/data/server/bench.rs
  tensorboard/data/server/cli.rs
  tensorboard/data/server/cli/dynamic_logdir.rs
  tensorboard/data/server/gcs.rs
  tensorboard/data/server/gcs/client.rs
  tensorboard/data/server/gcs/logdir.rs
Labels: cla: yes, core:rustboard, type:feature

#4647 rust: add refresh token authentication
  tensorboard/data/server/BUILD
  tensorboard/data/server/cli/dynamic_logdir.rs
  tensorboard/data/server/gcs.rs
  tensorboard/data/server/gcs/auth.rs
  tensorboard/data/server/gcs/client.rs
  tensorboard/data/server/gcs/gsutil.rs
Labels: cla: yes, core:rustboard, type:feature

#4672 tensorboard-data-server 0.3.0
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  tensorboard/data/server/lib.rs
  tensorboard/data/server/pip_package/tensorboard_data_server/__init__.py
Labels: cla: yes, core:rustboard

#4671 rust: add `bytes` dependency
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  tensorboard/data/server/cargo/BUILD.bazel
Labels: cla: yes, core:rustboard, dependencies

#4675 rust: remove copy in GCS reading
  tensorboard/data/server/BUILD
  tensorboard/data/server/gcs/client.rs
Labels: cla: yes, core:rustboard, theme:performance

#4676 pip: depend on `tensorboard-data-server`
  tensorboard/data/server_ingester.py
  tensorboard/pip_package/requirements.txt
Labels: cla: yes, core:rustboard, type:build/install

#4682 markdown: add testing deps
  tensorboard/webapp/widgets/markdown_renderer/BUILD
Labels: cla: yes

#4678 rust: use `TaggedRunMetadataValue` consistently
  tensorboard/data/server/run.rs
Labels: cla: yes, core:rustboard, type:cleanup

#4681 types: remove `features` from FeatureFlag
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
  tensorboard/webapp/feature_flag/store/feature_flag_types.ts
Labels: cla: yes

#4684 rust: fix disk logdir reading for relative paths
  tensorboard/data/server/disk_logdir.rs
Labels: cla: yes, core:rustboard, type:bug

#4677 rust: use `bytes::Bytes` for proto fields
  tensorboard/data/server/BUILD
  tensorboard/data/server/commit.rs
  tensorboard/data/server/data_compat.rs
  tensorboard/data/server/gen_protos_tool.rs
  tensorboard/data/server/run.rs
  tensorboard/data/server/server.rs
  tensorboard/data/server/tensorboard.data.pb.rs
  tensorboard/data/server/tensorboard.pb.rs
  tensorboard/data/server/writer.rs
Labels: cla: yes, core:rustboard, theme:performance

#4679 rust: upgrade to Rust 1.50.0
  .github/workflows/ci.yml
  third_party/rust.bzl
Labels: cla: yes, core:rustboard, type:build/install

#4686 timeseries: reflect smoothing setting in URL
  tensorboard/webapp/metrics/BUILD
  tensorboard/webapp/metrics/actions/BUILD
  tensorboard/webapp/metrics/actions/index.ts
  tensorboard/webapp/metrics/internal_types.ts
  tensorboard/webapp/metrics/store/BUILD
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/store/metrics_selectors.ts
  tensorboard/webapp/metrics/store/metrics_selectors_test.ts
  tensorboard/webapp/metrics/store/metrics_store_internal_utils.ts
  tensorboard/webapp/metrics/store/metrics_types.ts
  tensorboard/webapp/metrics/types.ts
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
  tensorboard/webapp/routes/BUILD
  tensorboard/webapp/routes/core_deeplink_provider.ts
  tensorboard/webapp/routes/core_deeplink_provider_test.ts
  tensorboard/webapp/routes/core_deeplink_provider_types.ts
Labels: cla: yes

#4680 Remove unnecessary "language in" setting
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
Labels: cla: yes

#4690 projector: fix the KNN algorithm
  tensorboard/plugins/projector/vz_projector/knn.ts
Labels: cla: yes

#4691 http_client: add XSRF header to non-GET requests
  tensorboard/webapp/webapp_data_source/BUILD
  tensorboard/webapp/webapp_data_source/tb_http_client.ts
  tensorboard/webapp/webapp_data_source/tb_http_client_test.ts
Labels: cla: yes, core:frontend

#4582 summary: initial code for TensorBoard-native summary writer
  tensorboard/BUILD
  tensorboard/summary/BUILD
  tensorboard/summary/__init__.py
  tensorboard/summary/_output.py
  tensorboard/summary/_output_test.py
  tensorboard/summary/_test_util.py
  tensorboard/summary/_writer.py
  tensorboard/summary/_writer_test.py
  tensorboard/summary/summary_test.py
Labels: cla: yes, core:summaries

#4694 ensure tensorboard.summary.writer has no TF build dependency
  tensorboard/summary/writer/BUILD
Labels: cla: yes, core:summaries

#4689 Plumb --samples_per_plugin to Rust data server
  tensorboard/data/server/bench.rs
  tensorboard/data/server/cli.rs
  tensorboard/data/server/logdir.rs
  tensorboard/data/server/run.rs
  tensorboard/data/server/types.rs
  tensorboard/data/server_ingester.py
  tensorboard/program.py
Labels: cla: yes, core:rustboard

#4696 timeseries: add option for monotonic x
  tensorboard/webapp/metrics/actions/index.ts
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/store/metrics_selectors.ts
  tensorboard/webapp/metrics/store/metrics_selectors_test.ts
  tensorboard/webapp/metrics/store/metrics_types.ts
  tensorboard/webapp/metrics/testing.ts
  tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
  tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
Labels: cla: yes

#4698 Fix uploader counts of scalars and tensors
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes

#4695 line chart: enable GPU line chart by default
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
Labels: cla: yes

#4697 graph: split FETCH_PBTXT_BYTES debug event into finer sources
  tensorboard/components/tb_debug/types.ts
  tensorboard/plugins/graph/tf_graph_common/parser.ts
Labels: cla: yes

#4706 Update README.md
  README.md
  docs/r1/overview.md
  tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts
Labels: cla: yes, type:docs

#4701 timeseries: refactor scalar container data fetch
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
Labels: cla: yes

#4709 rust: add rustfmt.toml to set `edition = "2018"`
  tensorboard/data/server/Cargo.toml
  tensorboard/data/server/rustfmt.toml
Labels: cla: yes, core:rustboard

#4708 alerts: plumb followupAction into store
  tensorboard/webapp/alert/store/BUILD
  tensorboard/webapp/alert/store/alert_reducers.ts
  tensorboard/webapp/alert/store/alert_reducers_test.ts
Labels: cla: yes

#4707 icon: add notification icon
  tensorboard/webapp/BUILD
  third_party/js.bzl
Labels: cla: yes

#4712 rust: fix a few Clippy warnings
  tensorboard/data/server/data_compat.rs
  tensorboard/data/server/run.rs
Labels: cla: yes, core:rustboard, type:cleanup

#4710 rust: add tensors to Commit and CommitBuilder
  tensorboard/data/server/commit.rs
Labels: cla: yes, core:rustboard

#4704 graph: create initial README with user instructions
  tensorboard/plugins/graph/README.md
Labels: cla: yes

#4705 graph: update README with technical details
  tensorboard/plugins/graph/README.md
  tensorboard/plugins/graph/tf_graph_common/hierarchy.ts
Labels: cla: yes
