Repository tensorflow/tensorboard, pull requests merged in 2021-04, with the labels that each got.

#4828 plugin_util: factor out summary metadata version checker
  tensorboard/BUILD
  tensorboard/plugin_util.py
  tensorboard/plugins/audio/BUILD
  tensorboard/plugins/audio/audio_plugin.py
  tensorboard/plugins/audio/metadata.py
  tensorboard/plugins/histogram/BUILD
  tensorboard/plugins/histogram/histograms_plugin.py
  tensorboard/plugins/histogram/metadata.py
  tensorboard/plugins/image/BUILD
  tensorboard/plugins/image/images_plugin.py
  tensorboard/plugins/image/metadata.py
  tensorboard/plugins/mesh/mesh_plugin.py
  tensorboard/plugins/mesh/metadata.py
  tensorboard/plugins/mesh/metadata_test.py
  tensorboard/plugins/metrics/metrics_plugin.py
  tensorboard/plugins/npmi/BUILD
  tensorboard/plugins/npmi/metadata.py
  tensorboard/plugins/npmi/npmi_plugin.py
  tensorboard/plugins/pr_curve/BUILD
  tensorboard/plugins/pr_curve/pr_curves_plugin.py
  tensorboard/plugins/scalar/BUILD
  tensorboard/plugins/scalar/metadata.py
  tensorboard/plugins/scalar/scalars_plugin.py
  tensorboard/plugins/text/metadata.py
  tensorboard/plugins/text/text_plugin.py
  tensorboard/plugins/text_v2/text_v2_plugin.py
Labels: cla: yes

#4834 rust: hold commit in `Arc` instead of leaking
  tensorboard/data/server/cli.rs
  tensorboard/data/server/server.rs
Labels: cla: yes, core:rustboard, type:cleanup

#4833 infra: upgrade FE dependencies
  tensorboard/plugins/graph/tf_graph_common/common_test.ts
  tensorboard/webapp/core/effects/core_effects_test.ts
  tensorboard/webapp/runs/data_source/testing.ts
  tensorboard/webapp/widgets/source_code/load_monaco_shim_test.ts
  yarn.lock
Labels: cla: yes

#4838 example: raw_scalars: use DataProvider
  tensorboard/examples/plugins/example_raw_scalars/tensorboard_plugin_example_raw_scalars/plugin.py
Labels: cla: yes

#4836 pip: relax `pandas` dep to 1.x
  tensorboard/pip_package/requirements_dev.txt
Labels: cla: yes, type:build/install

#4837 rust: downgrade logdir traversal errors
  tensorboard/data/server/disk_logdir.rs
Labels: cla: yes, core:rustboard, theme:usability

#4846 plugin api: implement reload listener
  tensorboard/components/experimental/plugin_lib/core.ts
  tensorboard/components/experimental/plugin_util/BUILD
  tensorboard/components/experimental/plugin_util/core-host-impl.ts
  tensorboard/components/experimental/plugin_util/message_types.ts
  tensorboard/components/experimental/plugin_util/plugin_api_host_test.ts
  tensorboard/webapp/BUILD
  tensorboard/webapp/core/store/core_selectors.ts
  tensorboard/webapp/selectors.ts
Labels: cla: yes

#4853 infra: update protos to TF at 2.5.0-rc0
  tensorboard/compat/proto/config.proto
  tensorboard/compat/proto/event.proto
  tensorboard/compat/proto/meta_graph.proto
  tensorboard/compat/proto/rewriter_config.proto
  tensorboard/compat/proto/saved_object_graph.proto
  tensorboard/compat/proto/struct.proto
  tensorboard/data/server/tensorboard.pb.rs
Labels: cla: yes

#4851 data: check liveness before blessing data server
  tensorboard/data/BUILD
  tensorboard/data/server_ingester.py
Labels: cla: yes, core:rustboard, theme:usability

#4848 Remove unneeded `tf.io.gfile.file_exists` checks
  tensorboard/compat/tensorflow_stub/io/gfile.py
  tensorboard/compat/tensorflow_stub/io/gfile_s3_test.py
  tensorboard/compat/tensorflow_stub/io/gfile_test.py
  tensorboard/summary/writer/event_file_writer.py
Labels: cla: yes, type:cleanup

#4859 sync: add missing ngrx store dep
  tensorboard/components/experimental/plugin_util/BUILD
Labels: cla: yes

#4856 time series: move the fit button to header
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
Labels: cla: yes

#4861 notification center: integrate markdown renderer
  tensorboard/webapp/notification_center/_redux/notification_notes.ts
  tensorboard/webapp/notification_center/_views/BUILD
  tensorboard/webapp/notification_center/_views/notification_center_component.ng.html
  tensorboard/webapp/notification_center/_views/notification_center_component.scss
  tensorboard/webapp/notification_center/_views/notification_center_test.ts
  tensorboard/webapp/notification_center/_views/views_module.ts
Labels: cla: yes

#4864 build: patch TF python_configure to fix genrule toolchain issues
  WORKSPACE
  third_party/tensorflow.patch
Labels: cla: yes, type:build/install

#4857 runs: prevent sort when filter button is clicked
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Labels: cla: yes

#4825 Add `async_call_with_retries` method to grpc_util.
  tensorboard/util/grpc_util.py
  tensorboard/util/grpc_util_test.py
Labels: cla: yes

#4868 sync: add missing dep on angular/core
  tensorboard/webapp/notification_center/_views/BUILD
Labels: cla: yes

#4867 graph: fix bug in parsing of _output_shapes attr
  tensorboard/plugins/graph/tf_graph_common/common_test.ts
  tensorboard/plugins/graph/tf_graph_common/graph.ts
Labels: cla: yes, plugin:graph

#4865 plugin api: cut tie to lodash and polymer
  tensorboard/components/BUILD
  tensorboard/components/experimental/plugin_util/BUILD
  tensorboard/components/experimental/plugin_util/core-host-impl.ts
  tensorboard/components/experimental/plugin_util/plugin_api_host_test.ts
  tensorboard/components/tf_globals/BUILD
  tensorboard/components/tf_storage/BUILD
  tensorboard/components/tf_storage/storage.ts
  tensorboard/components/tf_storage/storage_utils.ts
Labels: cla: yes

#4873 Test new IFRAME plugin behavior for PluginsContainer
  tensorboard/webapp/plugins/plugins_container_test.ts
Labels: cla: yes

#4874 infra: update JS dependencies.
  WORKSPACE
  package.json
  tensorboard/components/tf_backend/requestManager.ts
  tensorboard/components/tf_storage/storage.ts
  tensorboard/defs/defs.bzl
  tensorboard/plugins/hparams/tf_hparams_session_group_details/tf-hparams-session-group-details.ts
  tensorboard/plugins/mesh/tf_mesh_dashboard/mesh-viewer.ts
  yarn.lock
Labels: cla: yes

#4877 sync: fix the strictdep on @ngrx/store
  tensorboard/webapp/notification_center/_redux/BUILD
Labels: cla: yes

#4878 core: re-enable CorePluginTest and consolidate test cases
  tensorboard/plugins/core/core_plugin_test.py
Labels: cla: yes, core:backend

#4875 Factor public uploader errors into their own module.
  tensorboard/uploader/BUILD
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_errors.py
  tensorboard/uploader/uploader_subcommand.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes

#4870 rust: add gRPC reflection support
  tensorboard/data/server/.gitattributes
  tensorboard/data/server/BUILD
  tensorboard/data/server/DEVELOPMENT.md
  tensorboard/data/server/cli.rs
  tensorboard/data/server/descriptor.bin
  tensorboard/data/server/gen_protos_tool.rs
  tensorboard/data/server/lib.rs
  tensorboard/data/server/update_protos.py
  tensorboard/tools/license_test.sh
Labels: cla: yes, core:rustboard

#4876 what's new: data-source test
  tensorboard/webapp/notification_center/BUILD
  tensorboard/webapp/notification_center/_data_source/BUILD
  tensorboard/webapp/notification_center/_data_source/notification_center_data_source_test.ts
Labels: cla: yes

#4863 Adding remote_ip and x_forwarded_for to request context.
  tensorboard/context.py
  tensorboard/context_test.py
Labels: cla: yes

#4843 fix(doc) : fix API demo of debugger V2
  docs/debugger_v2.md
Labels: cla: yes

#4883 Revert "Factor public uploader errors into their own module. (#4875)"
  tensorboard/uploader/BUILD
  tensorboard/uploader/uploader.py
  tensorboard/uploader/uploader_errors.py
  tensorboard/uploader/uploader_subcommand.py
  tensorboard/uploader/uploader_test.py
Labels: cla: yes

#4886 visibility: make `tensorboard.context` public
  tensorboard/BUILD
Labels: cla: yes, type:build/install

#4892 Fix a bug in context.replace().
  tensorboard/context.py
  tensorboard/context_test.py
Labels: cla: yes

#4890 timeseries: fix fit-to-domain state issue
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
Labels: cla: yes

#4891 types: improve TbHttpClient types
  tensorboard/webapp/webapp_data_source/tb_http_client.ts
Labels: cla: yes

#4894 infra: remove the closure/goog/deps.js dep
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/BUILD
Labels: cla: yes

#4893 timeseries: remove Polymer based line chart
  tensorboard/webapp/metrics/views/card_renderer/BUILD
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_module.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
Labels: cla: yes

#4897 sync: fix the unknown input `runColorScale` issue
  tensorboard/webapp/metrics/views/card_renderer/card_view_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/card_view_test.ts
Labels: cla: yes

#4898 cleanup: remove unused line-chart widget
  tensorboard/webapp/BUILD
  tensorboard/webapp/metrics/BUILD
  tensorboard/webapp/metrics/internal_types.ts
  tensorboard/webapp/widgets/line_chart/BUILD
  tensorboard/webapp/widgets/line_chart/line_chart_component.ts
  tensorboard/webapp/widgets/line_chart/line_chart_module.ts
  tensorboard/webapp/widgets/line_chart/line_chart_test.ts
  tensorboard/webapp/widgets/line_chart/line_chart_types.ts
  tensorboard/webapp/widgets/line_chart/polymer_interop_types.ts
Labels: cla: yes

#4885 hparams: plugin new hparams to the runs table
  tensorboard/webapp/hparams/BUILD
  tensorboard/webapp/hparams/testing.ts
  tensorboard/webapp/runs/views/runs_selector/runs_selector_component.ts
  tensorboard/webapp/runs/views/runs_selector/runs_selector_test.ts
  tensorboard/webapp/runs/views/runs_table/BUILD
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Labels: cla: yes

#4849 core: fix the header pagination
  tensorboard/webapp/header/plugin_selector_component.scss
Labels: cla: yes

#4905 Making hparams_utils publicly visible
  tensorboard/plugins/hparams/BUILD
Labels: cla: yes

#4900 timeseries: correctly fix fit-to-domain
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/widgets/line_chart_v2/BUILD
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
Labels: cla: yes

#4904 hparams: cleanup hparams from runs feature
  tensorboard/webapp/runs/actions/runs_actions.ts
  tensorboard/webapp/runs/store/BUILD
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
  tensorboard/webapp/runs/store/runs_selectors.ts
  tensorboard/webapp/runs/store/runs_selectors_test.ts
  tensorboard/webapp/runs/store/runs_selectors_utils.ts
  tensorboard/webapp/runs/store/runs_selectors_utils_test.ts
  tensorboard/webapp/runs/store/runs_types.ts
  tensorboard/webapp/runs/store/testing.ts
  tensorboard/webapp/runs/types.ts
Labels: cla: yes

#4907 core: fix the plugin selector color
  tensorboard/webapp/header/plugin_selector_component.scss
Labels: cla: yes

#4899 what's new: utilize redirect for BE to read note json file
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
Labels: cla: yes

#4906 infra: remove JSCompiler from Vulcanize
  tensorboard/defs/internal/html.bzl
  tensorboard/defs/web.bzl
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/BUILD
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/Vulcanize.java
  tensorboard/plugins/graph/tf_graph_app/BUILD
  tensorboard/plugins/projector/tf_projector_plugin/BUILD
  tensorboard/plugins/projector/vz_projector/BUILD
  tensorboard/webapp/BUILD
Labels: cla: yes

#4908 routing: improve compare navigation
  tensorboard/webapp/app_routing/effects/app_routing_effects.ts
  tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
  tensorboard/webapp/app_routing/internal_utils.ts
  tensorboard/webapp/app_routing/internal_utils_test.ts
  tensorboard/webapp/app_routing/programmatical_navigation_module_test.ts
  tensorboard/webapp/app_routing/programmatical_navigation_types.ts
Labels: cla: yes

#4910 infra: remove unused vulcanize.bzl
  tensorboard/defs/vulcanize.bzl
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/BUILD
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/externs.js
Labels: cla: yes

#4903 what's new: move update last read timestamp from reducer to data source
  tensorboard/webapp/notification_center/_data_source/BUILD
  tensorboard/webapp/notification_center/_data_source/backend_types.ts
  tensorboard/webapp/notification_center/_data_source/notification_center_data_source.ts
  tensorboard/webapp/notification_center/_data_source/notification_center_data_source_test.ts
  tensorboard/webapp/notification_center/_data_source/testing.ts
  tensorboard/webapp/notification_center/_redux/notification_center_actions.ts
  tensorboard/webapp/notification_center/_redux/notification_center_effects.ts
  tensorboard/webapp/notification_center/_redux/notification_center_effects_test.ts
  tensorboard/webapp/notification_center/_redux/notification_center_reducers.ts
  tensorboard/webapp/notification_center/_redux/notification_center_types.ts
Labels: cla: yes

#4888 timeseries: preserve select all on page when new runs arrive
  tensorboard/webapp/alert/actions/BUILD
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
  tensorboard/webapp/runs/store/runs_types.ts
  tensorboard/webapp/runs/views/runs_table/BUILD
  tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_module.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Labels: cla: yes

#4912 Ensure name and description are set in the exporter mask
  tensorboard/uploader/uploader_subcommand.py
  tensorboard/uploader/uploader_subcommand_test.py
Labels: cla: yes

#4916 cleanup(line-chart): use un-deprecated API
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
Labels: cla: yes

#4909 Fix `--one_shot` for remote file system.
  tensorboard/uploader/BUILD
  tensorboard/uploader/uploader_subcommand.py
Labels: cla: yes

#4919 type: better type Polymer-Angular interops
  tensorboard/webapp/BUILD
  tensorboard/webapp/core/effects/BUILD
  tensorboard/webapp/core/effects/core_effects.ts
  tensorboard/webapp/deeplink/BUILD
  tensorboard/webapp/deeplink/hash.ts
  tensorboard/webapp/tb_polymer_interop_types.ts
  tensorboard/webapp/webapp_data_source/BUILD
  tensorboard/webapp/webapp_data_source/tb_server_data_source.ts
Labels: cla: yes

#4922 hparams: prevent experimentIds mutation
  tensorboard/webapp/hparams/_redux/utils.ts
  tensorboard/webapp/hparams/_redux/utils_test.ts
Labels: cla: yes

#4924 types: further improve Polymer interop types.
  tensorboard/webapp/settings/BUILD
  tensorboard/webapp/settings/polymer_interop_container.ts
  tensorboard/webapp/tb_polymer_interop_types.ts
  tensorboard/webapp/widgets/histogram/BUILD
  tensorboard/webapp/widgets/histogram/histogram_component.ts
  tensorboard/webapp/widgets/histogram/histogram_test.ts
  tensorboard/webapp/widgets/histogram/histogram_types.ts
Labels: cla: yes

#4917 deflag: remove enableFastChart feature flag.
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
  tensorboard/webapp/feature_flag/store/testing.ts
  tensorboard/webapp/feature_flag/testing.ts
  tensorboard/webapp/feature_flag/types.ts
  tensorboard/webapp/routes/dashboard_deeplink_provider.ts
  tensorboard/webapp/routes/dashboard_deeplink_provider_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
Labels: cla: yes
