Repository tensorflow/tensorboard, pull requests merged in 2021-12, with the labels that each got.

#5441 [time-namespaced state] Remove buildNavigatedActionFull.
  tensorboard/webapp/app_routing/testing.ts
Labels: cla: yes

#5445 [time-namespaced state] Rename enableTimespace flag to enableTimeNamespacedState.
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
Labels: cla: yes

#5442 Time Series: tooltip sort by alphabetical order
  tensorboard/webapp/metrics/effects/metrics_effects_test.ts
  tensorboard/webapp/metrics/internal_types.ts
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/store/metrics_types.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
Labels: cla: yes

#5443 histogram: clean up v2 code
  tensorboard/plugins/histogram/summary.py
  tensorboard/plugins/histogram/summary_test.py
  tensorboard/plugins/histogram/summary_v2.py
Labels: plugin:histogram, core:summaries, cla: yes

#5444 [time-namespaced state] Move navigationOptions out of Route.
  tensorboard/webapp/app_routing/effects/app_routing_effects.ts
  tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
  tensorboard/webapp/app_routing/store/app_routing_reducers_test.ts
  tensorboard/webapp/app_routing/store/app_routing_selectors_test.ts
  tensorboard/webapp/app_routing/testing.ts
  tensorboard/webapp/app_routing/types.ts
Labels: cla: yes

#5450 docs: fix typo
  docs/tensorboard_projector_plugin.ipynb
Labels: cla: yes

#5456 histogram: define a separate large sized py_test rule for `test_with_large_counts`
  tensorboard/plugins/histogram/BUILD
  tensorboard/plugins/histogram/summary_test.py
Labels: plugin:histogram, core:summaries

#5446 [time-namespaced state] Remove Navigation support for getFullPathFromRouteOrNav().
  tensorboard/webapp/app_routing/effects/app_routing_effects.ts
  tensorboard/webapp/app_routing/location.ts
  tensorboard/webapp/app_routing/location_test.ts
  tensorboard/webapp/app_routing/views/router_link_directive_container.ts
Labels: cla: yes
