Repository tensorflow/tensorboard, pull requests merged in 2021-06, with the labels that each got.

#5026 infra: add customization component
  tensorboard/webapp/BUILD
  tensorboard/webapp/customization/BUILD
  tensorboard/webapp/customization/customizable_component.ts
  tensorboard/webapp/customization/customization_module.ts
  tensorboard/webapp/customization/customization_test.ts
Labels: cla: yes

#5029 Fix BUILD for @angular/core/testing import.
  tensorboard/webapp/customization/BUILD
Labels: cla: yes, type:build/install

#5030 metrics: separate default settings from override
  tensorboard/webapp/metrics/store/metrics_initial_state_provider.ts
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/store/metrics_selectors.ts
  tensorboard/webapp/metrics/store/metrics_types.ts
  tensorboard/webapp/metrics/testing.ts
  tensorboard/webapp/metrics/types.ts
  tensorboard/webapp/routes/dashboard_deeplink_provider.ts
  tensorboard/webapp/routes/dashboard_deeplink_provider_test.ts
Labels: cla: yes

#5022 runs: persist colorBy in URL
  tensorboard/webapp/routes/BUILD
  tensorboard/webapp/routes/dashboard_deeplink_provider.ts
  tensorboard/webapp/routes/dashboard_deeplink_provider_test.ts
  tensorboard/webapp/routes/dashboard_deeplink_provider_types.ts
  tensorboard/webapp/runs/store/BUILD
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
  tensorboard/webapp/runs/types.ts
Labels: cla: yes

#5035 styles: refactor how material comps are styled
  tensorboard/webapp/styles.scss
  tensorboard/webapp/theme/_tb_theme.template.scss
Labels: cla: yes

#5034 Add button to TensorBoard.dev from main page.
  docs/_index.yaml
Labels: cla: yes

#5012 projector: simplify demo using fake data
  tensorboard/plugins/projector/BUILD
  tensorboard/plugins/projector/projector_demo.py
Labels: cla: yes, plugin:projector, type:docs

#5037 dark mode: disable media query based feature
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
Labels: cla: yes

#5036 docs: Graph tutorial link to tb.dev
  docs/graphs.ipynb
Labels: cla: yes

#5038 dark mode: enable dark mode at PluginComponent
  tensorboard/components/tf_dashboard_common/dashboard-style.ts
  tensorboard/components/tf_dashboard_common/tensorboard-color.ts
  tensorboard/components/tf_dashboard_common/tf-option-selector.ts
  tensorboard/components/tf_paginated_view/tf-category-paginated-view.ts
  tensorboard/components/tf_runs_selector/tf-runs-selector.ts
  tensorboard/components/vz_line_chart2/vz-line-chart2.ts
  tensorboard/plugins/scalar/tf_scalar_dashboard/tf-smoothing-input.ts
  tensorboard/webapp/metrics/views/metrics_container.scss
  tensorboard/webapp/plugins/BUILD
  tensorboard/webapp/plugins/plugins_component.ng.html
  tensorboard/webapp/plugins/plugins_component.scss
  tensorboard/webapp/plugins/plugins_component.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_component.scss
  tensorboard/webapp/theme/_tb_theme.template.scss
Labels: cla: yes

#5039 refactor: move inline_images to tensorboard/defs/
  tensorboard/defs/BUILD
  tensorboard/defs/defs.bzl
  tensorboard/defs/inline_images.py
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/inactive/BUILD
Labels: cla: yes

#5041 sync: remove unreachable code
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
Labels: cla: yes

#5040 dark mode: fix hparams, graph, mesh, and profile
  tensorboard/components/tf_dashboard_common/tensorboard-color.ts
  tensorboard/components/tf_dashboard_common/tf-dashboard-layout.ts
  tensorboard/components/tf_paginated_view/tf-category-paginated-view.ts
  tensorboard/plugins/graph/tf_graph/tf-graph-scene.html.ts
  tensorboard/plugins/graph/tf_graph_common/tf-graph-icon.ts
  tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts
  tensorboard/plugins/graph/tf_graph_info/tf-graph-info.ts
  tensorboard/plugins/graph/tf_graph_info/tf-node-info.ts
  tensorboard/plugins/graph/tf_graph_info/tf-node-list-item.ts
  tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.ts
  tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-list-item.ts
  tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/tf-hparams-parallel-coords-plot.ts
  tensorboard/plugins/hparams/tf_hparams_scatter_plot_matrix_plot/tf-hparams-scatter-plot-matrix-plot.ts
  tensorboard/plugins/hparams/tf_hparams_table_view/tf-hparams-table-view.ts
  tensorboard/plugins/mesh/tf_mesh_dashboard/tf-mesh-dashboard.ts
  tensorboard/plugins/profile_redirect/tf_profile_redirect_dashboard/tf-profile-redirect-dashboard.ts
  tensorboard/webapp/theme/_tb_theme.template.scss
Labels: cla: yes

#5042 dark mode: improve visuals of time series plugin
  tensorboard/webapp/metrics/views/_common.scss
  tensorboard/webapp/metrics/views/card_renderer/card_view_container.scss
  tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.scss
  tensorboard/webapp/metrics/views/card_renderer/image_card_component.scss
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
  tensorboard/webapp/metrics/views/main_view/card_grid_component.scss
  tensorboard/webapp/metrics/views/main_view/card_groups_component.scss
  tensorboard/webapp/metrics/views/main_view/filter_input_component.scss
  tensorboard/webapp/metrics/views/main_view/main_view_component.scss
  tensorboard/webapp/metrics/views/main_view/pinned_view_component.scss
  tensorboard/webapp/metrics/views/metrics_container.scss
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss
  tensorboard/webapp/runs/views/runs_table/runs_table_component.scss
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.scss
  tensorboard/webapp/theme/_tb_theme.template.scss
  tensorboard/webapp/widgets/filter_input/filter_input_component.scss
Labels: cla: yes

#5025 color grouping: move regexfilter attribute from runUi to runData
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
  tensorboard/webapp/runs/store/runs_selectors.ts
  tensorboard/webapp/runs/store/runs_selectors_test.ts
  tensorboard/webapp/runs/store/runs_types.ts
  tensorboard/webapp/runs/store/testing.ts
Labels: cla: yes

#5043 dark mode: improve GPU line chart under dark mode
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/chart.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/chart_types.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/integration_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_types.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/svg_renderer.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/message_types.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart_bridge.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart_test.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.scss
Labels: cla: yes

#5046 dark mode: improve debugger under dark mode
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_component.scss
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/common/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/common/_lib.scss
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/execution_data_component.scss
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_component.scss
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph/graph_op_component.scss
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/graph_executions/graph_executions_component.scss
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_component.scss
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/stack_trace/stack_trace_component.scss
Labels: cla: yes

#5047 debugger: fix mutating object by ref in reducers
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/store/debugger_reducers_test.ts
Labels: cla: yes

#5049 dark mode: support dark mode in the source-code
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_component.ng.html
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_component.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_container.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/source_files/source_files_container_test.ts
  tensorboard/webapp/widgets/source_code/source_code_component.ts
  tensorboard/webapp/widgets/source_code/source_code_container.ts
  tensorboard/webapp/widgets/source_code/source_code_container_test.ts
  tensorboard/webapp/widgets/source_code/testing.ts
Labels: cla: yes

#5050 dark mode; allow dark theme to use different vars
  tensorboard/webapp/theme/_tb_theme.template.scss
  tensorboard/webapp/theme/_variable.scss
Labels: cla: yes

#5053 debugger: deflake debugger v2 test
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_container_test.ts
Labels: cla: yes

#5052 docs: add experiment list information in tensorboard.dev tutorial colab
  docs/images/tbdev_experiment_list.png
  docs/tbdev_getting_started.ipynb
Labels: cla: yes, tbdev, type:docs

#5054 source-code: bug fix where dark mode did not apply
  tensorboard/webapp/widgets/source_code/source_code_component.ts
  tensorboard/webapp/widgets/source_code/source_code_container_test.ts
  tensorboard/webapp/widgets/source_code/testing.ts
Labels: cla: yes

#5051 dark mode: fix link styling
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.scss
  tensorboard/webapp/theme/_tb_theme.template.scss
Labels: cla: yes

#5056 Revert "docs: add experiment list information in tensorboard.dev tutorial colab"
  docs/images/tbdev_experiment_list.png
  docs/tbdev_getting_started.ipynb
Labels: cla: yes

#5058 dark mode: specify app-bar color via `default`
  tensorboard/webapp/theme/_tb_theme.template.scss
Labels: cla: yes

#5059 Fix_value_clipping_code
  docs/debugger_v2.md
Labels: cla: yes

#5048 color grouping: separate regexString from GroupBy
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
  tensorboard/webapp/runs/store/runs_selectors.ts
  tensorboard/webapp/runs/store/runs_selectors_test.ts
  tensorboard/webapp/runs/store/runs_types.ts
  tensorboard/webapp/runs/store/testing.ts
  tensorboard/webapp/runs/store/utils.ts
  tensorboard/webapp/runs/store/utils_test.ts
Labels: cla: yes

#5014 docs: update histogram demo to TF2
  tensorboard/plugins/histogram/histograms_demo.py
Labels: cla: yes

#5062 color grouping: remove unused code
  tensorboard/webapp/runs/store/utils.ts
Labels: cla: yes

#5060 source code: fix dark mode support
  tensorboard/webapp/widgets/source_code/editor_options.ts
  tensorboard/webapp/widgets/source_code/source_code_component.ts
  tensorboard/webapp/widgets/source_code/source_code_container_test.ts
  tensorboard/webapp/widgets/source_code/source_code_diff_component.ts
  tensorboard/webapp/widgets/source_code/source_code_diff_container.ts
  tensorboard/webapp/widgets/source_code/source_code_diff_container_test.ts
  tensorboard/webapp/widgets/source_code/testing.ts
Labels: cla: yes

#5061 theme: allow customizable `app-bar` theme var
  tensorboard/webapp/theme/_tb_theme.template.scss
Labels: cla: yes

#5055 chore: prevent test log spam
  tensorboard/webapp/widgets/source_code/load_monaco_shim_test.ts
Labels: cla: yes

#5067 dark mode: fix UI in Firefox
  tensorboard/components/polymer/BUILD
  tensorboard/components/polymer/dark_mode_mixin.ts
  tensorboard/components/tf_dashboard_common/BUILD
  tensorboard/components/tf_dashboard_common/tensorboard-color.ts
  tensorboard/components/tf_dashboard_common/tf-dashboard-layout.ts
  tensorboard/plugins/graph/tf_graph/BUILD
  tensorboard/plugins/graph/tf_graph/tf-graph-scene.html.ts
  tensorboard/plugins/graph/tf_graph/tf-graph-scene.ts
  tensorboard/plugins/graph/tf_graph_common/BUILD
  tensorboard/plugins/graph/tf_graph_common/tf-graph-icon.ts
  tensorboard/plugins/graph/tf_graph_controls/BUILD
  tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts
  tensorboard/plugins/graph/tf_graph_info/BUILD
  tensorboard/plugins/graph/tf_graph_info/tf-node-list-item.ts
  tensorboard/plugins/graph/tf_graph_op_compat_card/BUILD
  tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.ts
  tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/BUILD
  tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/tf-hparams-parallel-coords-plot.ts
  tensorboard/plugins/hparams/tf_hparams_table_view/BUILD
  tensorboard/plugins/hparams/tf_hparams_table_view/tf-hparams-table-view.ts
  tensorboard/webapp/core/views/dark_mode_supporter_container.ts
Labels: cla: yes

#5063 projector: fix broken KNN
  tensorboard/plugins/projector/vz_projector/BUILD
  tensorboard/plugins/projector/vz_projector/data.ts
  tensorboard/plugins/projector/vz_projector/knn.ts
  tensorboard/plugins/projector/vz_projector/knn_test.ts
Labels: cla: yes

#5066 histogram: avoid data transfer overhead for TPU outside compilation
  tensorboard/plugins/histogram/summary_v2.py
Labels: cla: yes, core:summaries, plugin:histogram

#5068 ci: pin tf-nightly to 20210614
  .github/workflows/ci.yml
Labels: cla: yes

#5070 Revert "histogram: avoid data transfer overhead for TPU outside compilation"
  tensorboard/plugins/histogram/summary_v2.py
Labels: cla: yes, core:summaries, plugin:histogram

#5071 infra: update officially supported Python version
  tensorboard/pip_package/requirements.txt
  tensorboard/pip_package/requirements_dev.txt
  tensorboard/pip_package/setup.py
Labels: cla: yes

#5065 feature flag: add flag for controlling dark mode
  tensorboard/webapp/feature_flag/effects/BUILD
  tensorboard/webapp/feature_flag/effects/feature_flag_effects.ts
  tensorboard/webapp/feature_flag/effects/feature_flag_effects_test.ts
  tensorboard/webapp/feature_flag/store/BUILD
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
  tensorboard/webapp/feature_flag/store/testing.ts
  tensorboard/webapp/feature_flag/testing.ts
  tensorboard/webapp/feature_flag/types.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
Labels: cla: yes

#5064 theme: color all links in header as white
  tensorboard/webapp/header/header_component.scss
Labels: cla: yes

#5075 projector: allow lib to be side loaded
  tensorboard/plugins/projector/vz_projector/BUILD
Labels: cla: yes

#5073 dark mode: improve style of range_input & run table
  tensorboard/webapp/runs/views/runs_table/runs_table_component.scss
  tensorboard/webapp/widgets/range_input/range_input_component.scss
Labels: cla: yes

#5078 scalar: fix axis label on Firefox
  tensorboard/components/vz_line_chart2/line-chart.ts
Labels: cla: yes, plugin:scalars

#5082 docs: add experiment list information in tensorboard.dev tutorial colab
  docs/images/tbdev_experiment_list.png
  docs/tbdev_getting_started.ipynb
Labels: cla: yes, tbdev, type:docs

#5083 pip: explicitly require Python 3.6 above
  tensorboard/pip_package/setup.py
Labels: cla: yes

#5084 color grouping: temporary remove regex
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ng.html
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Labels: cla: yes

#5085 hparams: rename keras.py to avoid import collision
  tensorboard/plugins/hparams/BUILD
  tensorboard/plugins/hparams/_keras.py
  tensorboard/plugins/hparams/_keras_test.py
  tensorboard/plugins/hparams/api.py
  tensorboard/plugins/hparams/api_test.py
Labels: cla: yes, plugin:hparams

#5087 Avoid using slash as division in sass
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
  tensorboard/webapp/notification_center/_views/notification_center_component.scss
  tensorboard/webapp/widgets/range_input/range_input_component.scss
Labels: cla: yes

#4942 core: fetch runs when alias changes
  tensorboard/webapp/core/effects/core_effects.ts
  tensorboard/webapp/core/effects/core_effects_test.ts
Labels: cla: yes

#5074 dark mode: enable media query based dark mode
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
  tensorboard/webapp/feature_flag/store/testing.ts
Labels: cla: yes

#5086 ci: unpin tf-nightly (from 20210614)
  .github/workflows/ci.yml
Labels: cla: yes, type:build/install

#5089 route: omit displayName from routeId.
  tensorboard/webapp/app_routing/internal_utils.ts
  tensorboard/webapp/app_routing/internal_utils_test.ts
Labels: cla: yes

#5091 plugin-lib: expose plugin lib for consumption
  tensorboard/components/experimental/plugin_lib/BUILD
Labels: cla: yes

#5092 core: fix data load when there are no routes
  tensorboard/webapp/app_routing/internal_utils.ts
  tensorboard/webapp/app_routing/store/app_routing_selectors.ts
  tensorboard/webapp/app_routing/store/app_routing_selectors_test.ts
  tensorboard/webapp/app_routing/types.ts
  tensorboard/webapp/core/effects/core_effects.ts
  tensorboard/webapp/core/effects/core_effects_test.ts
Labels: cla: yes

#5095 Remove remnants of settings properties from core.
  tensorboard/webapp/core/actions/BUILD
  tensorboard/webapp/core/actions/core_actions.ts
  tensorboard/webapp/core/store/BUILD
  tensorboard/webapp/core/store/core_selectors.ts
  tensorboard/webapp/core/store/core_types.ts
Labels: cla: yes

#5097 doc: update type in tb-customization cookbook example
  tensorboard/webapp/customization/customizable_component.ts
Labels: cla: yes

#5100 router: set correct initialState in reducers
  tensorboard/webapp/app_routing/BUILD
  tensorboard/webapp/app_routing/route_contexted_reducer_helper.ts
  tensorboard/webapp/app_routing/route_contexted_reducer_helper_test.ts
Labels: cla: yes

#5096 dark mode: button for toggling theme in header
  tensorboard/webapp/BUILD
  tensorboard/webapp/feature_flag/actions/feature_flag_actions.ts
  tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
  tensorboard/webapp/feature_flag/testing.ts
  tensorboard/webapp/feature_flag/types.ts
  tensorboard/webapp/header/BUILD
  tensorboard/webapp/header/dark_mode_toggle_component.ts
  tensorboard/webapp/header/dark_mode_toggle_container.ts
  tensorboard/webapp/header/dark_mode_toggle_test.ts
  tensorboard/webapp/header/header_component.ts
  tensorboard/webapp/header/header_module.ts
  tensorboard/webapp/testing/mat_icon_module.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
  third_party/js.bzl
Labels: cla: yes

#5101 router: allow onRouteIdChange to reason with route
  tensorboard/webapp/app_routing/BUILD
  tensorboard/webapp/app_routing/route_contexted_reducer_helper.ts
  tensorboard/webapp/app_routing/route_contexted_reducer_helper_test.ts
Labels: cla: yes

#5102 sync: add missing dependency on material menu
  tensorboard/webapp/header/BUILD
Labels: cla: yes

#5103 line-chart: set attribute when data is loaded once
  tensorboard/components/tf_dashboard_common/data-loader-behavior.ts
  tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.ts
Labels: cla: yes

#5081 color grouping: edit dialog for group by regex
  tensorboard/webapp/angular/BUILD
  tensorboard/webapp/runs/store/runs_selectors.ts
  tensorboard/webapp/runs/views/runs_table/BUILD
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog.ng.html
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.ts
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_container.ts
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_test.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_module.ts
Labels: cla: yes

#5106 dark mode: fix text plugin under dark mode
  tensorboard/components/tf_dashboard_common/tensorboard-color.ts
  tensorboard/components/tf_markdown_view/tf-markdown-view.ts
  tensorboard/plugins/text/tf_text_dashboard/tf-text-loader.ts
Labels: cla: yes
