Repository tensorflow/tensorboard, pull requests merged in 2021-05, with the labels that each got.

#4926 rust: switch `sync_all` calls to `flush`
  tensorboard/data/server/cli.rs
  tensorboard/data/server/disk_logdir.rs
  tensorboard/data/server/logdir.rs
  tensorboard/data/server/run.rs
Labels: cla: yes

#4929 debugger-v2: prevent runs request on reload
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/debugger_module.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/types.ts
Labels: cla: yes

#4935 Revert "refactor: use router event to fetch data."
  tensorboard/components/experimental/plugin_util/core-host-impl.ts
  tensorboard/components/experimental/plugin_util/plugin_api_host_test.ts
  tensorboard/webapp/BUILD
  tensorboard/webapp/app_container.ts
  tensorboard/webapp/app_test.ts
  tensorboard/webapp/core/BUILD
  tensorboard/webapp/core/actions/core_actions.ts
  tensorboard/webapp/core/core_module.ts
  tensorboard/webapp/core/effects/BUILD
  tensorboard/webapp/core/effects/core_effects.ts
  tensorboard/webapp/core/effects/core_effects_test.ts
  tensorboard/webapp/core/state.ts
  tensorboard/webapp/core/store/BUILD
  tensorboard/webapp/core/store/core_reducers.ts
  tensorboard/webapp/core/store/core_reducers_test.ts
  tensorboard/webapp/core/store/core_selectors.ts
  tensorboard/webapp/core/store/core_selectors_test.ts
  tensorboard/webapp/core/store/core_types.ts
  tensorboard/webapp/core/testing/BUILD
  tensorboard/webapp/core/testing/index.ts
  tensorboard/webapp/core/views/BUILD
  tensorboard/webapp/core/views/hash_storage_container.ts
  tensorboard/webapp/core/views/hash_storage_test.ts
  tensorboard/webapp/core/views/page_title_container.ts
  tensorboard/webapp/header/BUILD
  tensorboard/webapp/header/header_test.ts
  tensorboard/webapp/header/reload_container.ts
  tensorboard/webapp/plugins/plugins_container.ts
  tensorboard/webapp/plugins/plugins_container_test.ts
Labels: cla: yes

#4930 types: declare types to be public
  tensorboard/webapp/app_routing/types.ts
  tensorboard/webapp/experiments/types.ts
Labels: cla: yes

#4936 routing: permit registering RouteKind.UNKNOWN
  tensorboard/webapp/app_routing/route_registry_module.ts
  tensorboard/webapp/app_routing/route_registry_module_test.ts
Labels: cla: yes

#4927 core: fix relative redirect for /data/notifications
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
Labels: cla: yes, core:backend

#4932 what's new: adjust notification api path to absolute path
  tensorboard/webapp/notification_center/_data_source/notification_center_data_source.ts
  tensorboard/webapp/notification_center/_data_source/notification_center_data_source_test.ts
Labels: cla: yes

#4934 debugger-v2: refresh data on change plugin
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects.ts
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/effects/debugger_effects_test.ts
Labels: cla: yes

#4937 Fix broken Angular dashboards in need of localization module
  tensorboard/webapp/BUILD
  tensorboard/webapp/bootstrap.ts
  tensorboard/webapp/dev_assets/main_dev.ts
Labels: cla: yes

#4913 what's new: add full note link attribute
  tensorboard/webapp/notification_center/_data_source/backend_types.ts
  tensorboard/webapp/notification_center/_views/notification_center_component.ng.html
  tensorboard/webapp/notification_center/_views/notification_center_component.scss
  tensorboard/webapp/notification_center/_views/notification_center_test.ts
Labels: cla: yes

#4921 projector: remove Multiply blend mode
  tensorboard/plugins/projector/vz_projector/scatterPlotVisualizerSprites.ts
Labels: cla: yes

#4939 text-demo: Add text-specific screenshot. Add text demo to _book
  docs/_book.yaml
  docs/images/text_simple.png
  docs/text_summaries.ipynb
Labels: cla: yes

#4947 rust: upgrade to Rust 1.52.0
  .github/workflows/ci.yml
  third_party/rust.bzl
Labels: cla: yes, core:rustboard, type:build/install

#4953 Revert "refactor: use router event to fetch data (again) (#4941)"
  tensorboard/components/experimental/plugin_util/core-host-impl.ts
  tensorboard/components/experimental/plugin_util/plugin_api_host_test.ts
  tensorboard/webapp/BUILD
  tensorboard/webapp/app_container.ts
  tensorboard/webapp/app_test.ts
  tensorboard/webapp/core/BUILD
  tensorboard/webapp/core/actions/core_actions.ts
  tensorboard/webapp/core/core_module.ts
  tensorboard/webapp/core/effects/BUILD
  tensorboard/webapp/core/effects/core_effects.ts
  tensorboard/webapp/core/effects/core_effects_test.ts
  tensorboard/webapp/core/state.ts
  tensorboard/webapp/core/store/core_reducers.ts
  tensorboard/webapp/core/store/core_reducers_test.ts
  tensorboard/webapp/core/store/core_selectors.ts
  tensorboard/webapp/core/store/core_selectors_test.ts
  tensorboard/webapp/core/store/core_types.ts
  tensorboard/webapp/core/testing/index.ts
  tensorboard/webapp/core/views/BUILD
  tensorboard/webapp/core/views/hash_storage_container.ts
  tensorboard/webapp/core/views/hash_storage_test.ts
  tensorboard/webapp/core/views/page_title_container.ts
  tensorboard/webapp/header/header_test.ts
  tensorboard/webapp/header/reload_container.ts
  tensorboard/webapp/plugins/plugins_container.ts
  tensorboard/webapp/plugins/plugins_container_test.ts
Labels: cla: yes

#4957 runs: add groupBy enum and state to the reducer
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_types.ts
  tensorboard/webapp/runs/store/testing.ts
  tensorboard/webapp/runs/types.ts
Labels: cla: yes

#4960 cleanup: remove vestigial hparams from runs reducer
  tensorboard/webapp/runs/store/runs_reducers.ts
Labels: cla: yes

#4958 color grouping: add feature flag
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
  tensorboard/webapp/feature_flag/store/testing.ts
  tensorboard/webapp/feature_flag/testing.ts
  tensorboard/webapp/feature_flag/types.ts
Labels: cla: yes

#4961 what's new: export notification actions
  tensorboard/webapp/notification_center/BUILD
  tensorboard/webapp/notification_center/index.ts
Labels: cla: yes

#4959 runs: add state for remembering next assign color
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
  tensorboard/webapp/runs/store/runs_types.ts
  tensorboard/webapp/runs/store/testing.ts
  tensorboard/webapp/util/BUILD
  tensorboard/webapp/util/colors.ts
  tensorboard/webapp/util/colors_test.ts
Labels: cla: yes

#4962 plugin-api: fix getURLPluginData()
  tensorboard/components/experimental/plugin_util/BUILD
  tensorboard/components/experimental/plugin_util/core-host-impl.ts
  tensorboard/components/experimental/plugin_util/plugin_api_host_test.ts
  tensorboard/components/tf_storage/storage.ts
  tensorboard/webapp/tb_polymer_interop_types.ts
Labels: cla: yes

#4964 runs: refactor to move color state to data
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
  tensorboard/webapp/runs/store/runs_selectors.ts
  tensorboard/webapp/runs/store/runs_selectors_test.ts
  tensorboard/webapp/runs/store/runs_types.ts
  tensorboard/webapp/runs/store/testing.ts
Labels: cla: yes

#4879 Explicitly list ngrx dependencies in PluginApiHostModule.
  tensorboard/components/experimental/plugin_util/BUILD
  tensorboard/components/experimental/plugin_util/plugin_api_host_module.ts
Labels: cla: yes

#4956 what's new: small cosmetic changes to improve readability
  tensorboard/webapp/notification_center/_views/notification_center_component.ng.html
  tensorboard/webapp/notification_center/_views/notification_center_component.scss
Labels: cla: yes, core:frontend

#4969 docs: mark RustBoard status as shipped
  docs/design/rustboard.md
Labels: cla: yes, core:rustboard, type:docs

#4971 Fix sync by removing tf_storage dep
  tensorboard/components/experimental/plugin_util/BUILD
Labels: cla: yes

#4963 (docs) Add a sentence about smoothing to the scalars tutorial.
  docs/scalars_and_keras.ipynb
Labels: cla: yes, type:docs

#4973 Use an r-string so the \n doesn't break the site.
  tensorboard/plugins/text/summary_v2.py
Labels: cla: yes, type:docs

#4979 Import RouteRegistryModule from AppRoutingModule since it is a runtime dependency.
  tensorboard/webapp/app_routing/app_routing_module.ts
Labels: cla: yes

#4977 refactor: settings code structure to new format
  tensorboard/webapp/BUILD
  tensorboard/webapp/settings/BUILD
  tensorboard/webapp/settings/_views/BUILD
  tensorboard/webapp/settings/_views/dialog_component.css
  tensorboard/webapp/settings/_views/dialog_component.ts
  tensorboard/webapp/settings/_views/dialog_component_test.ts
  tensorboard/webapp/settings/_views/polymer_interop_container.ts
  tensorboard/webapp/settings/_views/polymer_interop_test.ts
  tensorboard/webapp/settings/_views/settings_button_component.ts
  tensorboard/webapp/settings/_views/settings_module.ts
  tensorboard/webapp/settings/_views/settings_test.ts
  tensorboard/webapp/settings/settings_module.ts
Labels: cla: yes

#4966 runs: implement Runs and Experiments grouping
  tensorboard/webapp/runs/store/BUILD
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
  tensorboard/webapp/runs/store/runs_selectors.ts
  tensorboard/webapp/runs/store/runs_selectors_test.ts
  tensorboard/webapp/runs/store/runs_types.ts
  tensorboard/webapp/runs/store/testing.ts
  tensorboard/webapp/runs/store/utils.ts
  tensorboard/webapp/runs/store/utils_test.ts
  tensorboard/webapp/runs/types.ts
Labels: cla: yes

#4967 flag: add feature flag for enableColorGroup
  tensorboard/webapp/routes/dashboard_deeplink_provider.ts
  tensorboard/webapp/routes/dashboard_deeplink_provider_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
Labels: cla: yes

#4976 infra: upgrade dependencies
  package.json
  yarn.lock
Labels: cla: yes

#4981 Fix sync errors about property renaming and linting
  tensorboard/webapp/widgets/filter_input/filter_input_component.ts
  tensorboard/webapp/widgets/filter_input/filter_input_test.ts
Labels: cla: yes

#4968 runs: conditionally add group menu button
  tensorboard/webapp/BUILD
  tensorboard/webapp/runs/views/runs_table/BUILD
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ts
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
  tensorboard/webapp/runs/views/runs_table/runs_table_component.scss
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_module.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
  tensorboard/webapp/testing/mat_icon_module.ts
  third_party/js.bzl
Labels: cla: yes

#4978 Cleanup how HashDeepLinker is provided in prod and test code.
  tensorboard/webapp/core/core_module.ts
  tensorboard/webapp/core/store/core_initial_state_provider.ts
  tensorboard/webapp/core/store/core_initial_state_provider_test.ts
  tensorboard/webapp/core/views/hash_storage_component.ts
  tensorboard/webapp/core/views/hash_storage_test.ts
  tensorboard/webapp/deeplink/BUILD
  tensorboard/webapp/deeplink/deeplink_module.ts
  tensorboard/webapp/deeplink/testing.ts
  tensorboard/webapp/deeplink/types.ts
  tensorboard/webapp/testing/BUILD
  tensorboard/webapp/testing/integration_test_module.ts
Labels: cla: yes

#4983 settings: add dependency on CoreModule
  tensorboard/webapp/settings/BUILD
  tensorboard/webapp/settings/settings_module.ts
Labels: cla: yes

#4980 runs: re-assign colors on runGroupByChanged event
  tensorboard/webapp/runs/actions/runs_actions.ts
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
Labels: cla: yes

#4974 router: change URL in between navigating & navigated
  tensorboard/webapp/app_routing/effects/app_routing_effects.ts
  tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
Labels: cla: yes

#4985 runs: add selector for groupBy.
  tensorboard/webapp/runs/store/runs_selectors.ts
  tensorboard/webapp/runs/store/runs_selectors_test.ts
Labels: cla: yes

#4988 hparams: fix the parallel coordinate layout
  tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/BUILD
  tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/axes.ts
  tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/interaction_manager.ts
  tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/lines.ts
  tensorboard/plugins/hparams/tf_hparams_parallel_coords_plot/tf-hparams-parallel-coords-plot.ts
  tensorboard/plugins/hparams/tf_hparams_query_pane/BUILD
  tensorboard/plugins/hparams/tf_hparams_types/BUILD
  tensorboard/plugins/hparams/tf_hparams_types/types.d.ts
Labels: cla: yes

#4989 Move constant creation in debugger_v2_plugin_test
  tensorboard/plugins/debugger_v2/debugger_v2_plugin_test.py
Labels: cla: yes

#4986 runs: fully implement color group by UI
  tensorboard/webapp/BUILD
  tensorboard/webapp/runs/views/runs_table/BUILD
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.scss
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ts
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
  tensorboard/webapp/testing/mat_icon_module.ts
  third_party/js.bzl
Labels: cla: yes

#4997 docs: update text demo
  tensorboard/plugins/text/text_demo.py
Labels: cla: yes

#5001 docs: update npmi demo
  tensorboard/plugins/npmi/csv_to_plugin_data_demo.py
  tensorboard/plugins/npmi/npmi_demo.py
  tensorboard/plugins/npmi/npy_to_embedding_data_demo.py
Labels: cla: yes

#4982 Add JSDoc to DeepLinkProvider interface definition
  tensorboard/webapp/app_routing/deep_link_provider.ts
Labels: cla: yes

#4998 docs: minor rewording for the projector plugin tutorial
  docs/tensorboard_projector_plugin.ipynb
Labels: cla: yes, type:docs

#5005 Minor fixes to debugger_v2 guide.
  docs/debugger_v2.md
Labels: cla: yes

#5006 docs: update graphs_demo.py
  tensorboard/plugins/graph/graphs_demo.py
Labels: cla: yes, plugin:graph, type:docs

#5011 custom scalars: update demo to TF 2.0 style
  tensorboard/plugins/custom_scalar/custom_scalar_demo.py
Labels: cla: yes, plugin:custom-scalars, tf-2.0, type:cleanup, type:docs

#5004 Update images_demo to be TF2-friendly, and simpler.
  tensorboard/plugins/image/BUILD
  tensorboard/plugins/image/images_demo.py
Labels: cla: yes, plugin:images

#4995 runs: fix the colorMap override feature
  tensorboard/webapp/runs/store/runs_selectors.ts
  tensorboard/webapp/runs/store/runs_selectors_test.ts
Labels: cla: yes

#5007 sync: fix object property accessor
  tensorboard/webapp/metrics/data_source/metrics_data_source.ts
Labels: cla: yes

#5013 core: toPromise is deprecated. use lastValueFrom instead
  tensorboard/webapp/metrics/data_source/BUILD
  tensorboard/webapp/metrics/data_source/metrics_data_source_test.ts
Labels: cla: yes

#4994 timeseries: persist and read settings
  tensorboard/webapp/metrics/actions/index.ts
  tensorboard/webapp/metrics/effects/BUILD
  tensorboard/webapp/metrics/effects/index.ts
  tensorboard/webapp/metrics/effects/metrics_effects_test.ts
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
Labels: cla: yes

#5010 line chart: improve major axis for numbers
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_utils.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_utils_test.ts
Labels: cla: yes

#5003 timeseries: improved formatting on tooltip
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/formatter.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/formatter_test.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_utils.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ng.html
Labels: cla: yes

#5009 docs: update scalars demo
  tensorboard/plugins/scalar/scalars_demo.py
Labels: cla: yes, plugin:scalars, tf-2.0, type:cleanup, type:docs

#4987 timeseries: make image support conditional
  tensorboard/webapp/feature_flag/store/BUILD
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
  tensorboard/webapp/feature_flag/store/testing.ts
  tensorboard/webapp/feature_flag/testing.ts
  tensorboard/webapp/feature_flag/types.ts
  tensorboard/webapp/metrics/BUILD
  tensorboard/webapp/metrics/data_source/BUILD
  tensorboard/webapp/metrics/data_source/metrics_data_source.ts
  tensorboard/webapp/metrics/data_source/metrics_data_source_module.ts
  tensorboard/webapp/metrics/data_source/metrics_data_source_test.ts
  tensorboard/webapp/metrics/metrics_module.ts
  tensorboard/webapp/metrics/views/card_renderer/card_view_test.ts
  tensorboard/webapp/metrics/views/card_renderer/image_card_test.ts
  tensorboard/webapp/metrics/views/right_pane/BUILD
  tensorboard/webapp/metrics/views/right_pane/right_pane_module.ts
  tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
  tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
  tensorboard/webapp/webapp_data_source/BUILD
Labels: cla: yes

#5000 docs: update example plugin demos
  tensorboard/examples/plugins/example_basic/tensorboard_plugin_example/demo.py
  tensorboard/examples/plugins/example_raw_scalars/tensorboard_plugin_example_raw_scalars/demo.py
Labels: cla: yes, type:docs

#4999 docs: update mesh demo
  tensorboard/plugins/mesh/BUILD
  tensorboard/plugins/mesh/README.md
  tensorboard/plugins/mesh/mesh_demo.py
  tensorboard/plugins/mesh/mesh_demo_v2.py
  tensorboard/plugins/mesh/summary.py
Labels: cla: yes, type:docs

#4996 docs: update audio demo to TF2
  tensorboard/plugins/audio/audio_demo.py
Labels: cla: yes, tf-2.0, type:docs

#5017 runs: move html to its own file
  tensorboard/webapp/runs/views/runs_table/BUILD
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ng.html
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ts
Labels: cla: yes

#5021 sync: add missing ngrx/store/testing dep
  tensorboard/webapp/metrics/data_source/BUILD
Labels: cla: yes

#5020 timeseries: fix runs table scrollable issue
  tensorboard/webapp/runs/views/runs_table/runs_table_component.scss
Labels: cla: yes

#5018 runs: create groupBy override vs. initial value
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
  tensorboard/webapp/runs/store/runs_selectors.ts
  tensorboard/webapp/runs/store/runs_selectors_test.ts
  tensorboard/webapp/runs/store/runs_types.ts
  tensorboard/webapp/runs/store/testing.ts
Labels: cla: yes

#5023 runs: fix run filter click target width
  tensorboard/webapp/runs/views/runs_table/runs_table_component.scss
Labels: cla: yes

#5016 color grouping: group runs by regex
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/utils.ts
  tensorboard/webapp/runs/store/utils_test.ts
  tensorboard/webapp/runs/types.ts
Labels: cla: yes

#5024 timeseries: keep runs table header sticky
  tensorboard/webapp/runs/views/runs_table/runs_table_component.scss
  tensorboard/webapp/theme/_tb_theme.template.scss
Labels: cla: yes

#5015 timeseries: use SI unit for STEP axis
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
Labels: cla: yes
