Repository tensorflow/tensorboard, pull requests merged in 2021-01, with the labels that each got.

#4515 py3: use `html.escape` unconditionally
  tensorboard/notebook.py
Labels: cla: yes, type:cleanup

#4516 proto: split `protos_all` into individual targets
  tensorboard/compat/proto/BUILD
Labels: cla: yes, core:rustboard, type:build/install

#4512 rust: run Clippy on tests and fix existing errors
  .github/workflows/ci.yml
  tensorboard/data/server/downsample.rs
  tensorboard/data/server/event_file.rs
  tensorboard/data/server/logdir.rs
  tensorboard/data/server/server.rs
  tensorboard/data/server/types.rs
  tensorboard/data/server/writer.rs
Labels: cla: yes, core:rustboard, type:build/install

#4513 rust: fix test warning on macOS
  tensorboard/data/server/logdir.rs
Labels: cla: yes, core:rustboard, type:build/install

#4514 py3: run `whitespace_hygiene_test.py` in Python 3
  tensorboard/tools/whitespace_hygiene_test.py
Labels: cla: yes, type:build/install, type:cleanup

#4508 projector: fix `RunPaths` result aliasing
  tensorboard/plugins/projector/projector_plugin.py
Labels: cla: yes, core:rustboard, plugin:projector

#4494 projector: read run names from data provider
  tensorboard/plugins/projector/BUILD
  tensorboard/plugins/projector/projector_plugin.py
  tensorboard/plugins/projector/projector_plugin_test.py
Labels: cla: yes, core:rustboard, plugin:projector

#4507 py3: remove `mock` backport
  tensorboard/BUILD
  tensorboard/backend/BUILD
  tensorboard/backend/application_test.py
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/data_ingester_test.py
  tensorboard/backend/event_processing/directory_loader_test.py
  tensorboard/backend/http_util_test.py
  tensorboard/backend/security_validator_test.py
  tensorboard/data/experimental/BUILD
  tensorboard/default_test.py
  tensorboard/manager_e2e_test.py
  tensorboard/manager_test.py
  tensorboard/plugins/core/BUILD
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/plugins/hparams/BUILD
  tensorboard/plugins/hparams/backend_context_test.py
  tensorboard/plugins/hparams/download_data_test.py
  tensorboard/plugins/hparams/keras_test.py
  tensorboard/plugins/hparams/list_metric_evals_test.py
  tensorboard/plugins/hparams/list_session_groups_test.py
  tensorboard/plugins/hparams/summary_v2_test.py
  tensorboard/plugins/mesh/BUILD
  tensorboard/plugins/mesh/metadata_test.py
  tensorboard/plugins/npmi/BUILD
  tensorboard/program_test.py
  tensorboard/tools/whitespace_hygiene_test.py
  tensorboard/uploader/BUILD
  tensorboard/uploader/exporter_test.py
  tensorboard/uploader/uploader_subcommand_test.py
  tensorboard/uploader/uploader_test.py
  tensorboard/uploader/util_test.py
  tensorboard/util/BUILD
  third_party/mock.BUILD
  third_party/mock_call_assertions.patch
  third_party/python.bzl
Labels: cla: yes, type:build/install, type:cleanup

#4497 cleanup: remove dev print for graph
  tensorboard/plugins/graph/tf_graph_common/render.ts
Labels: cla: yes

#4483 line chart: temporal axis
  tensorboard/webapp/widgets/line_chart_v2/sub_view/BUILD
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view_test.ts
Labels: cla: yes

#4486 line chart: support relative time
  tensorboard/webapp/metrics/views/card_renderer/BUILD
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
Labels: cla: yes

#4489 line chart: implement tooltip sort order
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ng.html
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts
Labels: cla: yes

#4491 line chart: improve interaction
  tensorboard/webapp/widgets/line_chart_v2/sub_view/BUILD
  tensorboard/webapp/widgets/line_chart_v2/sub_view/internal_types.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ng.html
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.scss
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view_test.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/testing.ts
Labels: cla: yes

#4520 line chart: use yScale for y-axis in grid
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_grid_view.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_grid_view_test.ts
Labels: cla: yes

#4496 graph: speed up "Normalizing names" step
  tensorboard/plugins/graph/tf_graph_common/graph.ts
Labels: cla: yes, core:frontend, plugin:graph, theme:performance

#4527 Update the link of FI colab.
  docs/fairness-indicators.md
Labels: cla: yes, type:docs

#4487 rust: implement `ListPlugins` RPC
  tensorboard/data/server/server.rs
Labels: cla: yes, core:rustboard

#4495 perf: improve graph build performance
  tensorboard/plugins/graph/tf_graph/tf-graph-scene.html.ts
  tensorboard/plugins/graph/tf_graph_common/common.ts
  tensorboard/plugins/graph/tf_graph_common/layout.ts
  tensorboard/plugins/graph/tf_graph_common/node.ts
  tensorboard/plugins/graph/tf_graph_common/util.ts
Labels: cla: yes, core:frontend, plugin:graph, theme:performance

#4502 Add a lengths argument to tensorboard.summary.audio.
  tensorboard/plugins/audio/summary_test.py
  tensorboard/plugins/audio/summary_v2.py
Labels: cla: yes, core:summaries, plugin:audio, type:feature

#4525 Fix unnecessary scroller bar in firefox and chrome
  tensorboard/plugins/projector/tf_projector_plugin/index.js
  tensorboard/plugins/projector/vz_projector/vz-projector-dashboard.ts
  tensorboard/webapp/plugins/plugins_component.ts
Labels: cla: yes

#4535 rust: build universal data server with no binary
  .github/workflows/ci.yml
  tensorboard/data/server/pip_package/build.py
  tensorboard/data/server/pip_package/tensorboard_data_server/__init__.py
  tensorboard/data/server_ingester.py
Labels: cla: yes, core:rustboard, type:build/install

#4526 refactor: tweak graph const. measurement
  tensorboard/plugins/graph/tf_graph/tf-graph.ts
Labels: cla: yes

#4528 infra: better type Map
  tensorboard/components/tf_categorization_utils/categorizationUtils.ts
  tensorboard/components/tf_paginated_view/tf-dom-repeat.ts
  tensorboard/defs/BUILD
  tensorboard/defs/defs.bzl
  tensorboard/defs/strict_type_check.d.ts
  tensorboard/plugins/hparams/tf_hparams_scatter_plot_matrix_plot/tf-hparams-scatter-plot-matrix-plot.ts
  tensorboard/plugins/hparams/tf_hparams_table_view/tf-hparams-table-view.ts
  tensorboard/plugins/mesh/tf_mesh_dashboard/array-buffer-data-provider.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/metrics/views/main_view/main_view_test.ts
  tensorboard/webapp/plugins/npmi/npmi_container_test.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_test.ts
  tensorboard/webapp/plugins/npmi/views/data_selection/results_download/results_download_test.ts
  tensorboard/webapp/plugins/npmi/views/main/main_container_test.ts
  tensorboard/webapp/plugins/text_v2/data_source/text_v2_server_data_source.ts
  tensorboard/webapp/plugins/text_v2/store/testing.ts
  tensorboard/webapp/plugins/text_v2/store/text_v2_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Labels: cla: yes

#4537 rust: add `base64` dependency
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  third_party/rust/BUILD.bazel
  third_party/rust/crates.bzl
  third_party/rust/remote/BUILD.base64-0.13.0.bazel
Labels: cla: yes, core:rustboard, dependencies

#4532 timeseries: stamp scalar only when first visible
  tensorboard/webapp/metrics/effects/index.ts
  tensorboard/webapp/metrics/effects/metrics_effects_test.ts
  tensorboard/webapp/metrics/store/metrics_selectors.ts
  tensorboard/webapp/metrics/store/metrics_selectors_test.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
Labels: cla: yes

#4539 rust: add `serde` and `serde_json` dependencies
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  third_party/rust/BUILD.bazel
  third_party/rust/crates.bzl
  third_party/rust/remote/BUILD.ryu-1.0.5.bazel
  third_party/rust/remote/BUILD.serde-1.0.118.bazel
  third_party/rust/remote/BUILD.serde_derive-1.0.118.bazel
  third_party/rust/remote/BUILD.serde_json-1.0.61.bazel
  third_party/rust/remote/BUILD.syn-1.0.48.bazel
Labels: cla: yes, core:rustboard, dependencies

#4542 Revert "Add a lengths argument to tensorboard.summary.audio."
  tensorboard/plugins/audio/summary_test.py
  tensorboard/plugins/audio/summary_v2.py
Labels: cla: yes, core:summaries, plugin:audio

#4423 ng: support path_prefix at router level
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/webapp/app_routing/BUILD
  tensorboard/webapp/app_routing/app_root.ts
  tensorboard/webapp/app_routing/app_root_test.ts
  tensorboard/webapp/app_routing/app_routing_module.ts
  tensorboard/webapp/app_routing/effects/BUILD
  tensorboard/webapp/app_routing/effects/app_routing_effects.ts
  tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
  tensorboard/webapp/app_routing/location.ts
  tensorboard/webapp/app_routing/location_test.ts
  tensorboard/webapp/app_routing/views/BUILD
  tensorboard/webapp/app_routing/views/app_routing_view_module.ts
  tensorboard/webapp/app_routing/views/router_link_directive_container.ts
  tensorboard/webapp/app_routing/views/router_link_test.ts
Labels: cla: yes

#4545 rust: define blob key encoding
  tensorboard/data/server/BUILD
  tensorboard/data/server/blob_key.rs
  tensorboard/data/server/data_compat.rs
  tensorboard/data/server/lib.rs
  tensorboard/data/server/server.rs
Labels: cla: yes, core:rustboard

#4548 ci: backport new CI to 2.4 release branch
  .github/workflows/ci.yml
  .travis.yml
  ci/bazelrc
  tensorboard/pip_package/test_pip_package.sh
Labels: cla: yes, type:build/install

#4549 2.4: ng: support path_prefix at router level (#4423)
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
  tensorboard/webapp/app_routing/BUILD
  tensorboard/webapp/app_routing/app_root.ts
  tensorboard/webapp/app_routing/app_root_test.ts
  tensorboard/webapp/app_routing/app_routing_module.ts
  tensorboard/webapp/app_routing/effects/BUILD
  tensorboard/webapp/app_routing/effects/app_routing_effects.ts
  tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
  tensorboard/webapp/app_routing/location.ts
  tensorboard/webapp/app_routing/location_test.ts
  tensorboard/webapp/app_routing/views/BUILD
  tensorboard/webapp/app_routing/views/app_routing_view_module.ts
  tensorboard/webapp/app_routing/views/router_link_directive_container.ts
  tensorboard/webapp/app_routing/views/router_link_test.ts
Labels: cla: yes

#4550 2.4: Remove `frame-ancestors *` CSP directive (#4332)
  tensorboard/backend/http_util.py
  tensorboard/backend/http_util_test.py
  tensorboard/backend/security_validator.py
Labels: cla: yes

#4536 py3: remove `six` from requirements
  tensorboard/pip_package/requirements.txt
Labels: cla: yes, type:build/install, type:cleanup

#4553 graph: disallow double click to select text
  tensorboard/plugins/graph/tf_graph/tf-graph-scene.html.ts
Labels: cla: yes

#4552 metrics: fix wall time rendering
  tensorboard/webapp/widgets/line_chart/line_chart_component.ts
  tensorboard/webapp/widgets/line_chart/line_chart_test.ts
Labels: cla: yes, plugin:time-series, type:bug

#4538 graph: Display sidebar for no data and inactive graph
  tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts
Labels: cla: yes

#4531 infra: suffix index.js and worker url with md5
  tensorboard/BUILD
  tensorboard/defs/internal/BUILD
  tensorboard/defs/internal/resource.bzl
  tensorboard/defs/internal/resource_digest_suffixer.py
  tensorboard/defs/internal/resource_digest_suffixer_test.py
  tensorboard/defs/js.bzl
  tensorboard/webapp/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_resource.template.ts
Labels: cla: yes

#4557 Post-release 2.4.1
  RELEASE.md
Labels: cla: yes

#4558 core: cache on JS resources when hash is present
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
Labels: cla: yes

#4562 rust: add `tokio-stream` dependency
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  third_party/rust/BUILD.bazel
  third_party/rust/crates.bzl
  third_party/rust/remote/BUILD.pin-project-lite-0.2.4.bazel
  third_party/rust/remote/BUILD.tokio-1.0.2.bazel
  third_party/rust/remote/BUILD.tokio-stream-0.1.2.bazel
Labels: cla: yes, core:rustboard, dependencies

#4560 cleanup: remove jspbfix
  tensorboard/java/org/tensorflow/tensorboard/vulcanize/BUILD
  third_party/BUILD
  third_party/jspbfix.js
Labels: cla: yes

#4559 line chart: fix axis layout
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view_test.ts
Labels: cla: yes

#4544 rust: load graphs into memory as blob sequences
  tensorboard/data/server/commit.rs
  tensorboard/data/server/data_compat.rs
  tensorboard/data/server/run.rs
  tensorboard/data/server/writer.rs
Labels: cla: yes, core:rustboard

#4561 line chart: refactor worker typing
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_pool.ts
Labels: cla: yes

#4546 rust: implement `ListPlugins` for blobs
  tensorboard/data/server/commit.rs
  tensorboard/data/server/server.rs
Labels: cla: yes, core:rustboard

#4563 rust: implement blob sequence RPCs and client
  tensorboard/data/grpc_provider.py
  tensorboard/data/grpc_provider_test.py
  tensorboard/data/server/BUILD
  tensorboard/data/server/server.rs
Labels: cla: yes, core:rustboard

#4567 rust: remove demo protobuf
  tensorboard/data/server/BUILD
  tensorboard/data/server/demo.pb.rs
  tensorboard/data/server/demo.proto
  tensorboard/data/server/gen_protos_tool.rs
  tensorboard/data/server/lib.rs
Labels: cla: yes, core:rustboard, type:cleanup

#4564 rust: support images and generic blob sequences
  tensorboard/data/server/data_compat.rs
Labels: cla: yes, core:rustboard, plugin:images

#4565 rust: pass summary metadata to `into_blob_sequence`
  tensorboard/data/server/data_compat.rs
  tensorboard/data/server/run.rs
Labels: cla: yes, core:rustboard

#4566 rust: support audio
  tensorboard/data/server/data_compat.rs
Labels: cla: yes, core:rustboard, plugin:audio

#4568 rust: support tagged run metadata graphs
  tensorboard/data/server/data_compat.rs
  tensorboard/data/server/run.rs
  tensorboard/data/server/writer.rs
Labels: cla: yes, core:rustboard, plugin:graph, plugin:graph:profile

#4569 rust: support graph sub-plugins
  tensorboard/data/server/data_compat.rs
Labels: cla: yes, core:rustboard, plugin:graph, plugin:graph:profile

#4540 line chart: update only visible charts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
Labels: cla: yes

#4574 tensorboard-data-server 0.1.0
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  tensorboard/data/server/cli.rs
  tensorboard/data/server/pip_package/tensorboard_data_server/__init__.py
Labels: cla: yes, core:rustboard

#4573 rust: make CRC checking optional
  tensorboard/data/server/bench.rs
  tensorboard/data/server/cli.rs
  tensorboard/data/server/event_file.rs
  tensorboard/data/server/logdir.rs
  tensorboard/data/server/run.rs
Labels: cla: yes, core:rustboard, theme:performance

#4575 line chart: fix axis layout
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts
Labels: cla: yes

#4578 rust: prefer Bazel-built server to Python dep
  tensorboard/data/server_ingester.py
Labels: cla: yes, core:rustboard

#4570 rust: organize `plugin_names` const module
  tensorboard/data/server/data_compat.rs
  tensorboard/data/server/run.rs
Labels: cla: yes, core:rustboard, type:cleanup

#4576 rust: quiet “listening on…” if `--port-file` given
  tensorboard/data/server/cli.rs
Labels: cla: yes, core:rustboard, theme:usability

#4579 diagnose: print data server info
  tensorboard/tools/diagnose_tensorboard.py
Labels: cla: yes, core:rustboard

#4583 core: drop support for negative `--reload_interval`
  tensorboard/backend/event_processing/data_ingester.py
  tensorboard/plugins/core/core_plugin.py
Labels: cla: yes, core:backend

#4577 rust: plumb reload interval to data server
  tensorboard/data/server/cli.rs
  tensorboard/data/server_ingester.py
  tensorboard/data/server_ingester_test.py
  tensorboard/program.py
Labels: cla: yes, core:rustboard

#4585 text: support fenced code blocks in Markdown
  tensorboard/plugin_util.py
Labels: cla: yes

#4587 tensorboard-data-server 0.2.0
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  tensorboard/data/server/cli.rs
  tensorboard/data/server/pip_package/tensorboard_data_server/__init__.py
Labels: cla: yes, core:rustboard

#4594 Expose getParams() in QueryParamsFeatureFlagDataSource
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
Labels: cla: yes

#4593 feature flag: persist only overridden flags
  tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts
  tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
  tensorboard/webapp/feature_flag/store/feature_flag_types.ts
  tensorboard/webapp/feature_flag/store/testing.ts
  tensorboard/webapp/routes/core_deeplink_provider.ts
  tensorboard/webapp/routes/core_deeplink_provider_test.ts
Labels: cla: yes

#4595 ci: run on pushes to tags
  .github/workflows/ci.yml
Labels: cla: yes, type:build/install

#4430 ng: dispatch coreLoaded after router is initialized
  tensorboard/webapp/BUILD
  tensorboard/webapp/app_container.ts
  tensorboard/webapp/app_test.ts
Labels: cla: yes

#4598 deps: add explicit dependency to test libs
  tensorboard/webapp/BUILD
Labels: cla: yes

#4599 Revert "feature flag: persist only overridden flags (#4593)"
  tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts
  tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
  tensorboard/webapp/feature_flag/store/feature_flag_types.ts
  tensorboard/webapp/feature_flag/store/testing.ts
  tensorboard/webapp/routes/core_deeplink_provider.ts
  tensorboard/webapp/routes/core_deeplink_provider_test.ts
Labels: cla: yes

#4600 Update protos for TF 2021-01-25 head
  tensorboard/compat/proto/config.proto
  tensorboard/compat/proto/graph.proto
  tensorboard/compat/proto/op_def.proto
  tensorboard/compat/proto/rewriter_config.proto
  tensorboard/compat/proto/saved_object_graph.proto
  tensorboard/compat/proto/summary.proto
  tensorboard/compat/proto/types.proto
  tensorboard/data/server/tensorboard.pb.rs
Labels: cla: yes, type:cleanup

#4590 line chart: restore thicker line width
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/series_line_view.ts
Labels: cla: yes

#4603 rustboard: propagate --verbosity=debug to tensorboard-data-server
  tensorboard/data/server_ingester.py
Labels: cla: yes, core:rustboard

#4608 proto: add dep from `:op_def` to `:resource_handle`
  tensorboard/compat/proto/BUILD
Labels: cla: yes, type:build/install

#4609 Introduce a selector providing a RunId to Run map
  tensorboard/webapp/runs/store/runs_selectors.ts
  tensorboard/webapp/runs/store/runs_selectors_test.ts
Labels: cla: yes

#4606 program: set WerkzeugServer to use HTTP/1.1 in a proper non-global way
  tensorboard/program.py
Labels: cla: yes, core:backend, type:cleanup

#4601 grpc_util: extract channel creds parsing and logic
  tensorboard/uploader/BUILD
  tensorboard/uploader/flags_parser.py
  tensorboard/uploader/flags_parser_test.py
  tensorboard/uploader/uploader_subcommand.py
  tensorboard/util/grpc_util.py
  tensorboard/util/grpc_util_test.py
Labels: cla: yes, core:rustboard, core:uploader, type:cleanup

#4607 cleanup: reduce amount of boilerplate needed in main.py
  tensorboard/BUILD
  tensorboard/main.py
  tensorboard/main_lib.py
  tensorboard/program.py
Labels: cla: yes, core:backend, type:cleanup

#4602 core: add `--grpc_creds_type` flag for data server
  tensorboard/data/BUILD
  tensorboard/data/server_ingester.py
  tensorboard/data/server_ingester_test.py
  tensorboard/plugins/core/BUILD
  tensorboard/plugins/core/core_plugin.py
  tensorboard/program.py
Labels: cla: yes, core:backend, core:rustboard

#4614 line chart: put fades around start&end of text
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts
Labels: cla: yes

#4612 feature: differentiate overridden flags from default
  tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts
  tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
  tensorboard/webapp/feature_flag/store/feature_flag_types.ts
  tensorboard/webapp/feature_flag/store/testing.ts
  tensorboard/webapp/routes/core_deeplink_provider.ts
  tensorboard/webapp/routes/core_deeplink_provider_test.ts
Labels: cla: yes

#4617 chore: fix typo of "overriden" to "overridden"
  tensorboard/components/tf_markdown_view/sanitize.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/plugins/plugins_component.ng.html
  tensorboard/webapp/routes/core_deeplink_provider.ts
  tensorboard/webapp/routes/core_deeplink_provider_test.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
Labels: cla: yes

#4613 proto: automatically update BUILD file
  tensorboard/compat/proto/BUILD
  tensorboard/compat/proto/update.sh
Labels: cla: yes, type:build/install

#4619 rust: list test data bucket in `DEVELOPMENT.md`
  tensorboard/data/server/DEVELOPMENT.md
Labels: cla: yes, core:rustboard, type:docs

#4618 data_compat: mark converted image and audio data
  tensorboard/data/server/BUILD
  tensorboard/data/server/data_compat.rs
  tensorboard/data/server/gen_protos_tool.rs
  tensorboard/data/server/tensorboard.pb.rs
  tensorboard/data_compat.py
  tensorboard/data_compat_test.py
  tensorboard/plugins/audio/BUILD
  tensorboard/plugins/audio/metadata.py
  tensorboard/plugins/audio/plugin_data.proto
  tensorboard/plugins/image/BUILD
  tensorboard/plugins/image/metadata.py
  tensorboard/plugins/image/plugin_data.proto
Labels: cla: yes, core:backend

#4620 graph: update metadata docs on plugin names
  tensorboard/plugins/graph/metadata.py
Labels: cla: yes, plugin:graph, type:docs

#4615 line chart: fill the origin with a rectangle
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts
Labels: cla: yes

#4622 line chart: support Fit domain button in timeseries
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
Labels: cla: yes

#4589 infra: implement dev assets
  tensorboard/BUILD
  tensorboard/webapp/dev_assets/BUILD
  tensorboard/webapp/dev_assets/main_dev.ts
Labels: cla: yes

#4624 line chart: update chart content when axis changes
  tensorboard/webapp/widgets/line_chart_v2/lib/chart.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/integration_test.ts
Labels: cla: yes

#4627 rust: add `crossbeam` dependency
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  third_party/rust/BUILD.bazel
  third_party/rust/crates.bzl
  third_party/rust/remote/BUILD.const_fn-0.4.5.bazel
  third_party/rust/remote/BUILD.crossbeam-0.8.0.bazel
  third_party/rust/remote/BUILD.crossbeam-channel-0.5.0.bazel
  third_party/rust/remote/BUILD.crossbeam-deque-0.8.0.bazel
  third_party/rust/remote/BUILD.crossbeam-epoch-0.9.1.bazel
  third_party/rust/remote/BUILD.crossbeam-queue-0.3.1.bazel
  third_party/rust/remote/BUILD.crossbeam-utils-0.8.1.bazel
  third_party/rust/remote/BUILD.memoffset-0.6.1.bazel
  third_party/rust/remote/BUILD.scopeguard-1.1.0.bazel
Labels: cla: yes, core:rustboard, dependencies

#4628 program: restore default assets zip provider
  tensorboard/BUILD
  tensorboard/assets.py
  tensorboard/assets_test.py
  tensorboard/main.py
  tensorboard/main_dev.py
  tensorboard/program.py
  tensorboard/program_test.py
Labels: cla: yes, core:backend, type:bug

#4524 infra: FE development environment
  tensorboard/defs/defs.bzl
  tensorboard/defs/internal/BUILD
  tensorboard/defs/internal/js.bzl
  tensorboard/defs/internal/rxjs_shims.js
  tensorboard/webapp/BUILD
  tensorboard/webapp/bootstrap.ts
  tensorboard/webapp/dev_assets/BUILD
  tensorboard/webapp/testing/BUILD
Labels: cla: yes

#4621 graph: fix file upload control when no initial data loaded
  tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts
  tensorboard/plugins/graph/tf_graph_loader/tf-graph-dashboard-loader.ts
Labels: cla: yes

#4625 line chart: auto reset viewBox when scaleType
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
Labels: cla: yes

#4580 introduce py_repl() rule for a convenient Bazel-aware python shell
  tensorboard/BUILD
  tensorboard/defs/py_repl.bzl
Labels: cla: yes
