Repository tensorflow/tensorboard, pull requests merged in 2021-09, with the labels that each got.

#5281 app_routing: expose registered route kinds
  tensorboard/webapp/app_routing/actions/app_routing_actions.ts
  tensorboard/webapp/app_routing/effects/app_routing_effects.ts
  tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
  tensorboard/webapp/app_routing/route_registry_module.ts
  tensorboard/webapp/app_routing/store/app_routing_reducers.ts
  tensorboard/webapp/app_routing/store/app_routing_reducers_test.ts
  tensorboard/webapp/app_routing/store/app_routing_selectors.ts
  tensorboard/webapp/app_routing/store/app_routing_selectors_test.ts
  tensorboard/webapp/app_routing/store/app_routing_types.ts
  tensorboard/webapp/app_routing/store/testing.ts
Labels: cla: yes

#5283 color group: omit Experiments if comparison is impossible
  tensorboard/webapp/runs/views/runs_table/BUILD
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ng.html
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ts
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Labels: cla: yes

#5282 timeseries: add feature flag for butter bar
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
  tensorboard/webapp/feature_flag/testing.ts
  tensorboard/webapp/feature_flag/types.ts
Labels: cla: yes

#5280 color group: enable the feature
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
Labels: cla: yes

#5284 timeseries: draft of promo banner
  tensorboard/webapp/metrics/views/BUILD
  tensorboard/webapp/metrics/views/metrics_container.scss
  tensorboard/webapp/metrics/views/metrics_container.ts
  tensorboard/webapp/metrics/views/metrics_container_test.ts
  tensorboard/webapp/metrics/views/metrics_promo_notice_component.ng.html
  tensorboard/webapp/metrics/views/metrics_promo_notice_component.ts
  tensorboard/webapp/metrics/views/metrics_promo_notice_container.ts
  tensorboard/webapp/metrics/views/metrics_views_module.ts
Labels: cla: yes

#5288 util: separate out IsCloudPath from io_wrapper
  tensorboard/backend/event_processing/BUILD
  tensorboard/backend/event_processing/directory_watcher.py
  tensorboard/backend/event_processing/io_wrapper.py
  tensorboard/backend/event_processing/io_wrapper_test.py
  tensorboard/util/BUILD
  tensorboard/util/io_util.py
  tensorboard/util/io_util_test.py
Labels: core:backend, cla: yes

#5291 timeseries: second draft of TS promotion
  tensorboard/webapp/metrics/actions/index.ts
  tensorboard/webapp/metrics/views/BUILD
  tensorboard/webapp/metrics/views/metrics_container.scss
  tensorboard/webapp/metrics/views/metrics_container.ts
  tensorboard/webapp/metrics/views/metrics_container_test.ts
  tensorboard/webapp/metrics/views/metrics_promo_notice_component.ng.html
  tensorboard/webapp/metrics/views/metrics_promo_notice_component.scss
  tensorboard/webapp/metrics/views/metrics_promo_notice_component.ts
  tensorboard/webapp/metrics/views/metrics_promo_notice_container.ts
  tensorboard/webapp/metrics/views/metrics_promo_notice_types.ts
  tensorboard/webapp/metrics/views/metrics_views_module.ts
Labels: cla: yes

#5292 timeseries: make promo dismissable
  tensorboard/webapp/metrics/metrics_module.ts
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/store/metrics_selectors.ts
  tensorboard/webapp/metrics/store/metrics_selectors_test.ts
  tensorboard/webapp/metrics/store/metrics_types.ts
  tensorboard/webapp/metrics/testing.ts
  tensorboard/webapp/metrics/views/metrics_container.ts
  tensorboard/webapp/metrics/views/metrics_container_test.ts
  tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts
  tensorboard/webapp/persistent_settings/_data_source/types.ts
Labels: cla: yes

#5295 timeseries: implement "go to scalars"
  tensorboard/webapp/core/store/BUILD
  tensorboard/webapp/core/store/core_reducers.ts
  tensorboard/webapp/core/store/core_reducers_test.ts
Labels: cla: yes

#5290 timeseries: adjust wording of empty match warning
  tensorboard/webapp/metrics/views/main_view/empty_tag_match_message_component.ts
  tensorboard/webapp/metrics/views/main_view/main_view_test.ts
Labels: cla: yes, plugin:time-series

#5296 Use overflow-wrap on location data text.
  tensorboard/components/tf_runs_selector/tf-runs-selector.ts
Labels: core:frontend, cla: yes

#5298 timeseries: theme group control
  tensorboard/webapp/metrics/views/main_view/card_grid_component.scss
Labels: cla: yes

#5304 chore: remove instance of `/` in SASS
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
Labels: cla: yes

#5300 timeseries: fix tags not fetching issue when loading
  tensorboard/webapp/metrics/effects/index.ts
  tensorboard/webapp/metrics/effects/metrics_effects_test.ts
Labels: cla: yes

#5302 linked time: implement histogram color for linked time
  tensorboard/webapp/widgets/histogram/histogram_component.ng.html
  tensorboard/webapp/widgets/histogram/histogram_component.scss
  tensorboard/webapp/widgets/histogram/histogram_component.ts
  tensorboard/webapp/widgets/histogram/histogram_test.ts
Labels: cla: yes

#5307 linked time: render end range fob in histogram
  tensorboard/webapp/widgets/histogram/histogram_component.ng.html
  tensorboard/webapp/widgets/histogram/histogram_test.ts
Labels: cla: yes

#5248 gfile: add support for fsspec filesystems
  .github/workflows/ci.yml
  tensorboard/BUILD
  tensorboard/compat/tensorflow_stub/BUILD
  tensorboard/compat/tensorflow_stub/io/gfile.py
  tensorboard/compat/tensorflow_stub/io/gfile_fsspec_test.py
  tensorboard/pip_package/requirements_dev.txt
  tensorboard/summary/writer/BUILD
  tensorboard/summary/writer/event_file_writer_fsspec_test.py
Labels: core:backend, cla: yes, core:notf

#5308 linked time: clipping indicator on histogram
  tensorboard/webapp/metrics/testing.ts
  tensorboard/webapp/metrics/views/card_renderer/BUILD
  tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.scss
  tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/histogram_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/histogram_card_module.ts
  tensorboard/webapp/metrics/views/card_renderer/histogram_card_test.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/utils.ts
  tensorboard/webapp/metrics/views/card_renderer/vis_selected_time_clipped_component.scss
Labels: cla: yes

#5311 Add tf.stop_gradient in tf.summary.histogram
  tensorboard/plugins/histogram/summary_test.py
  tensorboard/plugins/histogram/summary_v2.py
Labels: cla: yes

#5313 hash: fix issues with the app router.
  tensorboard/webapp/core/views/hash_storage_component.ts
  tensorboard/webapp/core/views/hash_storage_test.ts
Labels: cla: yes

#5315 Update migrate.ipynb
  docs/migrate.ipynb
Labels: cla: yes

#5317 line chart: skip axis label render based on visibility
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_utils.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_utils_test.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ng.html
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view_test.ts
Labels: cla: yes

#5318 dark mode: Style link colors in both dark and light modes in polymer plugins.
  tensorboard/components/tf_dashboard_common/dashboard-style.ts
  tensorboard/components/tf_dashboard_common/tensorboard-color.ts
  tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts
  tensorboard/plugins/hparams/tf_hparams_main/tf-hparams-main.ts
Labels: cla: yes

#5319 timeseries: show relative time in tooltip
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
  tensorboard/webapp/metrics/views/card_renderer/utils_test.ts
Labels: cla: yes

#5325 timeseries: keep all digits for step values in scalar cards
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/formatter.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/formatter_test.ts
Labels: cla: yes

#5324 timeseries: hide pinned section while filtering
  tensorboard/webapp/metrics/views/main_view/main_view_component.ng.html
  tensorboard/webapp/metrics/views/main_view/main_view_component.scss
  tensorboard/webapp/metrics/views/main_view/main_view_test.ts
Labels: cla: yes

#5303 linked time: fix fob positioning on scalar
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
Labels: cla: yes

#5323 cleanup: log as a warning instead of an error when HParams-plugin experiment data is not found
  tensorboard/plugins/hparams/get_experiment.py
  tensorboard/plugins/hparams/hparams_plugin.py
  tensorboard/plugins/hparams/tf_hparams_query_pane/tf-hparams-query-pane.ts
Labels: type:cleanup, cla: yes

#5332 Revert "cleanup: log as a warning instead of an error when HParams-plugin experiment data is not found"
  tensorboard/plugins/hparams/get_experiment.py
  tensorboard/plugins/hparams/hparams_plugin.py
  tensorboard/plugins/hparams/tf_hparams_query_pane/tf-hparams-query-pane.ts
Labels: cla: yes

#5301 timeseries: Adjust scroll position after pagination
  tensorboard/webapp/metrics/views/main_view/BUILD
  tensorboard/webapp/metrics/views/main_view/card_grid_component.ng.html
  tensorboard/webapp/metrics/views/main_view/card_grid_component.ts
  tensorboard/webapp/metrics/views/main_view/card_grid_test.ts
Labels: cla: yes

#5335 sync: add missing cdk scrolling dep
  tensorboard/webapp/metrics/views/main_view/BUILD
Labels: cla: yes

#5330 blame: ignore Prettier 2.4.1 reformatting
  .git-blame-ignore-revs
Labels: cla: yes

#5338 runs: remember color by id instead of hex
  tensorboard/webapp/runs/store/BUILD
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
  tensorboard/webapp/runs/store/runs_selectors.ts
  tensorboard/webapp/runs/store/runs_selectors_test.ts
  tensorboard/webapp/runs/store/runs_types.ts
  tensorboard/webapp/runs/store/testing.ts
  tensorboard/webapp/util/BUILD
  tensorboard/webapp/util/ui_selectors.ts
  tensorboard/webapp/util/ui_selectors_test.ts
Labels: cla: yes

#5336 chore: update tsconfig to enable `--noImplicitOverride`
  tensorboard/components/polymer/dark_mode_mixin.ts
  tensorboard/components/tf_backend/requestManager.ts
  tensorboard/components/tf_backend/tf-backend-polymer.ts
  tensorboard/components/tf_color_scale/tf-color-scale-polymer.ts
  tensorboard/components/tf_dashboard_common/data-loader-behavior.ts
  tensorboard/components/tf_dashboard_common/tf-filterable-checkbox-list.ts
  tensorboard/components/tf_dashboard_common/tf-option-selector.ts
  tensorboard/components/tf_globals/globals-polymer.ts
  tensorboard/components/tf_line_chart_data_loader/tf-line-chart-data-loader.ts
  tensorboard/components/tf_markdown_view/tf-markdown-view.ts
  tensorboard/components/tf_paginated_view/tf-paginated-view-store.ts
  tensorboard/components/tf_runs_selector/tf-runs-selector.ts
  tensorboard/components/tf_storage/tf-storage-polymer.ts
  tensorboard/components/vz_chart_helpers/plottable-interactions.ts
  tensorboard/components/vz_chart_helpers/vz-chart-tooltip.ts
  tensorboard/components/vz_line_chart2/line-chart-exporter.ts
  tensorboard/components/vz_line_chart2/linear-scale.ts
  tensorboard/components/vz_line_chart2/log-scale.ts
  tensorboard/components/vz_line_chart2/tf-scale.ts
  tensorboard/components/vz_line_chart2/vz-line-chart2.ts
  tensorboard/plugins/audio/tf_audio_dashboard/tf-audio-loader.ts
  tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-margin-chart-card.ts
  tensorboard/plugins/custom_scalar/tf_custom_scalar_dashboard/tf-custom-scalar-multi-line-chart-card.ts
  tensorboard/plugins/distribution/vz_distribution_chart/vz-distribution-chart.ts
  tensorboard/plugins/graph/tf_graph/tf-graph-scene.ts
  tensorboard/plugins/graph/tf_graph/tf-graph.ts
  tensorboard/plugins/graph/tf_graph_common/render.ts
  tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts
  tensorboard/plugins/graph/tf_graph_info/tf-graph-info.ts
  tensorboard/plugins/graph/tf_graph_loader/tf-graph-dashboard-loader.ts
  tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.ts
  tensorboard/plugins/histogram/vz_histogram_timeseries/vz-histogram-timeseries.ts
  tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.ts
  tensorboard/plugins/text/tf_text_dashboard/tf-text-loader.ts
  tensorboard/webapp/app_routing/route_config.ts
  tensorboard/webapp/app_routing/testing.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/threejs_coordinator.ts
  tsconfig.json
Labels: cla: yes

#5339 feat: adds experiment id as one of the searchable
  tensorboard/webapp/types/ui.ts
Labels: cla: yes

#5337 histogram: cast tf.reduce_sum input to float64
  tensorboard/plugins/histogram/summary.py
  tensorboard/plugins/histogram/summary_test.py
  tensorboard/plugins/histogram/summary_v2.py
Labels: plugin:histogram, core:summaries, cla: yes

#5334 timeseries: match selection using same logic
  tensorboard/webapp/experiments/store/testing.ts
  tensorboard/webapp/runs/views/runs_table/BUILD
  tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
  tensorboard/webapp/util/BUILD
  tensorboard/webapp/util/matcher.ts
  tensorboard/webapp/util/matcher_test.ts
  tensorboard/webapp/util/ui_selectors.ts
  tensorboard/webapp/util/ui_selectors_test.ts
Labels: cla: yes

#5314 timeseries: show indication when there is a new pin
  tensorboard/webapp/metrics/views/main_view/main_view_test.ts
  tensorboard/webapp/metrics/views/main_view/pinned_view_component.scss
  tensorboard/webapp/metrics/views/main_view/pinned_view_component.ts
  tensorboard/webapp/metrics/views/main_view/pinned_view_container.ts
Labels: cla: yes

#5342 color: put ColorPalette as state and improve data structure
  tensorboard/webapp/feature_flag/store/testing.ts
  tensorboard/webapp/runs/views/runs_table/BUILD
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_container.ts
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_test.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
  tensorboard/webapp/settings/BUILD
  tensorboard/webapp/settings/_redux/BUILD
  tensorboard/webapp/settings/_redux/settings_selectors.ts
  tensorboard/webapp/settings/_redux/settings_types.ts
  tensorboard/webapp/settings/testing.ts
  tensorboard/webapp/util/BUILD
  tensorboard/webapp/util/colors.ts
  tensorboard/webapp/util/ui_selectors.ts
  tensorboard/webapp/util/ui_selectors_test.ts
Labels: cla: yes

#5345 sync: change data-id binding to attribute
  tensorboard/webapp/metrics/views/main_view/main_view_test.ts
  tensorboard/webapp/metrics/views/main_view/pinned_view_component.ts
Labels: cla: yes

#5344 run selector: subdue violent exception when hparams are invalid
  tensorboard/webapp/hparams/_redux/utils.ts
  tensorboard/webapp/hparams/_redux/utils_test.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Labels: cla: yes

#5346 sync: remove test that causes segmentation fault
  tensorboard/plugins/histogram/summary_test.py
Labels: cla: yes

#5341 cleanup: log as info when no hparams experiment data is found
  tensorboard/plugins/hparams/BUILD
  tensorboard/plugins/hparams/get_experiment.py
  tensorboard/plugins/hparams/hparams_plugin.py
Labels: type:cleanup, cla: yes

#5348 histogram: add back the test for large counts
  tensorboard/plugins/histogram/BUILD
  tensorboard/plugins/histogram/summary_test.py
Labels: cla: yes

#5350 histogram: add histogram_v3 skeleton
  tensorboard/plugins/histogram/summary_v2.py
Labels: plugin:histogram, core:summaries, cla: yes

#5353 Add owner field to experiment proto.
  tensorboard/uploader/proto/experiment.proto
Labels: cla: yes
