Repository tensorflow/tensorboard, pull requests merged in 2021-08, with the labels that each got.

#5170 router: expose getExperimentIdsFromRouteParams and getRouteId
  tensorboard/webapp/app_routing/store_only_utils.ts
  tensorboard/webapp/app_routing/store_only_utils_test.ts
Labels: cla: yes, core:frontend

#5172 widget: intersection observer directive
  tensorboard/webapp/BUILD
  tensorboard/webapp/widgets/intersection_observer/BUILD
  tensorboard/webapp/widgets/intersection_observer/intersection_observer_directive.ts
  tensorboard/webapp/widgets/intersection_observer/intersection_observer_module.ts
  tensorboard/webapp/widgets/intersection_observer/intersection_observer_test.ts
  tensorboard/webapp/widgets/intersection_observer/intersection_observer_testing_module.ts
Labels: cla: yes

#5175 lint: fix g3-no-void-expression lint failure
  tensorboard/webapp/widgets/intersection_observer/intersection_observer_directive.ts
Labels: cla: yes

#5171 feature flag: add "enableLinkTime"
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
  tensorboard/webapp/feature_flag/testing.ts
  tensorboard/webapp/feature_flag/types.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
Labels: cla: yes

#5174 histogram: prevent render while invisible.
  tensorboard/webapp/widgets/histogram/BUILD
  tensorboard/webapp/widgets/histogram/histogram_module.ts
  tensorboard/webapp/widgets/histogram/histogram_v2_component.ng.html
  tensorboard/webapp/widgets/histogram/histogram_v2_component.ts
  tensorboard/webapp/widgets/histogram/histogram_v2_test.ts
Labels: cla: yes

#5176 linked time: add basic data model
  tensorboard/webapp/metrics/actions/index.ts
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/store/metrics_selectors.ts
  tensorboard/webapp/metrics/store/metrics_selectors_test.ts
  tensorboard/webapp/metrics/store/metrics_types.ts
  tensorboard/webapp/metrics/testing.ts
Labels: cla: yes

#5180 Replace QueryParamsFeatureFlagDataSource.getParams() with injectable class.
  tensorboard/webapp/webapp_data_source/BUILD
  tensorboard/webapp/webapp_data_source/query_params.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_module.ts
Labels: cla: yes

#5179 Remove unnecessary statements in http_util.py.
  tensorboard/backend/http_util.py
Labels: cla: yes

#5186 time series: ignore case when matching tags
  tensorboard/webapp/metrics/views/main_view/filter_input_container.ts
  tensorboard/webapp/metrics/views/main_view/filter_input_test.ts
  tensorboard/webapp/metrics/views/main_view/filtered_view_container.ts
  tensorboard/webapp/metrics/views/main_view/main_view_test.ts
Labels: cla: yes

#5185 color group: improve visuals of the component
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog.ng.html
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.scss
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ts
Labels: cla: yes

#5190 core: OSS TensorBoard page title should be `TensorBoard`
  tensorboard/webapp/core/views/page_title_test.ts
  tensorboard/webapp/experiments/store/experiments_reducers.ts
Labels: cla: yes, core:frontend

#5163 Update README.md to include no-data example
  README.md
Labels: cla: yes

#5192 🍒: OSS TensorBoard page title should be `TensorBoard` (#5190)
  tensorboard/webapp/core/views/page_title_test.ts
  tensorboard/webapp/experiments/store/experiments_reducers.ts
Labels: cla: yes

#5182 linked time: scalar single time step visuals
  tensorboard/webapp/metrics/internal_types.ts
  tensorboard/webapp/metrics/store/metrics_selectors.ts
  tensorboard/webapp/metrics/store/metrics_types.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
Labels: cla: yes

#5183 router: add a registry module for unsaved experiment updates
  tensorboard/webapp/app_routing/BUILD
  tensorboard/webapp/app_routing/dirty_updates_registry_module.ts
  tensorboard/webapp/app_routing/dirty_updates_registry_module_test.ts
  tensorboard/webapp/app_routing/dirty_updates_registry_types.ts
  tensorboard/webapp/app_routing/store_only_utils.ts
  tensorboard/webapp/app_routing/types.ts
Labels: core:frontend, cla: yes

#5195 Pin compat protos to tensorflow v2.6.0-rc2.
  tensorboard/compat/proto/BUILD
  tensorboard/compat/proto/config.proto
  tensorboard/compat/proto/cpp_shape_inference.proto
  tensorboard/compat/proto/full_type.proto
  tensorboard/compat/proto/function.proto
  tensorboard/compat/proto/op_def.proto
  tensorboard/compat/proto/rewriter_config.proto
  tensorboard/compat/proto/saved_object_graph.proto
  tensorboard/compat/proto/struct.proto
  tensorboard/compat/proto/tensor.proto
  tensorboard/compat/proto/types.proto
  tensorboard/data/server/descriptor.bin
  tensorboard/data/server/tensorboard.pb.rs
Labels: cla: yes

#5193 docs: document the Time Series dashboard
  README.md
  tensorboard/plugins/metrics/README.md
  tensorboard/plugins/metrics/images/timeseries_frontend_component_hierarchy.png
  tensorboard/plugins/metrics/images/timeseries_ui.png
Labels: cla: yes

#5177 histogram: migrate to Angular histogram
  tensorboard/webapp/metrics/views/card_renderer/BUILD
  tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/histogram_card_module.ts
  tensorboard/webapp/metrics/views/card_renderer/histogram_card_test.ts
  tensorboard/webapp/widgets/histogram/BUILD
  tensorboard/webapp/widgets/histogram/histogram_component.ts
  tensorboard/webapp/widgets/histogram/histogram_module.ts
  tensorboard/webapp/widgets/histogram/histogram_test.ts
  tensorboard/webapp/widgets/histogram/histogram_v2_component.ts
  tensorboard/webapp/widgets/histogram/histogram_v2_test.ts
Labels: cla: yes

#5194 ui: increase width and allow long dropdown items to wrap
  tensorboard/webapp/widgets/dropdown/dropdown_component.scss
  tensorboard/webapp/widgets/dropdown/dropdown_component.ts
Labels: cla: yes

#5200 core: make reload dialog functional
  tensorboard/webapp/settings/_redux/settings_reducers.ts
  tensorboard/webapp/settings/_redux/settings_reducers_test.ts
  tensorboard/webapp/settings/_views/settings_dialog_component.ts
  tensorboard/webapp/settings/_views/settings_test.ts
Labels: cla: yes

#5206 cherry-pick: core: make reload dialog functional (#5200)
  tensorboard/webapp/settings/_redux/settings_reducers.ts
  tensorboard/webapp/settings/_redux/settings_reducers_test.ts
  tensorboard/webapp/settings/_views/settings_dialog_component.ts
  tensorboard/webapp/settings/_views/settings_test.ts
Labels: cla: yes

#5203 Improve error message for proto_test
  tensorboard/compat/proto/proto_test.py
Labels: cla: yes

#5199 color grouping: add data attribute to color grouping dropdown menu
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ng.html
Labels: cla: yes

#5201 color grouping: change tooltip wording
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ng.html
Labels: cla: yes

#5196 core: no data warning message UI fix
  tensorboard/webapp/plugins/plugins_component.scss
Labels: cla: yes

#5197 linked time: scalar: put fob on axis for selected step
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
Labels: cla: yes

#5209 range_input: fix floating point noise
  tensorboard/webapp/widgets/range_input/range_input_component.ts
  tensorboard/webapp/widgets/range_input/range_input_test.ts
Labels: cla: yes

#5210 linked time: range view for scalars
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
Labels: cla: yes

#5212 color group: show message when regex does not match anything
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog.ng.html
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.scss
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_container.ts
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_test.ts
Labels: cla: yes

#5216 router: support conditional navigations and empty experiment names
  tensorboard/webapp/app_routing/internal_utils.ts
  tensorboard/webapp/app_routing/internal_utils_test.ts
  tensorboard/webapp/app_routing/programmatical_navigation_module.ts
  tensorboard/webapp/app_routing/programmatical_navigation_module_test.ts
  tensorboard/webapp/app_routing/programmatical_navigation_types.ts
  tensorboard/webapp/app_routing/store_only_utils.ts
  tensorboard/webapp/app_routing/store_only_utils_test.ts
Labels: cla: yes

#5215 line chart: zoom instruction show on top of other
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.scss
Labels: cla: yes

#5218 color grouping: generate preview for example filling
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.ts
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_test.ts
Labels: cla: yes

#5208 linked time: settings on the right pane
  tensorboard/webapp/metrics/actions/index.ts
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/store/metrics_selectors.ts
  tensorboard/webapp/metrics/store/metrics_selectors_test.ts
  tensorboard/webapp/metrics/store/metrics_types.ts
  tensorboard/webapp/metrics/testing.ts
  tensorboard/webapp/metrics/views/right_pane/BUILD
  tensorboard/webapp/metrics/views/right_pane/right_pane_module.ts
  tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.scss
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
  tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
Labels: cla: yes

#5191 Fix PR curve plugin to display correct thresholds
  tensorboard/plugins/pr_curve/pr_curve_demo.py
  tensorboard/plugins/pr_curve/pr_curves_plugin.py
  tensorboard/plugins/pr_curve/pr_curves_plugin_test.py
  tensorboard/plugins/pr_curve/summary_test.py
Labels: cla: yes

#5202 color grouping: set non-matched runs to light gray
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
  tensorboard/webapp/util/colors.ts
Labels: cla: yes

#5221 timeseries: state for remembering vis filter
  tensorboard/webapp/metrics/actions/index.ts
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/store/metrics_selectors.ts
  tensorboard/webapp/metrics/store/metrics_selectors_test.ts
  tensorboard/webapp/metrics/store/metrics_types.ts
  tensorboard/webapp/metrics/testing.ts
Labels: cla: yes

#5224 sync: fix attr.disabled issue
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
Labels: cla: yes

#5222 timeseries: filter card by visualization
  tensorboard/webapp/metrics/views/main_view/BUILD
  tensorboard/webapp/metrics/views/main_view/card_groups_container.ts
  tensorboard/webapp/metrics/views/main_view/filter_input_container.ts
  tensorboard/webapp/metrics/views/main_view/filter_input_test.ts
  tensorboard/webapp/metrics/views/main_view/filtered_view_container.ts
  tensorboard/webapp/metrics/views/main_view/main_view_component.ng.html
  tensorboard/webapp/metrics/views/main_view/main_view_component.scss
  tensorboard/webapp/metrics/views/main_view/main_view_component.ts
  tensorboard/webapp/metrics/views/main_view/main_view_container.ts
  tensorboard/webapp/metrics/views/main_view/main_view_module.ts
  tensorboard/webapp/metrics/views/main_view/main_view_test.ts
Labels: cla: yes

#5217 color grouping: trap focus in the dialog
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog.ng.html
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.ts
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_container.ts
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_test.ts
Labels: cla: yes

#5230 app routing: fix case when there are no selectors on registry
  tensorboard/webapp/app_routing/effects/app_routing_effects.ts
  tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
Labels: cla: yes

#5229 chore: buildifier WORKSPACE file
  .github/workflows/ci.yml
  WORKSPACE
Labels: type:cleanup, cla: yes

#5232 app_routing: expose symbols
  tensorboard/webapp/app_routing/BUILD
  tensorboard/webapp/app_routing/index.ts
Labels: cla: yes

#5231 chore: require node.js 12.21.0
  WORKSPACE
Labels: cla: yes

#5220 linked time: range on sidebar step selector
  tensorboard/webapp/metrics/actions/index.ts
  tensorboard/webapp/metrics/internal_types.ts
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/store/metrics_selectors.ts
  tensorboard/webapp/metrics/store/metrics_selectors_test.ts
  tensorboard/webapp/metrics/store/metrics_types.ts
  tensorboard/webapp/metrics/testing.ts
  tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
  tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
Labels: cla: yes

#5233 linked time: marker when extent is outside of linked time
  tensorboard/webapp/metrics/testing.ts
  tensorboard/webapp/metrics/views/card_renderer/BUILD
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.scss
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_module.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/metrics/views/card_renderer/vis_selected_time_clipped_component.scss
  tensorboard/webapp/metrics/views/card_renderer/vis_selected_time_clipped_component.ts
  tensorboard/webapp/metrics/views/card_renderer/vis_selected_time_clipped_module.ts
Labels: cla: yes

#5234 timeseries: improve card observer visibility logic with element ids
  tensorboard/webapp/metrics/actions/BUILD
  tensorboard/webapp/metrics/actions/index.ts
  tensorboard/webapp/metrics/effects/BUILD
  tensorboard/webapp/metrics/effects/metrics_effects_test.ts
  tensorboard/webapp/metrics/store/BUILD
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/store/metrics_selectors.ts
  tensorboard/webapp/metrics/store/metrics_selectors_test.ts
  tensorboard/webapp/metrics/store/metrics_types.ts
  tensorboard/webapp/metrics/testing.ts
  tensorboard/webapp/metrics/views/card_renderer/BUILD
  tensorboard/webapp/metrics/views/card_renderer/card_lazy_loader.ts
  tensorboard/webapp/metrics/views/card_renderer/card_lazy_loader_test.ts
  tensorboard/webapp/metrics/views/main_view/main_view_test.ts
  tensorboard/webapp/util/dom.ts
Labels: cla: yes

#5235 timeseries: fix visibility bug on filtered scalar cards
  tensorboard/webapp/metrics/views/card_renderer/BUILD
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_module.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
Labels: cla: yes

#5238 chore: upgrade dependencies
  .github/workflows/ci.yml
  WORKSPACE
  package.json
  tensorboard/components/polymer/legacy_class.ts
  tensorboard/plugins/mesh/tf_mesh_dashboard/BUILD
  tensorboard/webapp/alert/views/alert_snackbar_container.ts
  tensorboard/webapp/app_routing/route_contexted_reducer_helper.ts
  tensorboard/webapp/core/core_module.ts
  tensorboard/webapp/core/effects/core_effects_test.ts
  tensorboard/webapp/feature_flag/effects/feature_flag_effects.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/hparams/_redux/hparams_selectors.ts
  tensorboard/webapp/metrics/views/card_renderer/data_download_dialog_container.ts
  tensorboard/webapp/metrics/views/card_renderer/image_card_container.ts
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/metric_arithmetic_element_component.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
  tensorboard/webapp/settings/_views/polymer_interop_container.ts
  tensorboard/webapp/settings/_views/settings_dialog_component.ts
  tensorboard/webapp/settings/settings_module.ts
  tensorboard/webapp/widgets/intersection_observer/intersection_observer_directive.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/BUILD
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_interactive_view.ts
  tensorboard/webapp/widgets/range_input/range_input_component.ts
  tensorboard/webapp/widgets/resize_detector_directive.ts
  tensorboard/webapp/widgets/source_code/monaco/BUILD
  yarn.lock
Labels: cla: yes

#5241 test: drop stray debugger statement
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_test.ts
Labels: cla: yes

#5237 line chart: introduce onContextLost renderer callback
  tensorboard/webapp/widgets/line_chart_v2/lib/chart.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/chart_types.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/integration_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/message_types.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart_bridge.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart_test.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
Labels: cla: yes

#5240 notification: clip the date to today
  tensorboard/webapp/notification_center/_data_source/notification_center_data_source.ts
  tensorboard/webapp/notification_center/_data_source/notification_center_data_source_test.ts
  tensorboard/webapp/notification_center/_data_source/testing.ts
Labels: cla: yes

#5244 linked time: clip axis UI from leaving bound
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.scss
Labels: cla: yes

#5249 time series: deduplicate tags in the search
  tensorboard/webapp/metrics/views/main_view/filter_input_container.ts
  tensorboard/webapp/metrics/views/main_view/filter_input_test.ts
Labels: cla: yes

#5239 line chart: recreate charts upon fatal renderer errors
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
Labels: cla: yes

#5236 timeseries: persist tag filter in the URL
  tensorboard/webapp/metrics/internal_types.ts
  tensorboard/webapp/metrics/store/BUILD
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/routes/BUILD
  tensorboard/webapp/routes/dashboard_deeplink_provider.ts
  tensorboard/webapp/routes/dashboard_deeplink_provider_test.ts
  tensorboard/webapp/routes/dashboard_deeplink_provider_types.ts
  tensorboard/webapp/routes/testing.ts
Labels: cla: yes

#5242 ui: fix wrapping of dropdown items
  tensorboard/webapp/widgets/dropdown/dropdown_component.scss
  tensorboard/webapp/widgets/dropdown/dropdown_component.ts
Labels: cla: yes

#5252 timeseries: run selection based on regex filter
  tensorboard/webapp/runs/actions/runs_actions.ts
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
  tensorboard/webapp/util/ui_selectors.ts
  tensorboard/webapp/util/ui_selectors_test.ts
Labels: cla: yes

#5254 timeseries: fix memory leaks involving CardObserver and shareReplay
  tensorboard/webapp/metrics/views/card_renderer/card_lazy_loader.ts
  tensorboard/webapp/metrics/views/card_renderer/image_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/metrics/views/main_view/card_grid_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
Labels: cla: yes

#5250 time series: show sample on image
  tensorboard/webapp/metrics/internal_types.ts
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/views/card_renderer/image_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/image_card_component.scss
  tensorboard/webapp/metrics/views/card_renderer/image_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/image_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/image_card_test.ts
Labels: cla: yes

#5255 timeseries: show pinned view while filtering
  tensorboard/webapp/metrics/views/_common.scss
  tensorboard/webapp/metrics/views/main_view/card_groups_component.scss
  tensorboard/webapp/metrics/views/main_view/filtered_view_component.scss
  tensorboard/webapp/metrics/views/main_view/main_view_component.ng.html
  tensorboard/webapp/metrics/views/main_view/main_view_component.scss
  tensorboard/webapp/metrics/views/main_view/main_view_test.ts
  tensorboard/webapp/metrics/views/main_view/pinned_view_component.scss
Labels: cla: yes

#5260 histogram: pass color instead of scale
  tensorboard/webapp/metrics/views/card_renderer/histogram_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/histogram_card_test.ts
  tensorboard/webapp/widgets/histogram/histogram_v2_component.ts
  tensorboard/webapp/widgets/histogram/histogram_v2_test.ts
Labels: cla: yes

#5259 histogram: rename from v2 to plain
  tensorboard/webapp/widgets/histogram/BUILD
  tensorboard/webapp/widgets/histogram/histogram_component.ng.html
  tensorboard/webapp/widgets/histogram/histogram_component.scss
  tensorboard/webapp/widgets/histogram/histogram_component.ts
  tensorboard/webapp/widgets/histogram/histogram_module.ts
  tensorboard/webapp/widgets/histogram/histogram_test.ts
Labels: cla: yes

#5258 styles: TimeSeries UI improvements
  tensorboard/webapp/metrics/views/_common.scss
  tensorboard/webapp/metrics/views/main_view/main_view_component.scss
  tensorboard/webapp/runs/views/runs_table/runs_table_component.scss
  tensorboard/webapp/theme/_tb_theme.template.scss
Labels: cla: yes

#5262 timeseries: improve first paint
  tensorboard/webapp/metrics/views/card_renderer/BUILD
  tensorboard/webapp/metrics/views/card_renderer/card_renderer_module.ts
  tensorboard/webapp/metrics/views/card_renderer/card_view_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/card_view_component.ts
  tensorboard/webapp/metrics/views/card_renderer/card_view_container.ts
  tensorboard/webapp/metrics/views/card_renderer/card_view_test.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/metrics/views/main_view/card_grid_component.scss
Labels: cla: yes

#5251 Allow `google-auth < 3`
  tensorboard/pip_package/requirements.txt
Labels: cla: yes

#5261 histogram: use `transform` to prevent repaint
  tensorboard/webapp/widgets/histogram/histogram_component.ng.html
  tensorboard/webapp/widgets/histogram/histogram_component.scss
  tensorboard/webapp/widgets/histogram/histogram_component.ts
  tensorboard/webapp/widgets/histogram/histogram_test.ts
Labels: cla: yes

#5263 timeseries: improve tag filtering
  tensorboard/webapp/metrics/views/main_view/card_groups_component.ts
  tensorboard/webapp/metrics/views/main_view/filter_input_component.ng.html
  tensorboard/webapp/metrics/views/main_view/filter_input_component.scss
  tensorboard/webapp/metrics/views/main_view/filter_input_container.ts
  tensorboard/webapp/metrics/views/main_view/filter_input_test.ts
  tensorboard/webapp/metrics/views/main_view/filtered_view_component.ts
  tensorboard/webapp/metrics/views/main_view/filtered_view_container.ts
  tensorboard/webapp/theme/_tb_theme.template.scss
Labels: cla: yes

#5265 timeseries: debounce tag filter changes
  tensorboard/webapp/metrics/views/main_view/filtered_view_container.ts
  tensorboard/webapp/metrics/views/main_view/main_view_test.ts
Labels: cla: yes

#5266 bug: prevent scrollbar when angular dialog presents
  tensorboard/webapp/theme/_tb_theme.template.scss
Labels: cla: yes

#5268 widget: support margin on IntersectionObserver
  tensorboard/webapp/metrics/views/card_renderer/card_view_container.ts
  tensorboard/webapp/widgets/intersection_observer/BUILD
  tensorboard/webapp/widgets/intersection_observer/intersection_observer_directive.ts
  tensorboard/webapp/widgets/intersection_observer/intersection_observer_test.ts
Labels: cla: yes

#5275 router: do not warn users about dirty updates on the same page
  tensorboard/webapp/app_routing/effects/app_routing_effects.ts
  tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
Labels: core:frontend, cla: yes

#5276 infra: upgrade TypeScript to 4.4.2.
  package.json
  tensorboard/components/experimental/plugin_util/message.ts
  tensorboard/plugins/graph/tf_graph_common/minimap.ts
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/threejs_renderer.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/BUILD
  tensorboard/webapp/widgets/line_chart_v2/lib/worker/worker_chart.ts
  yarn.lock
Labels: cla: yes

#5277 infra: upgrade rules_sass deps
  WORKSPACE
Labels: cla: yes

#5278 infra: upgrade `@angular/material`
  package.json
  tensorboard/defs/defs.bzl
  tensorboard/webapp/BUILD
  yarn.lock
Labels: cla: yes
