Repository tensorflow/tensorboard, pull requests merged in 2021-03, with the labels that each got.

#4692 whats-new: notification component initial structure
  tensorboard/webapp/notification_center/BUILD
  tensorboard/webapp/notification_center/_notification_center_module.ts
  tensorboard/webapp/notification_center/_redux/BUILD
  tensorboard/webapp/notification_center/_redux/notification_center_actions.ts
  tensorboard/webapp/notification_center/_redux/notification_center_effects.ts
  tensorboard/webapp/notification_center/_redux/notification_center_reducers.ts
  tensorboard/webapp/notification_center/_redux/notification_center_reducers_test.ts
  tensorboard/webapp/notification_center/_redux/notification_center_selectors.ts
  tensorboard/webapp/notification_center/_redux/notification_center_selectors_test.ts
  tensorboard/webapp/notification_center/_redux/notification_center_types.ts
  tensorboard/webapp/notification_center/_views/BUILD
  tensorboard/webapp/notification_center/_views/notification_center_component.ng.html
  tensorboard/webapp/notification_center/_views/notification_center_component.scss
  tensorboard/webapp/notification_center/_views/notification_center_component.ts
  tensorboard/webapp/notification_center/_views/notification_center_container.ts
  tensorboard/webapp/notification_center/_views/view_types.ts
  tensorboard/webapp/notification_center/_views/views_module.ts
  tensorboard/webapp/notification_center/types.ts
Labels: cla: yes

#4699 timeseries: implement runs x-axis splitter
  tensorboard/webapp/metrics/views/card_renderer/BUILD
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
  tensorboard/webapp/metrics/views/card_renderer/utils.ts
  tensorboard/webapp/metrics/views/card_renderer/utils_test.ts
Labels: cla: yes

#4714 what's new: export notification module through index.js
  tensorboard/webapp/notification_center/BUILD
  tensorboard/webapp/notification_center/index.ts
Labels: cla: yes

#4683 [npmi] umap
  tensorboard/defs/defs.bzl
  tensorboard/defs/internal/js.bzl
  tensorboard/webapp/BUILD
  tensorboard/webapp/plugins/npmi/actions/npmi_actions.ts
  tensorboard/webapp/plugins/npmi/data_source/BUILD
  tensorboard/webapp/plugins/npmi/data_source/npmi_data_source.ts
  tensorboard/webapp/plugins/npmi/data_source/npmi_data_source_test.ts
  tensorboard/webapp/plugins/npmi/effects/npmi_effects_test.ts
  tensorboard/webapp/plugins/npmi/store/BUILD
  tensorboard/webapp/plugins/npmi/store/npmi_reducers.ts
  tensorboard/webapp/plugins/npmi/store/npmi_reducers_test.ts
  tensorboard/webapp/plugins/npmi/store/npmi_selectors.ts
  tensorboard/webapp/plugins/npmi/store/npmi_selectors_test.ts
  tensorboard/webapp/plugins/npmi/store/npmi_types.ts
  tensorboard/webapp/plugins/npmi/testing/BUILD
  tensorboard/webapp/plugins/npmi/testing/index.ts
  tensorboard/webapp/plugins/npmi/util/BUILD
  tensorboard/webapp/plugins/npmi/util/sort_annotations.ts
  tensorboard/webapp/plugins/npmi/util/sort_annotations_test.ts
  tensorboard/webapp/plugins/npmi/util/umap.ts
  tensorboard/webapp/plugins/npmi/util/umap_test.ts
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_container.ts
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/metric_arithmetic_element_container.ts
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/metric_arithmetic_element_test.ts
  tensorboard/webapp/testing/require_js_karma_config.js
Labels: cla: yes

#4717 graph: fix TS types for SlimGraph, Hierarchy, RenderGraphInfo usage
  tensorboard/plugins/graph/tf_graph/tf-graph.ts
  tensorboard/plugins/graph/tf_graph_app/BUILD
  tensorboard/plugins/graph/tf_graph_app/tf-graph-app.ts
  tensorboard/plugins/graph/tf_graph_board/tf-graph-board.ts
  tensorboard/plugins/graph/tf_graph_common/hierarchy.ts
  tensorboard/plugins/graph/tf_graph_common/render.ts
  tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts
  tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts
  tensorboard/plugins/graph/tf_graph_debugger_data_card/tf-graph-debugger-data-card.ts
  tensorboard/plugins/graph/tf_graph_info/tf-graph-info.ts
  tensorboard/plugins/graph/tf_graph_loader/tf-graph-dashboard-loader.ts
  tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.ts
Labels: cla: yes

#4719 npmi: tweak typing for sync
  tensorboard/webapp/plugins/npmi/util/umap_test.ts
Labels: cla: yes

#4721 line chart: extract HTML and style from axis
  tensorboard/webapp/widgets/line_chart_v2/sub_view/BUILD
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ng.html
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.scss
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts
Labels: cla: yes

#4711 line chart: support manual extent changes
  tensorboard/webapp/BUILD
  tensorboard/webapp/angular/BUILD
  tensorboard/webapp/testing/mat_icon_module.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ng.html
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/BUILD
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ng.html
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.scss
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view_test.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/sub_view_module.ts
  third_party/js.bzl
Labels: cla: yes

#4716 what's new: notification center icon and menu basic view
  tensorboard/webapp/notification_center/_views/BUILD
  tensorboard/webapp/notification_center/_views/notification_center_component.ng.html
  tensorboard/webapp/notification_center/_views/views_module.ts
Labels: cla: yes

#4718 Add ipynb tutorial for text summaries
  docs/text_summaries.ipynb
Labels: cla: yes, plugin:text, type:docs

#4730 sync: add cdk_testing_testbed and menu_testing
  tensorboard/webapp/angular/BUILD
  tensorboard/webapp/widgets/line_chart_v2/sub_view/BUILD
Labels: cla: yes

#4731 npmi: remove vz_projector dependency
  tensorboard/plugins/projector/vz_projector/BUILD
  tensorboard/webapp/plugins/npmi/util/BUILD
  tensorboard/webapp/plugins/npmi/util/umap.ts
Labels: cla: yes

#4722 Add a toggle that turns automatic high-degree node extraction off
  tensorboard/plugins/graph/tf_graph/tf-graph.ts
  tensorboard/plugins/graph/tf_graph_app/tf-graph-app.ts
  tensorboard/plugins/graph/tf_graph_board/tf-graph-board.ts
  tensorboard/plugins/graph/tf_graph_common/render.ts
  tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts
  tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts
Labels: cla: yes

#4726 rust: implement tensor RPCs and client
  tensorboard/data/BUILD
  tensorboard/data/grpc_provider.py
  tensorboard/data/grpc_provider_test.py
  tensorboard/data/server/server.rs
Labels: cla: yes, core:rustboard

#4734 rust: implement data_compat.rs basic tensor support
  tensorboard/data/server/data_compat.rs
  tensorboard/data/server/run.rs
  tensorboard/data/server/writer.rs
Labels: cla: yes, core:rustboard

#4735 rust: interpret summaries with no value as null tensors
  tensorboard/data/server/run.rs
Labels: cla: yes, core:rustboard

#4738 graph: fix `NotFoundError` typo
  tensorboard/plugins/graph/BUILD
  tensorboard/plugins/graph/graphs_plugin.py
  tensorboard/plugins/graph/graphs_plugin_test.py
Labels: cla: yes, plugin:graph, type:bug

#4739 rust: add `to_le_bytes!` macro for generating tensor_content fields
  tensorboard/data/server/data_compat.rs
Labels: cla: yes, core:rustboard

#4733 runs table: support hparam and metrics sorting
  tensorboard/webapp/runs/actions/runs_actions.ts
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
  tensorboard/webapp/runs/store/runs_selectors.ts
  tensorboard/webapp/runs/store/runs_selectors_test.ts
  tensorboard/webapp/runs/store/runs_types.ts
  tensorboard/webapp/runs/store/testing.ts
  tensorboard/webapp/runs/types.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Labels: cla: yes

#4724 graph: minor type fixes for ColorBy, templateIndex (1)
  tensorboard/plugins/graph/tf_graph/tf-graph-scene.ts
  tensorboard/plugins/graph/tf_graph/tf-graph.ts
  tensorboard/plugins/graph/tf_graph_board/tf-graph-board.ts
  tensorboard/plugins/graph/tf_graph_common/BUILD
  tensorboard/plugins/graph/tf_graph_common/node.ts
  tensorboard/plugins/graph/tf_graph_common/tf-graph-scene.ts
  tensorboard/plugins/graph/tf_graph_common/tf-node-icon.ts
  tensorboard/plugins/graph/tf_graph_common/view_types.ts
  tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts
  tensorboard/plugins/graph/tf_graph_info/tf-graph-info.ts
  tensorboard/plugins/graph/tf_graph_info/tf-node-info.ts
  tensorboard/plugins/graph/tf_graph_info/tf-node-list-item.ts
  tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-list-item.ts
Labels: cla: yes

#4725 graph: refactor Hierarchy, GraphOptions (2)
  tensorboard/plugins/graph/tf_graph/tf-graph.ts
  tensorboard/plugins/graph/tf_graph_board/tf-graph-board.ts
  tensorboard/plugins/graph/tf_graph_common/graph.ts
  tensorboard/plugins/graph/tf_graph_common/hierarchy.ts
  tensorboard/plugins/graph/tf_graph_common/loader.ts
  tensorboard/plugins/graph/tf_graph_common/node.ts
  tensorboard/plugins/graph/tf_graph_common/render.ts
  tensorboard/plugins/graph/tf_graph_common/template.ts
  tensorboard/plugins/graph/tf_graph_info/tf-graph-info.ts
  tensorboard/plugins/graph/tf_graph_loader/tf-graph-dashboard-loader.ts
  tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.ts
Labels: cla: yes

#4740 rust: support legacy TF 1.x histogram summaries
  tensorboard/data/server/data_compat.rs
Labels: cla: yes, core:rustboard

#4749 rust: add `prost-types` dependency
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  tensorboard/data/server/cargo/BUILD.bazel
  third_party/rust/remote/BUILD.prost-types-0.7.0.bazel
Labels: cla: yes, core:rustboard, dependencies

#4748 graph: fix pixelated SVG for Chromium
  tensorboard/plugins/graph/tf_graph/tf-graph-scene.html.ts
Labels: cla: yes

#4750 data_provider: add `GetExperiment` RPC
  tensorboard/data/proto/data_provider.proto
  tensorboard/data/server/BUILD
  tensorboard/data/server/DEVELOPMENT.md
  tensorboard/data/server/server.rs
  tensorboard/data/server/tensorboard.data.pb.rs
Labels: cla: yes, core:rustboard

#4751 rust: implement data location
  tensorboard/data/grpc_provider.py
  tensorboard/data/grpc_provider_test.py
  tensorboard/data/provider.py
  tensorboard/data/provider_test.py
  tensorboard/data/server/cli.rs
  tensorboard/data/server/server.rs
Labels: cla: yes, core:rustboard

#4727 line chart: improve major axis render
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ng.html
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.scss
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view_test.ts
Labels: cla: yes

#4756 server_ingester: perform tilde expansion on logdir
  tensorboard/data/server_ingester.py
  tensorboard/data/server_ingester_test.py
Labels: cla: yes, core:backend

#4741 graph: notify consumers when Hierarchy's templates update (3)
  tensorboard/plugins/graph/tf_graph/tf-graph-scene.ts
  tensorboard/plugins/graph/tf_graph/tf-graph.ts
  tensorboard/plugins/graph/tf_graph_common/hierarchy.ts
  tensorboard/plugins/graph/tf_graph_common/util.ts
  tensorboard/plugins/graph/tf_graph_info/tf-node-info.ts
  tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.ts
Labels: cla: yes

#4754 rust: support unbounded reservoirs
  tensorboard/data/server/cli.rs
  tensorboard/data/server/reservoir.rs
  tensorboard/data/server/run.rs
  tensorboard/data/server/types.rs
  tensorboard/data/server_ingester.py
  tensorboard/data/server_ingester_test.py
Labels: cla: yes, core:rustboard

#4742 graph: color large graphs by 'none' instead of 'structure' by default (4)
  tensorboard/components/tb_debug/types.ts
  tensorboard/plugins/graph/tf_graph_app/tf-graph-app.ts
  tensorboard/plugins/graph/tf_graph_board/tf-graph-board.ts
  tensorboard/plugins/graph/tf_graph_common/common_test.ts
  tensorboard/plugins/graph/tf_graph_common/hierarchy.ts
  tensorboard/plugins/graph/tf_graph_common/node.ts
  tensorboard/plugins/graph/tf_graph_common/view_types.ts
  tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts
  tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts
Labels: cla: yes

#4760 sync: fix graph symbols exported improperly
  tensorboard/plugins/graph/tf_graph/tf-graph-scene.ts
  tensorboard/plugins/graph/tf_graph/tf-graph.ts
  tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts
Labels: cla: yes

#4753 infra: allow SVG assets to be composed
  tensorboard/defs/defs.bzl
  tensorboard/tools/BUILD
  tensorboard/tools/mat_bundle_icon_svg.py
  tensorboard/tools/mat_bundle_icon_svg.sh
  tensorboard/tools/mat_bundle_icon_svg_test.py
Labels: cla: yes

#4762 default: switch to `EntryPoint.resolve`
  tensorboard/default.py
  tensorboard/default_test.py
Labels: cla: yes, type:build/install

#4759 graph: fix PNG download button
  tensorboard/plugins/graph/tf_graph/tf-graph-scene.ts
  tensorboard/plugins/graph/tf_graph/tf-graph.ts
  tensorboard/plugins/graph/tf_graph_app/tf-graph-app.ts
  tensorboard/plugins/graph/tf_graph_board/tf-graph-board.ts
  tensorboard/plugins/graph/tf_graph_common/minimap.ts
  tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts
  tensorboard/plugins/graph/tf_graph_dashboard/tf-graph-dashboard.ts
Labels: cla: yes

#4763 accumulator: ignore first `SessionLog.START` event
  tensorboard/backend/event_processing/plugin_event_accumulator.py
  tensorboard/backend/event_processing/plugin_event_accumulator_test.py
Labels: cla: yes, core:backend, type:bug

#4764 tensorboard-data-server 0.4.0
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  tensorboard/data/server/lib.rs
  tensorboard/data/server/pip_package/tensorboard_data_server/__init__.py
Labels: cla: yes, core:rustboard

#4755 core: dump some debug info in `/data/environment`
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/data/grpc_provider.py
  tensorboard/default.py
  tensorboard/http_api.md
  tensorboard/plugins/core/BUILD
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
Labels: cla: yes, core:backend, theme:usability

#4746 [npmi] Simplified UMAP Data Structure
  tensorboard/webapp/plugins/npmi/data_source/npmi_data_source.ts
  tensorboard/webapp/plugins/npmi/testing/index.ts
  tensorboard/webapp/plugins/npmi/util/sort_annotations_test.ts
  tensorboard/webapp/plugins/npmi/util/umap.ts
  tensorboard/webapp/plugins/npmi/util/umap_test.ts
Labels: cla: yes

#4776 histogram: remove unnecessary downsampling
  tensorboard/plugins/histogram/histograms_plugin.py
Labels: cla: yes, plugin:histogram, type:cleanup

#4758 line chart: conditionally disable fit to domain
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component.ts
  tensorboard/webapp/widgets/line_chart_v2/line_chart_component_test.ts
Labels: cla: yes

#4772 Typo
  docs/image_summaries.ipynb
Labels: cla: yes

#4773 cli: add `--load_fast=auto` option
  tensorboard/data/server/DEVELOPMENT.md
  tensorboard/data/server_ingester.py
  tensorboard/data/server_ingester_test.py
  tensorboard/plugins/core/core_plugin.py
  tensorboard/program.py
Labels: cla: yes, core:backend, core:rustboard

#4778 data: make metadata required, providing defaults
  tensorboard/data/dispatching_provider_test.py
  tensorboard/data/grpc_provider.py
  tensorboard/data/grpc_provider_test.py
  tensorboard/data/provider.py
  tensorboard/data/provider_test.py
Labels: cla: yes, core:backend

#4780 data: add data location to experiment metadata
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/backend/event_processing/data_provider_test.py
  tensorboard/data/grpc_provider.py
  tensorboard/data/provider.py
  tensorboard/data/provider_test.py
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
Labels: cla: yes, core:backend

#4775 mesh: add generic data support
  tensorboard/BUILD
  tensorboard/data/server/data_compat.rs
  tensorboard/dataclass_compat.py
  tensorboard/plugins/mesh/BUILD
  tensorboard/plugins/mesh/mesh_plugin.py
  tensorboard/plugins/mesh/mesh_plugin_test.py
Labels: cla: yes, core:rustboard, plugin:mesh

#4779 npmi: fix the undefined in the selector
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_component.ng.html
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_component.ts
Labels: cla: yes

#4728 line chart: improve small number on linear scale
  tensorboard/webapp/widgets/line_chart_v2/lib/scale.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/BUILD
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_utils.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_utils_test.ts
  tensorboard/webapp/widgets/line_chart_v2/sub_view/line_chart_axis_view.ts
Labels: cla: yes

#4774 custom_scalar: add generic data support
  tensorboard/BUILD
  tensorboard/data/server/data_compat.rs
  tensorboard/dataclass_compat.py
  tensorboard/plugins/custom_scalar/BUILD
  tensorboard/plugins/custom_scalar/custom_scalars_plugin.py
  tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
Labels: cla: yes, core:rustboard, plugin:custom-scalars

#4768 what's new: test boilerplate for _view/
  tensorboard/webapp/notification_center/BUILD
  tensorboard/webapp/notification_center/_views/BUILD
  tensorboard/webapp/notification_center/_views/notification_center_component.ng.html
  tensorboard/webapp/notification_center/_views/notification_center_test.ts
  tensorboard/webapp/testing/mat_icon_module.ts
Labels: cla: yes

#4785 cli: note when data server is used implicitly
  tensorboard/program.py
Labels: cla: yes, core:rustboard, theme:usability

#4786 cli: detect filesystems for `--load_fast=auto`
  tensorboard/program.py
  tensorboard/program_test.py
Labels: cla: yes, core:rustboard, theme:usability

#4791 sync: fix `@ngrx/store/testing` import
  tensorboard/webapp/notification_center/_views/BUILD
Labels: cla: yes, type:build/install

#4790 data: pass `--samples-per-plugin` unconditionally
  tensorboard/data/server_ingester.py
  tensorboard/data/server_ingester_test.py
Labels: cla: yes, core:rustboard, type:cleanup

#4788 rust: improve GCS credential error handling
  tensorboard/data/server/cli/dynamic_logdir.rs
  tensorboard/data/server/gcs/auth.rs
  tensorboard/data/server/gcs/gsutil.rs
Labels: cla: yes, core:rustboard, theme:usability

#4793 rust: improve startup error handling
  tensorboard/data/server/cli.rs
  tensorboard/data/server/cli/dynamic_logdir.rs
  tensorboard/data/server/gcs.rs
  tensorboard/data/server/gcs/auth.rs
  tensorboard/data/server/gcs/client.rs
Labels: cla: yes, core:rustboard, theme:usability

#4794 program: fall back from data server to multiplexer
  tensorboard/data/BUILD
  tensorboard/data/server_ingester.py
  tensorboard/data/server_ingester_test.py
  tensorboard/plugins/core/core_plugin.py
  tensorboard/program.py
  tensorboard/program_test.py
Labels: cla: yes, core:rustboard, theme:usability

#4792 tensorboard-data-server 0.5.0
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  tensorboard/data/server/lib.rs
  tensorboard/data/server/pip_package/tensorboard_data_server/__init__.py
Labels: cla: yes

#4806 pip: require tensorboard-data-server 0.5.0
  tensorboard/pip_package/requirements.txt
Labels: cla: yes

#4807 ci: install TensorBoard deps after TensorFlow
  .github/workflows/ci.yml
Labels: cla: yes, type:build/install

#4804 rust: support and default to `--host localhost`
  tensorboard/data/server/cli.rs
Labels: cla: yes, core:rustboard

#4797 docs: update `tf.summary.text()`
  tensorboard/plugins/text/summary_v2.py
Labels: cla: yes

#4796 docs: update `tf.summary.scalar()`
  tensorboard/plugins/scalar/summary_v2.py
Labels: cla: yes

#4810 tensorboard-data-server 0.6.0
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  tensorboard/data/server/lib.rs
  tensorboard/data/server/pip_package/tensorboard_data_server/__init__.py
Labels: cla: yes, core:rustboard

#4812 pip: require tensorboard-data-server 0.6.0
  tensorboard/pip_package/requirements.txt
Labels: cla: yes, core:rustboard, type:build/install

#4805 what's new: display red dot when there are unread messages
  tensorboard/webapp/notification_center/_redux/BUILD
  tensorboard/webapp/notification_center/_redux/notification_center_reducers.ts
  tensorboard/webapp/notification_center/_redux/notification_center_reducers_test.ts
  tensorboard/webapp/notification_center/_redux/notification_center_selectors.ts
  tensorboard/webapp/notification_center/_redux/notification_center_selectors_test.ts
  tensorboard/webapp/notification_center/_redux/notification_center_types.ts
  tensorboard/webapp/notification_center/_redux/testing.ts
  tensorboard/webapp/notification_center/_views/BUILD
  tensorboard/webapp/notification_center/_views/notification_center_component.ng.html
  tensorboard/webapp/notification_center/_views/notification_center_component.scss
  tensorboard/webapp/notification_center/_views/notification_center_component.ts
  tensorboard/webapp/notification_center/_views/notification_center_container.ts
  tensorboard/webapp/notification_center/_views/notification_center_test.ts
  tensorboard/webapp/notification_center/_views/view_types.ts
Labels: cla: yes

#4787 graph: ui polish for sidepane controls
  tensorboard/plugins/graph/tf_graph_controls/tf-graph-controls.ts
  tensorboard/plugins/graph/tf_graph_node_search/tf-graph-node-search.ts
Labels: cla: yes

#4809 program: fix data server advisory message
  tensorboard/program.py
Labels: cla: yes, core:rustboard, type:bug

#4815 timeseries: customizable settings w/ DI
  tensorboard/webapp/BUILD
  tensorboard/webapp/angular/BUILD
  tensorboard/webapp/metrics/BUILD
  tensorboard/webapp/metrics/metrics_integration_test.ts
  tensorboard/webapp/metrics/metrics_module.ts
  tensorboard/webapp/metrics/store/BUILD
  tensorboard/webapp/metrics/store/metrics_initial_state_provider.ts
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/runs/views/runs_selector/runs_selector_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
  tensorboard/webapp/testing/BUILD
  tensorboard/webapp/testing/integration_test_module.ts
  tensorboard/webapp/testing/mat_icon_module.ts
Labels: cla: yes

#4808 time series: download link
  tensorboard/webapp/metrics/data_source/metrics_data_source.ts
  tensorboard/webapp/metrics/data_source/metrics_data_source_test.ts
  tensorboard/webapp/metrics/data_source/types.ts
  tensorboard/webapp/metrics/testing.ts
  tensorboard/webapp/metrics/views/card_renderer/BUILD
  tensorboard/webapp/metrics/views/card_renderer/data_download_dialog_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/data_download_dialog_component.scss
  tensorboard/webapp/metrics/views/card_renderer/data_download_dialog_component.ts
  tensorboard/webapp/metrics/views/card_renderer/data_download_dialog_container.ts
  tensorboard/webapp/metrics/views/card_renderer/data_download_dialog_test.ts
  tensorboard/webapp/metrics/views/card_renderer/data_download_module.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_module.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/runs/types.ts
Labels: cla: yes

#4813 cli: enable fast Rust data loading by default
  tensorboard/plugins/core/core_plugin.py
Labels: cla: yes, core:rustboard, theme:performance

#4817 graph: fix 'ungroup this series' button
  tensorboard/plugins/graph/tf_graph/tf-graph.ts
  tensorboard/plugins/graph/tf_graph_board/tf-graph-board.ts
  tensorboard/plugins/graph/tf_graph_common/common_test.ts
  tensorboard/plugins/graph/tf_graph_common/graph.ts
  tensorboard/plugins/graph/tf_graph_common/hierarchy.ts
  tensorboard/plugins/graph/tf_graph_info/tf-graph-info.ts
  tensorboard/plugins/graph/tf_graph_op_compat_card/tf-graph-op-compat-card.ts
Labels: cla: yes

#4814 chore: upgrade threejs to 0.125.0
  package.json
  tensorboard/plugins/mesh/tf_mesh_dashboard/mesh-viewer.ts
  tensorboard/plugins/projector/vz_projector/scatterPlotVisualizer3DLabels.ts
  tensorboard/plugins/projector/vz_projector/scatterPlotVisualizerPolylines.ts
  tensorboard/plugins/projector/vz_projector/scatterPlotVisualizerSprites.ts
  yarn.lock
Labels: cla: yes

#4795 docs: update `tf.summary.image()`
  tensorboard/plugins/image/summary_v2.py
Labels: cla: yes

#4798 docs: update `tf.summary.histogram()`
  tensorboard/plugins/histogram/summary_v2.py
Labels: cla: yes

#4818 time series: fix the data download module
  tensorboard/webapp/metrics/views/card_renderer/data_download_module.ts
Labels: cla: yes

#4803 graph: relax the aggressive numeric node series detection
  tensorboard/plugins/graph/tf_graph_common/common_test.ts
  tensorboard/plugins/graph/tf_graph_common/hierarchy.ts
  tensorboard/plugins/graph/tf_graph_common/loader.ts
  tensorboard/plugins/graph/tf_graph_common/parser.ts
  tensorboard/plugins/graph/tf_graph_common/util.ts
Labels: cla: yes

#4821 histograms: warn when metadata version is too new
  tensorboard/plugins/histogram/BUILD
  tensorboard/plugins/histogram/histograms_plugin.py
  tensorboard/plugins/histogram/metadata.py
Labels: cla: yes, plugin:histogram

#4783 data: remove `data_location` method
  tensorboard/backend/event_processing/data_provider.py
  tensorboard/backend/event_processing/data_provider_test.py
  tensorboard/data/dispatching_provider.py
  tensorboard/data/dispatching_provider_test.py
  tensorboard/data/grpc_provider.py
  tensorboard/data/grpc_provider_test.py
  tensorboard/data/provider.py
  tensorboard/plugins/core/core_plugin.py
  tensorboard/plugins/core/core_plugin_test.py
Labels: cla: yes, core:backend

#4811 cli: add `--extra_data_server_flags`
  tensorboard/data/server_ingester.py
  tensorboard/data/server_ingester_test.py
  tensorboard/plugins/core/core_plugin.py
  tensorboard/program.py
Labels: cla: yes, core:rustboard

#4824 graph: update TPU-supported op allowlist
  tensorboard/plugins/graph/tf_graph_common/op.ts
Labels: cla: yes

#4826 pr_curves: warn when metadata version is too new
  tensorboard/plugins/pr_curve/BUILD
  tensorboard/plugins/pr_curve/metadata.py
  tensorboard/plugins/pr_curve/pr_curves_plugin.py
Labels: cla: yes, plugin:pr-curves

#4823 rust: upgrade to Rust 1.51.0
  .github/workflows/ci.yml
  third_party/rust.bzl
Labels: cla: yes, core:rustboard, type:build/install

#4832 ci: set manual Rust toolchains as default
  .github/workflows/ci.yml
Labels: cla: yes, core:rustboard, type:build/install

#4830 rust: use `std::array::IntoIter` where appropriate
  tensorboard/data/server/data_compat.rs
  tensorboard/data/server/server.rs
Labels: cla: yes, core:rustboard, type:cleanup
