Repository tensorflow/tensorboard, pull requests merged in 2021-07, with the labels that each got.

#5108 color grouping: default group by experiment on comparison view
  tensorboard/webapp/app_routing/testing.ts
  tensorboard/webapp/runs/store/BUILD
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
Labels: cla: yes

#5109 dark mode: apply color on warning message
  tensorboard/webapp/plugins/plugins_component.scss
Labels: cla: yes

#5110 runs: filter based on experiment name and classic name
  tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Labels: cla: yes

#5098 Refactor settings dialog so it has both container and component layers.
  tensorboard/webapp/settings/_views/BUILD
  tensorboard/webapp/settings/_views/dialog_component_test.ts
  tensorboard/webapp/settings/_views/settings_button_component.ts
  tensorboard/webapp/settings/_views/settings_dialog_component.css
  tensorboard/webapp/settings/_views/settings_dialog_component.ts
  tensorboard/webapp/settings/_views/settings_dialog_container.ts
  tensorboard/webapp/settings/_views/settings_module.ts
  tensorboard/webapp/settings/_views/settings_test.ts
Labels: cla: yes

#5113 color grouping: group by regex, set non-matched runs to inactive
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
Labels: cla: yes

#5118 Refactor settings in state to their own object.
  tensorboard/webapp/reloader/reloader_component_test.ts
  tensorboard/webapp/settings/_redux/settings_reducers.ts
  tensorboard/webapp/settings/_redux/settings_reducers_test.ts
  tensorboard/webapp/settings/_redux/settings_selectors.ts
  tensorboard/webapp/settings/_redux/settings_types.ts
  tensorboard/webapp/settings/_views/settings_test.ts
  tensorboard/webapp/settings/testing.ts
Labels: cla: yes

#5117 color grouping: add group by regex under feature flag
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
  tensorboard/webapp/feature_flag/testing.ts
  tensorboard/webapp/feature_flag/types.ts
  tensorboard/webapp/routes/dashboard_deeplink_provider.ts
  tensorboard/webapp/routes/dashboard_deeplink_provider_test.ts
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ng.html
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ts
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
Labels: cla: yes

#5121 core: extend page title module functionalities
  tensorboard/webapp/core/BUILD
  tensorboard/webapp/core/types.ts
  tensorboard/webapp/core/views/BUILD
  tensorboard/webapp/core/views/page_title_component.ts
  tensorboard/webapp/core/views/page_title_container.ts
  tensorboard/webapp/core/views/page_title_test.ts
Labels: cla: yes, core:frontend

#5099 docs: show explanation when --load_fast and --logdir_spec are passed
  tensorboard/program.py
Labels: cla: yes

#5125 theme: style mat-button not as hyperlink
  tensorboard/webapp/header/header_component.scss
  tensorboard/webapp/theme/_tb_theme.template.scss
Labels: cla: yes

#5124 fix build and lint errors in google3
  tensorboard/webapp/core/BUILD
  tensorboard/webapp/core/views/page_title_container.ts
Labels: cla: yes, type:bug

#5123 color grouping: Regex edit
  tensorboard/webapp/runs/store/runs_selectors_test.ts
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ng.html
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.scss
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ts
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Labels: cla: yes

#5126 type: missing optional injectable is null
  tensorboard/webapp/core/views/page_title_container.ts
Labels: cla: yes

#5127 color grouping: fix expid pass bug
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_container.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Labels: cla: yes

#5128 core: make title$ also listen to route kind observable
  tensorboard/webapp/core/views/page_title_container.ts
  tensorboard/webapp/core/views/page_title_test.ts
Labels: cla: yes, core:frontend

#5132 Add optional repository_id to Experiment
  tensorboard/webapp/experiments/types.ts
Labels: cla: yes

#5129 color grouping: group by regex, fill example and some diaglog wording
  tensorboard/webapp/runs/views/runs_table/BUILD
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog.ng.html
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.scss
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.ts
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_test.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Labels: cla: yes

#5135 metric: use persistent setting storage
  tensorboard/webapp/metrics/BUILD
  tensorboard/webapp/metrics/actions/index.ts
  tensorboard/webapp/metrics/data_source/BUILD
  tensorboard/webapp/metrics/data_source/metrics_data_source.ts
  tensorboard/webapp/metrics/data_source/metrics_data_source_module.ts
  tensorboard/webapp/metrics/data_source/metrics_data_source_test.ts
  tensorboard/webapp/metrics/data_source/types.ts
  tensorboard/webapp/metrics/effects/index.ts
  tensorboard/webapp/metrics/effects/metrics_effects_test.ts
  tensorboard/webapp/metrics/metrics_module.ts
  tensorboard/webapp/metrics/store/BUILD
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/testing.ts
Labels: cla: yes

#5093 histogram: avoid data transfer overhead for TPU outside compilation
  tensorboard/plugins/histogram/summary_v2.py
Labels: cla: yes, core:summaries, plugin:histogram

#5138 Fixed deprecated numpy types.
  tensorboard/compat/tensorflow_stub/dtypes.py
  tensorboard/plugins/text/summary_v2.py
  tensorboard/uploader/exporter.py
  tensorboard/util/tensor_util.py
Labels: cla: yes, type:cleanup

#5139 persist storage: use factory instead of selector
  tensorboard/webapp/metrics/metrics_module.ts
  tensorboard/webapp/persistent_settings/_redux/persistent_settings_effects_test.ts
  tensorboard/webapp/persistent_settings/persistent_settings_config_module.ts
  tensorboard/webapp/persistent_settings/persistent_settings_config_module_test.ts
Labels: cla: yes

#5136 feature_flag: dark mode in persistent storage
  tensorboard/webapp/feature_flag/BUILD
  tensorboard/webapp/feature_flag/feature_flag_module.ts
  tensorboard/webapp/feature_flag/store/BUILD
  tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts
  tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts
  tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts
  tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source_test.ts
  tensorboard/webapp/persistent_settings/_data_source/types.ts
  tensorboard/webapp/persistent_settings/_redux/BUILD
  tensorboard/webapp/persistent_settings/_redux/persistent_settings_effects.ts
  tensorboard/webapp/persistent_settings/index.ts
Labels: cla: yes

#5141 Revert "feature_flag: dark mode in persistent storage"
  tensorboard/webapp/feature_flag/BUILD
  tensorboard/webapp/feature_flag/feature_flag_module.ts
  tensorboard/webapp/feature_flag/store/BUILD
  tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts
  tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts
  tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts
  tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source_test.ts
  tensorboard/webapp/persistent_settings/_data_source/types.ts
  tensorboard/webapp/persistent_settings/_redux/BUILD
  tensorboard/webapp/persistent_settings/_redux/persistent_settings_effects.ts
  tensorboard/webapp/persistent_settings/index.ts
Labels: cla: yes

#5142 settings: persist settings in storage
  tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts
  tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source_test.ts
  tensorboard/webapp/persistent_settings/_data_source/types.ts
  tensorboard/webapp/persistent_settings/_redux/BUILD
  tensorboard/webapp/persistent_settings/_redux/persistent_settings_effects.ts
  tensorboard/webapp/persistent_settings/index.ts
  tensorboard/webapp/settings/BUILD
  tensorboard/webapp/settings/_redux/BUILD
  tensorboard/webapp/settings/_redux/settings_reducers.ts
  tensorboard/webapp/settings/_redux/settings_reducers_test.ts
  tensorboard/webapp/settings/settings_module.ts
Labels: cla: yes

#5144 chore: guard against property renaming for Angular-Polymer interop types
  tensorboard/webapp/tb_polymer_interop_types.ts
Labels: cla: yes

#5140 router: allow programmatical route definition
  tensorboard/webapp/app_routing/route_config.ts
  tensorboard/webapp/app_routing/route_config_test.ts
  tensorboard/webapp/app_routing/route_config_types.ts
  tensorboard/webapp/app_routing/route_registry_module.ts
Labels: cla: yes

#5143 feature_flag: dark mode in persistent storage
  tensorboard/webapp/feature_flag/BUILD
  tensorboard/webapp/feature_flag/feature_flag_module.ts
  tensorboard/webapp/feature_flag/store/BUILD
  tensorboard/webapp/feature_flag/store/feature_flag_reducers.ts
  tensorboard/webapp/feature_flag/store/feature_flag_reducers_test.ts
  tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts
  tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source_test.ts
  tensorboard/webapp/persistent_settings/_data_source/types.ts
  tensorboard/webapp/persistent_settings/index.ts
Labels: cla: yes

#5147 Revert "histogram: avoid data transfer overhead for TPU outside compilation"
  tensorboard/plugins/histogram/summary_v2.py
Labels: cla: yes, core:summaries, plugin:histogram

#5146 notification center: persist setting via common storage
  tensorboard/webapp/notification_center/BUILD
  tensorboard/webapp/notification_center/_data_source/backend_types.ts
  tensorboard/webapp/notification_center/_data_source/notification_center_data_source.ts
  tensorboard/webapp/notification_center/_data_source/notification_center_data_source_test.ts
  tensorboard/webapp/notification_center/_notification_center_module.ts
  tensorboard/webapp/notification_center/_redux/BUILD
  tensorboard/webapp/notification_center/_redux/notification_center_actions.ts
  tensorboard/webapp/notification_center/_redux/notification_center_effects.ts
  tensorboard/webapp/notification_center/_redux/notification_center_effects_test.ts
  tensorboard/webapp/notification_center/_redux/notification_center_reducers.ts
  tensorboard/webapp/notification_center/_redux/notification_center_reducers_test.ts
  tensorboard/webapp/notification_center/_redux/testing.ts
  tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts
  tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source_test.ts
  tensorboard/webapp/persistent_settings/_data_source/types.ts
Labels: cla: yes

#5149 projector: draw transparent sprites correctly
  tensorboard/plugins/projector/vz_projector/scatterPlotVisualizerSprites.ts
Labels: cla: yes

#5145 router: redirect with query parameter
  tensorboard/webapp/app_routing/effects/app_routing_effects.ts
  tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
  tensorboard/webapp/app_routing/route_config.ts
  tensorboard/webapp/app_routing/route_config_test.ts
  tensorboard/webapp/app_routing/route_config_types.ts
Labels: cla: yes

#5148 color grouping: grouping result preview
  tensorboard/webapp/runs/store/BUILD
  tensorboard/webapp/runs/store/runs_selectors.ts
  tensorboard/webapp/runs/store/runs_selectors_test.ts
  tensorboard/webapp/runs/views/runs_table/BUILD
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog.ng.html
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.scss
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_component.ts
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_container.ts
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_test.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Labels: cla: yes

#5150 Expose CompareExperimentStr parser as util
  tensorboard/webapp/app_routing/BUILD
  tensorboard/webapp/app_routing/store/BUILD
  tensorboard/webapp/app_routing/store/app_routing_selectors.ts
  tensorboard/webapp/app_routing/store_only_utils.ts
  tensorboard/webapp/app_routing/store_only_utils_test.ts
Labels: cla: yes

#5153 sync: fix import tslint and html analyze
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog.ng.html
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_container.ts
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_test.ts
Labels: cla: yes

#5154 docs: update tb.dev experiment list image
  docs/images/tbdev_experiment_list.png
Labels: cla: yes, tbdev, type:docs

#5156 histogram: avoid data transfer overhead for TPU outside compilation (3rd edition)
  tensorboard/plugins/histogram/summary_test.py
  tensorboard/plugins/histogram/summary_v2.py
Labels: cla: yes, core:summaries, plugin:histogram

#5151 color grouping: on clicking `Regex`, open dialog if regex string is empty
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ng.html
  tensorboard/webapp/runs/views/runs_table/runs_group_menu_button_component.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Labels: cla: yes

#5158 color grouping: preserve regexString when groupBy regex is fired
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
Labels: cla: yes

#5161 color grouping: rehydrated regexString from url
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
Labels: cla: yes

#5162 histogram: render Overlay and Offset charts
  tensorboard/webapp/widgets/histogram/BUILD
  tensorboard/webapp/widgets/histogram/histogram_module.ts
  tensorboard/webapp/widgets/histogram/histogram_v2_component.ng.html
  tensorboard/webapp/widgets/histogram/histogram_v2_component.scss
  tensorboard/webapp/widgets/histogram/histogram_v2_component.ts
  tensorboard/webapp/widgets/histogram/histogram_v2_test.ts
Labels: cla: yes

#5166 histogram: re-render on resize
  tensorboard/webapp/widgets/histogram/BUILD
  tensorboard/webapp/widgets/histogram/histogram_module.ts
  tensorboard/webapp/widgets/histogram/histogram_v2_component.ng.html
  tensorboard/webapp/widgets/histogram/histogram_v2_component.ts
  tensorboard/webapp/widgets/histogram/histogram_v2_test.ts
Labels: cla: yes

#5164 Provide QueryParamsFeatureFlagDataSource implementation
  tensorboard/webapp/webapp_data_source/tb_feature_flag_module.ts
Labels: cla: yes

#5160 color grouping: fix number and add tests
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog.ng.html
  tensorboard/webapp/runs/views/runs_table/regex_edit_dialog_test.ts
Labels: cla: yes

#5167 histogram: tooltips on histogram
  tensorboard/webapp/widgets/histogram/BUILD
  tensorboard/webapp/widgets/histogram/histogram_v2_component.ng.html
  tensorboard/webapp/widgets/histogram/histogram_v2_component.scss
  tensorboard/webapp/widgets/histogram/histogram_v2_component.ts
  tensorboard/webapp/widgets/histogram/histogram_v2_test.ts
Labels: cla: yes

#5169 histogram: support dark mode in Angular version
  tensorboard/webapp/widgets/histogram/histogram_v2_component.scss
Labels: cla: yes

#5168 sync: fix tslint
  tensorboard/webapp/widgets/histogram/histogram_v2_component.ts
Labels: cla: yes
