Repository tensorflow/tensorboard, pull requests merged in 2021-11, with the labels that each got.

#5393 bug: prevent violent error when Experiment metadata is missing
  tensorboard/webapp/runs/views/runs_table/runs_table_container.ts
  tensorboard/webapp/util/matcher.ts
  tensorboard/webapp/util/matcher_test.ts
  tensorboard/webapp/util/ui_selectors.ts
  tensorboard/webapp/util/ui_selectors_test.ts
Labels: cla: yes

#5397 time series: force use SVG renderer
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
Labels: cla: yes

#5396 DataFrame API: move ExperimentFromDev._pivot_dataframe to a separate utils.py
  tensorboard/data/experimental/BUILD
  tensorboard/data/experimental/experiment_from_dev.py
  tensorboard/data/experimental/utils.py
Labels: cla: yes

#5391 histogram: make legacy histogram visualization compatible with v3 data format
  tensorboard/plugins/histogram/tf_histogram_dashboard/BUILD
  tensorboard/plugins/histogram/tf_histogram_dashboard/histogramCore.ts
  tensorboard/plugins/histogram/tf_histogram_dashboard/histogram_core_test.ts
Labels: plugin:histogram, cla: yes

#5392 histogram: make timeseries histogram visualization compatible with v3 data format
  tensorboard/webapp/widgets/histogram/histogram_util.ts
  tensorboard/webapp/widgets/histogram/histogram_util_test.ts
Labels: plugin:histogram, cla: yes

#5401 fix tslint errors for copybara
  tensorboard/plugins/histogram/tf_histogram_dashboard/histogram_core_test.ts
Labels: cla: yes

#5394 Change RouteRegistryModule.getRouteConfigs() to have non-nullable return type.
  tensorboard/webapp/app_routing/effects/app_routing_effects.ts
  tensorboard/webapp/app_routing/route_registry_module.ts
  tensorboard/webapp/app_routing/route_registry_module_test.ts
Labels: cla: yes

#5405 Remove unnecessary property from some Navigation-related actions.
  tensorboard/webapp/app_routing/effects/app_routing_effects.ts
  tensorboard/webapp/app_routing/location.ts
  tensorboard/webapp/app_routing/testing.ts
Labels: cla: yes

#5406 alias: improve visuals of alias
  tensorboard/webapp/widgets/experiment_alias/experiment_alias_component.scss
Labels: cla: yes

#5407 widget: content wrapping input
  tensorboard/webapp/BUILD
  tensorboard/webapp/widgets/content_wrapping_input/BUILD
  tensorboard/webapp/widgets/content_wrapping_input/content_wrapping_input_component.scss
  tensorboard/webapp/widgets/content_wrapping_input/content_wrapping_input_component.ts
  tensorboard/webapp/widgets/content_wrapping_input/content_wrapping_input_module.ts
  tensorboard/webapp/widgets/content_wrapping_input/content_wrapping_input_test.ts
Labels: cla: yes

#5410 alias: implement edit mode
  tensorboard/webapp/widgets/experiment_alias/BUILD
  tensorboard/webapp/widgets/experiment_alias/experiment_alias_component.ts
  tensorboard/webapp/widgets/experiment_alias/experiment_alias_module.ts
  tensorboard/webapp/widgets/experiment_alias/experiment_alias_test.ts
Labels: cla: yes

#5404 histogram: remove `backwards` buckets in v1 histogram migration
  tensorboard/data_compat.py
  tensorboard/data_compat_test.py
Labels: plugin:histogram, cla: yes

#5409 histogram: make `summary_v2.histogram_pb` TPU compatible
  tensorboard/plugins/histogram/summary_test.py
  tensorboard/plugins/histogram/summary_v2.py
Labels: plugin:histogram, core:summaries, cla: yes

#5413 alias: render pretty alias in the scalars tooltip
  tensorboard/webapp/metrics/views/card_renderer/BUILD
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_component.ng.html
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_container.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_module.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_test.ts
  tensorboard/webapp/metrics/views/card_renderer/scalar_card_types.ts
Labels: cla: yes

#5412 Time Series: preserve run regex filter string in URL
  tensorboard/webapp/routes/dashboard_deeplink_provider.ts
  tensorboard/webapp/routes/dashboard_deeplink_provider_test.ts
  tensorboard/webapp/routes/dashboard_deeplink_provider_types.ts
  tensorboard/webapp/routes/testing.ts
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
  tensorboard/webapp/runs/types.ts
  tensorboard/webapp/runs/views/runs_table/runs_table_component.ng.html
Labels: cla: yes

#5415 histogram: set v3 as default
  tensorboard/plugins/histogram/summary.py
  tensorboard/plugins/histogram/summary_test.py
  tensorboard/plugins/histogram/summary_v2.py
  tensorboard/plugins/metrics/metrics_plugin_test.py
Labels: plugin:histogram, core:summaries, cla: yes

#5417 Time Series: fix color group preserve bug
  tensorboard/webapp/runs/store/runs_reducers.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
Labels: cla: yes

#5408 Time Series: change how groups collapses to more like Scalars
  tensorboard/webapp/BUILD
  tensorboard/webapp/metrics/BUILD
  tensorboard/webapp/metrics/internal_types.ts
  tensorboard/webapp/metrics/store/BUILD
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/utils.ts
  tensorboard/webapp/metrics/utils_test.ts
  tensorboard/webapp/metrics/views/main_view/BUILD
  tensorboard/webapp/metrics/views/main_view/card_grid_component.ng.html
  tensorboard/webapp/metrics/views/main_view/card_grid_component.scss
  tensorboard/webapp/metrics/views/main_view/card_grid_component.ts
  tensorboard/webapp/metrics/views/main_view/card_grid_container.ts
  tensorboard/webapp/metrics/views/main_view/card_group_toolbar_component.scss
  tensorboard/webapp/metrics/views/main_view/card_group_toolbar_component.ts
  tensorboard/webapp/metrics/views/main_view/card_group_toolbar_container.ts
  tensorboard/webapp/metrics/views/main_view/card_groups_component.scss
  tensorboard/webapp/metrics/views/main_view/card_groups_component.ts
  tensorboard/webapp/metrics/views/main_view/card_groups_container.ts
  tensorboard/webapp/metrics/views/main_view/common_selectors.ts
  tensorboard/webapp/metrics/views/main_view/filter_input_container.ts
  tensorboard/webapp/metrics/views/main_view/main_view_module.ts
  tensorboard/webapp/metrics/views/main_view/main_view_test.ts
  tensorboard/webapp/metrics/views/utils.ts
  tensorboard/webapp/metrics/views/utils_test.ts
Labels: cla: yes

#5423 line chart: fix bug where line does not update
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/renderer_test.ts
  tensorboard/webapp/widgets/line_chart_v2/lib/renderer/svg_renderer.ts
Labels: cla: yes

#5424 build: omit SASS target on js_binary
  tensorboard/webapp/BUILD
Labels: cla: yes

#5422 Feature Flag: add feature flag for card width setting
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
  tensorboard/webapp/feature_flag/testing.ts
  tensorboard/webapp/feature_flag/types.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
Labels: cla: yes

#5425 chore: Fix Angular Material style naming
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/common/BUILD
  tensorboard/webapp/tbdev_upload/tbdev_upload_dialog_component.scss
  tensorboard/webapp/theme/_tb_theme.template.scss
Labels: cla: yes

#5426 Time Series: fix dark mode color
  tensorboard/webapp/metrics/views/main_view/card_group_toolbar_component.scss
Labels: cla: yes

#5429 Time Series: inherit font
  tensorboard/webapp/metrics/views/main_view/card_group_toolbar_component.scss
Labels: cla: yes

#5431 chore: guard against mat-color and $mat-*
  .github/workflows/ci.yml
Labels: cla: yes

#5430 chore: explicitly depend on Angular Material style dep
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/common/BUILD
  tensorboard/plugins/debugger_v2/tf_debugger_v2_plugin/views/execution_data/BUILD
  tensorboard/webapp/BUILD
  tensorboard/webapp/_angular_material_theming.scss
  tensorboard/webapp/metrics/views/BUILD
  tensorboard/webapp/metrics/views/card_renderer/BUILD
  tensorboard/webapp/metrics/views/main_view/BUILD
  tensorboard/webapp/metrics/views/right_pane/BUILD
  tensorboard/webapp/notification_center/_views/BUILD
  tensorboard/webapp/plugins/npmi/views/annotations_list/BUILD
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotation/BUILD
  tensorboard/webapp/plugins/npmi/views/annotations_list/annotations_list_toolbar/annotations_search/BUILD
  tensorboard/webapp/plugins/npmi/views/annotations_list/header/BUILD
  tensorboard/webapp/plugins/npmi/views/data_selection/BUILD
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_arithmetic/metric_arithmetic_element/BUILD
  tensorboard/webapp/plugins/npmi/views/data_selection/metric_search/BUILD
  tensorboard/webapp/plugins/npmi/views/data_selection/results_download/BUILD
  tensorboard/webapp/plugins/npmi/views/embeddings/BUILD
  tensorboard/webapp/plugins/npmi/views/main/BUILD
  tensorboard/webapp/plugins/npmi/views/selected_annotations/BUILD
  tensorboard/webapp/plugins/npmi/views/violin_filters/BUILD
  tensorboard/webapp/plugins/npmi/views/violin_filters/violin_filter/BUILD
  tensorboard/webapp/runs/views/runs_table/BUILD
  tensorboard/webapp/tbdev_upload/BUILD
  tensorboard/webapp/theme/BUILD
  tensorboard/webapp/theme/_tb_palette.scss
  tensorboard/webapp/theme/_tb_theme.template.scss
  tensorboard/webapp/theme/_variable.scss
  tensorboard/webapp/widgets/content_wrapping_input/BUILD
  tensorboard/webapp/widgets/dropdown/BUILD
  tensorboard/webapp/widgets/line_chart_v2/sub_view/BUILD
  tensorboard/webapp/widgets/linked_time_fob/BUILD
  tensorboard/webapp/widgets/range_input/BUILD
Labels: cla: yes

#5428 Time Series: adjust card width (UI)
  tensorboard/webapp/metrics/store/metrics_selectors.ts
  tensorboard/webapp/metrics/store/metrics_selectors_test.ts
  tensorboard/webapp/metrics/store/metrics_types.ts
  tensorboard/webapp/metrics/testing.ts
  tensorboard/webapp/metrics/views/main_view/card_grid_component.ng.html
  tensorboard/webapp/metrics/views/main_view/card_grid_component.ts
  tensorboard/webapp/metrics/views/main_view/card_grid_container.ts
  tensorboard/webapp/metrics/views/main_view/card_grid_test.ts
  tensorboard/webapp/metrics/views/main_view/main_view_test.ts
Labels: cla: yes

#5432 Time Series: Card width adjustment, connect settings and ui together
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/views/main_view/card_grid_component.ts
  tensorboard/webapp/metrics/views/main_view/main_view_test.ts
  tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
  tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
Labels: cla: yes

#5434 timeseries: preserve card width setting in local storage
  tensorboard/webapp/metrics/metrics_module.ts
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source_test.ts
Labels: core:frontend, cla: yes, plugin:time-series

#5433 chore: remove now defunct webapp:angular_material_theming
  tensorboard/webapp/BUILD
Labels: cla: yes

#5435 [time-namespaced state] Generate namespace ids in app_routing_effects.
  tensorboard/webapp/app_routing/BUILD
  tensorboard/webapp/app_routing/actions/app_routing_actions.ts
  tensorboard/webapp/app_routing/effects/BUILD
  tensorboard/webapp/app_routing/effects/app_routing_effects.ts
  tensorboard/webapp/app_routing/effects/app_routing_effects_test.ts
  tensorboard/webapp/app_routing/route_contexted_reducer_helper.ts
  tensorboard/webapp/app_routing/route_contexted_reducer_helper_test.ts
  tensorboard/webapp/app_routing/store/app_routing_reducers.ts
  tensorboard/webapp/app_routing/store/app_routing_reducers_test.ts
  tensorboard/webapp/app_routing/store/app_routing_selectors.ts
  tensorboard/webapp/app_routing/store/app_routing_selectors_test.ts
  tensorboard/webapp/app_routing/store/app_routing_types.ts
  tensorboard/webapp/app_routing/store/testing.ts
  tensorboard/webapp/app_routing/testing.ts
  tensorboard/webapp/core/effects/core_effects_test.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
Labels: cla: yes

#5436 [time-namespaced state] Remove optionality of new navigated() properties.
  tensorboard/webapp/app_routing/actions/app_routing_actions.ts
  tensorboard/webapp/app_routing/route_contexted_reducer_helper.ts
  tensorboard/webapp/app_routing/store/app_routing_reducers.ts
Labels: cla: yes

#5439 Rename buildNavigatedActionFull to buildNavigatedAction.
  tensorboard/webapp/app_routing/testing.ts
  tensorboard/webapp/core/effects/core_effects_test.ts
  tensorboard/webapp/metrics/effects/metrics_effects_test.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/runs/store/runs_reducers_test.ts
Labels: cla: yes

#5440 [time-namespaced state] Add feature flag for time-namespaced state.
  tensorboard/webapp/feature_flag/store/feature_flag_selectors.ts
  tensorboard/webapp/feature_flag/store/feature_flag_selectors_test.ts
  tensorboard/webapp/feature_flag/store/feature_flag_store_config_provider.ts
  tensorboard/webapp/feature_flag/testing.ts
  tensorboard/webapp/feature_flag/types.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_test.ts
  tensorboard/webapp/webapp_data_source/tb_feature_flag_data_source_types.ts
Labels: cla: yes

#5437 timeseries: make the slider control min card width
  tensorboard/webapp/metrics/actions/index.ts
  tensorboard/webapp/metrics/metrics_module.ts
  tensorboard/webapp/metrics/store/metrics_reducers.ts
  tensorboard/webapp/metrics/store/metrics_reducers_test.ts
  tensorboard/webapp/metrics/store/metrics_selectors.ts
  tensorboard/webapp/metrics/store/metrics_selectors_test.ts
  tensorboard/webapp/metrics/store/metrics_types.ts
  tensorboard/webapp/metrics/testing.ts
  tensorboard/webapp/metrics/views/main_view/card_grid_component.ts
  tensorboard/webapp/metrics/views/main_view/card_grid_container.ts
  tensorboard/webapp/metrics/views/main_view/card_grid_test.ts
  tensorboard/webapp/metrics/views/main_view/main_view_test.ts
  tensorboard/webapp/metrics/views/right_pane/right_pane_test.ts
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.ng.html
  tensorboard/webapp/metrics/views/right_pane/settings_view_component.ts
  tensorboard/webapp/metrics/views/right_pane/settings_view_container.ts
  tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source.ts
  tensorboard/webapp/persistent_settings/_data_source/persistent_settings_data_source_test.ts
  tensorboard/webapp/persistent_settings/_data_source/types.ts
Labels: cla: yes
