Repository tensorflow/tensorboard, pull requests merged in 2022-12, with the labels that each got.

#6084 hparams: fix type check bug
  tensorboard/plugins/hparams/summary.py
Labels: core:backend, core:summaries, plugin:hparams

#6089 Upgrade rust version for CI to latest
  .github/workflows/ci.yml
Labels: type:build/install, rust

#6117 Remove deprecated alias `numpy.bool8`
  tensorboard/compat/tensorflow_stub/dtypes.py
Labels: type:cleanup
