Repository tensorflow/tensorboard, pull requests merged in 2022-06, with the labels that each got.

#5757 Add instructions on how to update Rustboard dependencies.
  tensorboard/data/server/DEVELOPMENT.md
Labels: core:rustboard

#5758 fix argument type error and tslint
  tensorboard/webapp/runs/views/runs_table/runs_table_test.ts
Labels: type:build/install

#5762 fix flaky test
  tensorboard/webapp/metrics/views/main_view/main_view_test.ts
Labels: type:cleanup

#5766 ci: build tb-nightly pip package and upload it as an artifact
  .github/workflows/ci.yml
  tensorboard/tools/update_version.sh
Labels: type:build/install

#5771 Remediate setup-node GH Action warning
  .github/workflows/ci.yml
Labels: type:cleanup

#5782 data: add `default_prefix` arg for DispatchingDataProvider
  tensorboard/data/dispatching_provider.py
  tensorboard/data/dispatching_provider_test.py
Labels: core:backend
