Repository tensorflow/tensorboard, pull requests merged in 2022-05, with the labels that each got.

#5694 docs: update README for XLA clustering visualization
  tensorboard/plugins/graph/README.md
  tensorboard/plugins/graph/images/xla_graph.png
Labels: type:docs

#5693 Remove LINT check from copied proto files
  tensorboard/compat/proto/attr_value.proto
  tensorboard/compat/proto/full_type.proto
  tensorboard/compat/proto/op_def.proto
  tensorboard/compat/proto/types.proto
  tensorboard/compat/proto/update.sh
  tensorboard/data/server/descriptor.bin
  tensorboard/data/server/tensorboard.pb.rs
Labels: type:cleanup

#5699 docs: clarify the default number of histogram buckets in summary API doc
  tensorboard/plugins/histogram/summary_v2.py
Labels: type:docs

#5698 Time Series: Elevate "Time Series" dashboard to first dashboard.
  tensorboard/default.py
Labels: plugin:time-series

#5722 ci: pin tf-nightly to 20220521
  .github/workflows/ci.yml
Labels: type:build/install
