Repository tensorflow/tensorboard, pull requests merged in 2023-01, with the labels that each got.

#6125 refactor python files
  tensorboard/backend/application_test.py
  tensorboard/backend/event_processing/data_provider_test.py
  tensorboard/backend/event_processing/event_accumulator_test.py
  tensorboard/backend/event_processing/event_multiplexer_test.py
  tensorboard/backend/event_processing/io_wrapper_test.py
  tensorboard/backend/event_processing/plugin_event_accumulator_test.py
  tensorboard/backend/event_processing/plugin_event_multiplexer_test.py
  tensorboard/backend/event_processing/reservoir_test.py
  tensorboard/compat/tensorflow_stub/io/gfile_tf_test.py
  tensorboard/manager_e2e_test.py
  tensorboard/manager_test.py
  tensorboard/plugins/custom_scalar/custom_scalars_plugin_test.py
  tensorboard/plugins/hparams/_keras_test.py
  tensorboard/plugins/image/images_plugin_test.py
  tensorboard/plugins/npmi/npmi_plugin_test.py
  tensorboard/plugins/pr_curve/pr_curves_plugin_test.py
  tensorboard/plugins/projector/projector_plugin.py
  tensorboard/plugins/projector/projector_plugin_test.py
  tensorboard/plugins/text/text_plugin_test.py
  tensorboard/plugins/text_v2/text_v2_plugin_test.py
  tensorboard/uploader/util.py
  tensorboard/util/tensor_util.py
Labels: type:cleanup

#6122 ci: upgrade `setup-python` and `upload-artifact` actions
  .github/workflows/ci.yml
Labels: type:build/install

#6121 cleanup: replace namedtuples with dataclasses in `event_accumulator`
  tensorboard/backend/event_processing/event_accumulator.py
Labels: core:backend, type:cleanup

#6144 infra: drop support for Python 3.7 and mark 3.11 as supported
  .github/workflows/ci.yml
  tensorboard/pip_package/setup.py
Labels: type:build/install

#6147 build: update protobuf to 3.19.6 and grpc to 1.48.2
  WORKSPACE
  tensorboard/data/server/descriptor.bin
  tensorboard/pip_package/requirements.txt
  third_party/grpc.patch
  third_party/protobuf.patch
  third_party/protobuf/BUILD
Labels: type:build/install

#6166 tensorboard-data-server 0.7.0
  tensorboard/data/server/Cargo.lock
  tensorboard/data/server/Cargo.toml
  tensorboard/data/server/lib.rs
  tensorboard/data/server/pip_package/tensorboard_data_server/__init__.py
Labels: type:build/install, release, core:rustboard

#6170 pip: require tensorboard-data-server 0.7.0
  tensorboard/pip_package/requirements.txt
Labels: type:build/install
